/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, Codex
-/

import MazurTorsion.Kubert.OrderTwentyFiveLehmerCuspCycle

/-!
# The order-twenty-five cusp-divisor lattice

The five cyclic modular units in the order-twenty-five descent have cusp-order
vector `(3, -1, 1, -2, -1)`.  This file isolates the integral linear-algebra
consequence needed by the genus-four descent: the five cyclic principal-divisor
relations annihilate every difference of cusp classes by `71`.

The relation predicate below is the explicit interface boundary.  A geometric
construction of the five divisor classes can supply it without exposing a
particular divisor implementation; `orderTwentyFive_firstCuspDifference_exactOrder`
is its named group-theoretic consumer.
-/

namespace MazurTorsion.Kubert

/-- The five cyclic relations generated by the cusp-order vector
`(3, -1, 1, -2, -1)`.  In the intended application the `pᵢ` are degree-zero
cusp classes in the Jacobian of the genus-four order-twenty-five quotient. -/
def orderTwentyFiveCuspDivisorRelations
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A) : Prop :=
  3 • p0 - p1 + p2 - 2 • p3 - p4 = 0 ∧
    (3 • p1 - p2 + p3 - 2 • p4 - p0 = 0) ∧
    (3 • p2 - p3 + p4 - 2 • p0 - p1 = 0) ∧
    (3 • p3 - p4 + p0 - 2 • p1 - p2 = 0) ∧
    3 • p4 - p0 + p1 - 2 • p2 - p3 = 0

/-- Rotating the five cusp classes preserves their cyclic divisor relations. -/
theorem orderTwentyFiveCuspDivisorRelations_rotate
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    orderTwentyFiveCuspDivisorRelations p1 p2 p3 p4 p0 := by
  rcases h with ⟨h0, h1, h2, h3, h4⟩
  exact ⟨h1, h2, h3, h4, h0⟩

/-- The determinant-`71` certificate for one adjacent cusp difference.  The
coefficients `12, -14, -5, 11` give an explicit integral row reduction of the
circulant relation matrix. -/
theorem orderTwentyFive_seventyOne_nsmul_firstCuspDifference
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    71 • (p0 - p1) = 0 := by
  rcases h with ⟨h0, h1, h2, h3, _h4⟩
  have hcombination :
      12 • (3 • p0 - p1 + p2 - 2 • p3 - p4) -
          14 • (3 • p1 - p2 + p3 - 2 • p4 - p0) -
          5 • (3 • p2 - p3 + p4 - 2 • p0 - p1) +
          11 • (3 • p3 - p4 + p0 - 2 • p1 - p2) = 0 := by
    rw [h0, h1, h2, h3]
    simp
  calc
    71 • (p0 - p1) =
        12 • (3 • p0 - p1 + p2 - 2 • p3 - p4) -
          14 • (3 • p1 - p2 + p3 - 2 • p4 - p0) -
          5 • (3 • p2 - p3 + p4 - 2 • p0 - p1) +
          11 • (3 • p3 - p4 + p0 - 2 • p1 - p2) := by
            abel
    _ = 0 := hcombination

/-- Every adjacent difference in the five-cycle is annihilated by `71`. -/
theorem orderTwentyFive_seventyOne_nsmul_adjacentCuspDifferences
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    71 • (p0 - p1) = 0 ∧ 71 • (p1 - p2) = 0 ∧
      71 • (p2 - p3) = 0 ∧ 71 • (p3 - p4) = 0 ∧
      71 • (p4 - p0) = 0 := by
  have h1 := orderTwentyFiveCuspDivisorRelations_rotate p0 p1 p2 p3 p4 h
  have h2 := orderTwentyFiveCuspDivisorRelations_rotate p1 p2 p3 p4 p0 h1
  have h3 := orderTwentyFiveCuspDivisorRelations_rotate p2 p3 p4 p0 p1 h2
  have h4 := orderTwentyFiveCuspDivisorRelations_rotate p3 p4 p0 p1 p2 h3
  exact ⟨
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p0 p1 p2 p3 p4 h,
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p1 p2 p3 p4 p0 h1,
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p2 p3 p4 p0 p1 h2,
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p3 p4 p0 p1 p2 h3,
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p4 p0 p1 p2 p3 h4⟩

/-- Every difference from a fixed cusp is annihilated by `71`.  This is the
form used when the first cusp is chosen as the Abel--Jacobi base point. -/
theorem orderTwentyFive_seventyOne_nsmul_basedCuspDifferences
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    71 • (p0 - p1) = 0 ∧ 71 • (p0 - p2) = 0 ∧
      71 • (p0 - p3) = 0 ∧ 71 • (p0 - p4) = 0 := by
  rcases orderTwentyFive_seventyOne_nsmul_adjacentCuspDifferences
      p0 p1 p2 p3 p4 h with ⟨h01, h12, h23, h34, _h40⟩
  constructor
  · exact h01
  constructor
  · calc
      71 • (p0 - p2) = 71 • (p0 - p1) + 71 • (p1 - p2) := by abel
      _ = 0 := by simp [h01, h12]
  constructor
  · calc
      71 • (p0 - p3) =
          71 • (p0 - p1) + 71 • (p1 - p2) + 71 • (p2 - p3) := by
            abel
      _ = 0 := by simp [h01, h12, h23]
  · calc
      71 • (p0 - p4) =
          71 • (p0 - p1) + 71 • (p1 - p2) +
            71 • (p2 - p3) + 71 • (p3 - p4) := by
              abel
      _ = 0 := by simp [h01, h12, h23, h34]

/-- The three remaining based cusp differences are explicit multiples of the
first one.  These coefficients identify the torsion factor in the Smith
normal form, not merely its exponent. -/
theorem orderTwentyFive_basedCuspDifferences_eq_multiples
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    p0 - p2 = 6 • (p0 - p1) ∧
      p0 - p3 = 31 • (p0 - p1) ∧
      p0 - p4 = 14 • (p0 - p1) := by
  rcases h with ⟨h0, h1, h2, h3, _h4⟩
  constructor
  · calc
      p0 - p2 = 6 • (p0 - p1) -
          (3 • p0 - p1 + p2 - 2 • p3 - p4) +
          (3 • p1 - p2 + p3 - 2 • p4 - p0) -
          (3 • p3 - p4 + p0 - 2 • p1 - p2) := by
            abel
      _ = 6 • (p0 - p1) := by rw [h0, h1, h3]; simp
  constructor
  · calc
      p0 - p3 = 31 • (p0 - p1) -
          5 • (3 • p0 - p1 + p2 - 2 • p3 - p4) +
          6 • (3 • p1 - p2 + p3 - 2 • p4 - p0) +
          2 • (3 • p2 - p3 + p4 - 2 • p0 - p1) -
          5 • (3 • p3 - p4 + p0 - 2 • p1 - p2) := by
            abel
      _ = 31 • (p0 - p1) := by rw [h0, h1, h2, h3]; simp
  · calc
      p0 - p4 = 14 • (p0 - p1) -
          2 • (3 • p0 - p1 + p2 - 2 • p3 - p4) +
          3 • (3 • p1 - p2 + p3 - 2 • p4 - p0) +
          (3 • p2 - p3 + p4 - 2 • p0 - p1) -
          2 • (3 • p3 - p4 + p0 - 2 • p1 - p2) := by
            abel
      _ = 14 • (p0 - p1) := by rw [h0, h1, h2, h3]; simp

/-- The subgroup generated by the four differences from a chosen cusp. -/
def orderTwentyFiveBasedCuspSubgroup
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A) : AddSubgroup A :=
  AddSubgroup.closure {p0 - p1, p0 - p2, p0 - p3, p0 - p4}

/-- The full based cuspidal subgroup is generated by the first adjacent
difference. -/
theorem orderTwentyFiveBasedCuspSubgroup_eq_zmultiples
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    orderTwentyFiveBasedCuspSubgroup p0 p1 p2 p3 p4 =
      AddSubgroup.zmultiples (p0 - p1) := by
  rcases orderTwentyFive_basedCuspDifferences_eq_multiples
      p0 p1 p2 p3 p4 h with ⟨h02, h03, h04⟩
  apply le_antisymm
  · rw [orderTwentyFiveBasedCuspSubgroup, AddSubgroup.closure_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl | rfl | rfl
    · exact AddSubgroup.mem_zmultiples (p0 - p1)
    · rw [h02]
      exact (AddSubgroup.zmultiples (p0 - p1)).nsmul_mem
        (AddSubgroup.mem_zmultiples (p0 - p1)) 6
    · rw [h03]
      exact (AddSubgroup.zmultiples (p0 - p1)).nsmul_mem
        (AddSubgroup.mem_zmultiples (p0 - p1)) 31
    · rw [h04]
      exact (AddSubgroup.zmultiples (p0 - p1)).nsmul_mem
        (AddSubgroup.mem_zmultiples (p0 - p1)) 14
  · apply AddSubgroup.zmultiples_le_of_mem
    exact AddSubgroup.subset_closure (by simp)

/-- Named downstream consumer of the cusp-divisor relation interface: two
distinct adjacent cusp classes differ by an element of exact order `71`. -/
theorem orderTwentyFive_firstCuspDifference_exactOrder
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4)
    (hne : p0 ≠ p1) :
    addOrderOf (p0 - p1) = 71 := by
  haveI : Fact (Nat.Prime 71) := ⟨by decide⟩
  apply addOrderOf_eq_prime
  · exact orderTwentyFive_seventyOne_nsmul_firstCuspDifference
      p0 p1 p2 p3 p4 h
  · exact sub_ne_zero.mpr hne

/-- If the first two cusp classes are distinct, the subgroup generated by all
four based cusp differences has exactly `71` elements. -/
theorem orderTwentyFiveBasedCuspSubgroup_natCard
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4)
    (hne : p0 ≠ p1) :
    Nat.card (orderTwentyFiveBasedCuspSubgroup p0 p1 p2 p3 p4) = 71 := by
  rw [orderTwentyFiveBasedCuspSubgroup_eq_zmultiples p0 p1 p2 p3 p4 h,
    Nat.card_zmultiples,
    orderTwentyFive_firstCuspDifference_exactOrder p0 p1 p2 p3 p4 h hne]

/-- The exact cyclic model of the subgroup generated by the five cusp
classes.  This is the finite-group input expected by the later `71`-descent. -/
noncomputable def orderTwentyFiveCuspidalSubgroupZModEquiv
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4)
    (hne : p0 ≠ p1) :
    ZMod 71 ≃+
      orderTwentyFiveBasedCuspSubgroup p0 p1 p2 p3 p4 := by
  let C := orderTwentyFiveBasedCuspSubgroup p0 p1 p2 p3 p4
  let D := p0 - p1
  have hC : C = AddSubgroup.zmultiples D :=
    orderTwentyFiveBasedCuspSubgroup_eq_zmultiples p0 p1 p2 p3 p4 h
  have hD : D ∈ C := by
    rw [hC]
    exact AddSubgroup.mem_zmultiples D
  let d : C := ⟨D, hD⟩
  apply zmodAddEquivOfGenerator (g := d)
  · intro x
    rw [AddSubgroup.mem_zmultiples_iff]
    have hx : (x : A) ∈ AddSubgroup.zmultiples D := by
      rw [← hC]
      exact x.property
    rcases hx with ⟨k, hk⟩
    exact ⟨k, Subtype.ext hk⟩
  · exact orderTwentyFiveBasedCuspSubgroup_natCard
      p0 p1 p2 p3 p4 h hne

end MazurTorsion.Kubert
