/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.EllipticCurve.VeluPair
import MazurTorsion.Kubert.OrderFive
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Ring

/-!
# The explicit quotient of the order-five Tate family

The nonzero points generated by `(0, 0)` on `orderFiveCurve c` occur in
the two opposite pairs with affine representatives `(0, 0)` and `(c, c²)`.
Vélu's paired formulas therefore give a rational map with poles only at
`x = 0` and `x = c`.  This file records the resulting target curve and
checks both its discriminant and the affine equation map.

The point constructor at the end is the named downstream consumer of the
coordinate interface.  Additivity and the dual composition are deliberately
left separate; neither is assumed by the equation calculation here.
-/

open scoped WeierstrassCurve.Affine

namespace MazurTorsion.Kubert

/-- The Vélu quotient of `orderFiveCurve c` by its marked order-five
subgroup. -/
def orderFiveVeluTarget (c : ℚ) : WeierstrassCurve ℚ :=
  ⟨1 - c, -c, -c,
    -5 * c * (c ^ 2 + 2 * c - 1),
    -c * (c ^ 4 + 10 * c ^ 3 - 5 * c ^ 2 + 15 * c - 1)⟩

@[simp] theorem orderFiveVeluTarget_a₁ (c : ℚ) :
    (orderFiveVeluTarget c).a₁ = 1 - c := rfl

@[simp] theorem orderFiveVeluTarget_a₂ (c : ℚ) :
    (orderFiveVeluTarget c).a₂ = -c := rfl

@[simp] theorem orderFiveVeluTarget_a₃ (c : ℚ) :
    (orderFiveVeluTarget c).a₃ = -c := rfl

@[simp] theorem orderFiveVeluTarget_a₄ (c : ℚ) :
    (orderFiveVeluTarget c).a₄ =
      -5 * c * (c ^ 2 + 2 * c - 1) := rfl

@[simp] theorem orderFiveVeluTarget_a₆ (c : ℚ) :
    (orderFiveVeluTarget c).a₆ =
      -c * (c ^ 4 + 10 * c ^ 3 - 5 * c ^ 2 + 15 * c - 1) := rfl

/-- The quotient discriminant is the expected fifth power of the second
factor in the source discriminant. -/
theorem orderFiveVeluTarget_discriminant (c : ℚ) :
    (orderFiveVeluTarget c).Δ =
      c * (c ^ 2 - 11 * c - 1) ^ 5 := by
  simp only [orderFiveVeluTarget, WeierstrassCurve.Δ,
    WeierstrassCurve.b₂, WeierstrassCurve.b₄, WeierstrassCurve.b₆,
    WeierstrassCurve.b₈]
  ring

/-- The checked discriminant formula makes the Vélu target elliptic away
from the two cuspidal factors of the source family. -/
theorem orderFiveVeluTarget_isElliptic
    (c : ℚ) (hc : c ≠ 0) (hfactor : c ^ 2 - 11 * c - 1 ≠ 0) :
    (orderFiveVeluTarget c).IsElliptic := by
  rw [WeierstrassCurve.isElliptic_iff, isUnit_iff_ne_zero,
    orderFiveVeluTarget_discriminant]
  exact mul_ne_zero hc (pow_ne_zero 5 hfactor)

/-- The abscissa of the paired Vélu map away from the two kernel
abscissae. -/
def orderFiveVeluX (c x : ℚ) : ℚ :=
  x + (c ^ 2 - c) / x + c ^ 2 / x ^ 2 +
    c ^ 2 * (c + 1) / (x - c) + c ^ 4 / (x - c) ^ 2

/-- The completed-ordinate multiplier, i.e. the derivative of
`orderFiveVeluX` with respect to `x`. -/
def orderFiveVeluDifferential (c x : ℚ) : ℚ :=
  1 - (c ^ 2 - c) / x ^ 2 - 2 * c ^ 2 / x ^ 3 -
    c ^ 2 * (c + 1) / (x - c) ^ 2 -
    2 * c ^ 4 / (x - c) ^ 3

/-- The ordinate of the paired Vélu map, recovered from completed
ordinates. -/
def orderFiveVeluY (c x y : ℚ) : ℚ :=
  ((2 * y + (1 - c) * x - c) * orderFiveVeluDifferential c x -
      (1 - c) * orderFiveVeluX c x + c) / 2

/-- Algebraic certificate that the explicit Vélu coordinates carry the
source equation to the target equation. -/
private theorem orderFiveVelu_residual_identity
    (c x y : ℚ) (hx0 : x ≠ 0) (hxc : x ≠ c) :
    orderFiveVeluY c x y ^ 2 +
          (1 - c) * orderFiveVeluX c x * orderFiveVeluY c x y -
          c * orderFiveVeluY c x y -
        (orderFiveVeluX c x ^ 3 - c * orderFiveVeluX c x ^ 2 -
          5 * c * (c ^ 2 + 2 * c - 1) * orderFiveVeluX c x -
          c * (c ^ 4 + 10 * c ^ 3 - 5 * c ^ 2 + 15 * c - 1)) =
      orderFiveVeluDifferential c x ^ 2 *
        (y ^ 2 + (1 - c) * x * y - c * y - (x ^ 3 - c * x ^ 2)) := by
  simp only [orderFiveVeluX, orderFiveVeluY,
    orderFiveVeluDifferential]
  field_simp [hx0, sub_ne_zero.mpr hxc]
  ring

/-- Away from the four nonidentity kernel points, the paired Vélu
coordinates send a source point to the quotient curve. -/
theorem orderFiveVelu_equation
    {c x y : ℚ}
    (hP : (orderFiveCurve c).toAffine.Nonsingular x y)
    (hx0 : x ≠ 0) (hxc : x ≠ c) :
    (orderFiveVeluTarget c).toAffine.Equation
      (orderFiveVeluX c x) (orderFiveVeluY c x y) := by
  have hsource :
      y ^ 2 + (1 - c) * x * y - c * y - (x ^ 3 - c * x ^ 2) = 0 := by
    have hcurve := hP.1
    rw [WeierstrassCurve.Affine.equation_iff] at hcurve
    simp only [orderFiveCurve_a₁, orderFiveCurve_a₂,
      orderFiveCurve_a₃, orderFiveCurve_a₄,
      orderFiveCurve_a₆] at hcurve
    linear_combination hcurve
  have htarget := orderFiveVelu_residual_identity c x y hx0 hxc
  rw [hsource, mul_zero] at htarget
  rw [WeierstrassCurve.Affine.equation_iff]
  simp only [orderFiveVeluTarget_a₁, orderFiveVeluTarget_a₂,
    orderFiveVeluTarget_a₃, orderFiveVeluTarget_a₄,
    orderFiveVeluTarget_a₆]
  linear_combination htarget

/-- Denominator-safe affine consumer of the explicit order-five Vélu
coordinates. -/
noncomputable def orderFiveVeluPoint
    {c x y : ℚ}
    (hP : (orderFiveCurve c).toAffine.Nonsingular x y)
    (hx0 : x ≠ 0) (hxc : x ≠ c)
    (hc : c ≠ 0) (hfactor : c ^ 2 - 11 * c - 1 ≠ 0) :
    (orderFiveVeluTarget c).toAffine.Point :=
  letI : (orderFiveVeluTarget c).IsElliptic :=
    orderFiveVeluTarget_isElliptic c hc hfactor
  .some (orderFiveVeluX c x) (orderFiveVeluY c x y)
    ((orderFiveVeluTarget c).toAffine.equation_iff_nonsingular.mp
      (orderFiveVelu_equation hP hx0 hxc))

end MazurTorsion.Kubert
