/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, Codex
-/

import MazurTorsion.Kubert.OrderTwentyFiveLehmerCuspCycle

/-!
# The order-twenty-five cusp-divisor lattice

The five cyclic modular units in the order-twenty-five descent have cusp-order
vector `(3, -1, 1, -2, -1)`.  This file isolates the integral linear-algebra
consequence needed by the genus-four descent: the five cyclic principal-divisor
relations annihilate every difference of cusp classes by `71`.

The relation predicate below is the explicit interface boundary.  A geometric
construction of the five divisor classes can supply it without exposing a
particular divisor implementation; `orderTwentyFive_firstCuspDifference_exactOrder`
is its named group-theoretic consumer.
-/

namespace MazurTorsion.Kubert

/-- The five cyclic relations generated by the cusp-order vector
`(3, -1, 1, -2, -1)`.  In the intended application the `pᵢ` are degree-zero
cusp classes in the Jacobian of the genus-four order-twenty-five quotient. -/
def orderTwentyFiveCuspDivisorRelations
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A) : Prop :=
  3 • p0 - p1 + p2 - 2 • p3 - p4 = 0 ∧
    (3 • p1 - p2 + p3 - 2 • p4 - p0 = 0) ∧
    (3 • p2 - p3 + p4 - 2 • p0 - p1 = 0) ∧
    (3 • p3 - p4 + p0 - 2 • p1 - p2 = 0) ∧
    3 • p4 - p0 + p1 - 2 • p2 - p3 = 0

/-- Rotating the five cusp classes preserves their cyclic divisor relations. -/
theorem orderTwentyFiveCuspDivisorRelations_rotate
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    orderTwentyFiveCuspDivisorRelations p1 p2 p3 p4 p0 := by
  rcases h with ⟨h0, h1, h2, h3, h4⟩
  exact ⟨h1, h2, h3, h4, h0⟩

/-- The determinant-`71` certificate for one adjacent cusp difference.  The
coefficients `12, -14, -5, 11` give an explicit integral row reduction of the
circulant relation matrix. -/
theorem orderTwentyFive_seventyOne_nsmul_firstCuspDifference
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    71 • (p0 - p1) = 0 := by
  rcases h with ⟨h0, h1, h2, h3, _h4⟩
  have hcombination :
      12 • (3 • p0 - p1 + p2 - 2 • p3 - p4) -
          14 • (3 • p1 - p2 + p3 - 2 • p4 - p0) -
          5 • (3 • p2 - p3 + p4 - 2 • p0 - p1) +
          11 • (3 • p3 - p4 + p0 - 2 • p1 - p2) = 0 := by
    rw [h0, h1, h2, h3]
    simp
  calc
    71 • (p0 - p1) =
        12 • (3 • p0 - p1 + p2 - 2 • p3 - p4) -
          14 • (3 • p1 - p2 + p3 - 2 • p4 - p0) -
          5 • (3 • p2 - p3 + p4 - 2 • p0 - p1) +
          11 • (3 • p3 - p4 + p0 - 2 • p1 - p2) := by
            abel
    _ = 0 := hcombination

/-- Every adjacent difference in the five-cycle is annihilated by `71`. -/
theorem orderTwentyFive_seventyOne_nsmul_adjacentCuspDifferences
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    71 • (p0 - p1) = 0 ∧ 71 • (p1 - p2) = 0 ∧
      71 • (p2 - p3) = 0 ∧ 71 • (p3 - p4) = 0 ∧
      71 • (p4 - p0) = 0 := by
  have h1 := orderTwentyFiveCuspDivisorRelations_rotate p0 p1 p2 p3 p4 h
  have h2 := orderTwentyFiveCuspDivisorRelations_rotate p1 p2 p3 p4 p0 h1
  have h3 := orderTwentyFiveCuspDivisorRelations_rotate p2 p3 p4 p0 p1 h2
  have h4 := orderTwentyFiveCuspDivisorRelations_rotate p3 p4 p0 p1 p2 h3
  exact ⟨
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p0 p1 p2 p3 p4 h,
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p1 p2 p3 p4 p0 h1,
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p2 p3 p4 p0 p1 h2,
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p3 p4 p0 p1 p2 h3,
    orderTwentyFive_seventyOne_nsmul_firstCuspDifference p4 p0 p1 p2 p3 h4⟩

/-- Every difference from a fixed cusp is annihilated by `71`.  This is the
form used when the first cusp is chosen as the Abel--Jacobi base point. -/
theorem orderTwentyFive_seventyOne_nsmul_basedCuspDifferences
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4) :
    71 • (p0 - p1) = 0 ∧ 71 • (p0 - p2) = 0 ∧
      71 • (p0 - p3) = 0 ∧ 71 • (p0 - p4) = 0 := by
  rcases orderTwentyFive_seventyOne_nsmul_adjacentCuspDifferences
      p0 p1 p2 p3 p4 h with ⟨h01, h12, h23, h34, _h40⟩
  constructor
  · exact h01
  constructor
  · calc
      71 • (p0 - p2) = 71 • (p0 - p1) + 71 • (p1 - p2) := by abel
      _ = 0 := by simp [h01, h12]
  constructor
  · calc
      71 • (p0 - p3) =
          71 • (p0 - p1) + 71 • (p1 - p2) + 71 • (p2 - p3) := by
            abel
      _ = 0 := by simp [h01, h12, h23]
  · calc
      71 • (p0 - p4) =
          71 • (p0 - p1) + 71 • (p1 - p2) +
            71 • (p2 - p3) + 71 • (p3 - p4) := by
              abel
      _ = 0 := by simp [h01, h12, h23, h34]

/-- Named downstream consumer of the cusp-divisor relation interface: two
distinct adjacent cusp classes differ by an element of exact order `71`. -/
theorem orderTwentyFive_firstCuspDifference_exactOrder
    {A : Type*} [AddCommGroup A] (p0 p1 p2 p3 p4 : A)
    (h : orderTwentyFiveCuspDivisorRelations p0 p1 p2 p3 p4)
    (hne : p0 ≠ p1) :
    addOrderOf (p0 - p1) = 71 := by
  haveI : Fact (Nat.Prime 71) := ⟨by decide⟩
  apply addOrderOf_eq_prime
  · exact orderTwentyFive_seventyOne_nsmul_firstCuspDifference
      p0 p1 p2 p3 p4 h
  · exact sub_ne_zero.mpr hne

end MazurTorsion.Kubert
