/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.Kubert.OrderSevenBacktrackingDivisionCertificateEval1
import Mathlib.Tactic.Ring

/-!
# Division-factor evaluation shard 2

This serial interpolation shard verifies a small block of rational abscissas.
-/

namespace MazurTorsion.Kubert.OrderSevenBacktrackingCertificate.Internal

private lemma eval_10 (d : ℚ) :
    DivisionEvalCertificate d 10 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

private lemma eval_11 (d : ℚ) :
    DivisionEvalCertificate d 11 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

private lemma eval_12 (d : ℚ) :
    DivisionEvalCertificate d 12 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

private lemma eval_13 (d : ℚ) :
    DivisionEvalCertificate d 13 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

private lemma eval_14 (d : ℚ) :
    DivisionEvalCertificate d 14 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

theorem divisionEvalBlock2 (d : ℚ) (i : Fin 5) :
    DivisionEvalCertificate d ((i : ℚ) + 10) := by
  fin_cases i
  · (convert eval_10 d using 1; norm_num)
  · (convert eval_11 d using 1; norm_num)
  · (convert eval_12 d using 1; norm_num)
  · (convert eval_13 d using 1; norm_num)
  · (convert eval_14 d using 1; norm_num)

end MazurTorsion.Kubert.OrderSevenBacktrackingCertificate.Internal
