/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/
module
public import MazurTorsion.Kubert.OrderSevenBacktrackingDivisionCertificateEval2
import Mathlib.Tactic.Ring

/-!
# Division-factor evaluation shard 3

This serial interpolation shard verifies a small block of rational abscissas.
-/

namespace MazurTorsion.Kubert.OrderSevenBacktrackingCertificate.Internal

private lemma eval_15 (d : ℚ) :
    DivisionEvalCertificate d 15 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

private lemma eval_16 (d : ℚ) :
    DivisionEvalCertificate d 16 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

private lemma eval_17 (d : ℚ) :
    DivisionEvalCertificate d 17 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

private lemma eval_18 (d : ℚ) :
    DivisionEvalCertificate d 18 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

private lemma eval_19 (d : ℚ) :
    DivisionEvalCertificate d 19 := by
  unfold DivisionEvalCertificate
  rw [quotient_prePsiSeven]
  simp [dualKernelPolynomial,
        divisionCofactor0,
        divisionCofactorData0,
        divisionCofactor1,
        divisionCofactorData1,
        divisionCofactor2,
        divisionCofactorData2,
        Internal.divisionCofactor0Coefficient0,
        Internal.divisionCofactor0Coefficient0Chunk0,
        Internal.divisionCofactor0Coefficient0Chunk1,
        Internal.divisionCofactor0Coefficient0Chunk2,
        Internal.divisionCofactor0Coefficient1,
        Internal.divisionCofactor0Coefficient1Chunk0,
        Internal.divisionCofactor0Coefficient1Chunk1,
        Internal.divisionCofactor0Coefficient2,
        Internal.divisionCofactor0Coefficient2Chunk0,
        Internal.divisionCofactor0Coefficient2Chunk1,
        Internal.divisionCofactor0Coefficient3,
        Internal.divisionCofactor0Coefficient3Chunk0,
        Internal.divisionCofactor0Coefficient3Chunk1,
        Internal.divisionCofactor0Coefficient4,
        Internal.divisionCofactor0Coefficient4Chunk0,
        Internal.divisionCofactor0Coefficient5,
        Internal.divisionCofactor0Coefficient5Chunk0,
        Internal.divisionCofactor0Coefficient6,
        Internal.divisionCofactor0Coefficient6Chunk0,
        Internal.divisionCofactor0Coefficient7,
        Internal.divisionCofactor0Coefficient7Chunk0,
        Internal.divisionCofactor1Coefficient0,
        Internal.divisionCofactor1Coefficient0Chunk0,
        Internal.divisionCofactor1Coefficient0Chunk1,
        Internal.divisionCofactor1Coefficient0Chunk2,
        Internal.divisionCofactor1Coefficient1,
        Internal.divisionCofactor1Coefficient1Chunk0,
        Internal.divisionCofactor1Coefficient1Chunk1,
        Internal.divisionCofactor1Coefficient2,
        Internal.divisionCofactor1Coefficient2Chunk0,
        Internal.divisionCofactor1Coefficient2Chunk1,
        Internal.divisionCofactor1Coefficient3,
        Internal.divisionCofactor1Coefficient3Chunk0,
        Internal.divisionCofactor1Coefficient3Chunk1,
        Internal.divisionCofactor1Coefficient4,
        Internal.divisionCofactor1Coefficient4Chunk0,
        Internal.divisionCofactor1Coefficient5,
        Internal.divisionCofactor1Coefficient5Chunk0,
        Internal.divisionCofactor1Coefficient6,
        Internal.divisionCofactor1Coefficient6Chunk0,
        Internal.divisionCofactor1Coefficient7,
        Internal.divisionCofactor1Coefficient7Chunk0,
        Internal.divisionCofactor2Coefficient0,
        Internal.divisionCofactor2Coefficient0Chunk0,
        Internal.divisionCofactor2Coefficient0Chunk1,
        Internal.divisionCofactor2Coefficient0Chunk2,
        Internal.divisionCofactor2Coefficient1,
        Internal.divisionCofactor2Coefficient1Chunk0,
        Internal.divisionCofactor2Coefficient1Chunk1,
        Internal.divisionCofactor2Coefficient2,
        Internal.divisionCofactor2Coefficient2Chunk0,
        Internal.divisionCofactor2Coefficient2Chunk1,
        Internal.divisionCofactor2Coefficient3,
        Internal.divisionCofactor2Coefficient3Chunk0,
        Internal.divisionCofactor2Coefficient3Chunk1,
        Internal.divisionCofactor2Coefficient4,
        Internal.divisionCofactor2Coefficient4Chunk0,
        Internal.divisionCofactor2Coefficient5,
        Internal.divisionCofactor2Coefficient5Chunk0,
        Internal.divisionCofactor2Coefficient6,
        Internal.divisionCofactor2Coefficient6Chunk0,
        Internal.divisionCofactor2Coefficient7,
        Internal.divisionCofactor2Coefficient7Chunk0,
        orderSevenQuotient,
        orderSevenB,
        orderSevenC,
        WeierstrassCurve.Ψ₂Sq,
        WeierstrassCurve.Ψ₃,
        WeierstrassCurve.preΨ₄,
        WeierstrassCurve.b₂,
        WeierstrassCurve.b₄,
        WeierstrassCurve.b₆,
        WeierstrassCurve.b₈]
  ring

public theorem divisionEvalBlock3 (d : ℚ) (i : Fin 5) :
    DivisionEvalCertificate d ((i : ℚ) + 15) := by
  fin_cases i
  · (convert eval_15 d using 1; norm_num)
  · (convert eval_16 d using 1; norm_num)
  · (convert eval_17 d using 1; norm_num)
  · (convert eval_18 d using 1; norm_num)
  · (convert eval_19 d using 1; norm_num)

end MazurTorsion.Kubert.OrderSevenBacktrackingCertificate.Internal
