import MazurTorsion.NumberTheory.XOneEighteenEisensteinIntegers

open NumberField Polynomial

#print axioms MazurTorsion.XOneEighteenDescent.common_dvd_splitEisensteinFactors_dvd_two_mul_threePrime
#print axioms MazurTorsion.XOneEighteenDescent.splitEisensteinThreePrime_associated
#print axioms MazurTorsion.XOneEighteenDescent.splitEisensteinThreePrime_prime
#print axioms MazurTorsion.XOneEighteenDescent.common_prime_splitEisensteinFactors_support
#print axioms MazurTorsion.XOneEighteenDescent.eisensteinIntegerObstruction_of_primeSupported
#print axioms MazurTorsion.XOneEighteenDescent.rationalPoint_addOrderOf_ne_eighteen_of_primeSupportedEisensteinIntegerObstruction
