import MazurTorsion.ModularCurve.AffineCuspQExpansion
import MazurTorsion.ModularCurve.XZeroCyclicQuotient

#print axioms Ideal.Fiber.exists_detectedVector_of_unit_qExpansion
#print axioms Ideal.Fiber.isAffineFiberDegreeOneCotangent_of_qParameter
#print axioms Ideal.Fiber.isFormalImmersionAtSpecMap_of_qParameter
#print axioms MazurTorsion.ModularCurve.AffineCuspQExpansion.isFormalImmersionAtSpecMap_of_unit_qExpansion

#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.PointQuotient
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.quotientMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.quotientMap_surjective
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.quotientMap_ker
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.carrier_le_nsmul_ker
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.dualMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.dualMap_mk
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.dualMap_comp_quotientMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.quotientMap_comp_dualMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.dualMap_ker
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.mapPointQuotient
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.mapPointQuotient_quotientMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalCyclicSubgroup.mapPointQuotient_dualMap

#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.PointQuotient
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.pointQuotientMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.pointQuotientDualMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.pointQuotientDualMap_comp_pointQuotientMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.pointQuotientMap_comp_pointQuotientDualMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.variableChangePointEquiv
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.variableChangePointQuotientEquiv
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.variableChangePointQuotientEquiv_pointQuotientMap
#print axioms MazurTorsion.ModularCurve.XZeroModuli.RationalDatum.variableChangePointQuotientEquiv_dualMap
