/-
Copyright (c) 2026 The AINTLIB contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AINTLIB ModularCurves project

This is a declaration-sliced adaptation of the chartwise algebraic prefix of
AINTLIB's `ForMathlib/ProjClosedImmersion.lean`. Exact source and license
provenance are recorded in `PORTING.md`.
-/

import MazurTorsion.Upstream.AINTLIB.ForMathlib.GradedQuotient
import Mathlib.RingTheory.GradedAlgebra.HomogeneousLocalization

/-!
# Away charts of a homogeneous quotient

The degree-zero away-localization map induced by a homogeneous quotient is
surjective. If the homogeneous ideal is principal, its chartwise kernel is
generated by the dehomogenized equation. These are the algebraic chart facts
needed for the projective Weierstrass smoothness argument.

The option-dependent scheme-level closed-immersion theorem from the source
file is deliberately not included.
-/

namespace HomogeneousIdeal

open HomogeneousLocalization

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
  {𝒜 : ℕ → Submodule R A} [GradedAlgebra 𝒜] (I : HomogeneousIdeal 𝒜)

private def awayValRingHom (x : Submonoid A) :
    HomogeneousLocalization 𝒜 x →+* Localization x where
  toFun := HomogeneousLocalization.val
  map_one' := HomogeneousLocalization.val_one
  map_mul' := HomogeneousLocalization.val_mul
  map_zero' := HomogeneousLocalization.val_zero
  map_add' := HomogeneousLocalization.val_add

@[simp]
private lemma awayValRingHom_apply (x : Submonoid A)
    (y : HomogeneousLocalization 𝒜 x) : awayValRingHom x y = y.val :=
  rfl

/-- The degree-zero away-localization map induced by a homogeneous quotient
is surjective. -/
theorem away_map_quotientGradingHom_surjective {d : ℕ} {s : A} (hs : s ∈ 𝒜 d) :
    Function.Surjective (Away.map (quotientGradingHom I) s) := by
  intro z
  obtain ⟨n, a', ha', rfl⟩ :=
    HomogeneousLocalization.Away.mk_surjective _ (mk_mem_quotientGrading I hs) z
  obtain ⟨a, ha, rfl⟩ := Submodule.mem_map.mp ha'
  refine ⟨HomogeneousLocalization.Away.mk 𝒜 hs n a ha, ?_⟩
  rw [Away.map_mk]
  rfl

section Kernel

private lemma away_mk_shift {e : ℕ} {s : A} (hs : s ∈ 𝒜 e) (n m : ℕ) (p : A)
    (hp : p ∈ 𝒜 (n • e)) :
    HomogeneousLocalization.Away.mk 𝒜 hs (n + m) (s ^ m * p)
        (by
          simpa only [add_smul, add_comm] using
            SetLike.mul_mem_graded (SetLike.pow_mem_graded m hs) hp) =
      HomogeneousLocalization.Away.mk 𝒜 hs n p hp := by
  apply val_injective
  rw [Away.val_mk, Away.val_mk, Localization.mk_eq_mk_iff,
    Localization.r_iff_exists]
  exact ⟨1, by simp [pow_add, mul_assoc]⟩

private lemma away_mk_mul {e : ℕ} {s : A} (hs : s ∈ 𝒜 e) (i j : ℕ) (p q : A)
    (hp : p ∈ 𝒜 (i • e)) (hq : q ∈ 𝒜 (j • e)) :
    HomogeneousLocalization.Away.mk 𝒜 hs i p hp *
        HomogeneousLocalization.Away.mk 𝒜 hs j q hq =
      HomogeneousLocalization.Away.mk 𝒜 hs (i + j) (p * q)
        (by
          simpa only [add_smul] using SetLike.mul_mem_graded hp hq) := by
  apply val_injective
  rw [val_mul, Away.val_mk, Away.val_mk, Away.val_mk, Localization.mk_mul,
    Localization.mk_eq_mk_iff, Localization.r_iff_exists]
  exact ⟨1, by simp [pow_add]⟩

private lemma ker_away_map_le_span {d : ℕ} {F : A} (hF : F ∈ 𝒜 d)
    (hI : I.toIdeal = Ideal.span {F}) {s : A} (hs : s ∈ 𝒜 1) :
    RingHom.ker (Away.map (quotientGradingHom I) s) ≤
      Ideal.span {HomogeneousLocalization.Away.mk 𝒜 hs d F (by simpa using hF)} := by
  intro z hz
  obtain ⟨n, p, hp, rfl⟩ := HomogeneousLocalization.Away.mk_surjective _ hs z
  rw [RingHom.mem_ker, Away.map_mk] at hz
  have hval := congrArg
    (awayValRingHom (𝒜 := quotientGrading I)
      (Submonoid.powers ((quotientGradingHom I) s))) hz
  rw [awayValRingHom_apply, awayValRingHom_apply, Away.val_mk, val_zero] at hval
  have hzero : algebraMap (A ⧸ I.toIdeal)
      (Localization (Submonoid.powers ((quotientGradingHom I) s)))
      ((quotientGradingHom I) p) = 0 := by
    rw [← Localization.mk_one_eq_algebraMap, Localization.mk_eq_mk',
      IsLocalization.mk'_eq_zero_iff]
    rwa [Localization.mk_eq_mk', IsLocalization.mk'_eq_zero_iff] at hval
  obtain ⟨⟨c, k, rfl⟩, hc⟩ := (IsLocalization.map_eq_zero_iff
    (Submonoid.powers ((quotientGradingHom I) s)) _ _).mp hzero
  have hmem : s ^ k * p ∈ I.toIdeal := by
    have : (quotientGradingHom I) (s ^ k * p) = 0 := by
      rw [map_mul, map_pow]
      exact hc
    rwa [quotientGradingHom_apply, ← RingHom.mem_ker, Ideal.mk_ker] at this
  rw [hI, Ideal.mem_span_singleton] at hmem
  obtain ⟨c, hc'⟩ := hmem
  have hgraded : s ^ k * p ∈ 𝒜 (k + n) := by
    simpa [add_smul, smul_eq_mul, mul_comm] using
      SetLike.mul_mem_graded (SetLike.pow_mem_graded k hs) hp
  have hcomponent := congrArg (fun x => (DirectSum.decompose 𝒜 x (k + n) : A)) hc'
  simp only at hcomponent
  rw [DirectSum.decompose_of_mem_same 𝒜 hgraded] at hcomponent
  by_cases hd : d ≤ k + n
  · have hcomp : s ^ k * p =
        F * (DirectSum.decompose 𝒜 c (k + n - d) : A) := by
      have hmul := DirectSum.coe_decompose_mul_add_of_left_mem (j := k + n - d) 𝒜
        (b := c) hF
      rw [show d + (k + n - d) = k + n by lia] at hmul
      rw [hcomponent, hmul]
    have hcDegree : (DirectSum.decompose 𝒜 c (k + n - d) : A) ∈
        𝒜 ((k + n - d) • 1) := by
      simp
    rw [Ideal.mem_span_singleton]
    refine ⟨HomogeneousLocalization.Away.mk 𝒜 hs (k + n - d)
      (DirectSum.decompose 𝒜 c (k + n - d) : A) hcDegree, ?_⟩
    rw [away_mk_mul]
    apply val_injective
    rw [Away.val_mk, Away.val_mk, Localization.mk_eq_mk_iff,
      Localization.r_iff_exists]
    refine ⟨1, ?_⟩
    simp only [OneMemClass.coe_one, one_mul]
    rw [← hcomp, show d + (k + n - d) = k + n by lia]
    ring
  · rw [DirectSum.coe_decompose_mul_of_left_mem_of_not_le 𝒜 hF hd] at hcomponent
    have hmkZero : HomogeneousLocalization.Away.mk 𝒜 hs n p hp = 0 := by
      rw [← away_mk_shift (𝒜 := 𝒜) hs n k p hp]
      apply val_injective
      rw [Away.val_mk, val_zero, hcomponent]
      exact Localization.mk_zero _
    rw [hmkZero]
    exact zero_mem _

/-- For a principal homogeneous quotient, the kernel on a degree-one away
chart is generated by the dehomogenized equation. -/
theorem ker_away_map_quotientGradingHom {d : ℕ} {F : A} (hF : F ∈ 𝒜 d)
    (hI : I.toIdeal = Ideal.span {F}) {s : A} (hs : s ∈ 𝒜 1) :
    RingHom.ker (Away.map (quotientGradingHom I) s) =
      Ideal.span {HomogeneousLocalization.Away.mk 𝒜 hs d F (by simpa using hF)} := by
  refine le_antisymm (ker_away_map_le_span I hF hI hs) ?_
  intro z hz
  rw [Ideal.mem_span_singleton] at hz
  obtain ⟨c, rfl⟩ := hz
  rw [RingHom.mem_ker, map_mul]
  have hFzero : Away.map (quotientGradingHom I) s
      (HomogeneousLocalization.Away.mk 𝒜 hs d F (by simp [hF])) = 0 := by
    rw [Away.map_mk]
    have hFI : (quotientGradingHom I) F = 0 := by
      rw [quotientGradingHom_apply, ← RingHom.mem_ker, Ideal.mk_ker, hI]
      exact Ideal.subset_span rfl
    apply val_injective
    rw [Away.val_mk, val_zero, hFI]
    exact Localization.mk_zero _
  rw [hFzero, zero_mul]

end Kernel

end HomogeneousIdeal
