/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.ModularCurve.AffineCuspArithmeticConsumers

/-!
# A represented one-coordinate integral cusp chart

This file constructs the standard affine cusp chart over an arbitrary base ring,
rather than postulating its local geometry.  Its coordinate ring is the
one-variable polynomial algebra, presented as `MvPolynomial PUnit R`.  Evaluation
at zero gives a genuine affine structural section.  After passing to every prime
fibre, the canonical point selected by that section is proved to be generated by
the polynomial variable.  Consequently its image in the localized fibre ring
generates the maximal ideal and survives modulo its square.

The final theorem is a real consumer: the checked Hecke/q-expansion criterion
proves formal immersion for a genuine morphism out of this represented affine
chart without taking a cusp prime, a section, a maximal-ideal equality, or a
nonzero cotangent class as premises.

This is the standard local model required by an integral modular cusp; it does not
identify any modular curve with this chart.  The remaining modular-geometric seam
is an affine neighbourhood of the infinity section on integral `X_0(N)`, together
with its comparison to this coordinate and the optimal-quotient q-expansion.
-/

noncomputable section

open Algebra TensorProduct AlgebraicGeometry CategoryTheory
open Ideal.Fiber

namespace MazurTorsion.ModularCurve.AffineCuspPolynomialChart

open MazurTorsion.ModularCurve.AffineCuspQExpansion

universe u

/-- The represented one-coordinate affine chart over `R`. -/
abbrev CoordinateRing (R : Type u) [CommRing R] := MvPolynomial PUnit R

/-- Evaluation at the origin of the affine coordinate. -/
noncomputable def zeroRetraction (R : Type u) [CommRing R] :
    CoordinateRing R →ₐ[R] R :=
  MvPolynomial.aeval fun _ => 0

/-- The zero evaluation is represented by an actual section of affine schemes. -/
noncomputable def zeroSection (R : Type u) [CommRing R] :
    AffineStructuralSection (R := R) (T := CoordinateRing R) where
  toSpec := Spec.map (CommRingCat.ofHom (zeroRetraction R).toRingHom)
  isSection := by
    rw [← Spec.map_comp, ← CommRingCat.ofHom_comp]
    convert Spec.map_id (.of R)
    ext r
    simp [zeroRetraction]

/-- Extracting the coordinate-ring retraction from the represented section
recovers evaluation at zero. -/
theorem zeroSection_retraction (R : Type u) [CommRing R] :
    (zeroSection R).retraction = zeroRetraction R := by
  apply AlgHom.ext
  intro f
  simp [AffineStructuralSection.retraction, zeroSection, zeroRetraction]

/-- Base change of the one-coordinate chart is the ordinary polynomial ring over
the residue field. -/
noncomputable def fiberCoordinate
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    p.Fiber (CoordinateRing R) ≃ₐ[p.ResidueField]
      Polynomial p.ResidueField :=
  (MvPolynomial.algebraTensorAlgEquiv R p.ResidueField).trans
    (MvPolynomial.uniqueAlgEquiv p.ResidueField PUnit)

/-- The coordinate in the special fibre, written before applying
`fiberCoordinate`. -/
noncomputable def fiberVariable
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    p.Fiber (CoordinateRing R) :=
  (fiberCoordinate R p).symm Polynomial.X

/-- Evaluation on the base-changed section agrees with evaluation of the fibre
polynomial at zero. -/
theorem fiberRetraction_eq_eval
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    (zeroSection R).fiberRetraction p =
      (Polynomial.aeval (0 : p.ResidueField)).comp
        (fiberCoordinate R p).toAlgHom := by
  apply Algebra.TensorProduct.ext'
  intro k f
  simp only [AlgHom.coe_comp, Polynomial.coe_aeval_eq_eval,
    AlgEquiv.coe_toAlgHom, Function.comp_apply]
  rw [AffineStructuralSection.fiberRetraction,
    Algebra.TensorProduct.lift_tmul, zeroSection_retraction]
  simp only [AlgHom.coe_id, id_eq, AlgHom.coe_comp, Function.comp_apply,
    Algebra.ofId_apply]
  induction f using MvPolynomial.induction_on with
  | C a => simp [fiberCoordinate, zeroRetraction]
  | add f g hf hg =>
      simpa only [map_add, tmul_add, mul_add, Polynomial.eval_add] using
        congrArg₂ (· + ·) hf hg
  | mul_X f i hf => simp [fiberCoordinate, zeroRetraction]

/-- Evaluation at zero on a one-variable polynomial ring has kernel generated by
the coordinate. -/
private theorem ker_zeroRetraction (K : Type u) [Field K] :
    RingHom.ker (zeroRetraction K).toRingHom =
      Ideal.span {(MvPolynomial.X default : CoordinateRing K)} := by
  ext f
  rw [RingHom.mem_ker, Ideal.mem_span_singleton]
  rw [← map_dvd_iff (MvPolynomial.uniqueAlgEquiv K PUnit)]
  change MvPolynomial.eval₂ (algebraMap K K) (fun _ => 0) f = 0 ↔ _
  rw [← MvPolynomial.eval₂_const_uniqueAlgEquiv]
  simp [Polynomial.X_dvd_iff, Polynomial.coeff_zero_eq_eval_zero]

/-- The canonical fibre point selected by the zero section is exactly the
principal coordinate ideal. -/
theorem fiberPrime_eq_span
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    (zeroSection R).fiberPrime p = Ideal.span {fiberVariable R p} := by
  ext f
  rw [AffineStructuralSection.fiberPrime, RingHom.mem_ker]
  rw [fiberRetraction_eq_eval]
  rw [Ideal.mem_span_singleton]
  rw [← map_dvd_iff (fiberCoordinate R p)]
  simp [fiberVariable, Polynomial.X_dvd_iff,
    Polynomial.coeff_zero_eq_aeval_zero]

/-- The local q-parameter obtained by localizing the special-fibre coordinate at
the canonical cusp prime. -/
noncomputable def qParameter
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    Localization.AtPrime ((zeroSection R).fiberPrime p) :=
  algebraMap (p.Fiber (CoordinateRing R))
    (Localization.AtPrime ((zeroSection R).fiberPrime p))
    (fiberVariable R p)

/-- The constructed q-parameter generates the maximal ideal of the localized
special fibre. -/
theorem maximalIdeal_eq_span_qParameter
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    IsLocalRing.maximalIdeal
        (Localization.AtPrime ((zeroSection R).fiberPrime p)) =
      Ideal.span {qParameter R p} := by
  let locMap := algebraMap (p.Fiber (CoordinateRing R))
    (Localization.AtPrime ((zeroSection R).fiberPrime p))
  calc
    IsLocalRing.maximalIdeal
        (Localization.AtPrime ((zeroSection R).fiberPrime p)) =
        Ideal.map locMap ((zeroSection R).fiberPrime p) :=
      Localization.AtPrime.map_eq_maximalIdeal.symm
    _ = Ideal.map locMap (Ideal.span {fiberVariable R p}) :=
      congrArg (Ideal.map locMap) (fiberPrime_eq_span R p)
    _ = Ideal.span {qParameter R p} := by
      rw [Ideal.map_span]
      simp [locMap, qParameter]

/-- The special-fibre coordinate is nonzero. -/
theorem fiberVariable_ne_zero
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    fiberVariable R p ≠ 0 := by
  intro hzero
  have hX := congrArg (fiberCoordinate R p) hzero
  apply (Polynomial.X_ne_zero :
    (Polynomial.X : Polynomial p.ResidueField) ≠ 0)
  simpa only [fiberVariable, AlgEquiv.apply_symm_apply, map_zero] using hX

/-- Localization at the cusp does not kill the q-parameter. -/
theorem qParameter_ne_zero
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    qParameter R p ≠ 0 := by
  letI : IsDomain (p.Fiber (CoordinateRing R)) :=
    (fiberCoordinate R p).toRingEquiv.toMulEquiv.isDomain _
  intro hzero
  apply fiberVariable_ne_zero R p
  apply (IsLocalization.injective
      (Localization.AtPrime ((zeroSection R).fiberPrime p))
      ((zeroSection R).fiberPrime p).primeCompl_le_nonZeroDivisors)
  simpa [qParameter] using hzero

/-- The q-parameter gives a nonzero cotangent class: it does not belong to the
square of the cusp maximal ideal. -/
theorem qParameter_not_mem_maximalIdeal_sq
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    qParameter R p ∉
      IsLocalRing.maximalIdeal
          (Localization.AtPrime ((zeroSection R).fiberPrime p)) ^ 2 := by
  letI : IsDomain (p.Fiber (CoordinateRing R)) :=
    (fiberCoordinate R p).toRingEquiv.toMulEquiv.isDomain _
  intro hsq
  rw [maximalIdeal_eq_span_qParameter,
    Ideal.span_singleton_pow] at hsq
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton.mp hsq
  have hcancel : (1 : Localization.AtPrime
      ((zeroSection R).fiberPrime p)) = qParameter R p * c := by
    apply mul_left_cancel₀ (qParameter_ne_zero R p)
    simpa [pow_two, mul_assoc] using hc
  have hunit : IsUnit (qParameter R p) :=
    isUnit_iff_exists_inv.mpr ⟨c, hcancel.symm⟩
  have hmem : qParameter R p ∈ IsLocalRing.maximalIdeal
      (Localization.AtPrime ((zeroSection R).fiberPrime p)) := by
    rw [maximalIdeal_eq_span_qParameter]
    exact Ideal.mem_span_singleton_self _
  exact (IsLocalRing.mem_maximalIdeal (qParameter R p)).mp hmem hunit

/-- The explicit fibre coordinate transports Hilbert-basis Noetherianity to the
represented special fibre. -/
instance fiber_isNoetherianRing
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] :
    IsNoetherianRing (p.Fiber (CoordinateRing R)) :=
  isNoetherianRing_of_ringEquiv (Polynomial p.ResidueField)
    (fiberCoordinate R p).symm.toRingEquiv

/-- The represented polynomial cusp chart feeds the checked Hecke/q-expansion
formal-immersion criterion.  All local cusp geometry is now constructed; the
remaining inputs describe the quotient-side expansion. -/
theorem isFormalImmersionAtSpecMap_of_heckeEigen_qExpansion
    {R S : Type u} [CommRing R] [CommRing S]
    [Algebra R S] [IsNoetherianRing R] [IsNoetherianRing S]
    (p : Ideal R) [p.IsPrime]
    (g : S →ₐ[R] CoordinateRing R)
    (sourceParameter : Localization.AtPrime
      (((zeroSection R).fiberPrime p).comap (Ideal.Fiber.map p g)))
    (hsourceMem : sourceParameter ∈ IsLocalRing.maximalIdeal
      (Localization.AtPrime
        (((zeroSection R).fiberPrime p).comap (Ideal.Fiber.map p g))))
    (qCoordinate :
      LocalCompletion.Ring
          (Localization.AtPrime ((zeroSection R).fiberPrime p)) ≃+*
        PowerSeries
          (IsLocalRing.ResidueField
            (Localization.AtPrime ((zeroSection R).fiberPrime p))))
    (Q : PowerSeries
      (IsLocalRing.ResidueField
        (Localization.AtPrime ((zeroSection R).fiberPrime p))))
    (hqExpansion :
      qCoordinate
          (completionRingHom
            (Localization.AtPrime ((zeroSection R).fiberPrime p))
            (localizedMap p g ((zeroSection R).fiberPrime p)
              sourceParameter)) = Q)
    (hQ : Q ≠ 0)
    (hecke : ℕ → Module.End
      (IsLocalRing.ResidueField
        (Localization.AtPrime ((zeroSection R).fiberPrime p)))
      (PowerSeries
        (IsLocalRing.ResidueField
          (Localization.AtPrime ((zeroSection R).fiberPrime p)))))
    (eigenvalue : ℕ →
      IsLocalRing.ResidueField
        (Localization.AtPrime ((zeroSection R).fiberPrime p)))
    (hfirst : ∀ n, PowerSeries.coeff 1 (hecke n Q) =
      PowerSeries.coeff n Q)
    (heigen : ∀ n, hecke n Q = eigenvalue n • Q) :
    IsFormalImmersionAt
      (Spec.map (CommRingCat.ofHom g.toRingHom))
      (targetSpecPoint p ((zeroSection R).fiberPrime p)) :=
  isFormalImmersionAtSpecMap_of_heckeEigen_qExpansion_of_structuralSection
      p g (zeroSection R) (qParameter R p)
      (maximalIdeal_eq_span_qParameter R p)
      (qParameter_not_mem_maximalIdeal_sq R p) sourceParameter hsourceMem
      qCoordinate Q hqExpansion hQ hecke eigenvalue hfirst heigen

section ArithmeticConsumers

open MazurTorsion.EllipticCurve
open MazurTorsion.IntegerPrimeSpecialization
open MazurTorsion.OrderThirtyFive
open MazurTorsion.PrimeOrder
open WeierstrassCurve WeierstrassCurve.Affine

private abbrev FiveBase := atFive.adicCompletionIntegers ℚ

private abbrev FivePrime : Ideal FiveBase :=
  MazurTorsion.PrimeOrder.affineCuspSpecialFiberIdealAtFive

private noncomputable abbrev FiveCuspPrime :
    Ideal (FivePrime.Fiber (CoordinateRing FiveBase)) :=
  (zeroSection FiveBase).fiberPrime FivePrime

/-- At the selected auxiliary prime five, the constructed polynomial cusp
geometry feeds the unconditional prime-order arithmetic endpoint.  Only the
quotient-side Hecke expansion and the two genuine modular sections remain as
geometric inputs. -/
theorem rationalPoint_primeOrder_ne_of_polynomialCuspAtFive
    {E : WeierstrassCurve ℚ} [E.IsElliptic]
    {S : Type} [CommRing S] [Algebra FiveBase S]
    [IsNoetherianRing S]
    (g : S →ₐ[FiveBase] CoordinateRing FiveBase)
    (modularSection :
      Spec (.of FiveBase) ⟶ Spec (.of (CoordinateRing FiveBase)))
    (sourceParameter : Localization.AtPrime
      (FiveCuspPrime.comap (Ideal.Fiber.map FivePrime g)))
    (hsourceMem : sourceParameter ∈ IsLocalRing.maximalIdeal
      (Localization.AtPrime
        (FiveCuspPrime.comap (Ideal.Fiber.map FivePrime g))))
    (qCoordinate :
      LocalCompletion.Ring (Localization.AtPrime FiveCuspPrime) ≃+*
        PowerSeries
          (IsLocalRing.ResidueField
            (Localization.AtPrime FiveCuspPrime)))
    (Q : PowerSeries
      (IsLocalRing.ResidueField (Localization.AtPrime FiveCuspPrime)))
    (hqExpansion :
      qCoordinate
          (completionRingHom (Localization.AtPrime FiveCuspPrime)
            (localizedMap FivePrime g FiveCuspPrime sourceParameter)) = Q)
    (hQ : Q ≠ 0)
    (hecke : ℕ → Module.End
      (IsLocalRing.ResidueField (Localization.AtPrime FiveCuspPrime))
      (PowerSeries
        (IsLocalRing.ResidueField (Localization.AtPrime FiveCuspPrime))))
    (eigenvalue : ℕ →
      IsLocalRing.ResidueField (Localization.AtPrime FiveCuspPrime))
    (hfirst : ∀ n, PowerSeries.coeff 1 (hecke n Q) =
      PowerSeries.coeff n Q)
    (heigen : ∀ n, hecke n Q = eigenvalue n • Q)
    (hne : modularSection ≠ (zeroSection FiveBase).toSpec)
    (hspecializes : ¬ atFive.valuation ℚ E.j ≤ 1 →
      modularSection (IsLocalRing.closedPoint FiveBase) =
        (zeroSection FiveBase).toSpec
          (IsLocalRing.closedPoint FiveBase))
    (hquotient : ¬ atFive.valuation ℚ E.j ≤ 1 →
      modularSection ≫ Spec.map (CommRingCat.ofHom g.toRingHom) =
        (zeroSection FiveBase).toSpec ≫
          Spec.map (CommRingCat.ofHom g.toRingHom))
    (P : E.toAffine.Point)
    (N : ℕ) (hprime : N.Prime) (hN : 11 ≤ N) :
    addOrderOf P ≠ N :=
  rationalPoint_primeOrder_ne_of_affineCuspHeckeQExpansionAtFive_of_structuralSection
      g (zeroSection FiveBase) modularSection (qParameter FiveBase FivePrime)
      (maximalIdeal_eq_span_qParameter FiveBase FivePrime)
      (qParameter_not_mem_maximalIdeal_sq FiveBase FivePrime)
      sourceParameter hsourceMem qCoordinate Q hqExpansion hQ hecke eigenvalue
      hfirst heigen hne hspecializes hquotient P N hprime hN

private abbrev ElevenBase := atEleven.adicCompletionIntegers ℚ

private abbrev ElevenPrime : Ideal ElevenBase :=
  MazurTorsion.OrderThirtyFive.affineCuspSpecialFiberIdealAtEleven

private noncomputable abbrev ElevenCuspPrime :
    Ideal (ElevenPrime.Fiber (CoordinateRing ElevenBase)) :=
  (zeroSection ElevenBase).fiberPrime ElevenPrime

/-- At auxiliary prime eleven, the same constructed cusp geometry feeds the
unconditional order-35 arithmetic endpoint. -/
theorem rationalPoint_orderThirtyFive_ne_of_polynomialCuspAtEleven
    {E : WeierstrassCurve ℚ} [E.IsElliptic]
    {S : Type} [CommRing S] [Algebra ElevenBase S]
    [IsNoetherianRing S]
    (g : S →ₐ[ElevenBase] CoordinateRing ElevenBase)
    (modularSection :
      Spec (.of ElevenBase) ⟶ Spec (.of (CoordinateRing ElevenBase)))
    (sourceParameter : Localization.AtPrime
      (ElevenCuspPrime.comap (Ideal.Fiber.map ElevenPrime g)))
    (hsourceMem : sourceParameter ∈ IsLocalRing.maximalIdeal
      (Localization.AtPrime
        (ElevenCuspPrime.comap (Ideal.Fiber.map ElevenPrime g))))
    (qCoordinate :
      LocalCompletion.Ring (Localization.AtPrime ElevenCuspPrime) ≃+*
        PowerSeries
          (IsLocalRing.ResidueField
            (Localization.AtPrime ElevenCuspPrime)))
    (Q : PowerSeries
      (IsLocalRing.ResidueField (Localization.AtPrime ElevenCuspPrime)))
    (hqExpansion :
      qCoordinate
          (completionRingHom (Localization.AtPrime ElevenCuspPrime)
            (localizedMap ElevenPrime g ElevenCuspPrime
              sourceParameter)) = Q)
    (hQ : Q ≠ 0)
    (hecke : ℕ → Module.End
      (IsLocalRing.ResidueField (Localization.AtPrime ElevenCuspPrime))
      (PowerSeries
        (IsLocalRing.ResidueField (Localization.AtPrime ElevenCuspPrime))))
    (eigenvalue : ℕ →
      IsLocalRing.ResidueField (Localization.AtPrime ElevenCuspPrime))
    (hfirst : ∀ n, PowerSeries.coeff 1 (hecke n Q) =
      PowerSeries.coeff n Q)
    (heigen : ∀ n, hecke n Q = eigenvalue n • Q)
    (hne : modularSection ≠ (zeroSection ElevenBase).toSpec)
    (hspecializes : ¬ atEleven.valuation ℚ E.j ≤ 1 →
      modularSection (IsLocalRing.closedPoint ElevenBase) =
        (zeroSection ElevenBase).toSpec
          (IsLocalRing.closedPoint ElevenBase))
    (hquotient : ¬ atEleven.valuation ℚ E.j ≤ 1 →
      modularSection ≫ Spec.map (CommRingCat.ofHom g.toRingHom) =
        (zeroSection ElevenBase).toSpec ≫
          Spec.map (CommRingCat.ofHom g.toRingHom))
    (P : E.toAffine.Point) :
    addOrderOf P ≠ 35 :=
  rationalPoint_orderThirtyFive_ne_of_affineCuspHeckeQExpansionAtEleven_of_structuralSection
      g (zeroSection ElevenBase) modularSection
      (qParameter ElevenBase ElevenPrime)
      (maximalIdeal_eq_span_qParameter ElevenBase ElevenPrime)
      (qParameter_not_mem_maximalIdeal_sq ElevenBase ElevenPrime)
      sourceParameter hsourceMem qCoordinate Q hqExpansion hQ hecke eigenvalue
      hfirst heigen hne hspecializes hquotient P

end ArithmeticConsumers

end MazurTorsion.ModularCurve.AffineCuspPolynomialChart
