/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.ModularCurve.CompleteDVRCoordinate
import Mathlib.RingTheory.AdicCompletion.AsTensorProduct
import Mathlib.RingTheory.Flat.TorsionFree

/-!
# Completing a discrete valuation stalk

The maximal-ideal-adic completion of a discrete valuation ring is again a discrete valuation
ring.  This file proves the missing instance bridge needed to apply the power-series coordinate
construction to the completed stalk of a smooth curve.

The domain argument is explicit.  Flatness of Noetherian adic completion keeps the image of a
uniformizer regular.  The completed maximal ideal is generated by that image, and adic
separatedness then factors every nonzero completed element as a unit times a power of the
uniformizer.  This simultaneously rules out zero divisors and supplies the DVR factorization.

For coefficients, an algebra over a field is required already on the uncompleted stalk, and its
map onto the residue field is required to be surjective.  These are exactly equal-characteristic
coefficient-field data.  They cannot be supplied by a residue-characteristic field for a
mixed-characteristic DVR.
-/

namespace MazurTorsion.ModularCurve

open _root_.AlgebraicGeometry
open CategoryTheory Ideal
open TauCeti.AlgebraicGeometry.SchemeWeilDivisor

universe u

namespace CompleteDVRStalk

noncomputable section

/-- In a separated local ring with principal maximal ideal, every nonzero element is a unit times
a power of a chosen generator.  No domain hypothesis is used. -/
theorem exists_unit_mul_pow_of_maximalIdeal_eq_span
    {A : Type*} [CommRing A] [IsLocalRing A]
    [IsHausdorff (IsLocalRing.maximalIdeal A) A]
    {q x : A} (hmax : IsLocalRing.maximalIdeal A = Ideal.span {q}) (hx : x ≠ 0) :
    ∃ (n : ℕ) (v : Aˣ), x = v * q ^ n := by
  classical
  have hex : ∃ N : ℕ, x ∉ IsLocalRing.maximalIdeal A ^ N := by
    by_contra h
    push Not at h
    apply hx
    apply IsHausdorff.haus (I := IsLocalRing.maximalIdeal A) (M := A) inferInstance x
    intro n
    rw [SModEq.zero]
    simpa using h n
  have hfind_ne : Nat.find hex ≠ 0 := by
    intro hzero
    have hnot := Nat.find_spec hex
    rw [hzero, pow_zero] at hnot
    exact hnot (by simp)
  obtain ⟨n, hn⟩ := Nat.exists_eq_succ_of_ne_zero hfind_ne
  have hxmem : x ∈ IsLocalRing.maximalIdeal A ^ n := by
    apply Classical.not_not.mp
    exact Nat.find_min hex (hn ▸ Nat.lt_succ_self n)
  have hxnot : x ∉ IsLocalRing.maximalIdeal A ^ (n + 1) := by
    simpa [hn] using Nat.find_spec hex
  rw [hmax, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hxmem hxnot
  obtain ⟨a, ha⟩ := hxmem
  have haunit : IsUnit a := by
    have ha_not_mem : a ∉ IsLocalRing.maximalIdeal A := by
      intro hamem
      rw [hmax, Ideal.mem_span_singleton] at hamem
      obtain ⟨b, hb⟩ := hamem
      apply hxnot
      refine ⟨b, ?_⟩
      rw [ha, hb, pow_succ]
      ring
    simpa [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] using ha_not_mem
  obtain ⟨v, rfl⟩ := haunit
  exact ⟨n, v, by simp [ha, mul_comm]⟩

/-- A coefficient-field section of a local homomorphism to a field surjects onto the residue
field.  This is the algebraic form in which a rational section of a curve supplies the coefficient
input for its completed local ring. -/
theorem coefficientField_surjective_of_algebraMap_retraction
    {K A : Type*} [Field K] [CommRing A] [IsLocalRing A] [Algebra K A]
    (r : A →+* K) [IsLocalHom r]
    (hretract : r.comp (algebraMap K A) = RingHom.id K) :
    Function.Surjective
      ((Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)).comp (algebraMap K A)) := by
  have hr : Function.Surjective r := by
    intro c
    refine ⟨algebraMap K A c, ?_⟩
    exact DFunLike.congr_fun hretract c
  intro y
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective y
  refine ⟨r a, ?_⟩
  apply (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).mpr
  rw [← IsLocalRing.ker_eq_maximalIdeal r hr, RingHom.mem_ker, map_sub]
  have hsection := DFunLike.congr_fun hretract (r a)
  change r (algebraMap K A (r a)) = r a at hsection
  rw [hsection, sub_self]

variable (R : Type*) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]

private abbrev Completion :=
  AdicCompletion (IsLocalRing.maximalIdeal R) R

/-- The image of a DVR uniformizer generates the maximal ideal of its completion. -/
theorem maximalIdeal_completion_eq_span {q : R} (hq : Irreducible q) :
    IsLocalRing.maximalIdeal (Completion R) =
      Ideal.span {(algebraMap R (Completion R)) q} := by
  rw [AdicCompletion.maximalIdeal_eq_map]
  calc
    (IsLocalRing.maximalIdeal R).map (algebraMap R (Completion R)) =
        (Ideal.span {q}).map (algebraMap R (Completion R)) :=
      congrArg (fun I : Ideal R ↦ I.map (algebraMap R (Completion R))) hq.maximalIdeal_eq
    _ = Ideal.span {(algebraMap R (Completion R)) q} := by
      rw [Ideal.map_span]
      simp

/-- The image of a nonzero element of a DVR is regular in its adic completion.  This is the
flatness input in the domain proof. -/
theorem isRegular_algebraMap_completion {q : R} (hq : q ≠ 0) :
    IsRegular ((algebraMap R (Completion R)) q) := by
  have hqR : IsRegular q := isRegular_iff_ne_zero.mpr hq
  have hsmulR : IsSMulRegular (Completion R) q :=
    Module.Flat.isSMulRegular_of_isRegular hqR
  have hsmulCompletion :
      IsSMulRegular (Completion R) ((algebraMap R (Completion R)) q) :=
    (isSMulRegular_algebraMap_iff (Completion R)).mpr hsmulR
  exact (Commute.isRegular_iff (fun _ ↦ mul_comm _ _)).mpr hsmulCompletion.isLeftRegular

/-- The maximal-ideal-adic completion of a DVR is a domain. -/
theorem isDomain_completion : IsDomain (Completion R) := by
  obtain ⟨q, hq⟩ := IsDiscreteValuationRing.exists_irreducible R
  have hqregular := isRegular_algebraMap_completion R hq.ne_zero
  have hfactor : ∀ {x : Completion R}, x ≠ 0 →
      ∃ (n : ℕ) (v : (Completion R)ˣ),
        x = v * (algebraMap R (Completion R) q) ^ n := by
    intro x hx
    exact exists_unit_mul_pow_of_maximalIdeal_eq_span
      (maximalIdeal_completion_eq_span R hq) hx
  have hcancel : IsCancelMulZero (Completion R) :=
    isCancelMulZero_iff_forall_isRegular.mpr fun {x} hx ↦ by
      obtain ⟨n, v, rfl⟩ := hfactor hx
      exact v.isRegular.mul (hqregular.pow n)
  letI : NoZeroDivisors (Completion R) :=
    isCancelMulZero_iff_noZeroDivisors.mp hcancel
  exact NoZeroDivisors.to_isDomain (Completion R)

/-- The maximal-ideal-adic completion of a DVR is again a DVR. -/
theorem isDiscreteValuationRing_completion :
    letI : IsDomain (Completion R) := isDomain_completion R
    IsDiscreteValuationRing (Completion R) := by
  letI : IsDomain (Completion R) := isDomain_completion R
  obtain ⟨q, hq⟩ := IsDiscreteValuationRing.exists_irreducible R
  let qhat : Completion R := algebraMap R (Completion R) q
  have hmax : IsLocalRing.maximalIdeal (Completion R) = Ideal.span {qhat} :=
    maximalIdeal_completion_eq_span R hq
  have hqhat : Irreducible qhat :=
    IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal qhat
      (isRegular_algebraMap_completion R hq.ne_zero).ne_zero hmax
  apply IsDiscreteValuationRing.ofHasUnitMulPowIrreducibleFactorization
  refine ⟨qhat, hqhat, ?_⟩
  intro x hx
  obtain ⟨n, v, hv⟩ :=
    exists_unit_mul_pow_of_maximalIdeal_eq_span hmax hx
  refine ⟨n, ?_⟩
  rw [hv]
  exact associated_unit_mul_right _ _ v.isUnit

/-- A coefficient field that surjects onto the residue field before completion still surjects
after completion.  The proof uses the checked residue-field isomorphism induced by the completion
map. -/
theorem coefficientField_surjective_completion
    (K : Type*) [Field K] [Algebra K R]
    (hcoeff : Function.Surjective
      ((Ideal.Quotient.mk (IsLocalRing.maximalIdeal R)).comp (algebraMap K R))) :
    Function.Surjective
      ((Ideal.Quotient.mk (IsLocalRing.maximalIdeal (Completion R))).comp
        (algebraMap K (Completion R))) := by
  change Function.Surjective ((IsLocalRing.residue R).comp (algebraMap K R)) at hcoeff
  change Function.Surjective
    ((IsLocalRing.residue (Completion R)).comp (algebraMap K (Completion R)))
  intro y
  obtain ⟨y, rfl⟩ := (AdicCompletion.residueField_map_bijective R).2 y
  obtain ⟨r, rfl⟩ := IsLocalRing.residue_surjective y
  obtain ⟨c, hc⟩ := hcoeff (IsLocalRing.residue R r)
  refine ⟨c, ?_⟩
  change IsLocalRing.residue (Completion R) (algebraMap K (Completion R) c) =
    IsLocalRing.ResidueField.map (algebraMap R (Completion R))
      (IsLocalRing.residue R r)
  calc
    IsLocalRing.residue (Completion R) (algebraMap K (Completion R) c) =
        IsLocalRing.residue (Completion R)
          (algebraMap R (Completion R) (algebraMap K R c)) := by
      rw [IsScalarTower.algebraMap_apply K R (Completion R)]
    _ = IsLocalRing.ResidueField.map (algebraMap R (Completion R))
          (IsLocalRing.residue R (algebraMap K R c)) := by simp
    _ = IsLocalRing.ResidueField.map (algebraMap R (Completion R))
          (IsLocalRing.residue R r) := congrArg _ hc

/-- A uniformizer remains a uniformizer after completing a DVR. -/
theorem irreducible_algebraMap_completion {q : R} (hq : Irreducible q) :
    letI : IsDomain (Completion R) := isDomain_completion R
    Irreducible ((algebraMap R (Completion R)) q) := by
  letI : IsDomain (Completion R) := isDomain_completion R
  exact IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal
    ((algebraMap R (Completion R)) q)
    (isRegular_algebraMap_completion R hq.ne_zero).ne_zero
    (maximalIdeal_completion_eq_span R hq)

/-- The power-series coordinate on a completed equal-characteristic DVR, constructed entirely
from the uncompleted DVR, its coefficient field, and a uniformizer. -/
noncomputable def stalkCompletionRingEquiv
    (K : Type*) [Field K] [Algebra K R]
    (q : R) (hq : Irreducible q)
    (hcoeff : Function.Surjective
      ((Ideal.Quotient.mk (IsLocalRing.maximalIdeal R)).comp (algebraMap K R))) :
    Completion R ≃+* PowerSeries K := by
  letI : IsDomain (Completion R) := isDomain_completion R
  letI : IsDiscreteValuationRing (Completion R) :=
    isDiscreteValuationRing_completion R
  exact CompleteDVRCoordinate.ringEquiv
    (algebraMap R (Completion R) q)
    (irreducible_algebraMap_completion R hq)
    (coefficientField_surjective_completion R K hcoeff)

/-- Construct the completed DVR coordinate from an actual local retraction onto its coefficient
field.  This is the interface expected from a rational section of a smooth curve. -/
noncomputable def stalkCompletionRingEquivOfRetraction
    (K : Type*) [Field K] [Algebra K R]
    (r : R →+* K) [IsLocalHom r]
    (hretract : r.comp (algebraMap K R) = RingHom.id K)
    (q : R) (hq : Irreducible q) :
    Completion R ≃+* PowerSeries K :=
  stalkCompletionRingEquiv R K q hq
    (coefficientField_surjective_of_algebraMap_retraction r hretract)

@[simp]
theorem stalkCompletionRingEquiv_uniformizer
    (K : Type*) [Field K] [Algebra K R]
    (q : R) (hq : Irreducible q)
    (hcoeff : Function.Surjective
      ((Ideal.Quotient.mk (IsLocalRing.maximalIdeal R)).comp (algebraMap K R))) :
    stalkCompletionRingEquiv R K q hq hcoeff (algebraMap R (Completion R) q) =
      (PowerSeries.X : PowerSeries K) := by
  letI : IsDomain (Completion R) := isDomain_completion R
  letI : IsDiscreteValuationRing (Completion R) :=
    isDiscreteValuationRing_completion R
  exact CompleteDVRCoordinate.ringEquiv_uniformizer _ _ _

end

section SmoothCurve

variable {X Y : Scheme.{u}}

/-- The checked completed-stalk coordinate at a non-generic point of a smooth integral curve.
The explicit algebra and residue-surjectivity hypotheses are the honest equal-characteristic
coefficient-field input. -/
noncomputable def smoothCurveStalkCompletionRingEquiv
    (K : Type u) [Field K] (X : Scheme.{u}) [IsIntegral X]
    (π : X ⟶ Spec (.of K)) [SmoothOfRelativeDimension 1 π]
    (x : X) (hx : x ≠ genericPoint X)
    [Algebra K (X.presheaf.stalk x)]
    (q : X.presheaf.stalk x) (hq : Irreducible q)
    (hcoeff : Function.Surjective
      ((Ideal.Quotient.mk (IsLocalRing.maximalIdeal (X.presheaf.stalk x))).comp
        (algebraMap K (X.presheaf.stalk x)))) :
    Scheme.CompletedStalk X x ≃+* PowerSeries K := by
  letI : IsDiscreteValuationRing (X.presheaf.stalk x) :=
    isDiscreteValuationRing_stalk_of_ne_genericPoint_of_smoothRelativeDimension_one
      K X π x hx
  exact stalkCompletionRingEquiv (X.presheaf.stalk x) K q hq hcoeff

/-- The completed-stalk coordinate at a smooth rational point, with the coefficient input stated
as the actual local-ring retraction furnished by that point.  This removes the lower-level residue
quotient surjectivity hypothesis from the cusp-facing API. -/
noncomputable def rationalPointStalkCompletionRingEquiv
    (K : Type u) [Field K] (X : Scheme.{u}) [IsIntegral X]
    (π : X ⟶ Spec (.of K)) [SmoothOfRelativeDimension 1 π]
    (g : Spec (.of K) ⟶ X)
    (hx : g (IsLocalRing.closedPoint K) ≠ genericPoint X)
    [Algebra K (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))]
    (hretract :
      (Scheme.stalkClosedPointTo g).hom.comp
          (algebraMap K (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))) =
        RingHom.id K)
    (q : X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
    (hq : Irreducible q) :
    Scheme.CompletedStalk X (g (IsLocalRing.closedPoint K)) ≃+* PowerSeries K := by
  letI : IsDiscreteValuationRing
      (X.presheaf.stalk (g (IsLocalRing.closedPoint K))) :=
    isDiscreteValuationRing_stalk_of_ne_genericPoint_of_smoothRelativeDimension_one
      K X π (g (IsLocalRing.closedPoint K)) hx
  exact stalkCompletionRingEquivOfRetraction
    (X.presheaf.stalk (g (IsLocalRing.closedPoint K))) K
    (Scheme.stalkClosedPointTo g).hom hretract q hq

/-- A normalized first-`q` expansion in the coordinate constructed from the actual smooth-curve
stalk proves the formal-immersion predicate.  In particular, this consumer no longer assumes
domain, DVR, or completeness instances on the completed stalk. -/
theorem isFormalImmersionAt_of_smoothCurveStalkDVR_normalizedQExpansion
    (K : Type u) [Field K] (X : Scheme.{u}) [IsIntegral X]
    (π : X ⟶ Spec (.of K)) [SmoothOfRelativeDimension 1 π]
    (Y : Scheme.{u}) [IsLocallyNoetherian Y]
    (f : X ⟶ Y) (g : Spec (.of K) ⟶ X)
    [IsIso (X.descResidueField (Scheme.stalkClosedPointTo g))]
    [IsIso (Y.descResidueField (Scheme.stalkClosedPointTo (g ≫ f)))]
    (hx : g (IsLocalRing.closedPoint K) ≠ genericPoint X)
    [Algebra K (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))]
    (q : X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
    (hq : Irreducible q)
    (hcoeff : Function.Surjective
      ((Ideal.Quotient.mk
          (IsLocalRing.maximalIdeal
            (X.presheaf.stalk (g (IsLocalRing.closedPoint K))))).comp
        (algebraMap K (X.presheaf.stalk (g (IsLocalRing.closedPoint K))))))
    (targetParameter : IsLocalRing.maximalIdeal
      (Y.presheaf.stalk (f (g (IsLocalRing.closedPoint K)))))
    (c : K) (hc : c ≠ 0) (F : PowerSeries K)
    (hqExpansion :
      smoothCurveStalkCompletionRingEquiv K X π
          (g (IsLocalRing.closedPoint K)) hx q hq hcoeff
        (algebraMap
          (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
          (Scheme.CompletedStalk X (g (IsLocalRing.closedPoint K)))
          ((f.stalkMap (g (IsLocalRing.closedPoint K))).hom targetParameter)) =
        PowerSeries.C c * PowerSeries.X + PowerSeries.X ^ 2 * F) :
    AlgebraicGeometry.IsFormalImmersionAt f (g (IsLocalRing.closedPoint K)) := by
  let x := g (IsLocalRing.closedPoint K)
  letI : IsDiscreteValuationRing (X.presheaf.stalk x) :=
    isDiscreteValuationRing_stalk_of_ne_genericPoint_of_smoothRelativeDimension_one
      K X π x hx
  letI : IsDomain (Scheme.CompletedStalk X x) :=
    isDomain_completion (X.presheaf.stalk x)
  letI : IsDiscreteValuationRing (Scheme.CompletedStalk X x) :=
    isDiscreteValuationRing_completion (X.presheaf.stalk x)
  apply DegreeOneCotangentCertificate.isFormalImmersionAt_of_completeDVR_normalizedQExpansion
    K X π Y f g hx
    (algebraMap (X.presheaf.stalk x) (Scheme.CompletedStalk X x) q)
    (irreducible_algebraMap_completion (X.presheaf.stalk x) hq)
    (coefficientField_surjective_completion (X.presheaf.stalk x) K hcoeff)
    targetParameter c hc F
  simpa only [smoothCurveStalkCompletionRingEquiv, stalkCompletionRingEquiv] using hqExpansion

/-- Cusp-facing formal-immersion consumer using a local retraction onto the coefficient field,
rather than a separately supplied surjectivity theorem for the residue quotient. -/
theorem isFormalImmersionAt_of_rationalPointStalkDVR_normalizedQExpansion
    (K : Type u) [Field K] (X : Scheme.{u}) [IsIntegral X]
    (π : X ⟶ Spec (.of K)) [SmoothOfRelativeDimension 1 π]
    (Y : Scheme.{u}) [IsLocallyNoetherian Y]
    (f : X ⟶ Y) (g : Spec (.of K) ⟶ X)
    [IsIso (X.descResidueField (Scheme.stalkClosedPointTo g))]
    [IsIso (Y.descResidueField (Scheme.stalkClosedPointTo (g ≫ f)))]
    (hx : g (IsLocalRing.closedPoint K) ≠ genericPoint X)
    [Algebra K (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))]
    (hretract :
      (Scheme.stalkClosedPointTo g).hom.comp
          (algebraMap K (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))) =
        RingHom.id K)
    (q : X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
    (hq : Irreducible q)
    (targetParameter : IsLocalRing.maximalIdeal
      (Y.presheaf.stalk (f (g (IsLocalRing.closedPoint K)))))
    (c : K) (hc : c ≠ 0) (F : PowerSeries K)
    (hqExpansion :
      rationalPointStalkCompletionRingEquiv K X π g hx hretract q hq
        (algebraMap
          (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
          (Scheme.CompletedStalk X (g (IsLocalRing.closedPoint K)))
          ((f.stalkMap (g (IsLocalRing.closedPoint K))).hom targetParameter)) =
        PowerSeries.C c * PowerSeries.X + PowerSeries.X ^ 2 * F) :
    AlgebraicGeometry.IsFormalImmersionAt f (g (IsLocalRing.closedPoint K)) := by
  apply isFormalImmersionAt_of_smoothCurveStalkDVR_normalizedQExpansion
    K X π Y f g hx q hq
    (coefficientField_surjective_of_algebraMap_retraction
      (Scheme.stalkClosedPointTo g).hom hretract)
    targetParameter c hc F
  simpa only [rationalPointStalkCompletionRingEquiv,
    smoothCurveStalkCompletionRingEquiv, stalkCompletionRingEquivOfRetraction] using hqExpansion

/-- The completed-stalk DVR bridge and normalized expansion separate actual local-spectrum
morphisms.  This is the downstream collision test for the constructed coordinate. -/
theorem specMap_fromStalk_eq_of_smoothCurveStalkDVR_normalizedQExpansion
    (K : Type u) [Field K] (X : Scheme.{u}) [IsIntegral X]
    (π : X ⟶ Spec (.of K)) [SmoothOfRelativeDimension 1 π]
    (Y : Scheme.{u}) [IsLocallyNoetherian Y]
    (f : X ⟶ Y) (g : Spec (.of K) ⟶ X)
    [IsIso (X.descResidueField (Scheme.stalkClosedPointTo g))]
    [IsIso (Y.descResidueField (Scheme.stalkClosedPointTo (g ≫ f)))]
    (hx : g (IsLocalRing.closedPoint K) ≠ genericPoint X)
    [Algebra K (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))]
    (q : X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
    (hq : Irreducible q)
    (hcoeff : Function.Surjective
      ((Ideal.Quotient.mk
          (IsLocalRing.maximalIdeal
            (X.presheaf.stalk (g (IsLocalRing.closedPoint K))))).comp
        (algebraMap K (X.presheaf.stalk (g (IsLocalRing.closedPoint K))))))
    (targetParameter : IsLocalRing.maximalIdeal
      (Y.presheaf.stalk (f (g (IsLocalRing.closedPoint K)))))
    (c : K) (hc : c ≠ 0) (F : PowerSeries K)
    (hqExpansion :
      smoothCurveStalkCompletionRingEquiv K X π
          (g (IsLocalRing.closedPoint K)) hx q hq hcoeff
        (algebraMap
          (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
          (Scheme.CompletedStalk X (g (IsLocalRing.closedPoint K)))
          ((f.stalkMap (g (IsLocalRing.closedPoint K))).hom targetParameter)) =
        PowerSeries.C c * PowerSeries.X + PowerSeries.X ^ 2 * F)
    (S : Type u) [CommRing S] [IsLocalRing S] [IsNoetherianRing S]
    (a b : X.presheaf.stalk (g (IsLocalRing.closedPoint K)) →+* S)
    [IsLocalHom a] [IsLocalHom b]
    (hrestrict :
      a.comp (f.stalkMap (g (IsLocalRing.closedPoint K))).hom =
        b.comp (f.stalkMap (g (IsLocalRing.closedPoint K))).hom) :
    Spec.map (CommRingCat.ofHom a) ≫
        X.fromSpecStalk (g (IsLocalRing.closedPoint K)) =
      Spec.map (CommRingCat.ofHom b) ≫
        X.fromSpecStalk (g (IsLocalRing.closedPoint K)) := by
  have hformal :=
    isFormalImmersionAt_of_smoothCurveStalkDVR_normalizedQExpansion
      K X π Y f g hx q hq hcoeff targetParameter c hc F hqExpansion
  exact hformal.specMap_fromStalk_ext_of_isNoetherian a b hrestrict

/-- The complete-DVR stalk construction feeds the arithmetic collision in its final morphism-level
form: arbitrary local points specializing to the cusp are equal when their quotient images agree.
No domain, DVR, completeness, or power-series-coordinate instance is assumed on the completed
stalk. -/
theorem spec_eq_of_smoothCurveStalkDVR_normalizedQExpansion_of_comp_eq
    (K : Type u) [Field K] (X : Scheme.{u}) [IsIntegral X]
    (π : X ⟶ Spec (.of K)) [SmoothOfRelativeDimension 1 π]
    (Y : Scheme.{u}) [IsLocallyNoetherian Y]
    (f : X ⟶ Y) (g : Spec (.of K) ⟶ X)
    [IsIso (X.descResidueField (Scheme.stalkClosedPointTo g))]
    [IsIso (Y.descResidueField (Scheme.stalkClosedPointTo (g ≫ f)))]
    (hx : g (IsLocalRing.closedPoint K) ≠ genericPoint X)
    [Algebra K (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))]
    (q : X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
    (hq : Irreducible q)
    (hcoeff : Function.Surjective
      ((Ideal.Quotient.mk
          (IsLocalRing.maximalIdeal
            (X.presheaf.stalk (g (IsLocalRing.closedPoint K))))).comp
        (algebraMap K (X.presheaf.stalk (g (IsLocalRing.closedPoint K))))))
    (targetParameter : IsLocalRing.maximalIdeal
      (Y.presheaf.stalk (f (g (IsLocalRing.closedPoint K)))))
    (c : K) (hc : c ≠ 0) (F : PowerSeries K)
    (hqExpansion :
      smoothCurveStalkCompletionRingEquiv K X π
          (g (IsLocalRing.closedPoint K)) hx q hq hcoeff
        (algebraMap
          (X.presheaf.stalk (g (IsLocalRing.closedPoint K)))
          (Scheme.CompletedStalk X (g (IsLocalRing.closedPoint K)))
          ((f.stalkMap (g (IsLocalRing.closedPoint K))).hom targetParameter)) =
        PowerSeries.C c * PowerSeries.X + PowerSeries.X ^ 2 * F)
    (S : Type u) [CommRing S] [IsLocalRing S] [IsNoetherianRing S]
    (s t : Spec (.of S) ⟶ X)
    (hs : s (IsLocalRing.closedPoint S) = g (IsLocalRing.closedPoint K))
    (ht : t (IsLocalRing.closedPoint S) = g (IsLocalRing.closedPoint K))
    (himage : s ≫ f = t ≫ f) :
    s = t := by
  have hformal :=
    isFormalImmersionAt_of_smoothCurveStalkDVR_normalizedQExpansion
      K X π Y f g hx q hq hcoeff targetParameter c hc F hqExpansion
  have hformalAtS :
      AlgebraicGeometry.IsFormalImmersionAt f
        (s (IsLocalRing.closedPoint S)) := by
    simpa only [hs] using hformal
  exact hformalAtS.spec_ext_of_comp_eq_of_isNoetherian s t
    (hs.trans ht.symm) himage

end SmoothCurve

end CompleteDVRStalk

end MazurTorsion.ModularCurve
