/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI Codex
-/

import MazurTorsion.AlgebraicGeometry.FormalImmersionNakayama
import MazurTorsion.NumberTheory.OrderThirtyFiveInfinityChartScheme
import Mathlib.Algebra.Field.ZMod
import Mathlib.RingTheory.DualNumber
import Mathlib.RingTheory.Localization.Submodule

/-!
# The characteristic-eleven cusp of the level-35 infinity chart

This file identifies the actual cusp ideal on the represented infinity chart
of the explicit level-35 hyperelliptic model.  It is the local-algebra input
needed to turn the exact first-order quotient identity into a formal
immersion at eleven.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory Polynomial

namespace MazurTorsion.OrderThirtyFive.InfinityChartCuspAtEleven

open InfinityChartScheme

/-- The residue field at the auxiliary prime eleven. -/
abbrev ResidueField := ZMod 11

local instance primeEleven : Fact (Nat.Prime 11) := ⟨by decide⟩

/-- The ideal of the selected branch `(t,s)=(0,1)` on the source open. -/
def cuspPrime : Ideal (SourceOpenRing ResidueField) :=
  RingHom.ker (cuspRetraction ResidueField).toRingHom

/-- Evaluation at the selected cusp is onto its residue field. -/
theorem cuspRetraction_surjective :
    Function.Surjective (cuspRetraction ResidueField) := by
  intro a
  exact ⟨algebraMap ResidueField (SourceOpenRing ResidueField) a,
    (cuspRetraction ResidueField).commutes a⟩

instance cuspPrime_isPrime : cuspPrime.IsPrime :=
  RingHom.ker_isPrime _

theorem cuspPrime_isMaximal : cuspPrime.IsMaximal :=
  RingHom.ker_isMaximal_of_surjective _ cuspRetraction_surjective

/-- Before localization, the selected cusp ideal is generated by the two
coordinate differences `t` and `s-1`. -/
theorem sourceCuspEvaluation_ker :
    RingHom.ker (sourceCuspEvaluation ResidueField).toRingHom =
      Ideal.span
        ({sourceT ResidueField, sourceS ResidueField - 1} :
          Set (SourceRing ResidueField)) := by
  let J : Ideal (SourceRing ResidueField) :=
    Ideal.span
      ({sourceT ResidueField, sourceS ResidueField - 1} :
        Set (SourceRing ResidueField))
  let qmap : SourceRing ResidueField →+*
      (SourceRing ResidueField) ⧸ J :=
    (Ideal.Quotient.mkₐ ResidueField J).toRingHom
  let evalThenConst : SourceRing ResidueField →+*
      (SourceRing ResidueField) ⧸ J :=
    (algebraMap ResidueField ((SourceRing ResidueField) ⧸ J)).comp
      (sourceCuspEvaluation ResidueField).toRingHom
  have hbase : qmap.comp
        (AdjoinRoot.of (sourceEquation ResidueField)) =
      (algebraMap ResidueField ((SourceRing ResidueField) ⧸ J)).comp
        (Polynomial.evalRingHom 0) := by
    apply Polynomial.ringHom_ext
    · intro r
      simp only [RingHom.comp_apply, coe_evalRingHom, eval_C]
      have hscalar :
          (AdjoinRoot.of (sourceEquation ResidueField)) (C r) =
            algebraMap ResidueField (SourceRing ResidueField) r := by
        simpa only [RingHom.comp_apply, Polynomial.algebraMap_apply,
          Algebra.algebraMap_self, RingHom.id_apply] using
            (DFunLike.congr_fun
              (AdjoinRoot.algebraMap_eq'
                (f := sourceEquation ResidueField) ResidueField) r).symm
      rw [hscalar]
      exact (Ideal.Quotient.mkₐ ResidueField J).commutes r
    · change qmap (sourceT ResidueField) = _
      rw [show qmap (sourceT ResidueField) = 0 by
        apply Ideal.Quotient.eq_zero_iff_mem.mpr
        exact Ideal.subset_span (by simp)]
      simp
  have hevalBase :
      (sourceCuspEvaluation ResidueField).toRingHom.comp
          (AdjoinRoot.of (sourceEquation ResidueField)) =
        Polynomial.evalRingHom 0 := by
    apply Polynomial.ringHom_ext
    · intro r
      simp only [RingHom.comp_apply, coe_evalRingHom, eval_C]
      have hscalar :
          (AdjoinRoot.of (sourceEquation ResidueField)) (C r) =
            algebraMap ResidueField (SourceRing ResidueField) r := by
        simpa only [RingHom.comp_apply, Polynomial.algebraMap_apply,
          Algebra.algebraMap_self, RingHom.id_apply] using
            (DFunLike.congr_fun
              (AdjoinRoot.algebraMap_eq'
                (f := sourceEquation ResidueField) ResidueField) r).symm
      rw [hscalar]
      exact (sourceCuspEvaluation ResidueField).commutes r
    · simp only [RingHom.comp_apply, coe_evalRingHom, eval_X]
      change sourceCuspEvaluation ResidueField
          (sourceT ResidueField) = 0
      exact sourceCuspEvaluation_t ResidueField
  have hevalThenConstBase :
      evalThenConst.comp
          (AdjoinRoot.of (sourceEquation ResidueField)) =
        (algebraMap ResidueField
          ((SourceRing ResidueField) ⧸ J)).comp
            (Polynomial.evalRingHom 0) := by
    change ((algebraMap ResidueField
        ((SourceRing ResidueField) ⧸ J)).comp
          (sourceCuspEvaluation ResidueField).toRingHom).comp
            (AdjoinRoot.of (sourceEquation ResidueField)) = _
    rw [RingHom.comp_assoc, hevalBase]
  have hevalRoot : evalThenConst (sourceS ResidueField) = 1 := by
    change algebraMap ResidueField
        ((SourceRing ResidueField) ⧸ J)
          (sourceCuspEvaluation ResidueField
            (sourceS ResidueField)) = 1
    rw [sourceCuspEvaluation_s, map_one]
  have hroot : qmap (sourceS ResidueField) = 1 := by
    apply sub_eq_zero.mp
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    exact Ideal.subset_span (by simp)
  have hmaps : qmap = evalThenConst := by
    apply RingHom.ext
    intro x
    induction x using AdjoinRoot.induction_on with
    | ih p =>
        rw [← AdjoinRoot.aeval_eq p]
        change qmap (Polynomial.eval₂
            (AdjoinRoot.of (sourceEquation ResidueField))
            (sourceS ResidueField) p) =
          evalThenConst (Polynomial.eval₂
            (AdjoinRoot.of (sourceEquation ResidueField))
            (sourceS ResidueField) p)
        rw [Polynomial.hom_eval₂, Polynomial.hom_eval₂, hroot]
        rw [hbase, hevalThenConstBase, hevalRoot]
  change RingHom.ker (sourceCuspEvaluation ResidueField).toRingHom = J
  apply le_antisymm
  · intro a ha
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    change qmap a = 0
    rw [hmaps]
    change algebraMap ResidueField ((SourceRing ResidueField) ⧸ J)
        (sourceCuspEvaluation ResidueField a) = 0
    change sourceCuspEvaluation ResidueField a = 0 at ha
    rw [ha, map_zero]
  · rw [Ideal.span_le]
    intro a ha
    rcases Set.mem_insert_iff.mp ha with rfl | ha
    · change sourceCuspEvaluation ResidueField
          (sourceT ResidueField) = 0
      exact sourceCuspEvaluation_t ResidueField
    · rw [Set.mem_singleton_iff] at ha
      subst a
      change sourceCuspEvaluation ResidueField
          (sourceS ResidueField - 1) = 0
      rw [map_sub, map_one,
        sourceCuspEvaluation_s, sub_self]

/-- On the principal open, the cusp ideal is still generated by the two
coordinate differences. -/
theorem cuspPrime_eq_span_coordinates :
    cuspPrime =
      Ideal.span
        ({openT ResidueField, openS ResidueField - 1} :
          Set (SourceOpenRing ResidueField)) := by
  let J : Ideal (SourceOpenRing ResidueField) :=
    Ideal.span
      ({openT ResidueField, openS ResidueField - 1} :
        Set (SourceOpenRing ResidueField))
  change RingHom.ker (cuspRetraction ResidueField).toRingHom = J
  apply le_antisymm
  · intro z hz
    obtain ⟨n, a, hza⟩ :=
      IsLocalization.Away.surj (sourceDenominator ResidueField) z
    have haKer :
        a ∈ RingHom.ker
          (sourceCuspEvaluation ResidueField).toRingHom := by
      change sourceCuspEvaluation ResidueField a = 0
      have h := congrArg (cuspRetraction ResidueField) hza
      change cuspRetraction ResidueField z = 0 at hz
      rw [map_mul, map_pow, cuspRetraction_algebraMap,
        cuspRetraction_algebraMap, hz, zero_mul] at h
      exact h.symm
    have haSource :
        a ∈ Ideal.span
          ({sourceT ResidueField, sourceS ResidueField - 1} :
            Set (SourceRing ResidueField)) := by
      rw [← sourceCuspEvaluation_ker]
      exact haKer
    let sourceMap : SourceRing ResidueField →+*
        SourceOpenRing ResidueField :=
      algebraMap (SourceRing ResidueField)
        (SourceOpenRing ResidueField)
    have hmap :
        Ideal.map sourceMap
            (Ideal.span
              ({sourceT ResidueField, sourceS ResidueField - 1} :
                Set (SourceRing ResidueField))) ≤ J := by
      rw [Ideal.map_span, Ideal.span_le]
      rintro b ⟨a, ha, rfl⟩
      rcases Set.mem_insert_iff.mp ha with rfl | ha
      · exact Ideal.subset_span (by simp [sourceMap, openT])
      · rw [Set.mem_singleton_iff] at ha
        subst a
        exact Ideal.subset_span (by simp [sourceMap, openS])
    have haOpen : sourceMap a ∈ J :=
      hmap (Ideal.mem_map_of_mem sourceMap haSource)
    have hprod :
        z * sourceMap (sourceDenominator ResidueField) ^ n ∈ J := by
      rw [hza]
      exact haOpen
    exact (J.mul_unit_mem_iff_mem
      ((IsLocalization.Away.algebraMap_isUnit
        (sourceDenominator ResidueField)).pow n)).mp hprod
  · rw [Ideal.span_le]
    intro a ha
    rcases Set.mem_insert_iff.mp ha with rfl | ha
    · change cuspRetraction ResidueField (openT ResidueField) = 0
      exact cuspRetraction_openT ResidueField
    · rw [Set.mem_singleton_iff] at ha
      subst a
      change cuspRetraction ResidueField
          (openS ResidueField - 1) = 0
      rw [map_sub, map_one, cuspRetraction_openS, sub_self]

/-- The polynomial remaining after dividing the source equation minus one
by the infinity parameter. -/
def sourcePolynomialTail (t : SourceOpenRing ResidueField) :
    SourceOpenRing ResidueField :=
  t ^ 7 + 4 * t ^ 6 - 6 * t ^ 5 + 4 * t ^ 4 - 9 * t ^ 3 -
    4 * t ^ 2 - 6 * t - 4

/-- The source equation factored at the cusp branch `s=1`. -/
theorem ordinate_factorization :
    (openS ResidueField - 1) * (openS ResidueField + 1) =
      openT ResidueField * sourcePolynomialTail (openT ResidueField) := by
  rw [show (openS ResidueField - 1) *
      (openS ResidueField + 1) = openS ResidueField ^ 2 - 1 by ring,
    open_source_equation]
  simp only [sourcePolynomialValue, sourcePolynomialTail]
  ring

/-- The local ring of the selected characteristic-eleven cusp. -/
abbrev CuspLocalRing := Localization.AtPrime cuspPrime

/-- The infinity parameter in the actual cusp local ring. -/
def qParameter : CuspLocalRing :=
  algebraMap (SourceOpenRing ResidueField) CuspLocalRing
    (openT ResidueField)

/-- The ordinate difference in the actual cusp local ring. -/
def ordinateDifference : CuspLocalRing :=
  algebraMap (SourceOpenRing ResidueField) CuspLocalRing
    (openS ResidueField - 1)

/-- The other branch factor is a unit at the selected cusp. -/
theorem ordinatePlusOne_isUnit :
    IsUnit (algebraMap (SourceOpenRing ResidueField) CuspLocalRing
      (openS ResidueField + 1)) := by
  rw [IsLocalization.AtPrime.isUnit_to_map_iff
    CuspLocalRing cuspPrime]
  change openS ResidueField + 1 ∉ cuspPrime
  change cuspRetraction ResidueField
      (openS ResidueField + 1) ≠ 0
  rw [map_add, cuspRetraction_openS, map_one]
  exact (by decide : (2 : ResidueField) ≠ 0)

/-- The source equation eliminates the ordinate direction in the cusp local
ring. -/
theorem qParameter_dvd_ordinateDifference :
    qParameter ∣ ordinateDifference := by
  have hrelation := congrArg
    (algebraMap (SourceOpenRing ResidueField) CuspLocalRing)
    ordinate_factorization
  have hdiv : qParameter ∣
      ordinateDifference *
        algebraMap (SourceOpenRing ResidueField) CuspLocalRing
          (openS ResidueField + 1) := by
    refine ⟨algebraMap (SourceOpenRing ResidueField) CuspLocalRing
      (sourcePolynomialTail (openT ResidueField)), ?_⟩
    simpa only [ordinateDifference, qParameter, map_mul] using hrelation
  exact (ordinatePlusOne_isUnit.dvd_mul_right).mp hdiv

/-- The infinity parameter generates the cusp maximal ideal. -/
theorem maximalIdeal_eq_span_qParameter :
    IsLocalRing.maximalIdeal CuspLocalRing =
      Ideal.span ({qParameter} : Set CuspLocalRing) := by
  let locMap : SourceOpenRing ResidueField →+* CuspLocalRing :=
    algebraMap (SourceOpenRing ResidueField) CuspLocalRing
  calc
    IsLocalRing.maximalIdeal CuspLocalRing =
        Ideal.map locMap cuspPrime :=
      Localization.AtPrime.map_eq_maximalIdeal.symm
    _ = Ideal.map locMap
        (Ideal.span
          ({openT ResidueField, openS ResidueField - 1} :
            Set (SourceOpenRing ResidueField))) := by
      exact congrArg (Ideal.map locMap)
        cuspPrime_eq_span_coordinates
    _ = Ideal.span
        ({locMap (openT ResidueField),
          locMap (openS ResidueField - 1)} : Set CuspLocalRing) := by
      rw [Ideal.map_span]
      congr 1
      ext a
      simp [eq_comm]
    _ = Ideal.span ({qParameter} : Set CuspLocalRing) := by
      apply le_antisymm
      · rw [Ideal.span_le]
        intro a ha
        rcases Set.mem_insert_iff.mp ha with rfl | ha
        · change qParameter ∈ Ideal.span ({qParameter} : Set CuspLocalRing)
          exact Ideal.mem_span_singleton_self qParameter
        · rw [Set.mem_singleton_iff] at ha
          subst a
          apply Ideal.mem_span_singleton.mpr
          simpa [locMap, ordinateDifference] using
            qParameter_dvd_ordinateDifference
      · rw [Ideal.span_le]
        intro a ha
        rw [Set.mem_singleton_iff] at ha
        subst a
        exact Ideal.subset_span (by simp [locMap, qParameter])

theorem qParameter_mem_maximalIdeal :
    qParameter ∈ IsLocalRing.maximalIdeal CuspLocalRing := by
  rw [maximalIdeal_eq_span_qParameter]
  exact Ideal.mem_span_singleton_self qParameter

/-! ## A nonzero tangent vector -/

/-- Evaluation of the infinity parameter at the dual-number tangent. -/
def cuspTangentBase :
    Polynomial ResidueField →ₐ[ResidueField] DualNumber ResidueField :=
  Polynomial.aeval DualNumber.eps

/-- The first-order ordinate on the selected branch. -/
def cuspTangentOrdinate : DualNumber ResidueField :=
  1 - 2 * DualNumber.eps

@[simp]
theorem cuspTangentBase_X :
    cuspTangentBase X = (DualNumber.eps : DualNumber ResidueField) := by
  simp [cuspTangentBase]

/-- The displayed dual-number tangent satisfies the source equation. -/
theorem cuspTangent_sourceEquation :
    (sourceEquation ResidueField).eval₂ cuspTangentBase
      cuspTangentOrdinate = 0 := by
  rw [sourceEquation]
  simp only [eval₂_sub, eval₂_pow, eval₂_X, eval₂_C]
  change cuspTangentOrdinate ^ 2 -
      cuspTangentBase (sourcePolynomial ResidueField) = 0
  simp only [sourcePolynomial, map_add, map_sub, map_mul, map_pow,
    map_ofNat, map_one, cuspTangentBase_X]
  dsimp only [cuspTangentOrdinate]
  have heps :
      (DualNumber.eps : DualNumber ResidueField) ^ 2 = 0 :=
    DualNumber.eps_pow_two
  linear_combination
    (-(DualNumber.eps : DualNumber ResidueField) ^ 6 -
      4 * DualNumber.eps ^ 5 + 6 * DualNumber.eps ^ 4 -
      4 * DualNumber.eps ^ 3 + 9 * DualNumber.eps ^ 2 +
      4 * DualNumber.eps + 10) * heps

/-- The nonconstant tangent of the selected cusp on the source ring. -/
def sourceCuspTangent :
    SourceRing ResidueField →ₐ[ResidueField] DualNumber ResidueField :=
  AdjoinRoot.liftAlgHom (sourceEquation ResidueField) cuspTangentBase
    cuspTangentOrdinate cuspTangent_sourceEquation

@[simp]
theorem sourceCuspTangent_t :
    sourceCuspTangent (sourceT ResidueField) = DualNumber.eps := by
  simp [sourceCuspTangent, sourceT, cuspTangentBase]

@[simp]
theorem sourceCuspTangent_s :
    sourceCuspTangent (sourceS ResidueField) =
      cuspTangentOrdinate := by
  simp [sourceCuspTangent, sourceS]

@[simp]
theorem sourceCuspTangent_denominator :
    sourceCuspTangent (sourceDenominator ResidueField) =
      1 + DualNumber.eps := by
  simp [sourceDenominator, quotientDenominator,
    DualNumber.eps_pow_two]

/-- Projection from the dual numbers to their constant term. -/
def dualNumberResidue : DualNumber ResidueField →+* ResidueField :=
  (TrivSqZeroExt.fstHom ResidueField ResidueField ResidueField).toRingHom

@[simp]
theorem dualNumberResidue_eps :
    dualNumberResidue (DualNumber.eps : DualNumber ResidueField) = 0 := by
  rfl

/-- The constant term of the explicit tangent is the selected cusp
evaluation on the source ring. -/
theorem dualNumberResidue_comp_sourceCuspTangent :
    dualNumberResidue.comp sourceCuspTangent.toRingHom =
      (sourceCuspEvaluation ResidueField).toRingHom := by
  let tangentResidue : SourceRing ResidueField →+* ResidueField :=
    dualNumberResidue.comp sourceCuspTangent.toRingHom
  have htangentBase : tangentResidue.comp
        (AdjoinRoot.of (sourceEquation ResidueField)) =
      Polynomial.evalRingHom 0 := by
    apply Polynomial.ringHom_ext
    · intro r
      simp only [RingHom.comp_apply, coe_evalRingHom, eval_C]
      have hscalar :
          (AdjoinRoot.of (sourceEquation ResidueField)) (C r) =
            algebraMap ResidueField (SourceRing ResidueField) r := by
        simpa only [RingHom.comp_apply, Polynomial.algebraMap_apply,
          Algebra.algebraMap_self, RingHom.id_apply] using
            (DFunLike.congr_fun
              (AdjoinRoot.algebraMap_eq'
                (f := sourceEquation ResidueField) ResidueField) r).symm
      rw [hscalar]
      change dualNumberResidue
          (sourceCuspTangent
            (algebraMap ResidueField (SourceRing ResidueField) r)) = r
      rw [sourceCuspTangent.commutes]
      rfl
    · simp only [RingHom.comp_apply, coe_evalRingHom, eval_X]
      change dualNumberResidue
          (sourceCuspTangent (sourceT ResidueField)) = 0
      rw [sourceCuspTangent_t, dualNumberResidue_eps]
  have hevaluationBase :
      (sourceCuspEvaluation ResidueField).toRingHom.comp
          (AdjoinRoot.of (sourceEquation ResidueField)) =
        Polynomial.evalRingHom 0 := by
    apply Polynomial.ringHom_ext
    · intro r
      simp only [RingHom.comp_apply, coe_evalRingHom, eval_C]
      have hscalar :
          (AdjoinRoot.of (sourceEquation ResidueField)) (C r) =
            algebraMap ResidueField (SourceRing ResidueField) r := by
        simpa only [RingHom.comp_apply, Polynomial.algebraMap_apply,
          Algebra.algebraMap_self, RingHom.id_apply] using
            (DFunLike.congr_fun
              (AdjoinRoot.algebraMap_eq'
                (f := sourceEquation ResidueField) ResidueField) r).symm
      rw [hscalar]
      exact (sourceCuspEvaluation ResidueField).commutes r
    · simp only [RingHom.comp_apply, coe_evalRingHom, eval_X]
      exact sourceCuspEvaluation_t ResidueField
  have htangentRoot : tangentResidue (sourceS ResidueField) = 1 := by
    change dualNumberResidue
        (sourceCuspTangent (sourceS ResidueField)) = 1
    rw [sourceCuspTangent_s]
    rfl
  change tangentResidue =
    (sourceCuspEvaluation ResidueField).toRingHom
  apply RingHom.ext
  intro x
  induction x using AdjoinRoot.induction_on with
  | ih p =>
      rw [← AdjoinRoot.aeval_eq p]
      change tangentResidue (Polynomial.eval₂
          (AdjoinRoot.of (sourceEquation ResidueField))
          (sourceS ResidueField) p) =
        (sourceCuspEvaluation ResidueField).toRingHom (Polynomial.eval₂
          (AdjoinRoot.of (sourceEquation ResidueField))
          (sourceS ResidueField) p)
      rw [Polynomial.hom_eval₂, Polynomial.hom_eval₂,
        htangentBase, hevaluationBase, htangentRoot]
      apply congrArg
        (fun z : ResidueField ↦
          Polynomial.eval₂ (Polynomial.evalRingHom 0) z p)
      exact (sourceCuspEvaluation_s ResidueField).symm

/-- The inverted denominator remains a unit on the dual-number tangent. -/
theorem sourceCuspTangent_denominator_isUnit :
    IsUnit (sourceCuspTangent (sourceDenominator ResidueField)) := by
  rw [sourceCuspTangent_denominator,
    TrivSqZeroExt.isUnit_iff_isUnit_fst]
  simp

/-- The explicit tangent on the principal open source chart. -/
def openCuspTangent :
    SourceOpenRing ResidueField →+* DualNumber ResidueField :=
  IsLocalization.Away.lift (sourceDenominator ResidueField)
    sourceCuspTangent_denominator_isUnit

@[simp]
theorem openCuspTangent_algebraMap (a : SourceRing ResidueField) :
    openCuspTangent
        (algebraMap (SourceRing ResidueField)
          (SourceOpenRing ResidueField) a) =
      sourceCuspTangent.toRingHom a := by
  rw [openCuspTangent, IsLocalization.Away.lift_eq]

@[simp]
theorem openCuspTangent_t :
    openCuspTangent (openT ResidueField) = DualNumber.eps := by
  simp [openT]

/-- Taking the constant term after the tangent agrees with the actual cusp
retraction on the source open. -/
theorem dualNumberResidue_comp_openCuspTangent :
    dualNumberResidue.comp openCuspTangent =
      (cuspRetraction ResidueField).toRingHom := by
  apply IsLocalization.ringHom_ext
    (Submonoid.powers (sourceDenominator ResidueField))
  apply RingHom.ext
  intro a
  simp only [RingHom.comp_apply]
  rw [openCuspTangent_algebraMap]
  change dualNumberResidue (sourceCuspTangent.toRingHom a) =
    cuspRetraction ResidueField
      (algebraMap (SourceRing ResidueField)
        (SourceOpenRing ResidueField) a)
  have hleft := RingHom.congr_fun
    dualNumberResidue_comp_sourceCuspTangent a
  have hright := cuspRetraction_algebraMap ResidueField a
  exact hleft.trans hright.symm

/-- Every source function nonvanishing at the cusp maps to a unit along the
dual-number tangent. -/
theorem openCuspTangent_isUnit_of_not_mem_cuspPrime
    {a : SourceOpenRing ResidueField} (ha : a ∉ cuspPrime) :
    IsUnit (openCuspTangent a) := by
  rw [TrivSqZeroExt.isUnit_iff_isUnit_fst]
  have hne : cuspRetraction ResidueField a ≠ 0 := by
    intro hzero
    apply ha
    exact hzero
  have hconstant := RingHom.congr_fun
    dualNumberResidue_comp_openCuspTangent a
  change (openCuspTangent a).fst = cuspRetraction ResidueField a at hconstant
  rw [hconstant]
  exact isUnit_iff_ne_zero.mpr hne

/-- The tangent extends to the actual cusp local ring. -/
def cuspLocalTangent : CuspLocalRing →+* DualNumber ResidueField :=
  IsLocalization.lift (S := CuspLocalRing) (g := openCuspTangent)
    (fun a : cuspPrime.primeCompl ↦
      openCuspTangent_isUnit_of_not_mem_cuspPrime a.property)

@[simp]
theorem cuspLocalTangent_algebraMap
    (a : SourceOpenRing ResidueField) :
    cuspLocalTangent
        (algebraMap (SourceOpenRing ResidueField) CuspLocalRing a) =
      openCuspTangent a := by
  rw [cuspLocalTangent, IsLocalization.lift_eq]

@[simp]
theorem cuspLocalTangent_qParameter :
    cuspLocalTangent qParameter = DualNumber.eps := by
  simp [qParameter]

theorem cuspLocalTangent_qParameter_ne_zero :
    cuspLocalTangent qParameter ≠ 0 := by
  rw [cuspLocalTangent_qParameter]
  intro hzero
  have hsnd := congrArg TrivSqZeroExt.snd hzero
  simp at hsnd

/-- The geometric infinity parameter has a nonzero cotangent class. -/
theorem qParameter_not_mem_maximalIdeal_sq :
    qParameter ∉ IsLocalRing.maximalIdeal CuspLocalRing ^ 2 := by
  intro hsq
  rw [maximalIdeal_eq_span_qParameter,
    Ideal.span_singleton_pow] at hsq
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton.mp hsq
  apply cuspLocalTangent_qParameter_ne_zero
  calc
    cuspLocalTangent qParameter =
        cuspLocalTangent (qParameter ^ 2 * c) :=
      congrArg cuspLocalTangent hc
    _ = 0 := by simp [DualNumber.eps_pow_two]

/-- In particular, the cusp parameter itself is nonzero. -/
theorem qParameter_ne_zero : qParameter ≠ 0 := by
  intro hzero
  apply cuspLocalTangent_qParameter_ne_zero
  rw [hzero, map_zero]

/-! ## The quotient cusp and its localized map -/

/-- Evaluation of the quotient abscissa at the image cusp `W=1`. -/
def targetCuspBase :
    Polynomial ResidueField →ₐ[ResidueField] ResidueField :=
  Polynomial.aeval 1

/-- The image cusp `(W,R)=(1,7)` lies on the quotient curve in
characteristic eleven. -/
theorem targetCusp_equation :
    (targetEquation ResidueField).eval₂ targetCuspBase
      (7 : ResidueField) = 0 := by
  simp [targetEquation, targetPolynomial, targetCuspBase]
  norm_num

/-- Evaluation at the image cusp on the explicit quotient chart. -/
def targetCuspEvaluation :
    TargetRing ResidueField →ₐ[ResidueField] ResidueField :=
  AdjoinRoot.liftAlgHom (targetEquation ResidueField) targetCuspBase 7
    targetCusp_equation

@[simp]
theorem targetCuspEvaluation_w :
    targetCuspEvaluation (targetW ResidueField) = 1 := by
  simp [targetCuspEvaluation, targetW, targetCuspBase]

@[simp]
theorem targetCuspEvaluation_r :
    targetCuspEvaluation (targetR ResidueField) = 7 := by
  simp [targetCuspEvaluation, targetR]

/-- The quotient map carries the selected source cusp to `(W,R)=(1,7)`. -/
theorem cuspRetraction_comp_targetToOpenRing :
    (cuspRetraction ResidueField).comp
        (targetToOpenRing ResidueField) =
      targetCuspEvaluation := by
  apply AdjoinRoot.algHom_ext' (S := ResidueField)
  · apply Polynomial.algHom_ext
    change cuspRetraction ResidueField
        (targetToOpenRing ResidueField (targetW ResidueField)) =
      targetCuspEvaluation (targetW ResidueField)
    rw [targetToOpenRing_w, cuspRetraction_openQuotientW,
      targetCuspEvaluation_w]
  · change cuspRetraction ResidueField
        (targetToOpenRing ResidueField (targetR ResidueField)) =
      targetCuspEvaluation (targetR ResidueField)
    rw [targetToOpenRing_r, cuspRetraction_openQuotientR,
      targetCuspEvaluation_r]

/-- The prime ideal of the image cusp on the quotient chart. -/
def targetCuspPrime : Ideal (TargetRing ResidueField) :=
  RingHom.ker targetCuspEvaluation.toRingHom

/-- Evaluation at the image cusp is onto its residue field. -/
theorem targetCuspEvaluation_surjective :
    Function.Surjective targetCuspEvaluation := by
  intro a
  exact ⟨algebraMap ResidueField (TargetRing ResidueField) a,
    targetCuspEvaluation.commutes a⟩

instance targetCuspPrime_isPrime : targetCuspPrime.IsPrime :=
  RingHom.ker_isPrime _

theorem targetCuspPrime_isMaximal : targetCuspPrime.IsMaximal :=
  RingHom.ker_isMaximal_of_surjective _ targetCuspEvaluation_surjective

/-- The source cusp lies over precisely the displayed target cusp. -/
theorem targetCuspPrime_eq_comap :
    targetCuspPrime =
      cuspPrime.comap (targetToOpenRing ResidueField).toRingHom := by
  ext a
  change targetCuspEvaluation a = 0 ↔
    cuspRetraction ResidueField
      (targetToOpenRing ResidueField a) = 0
  have h := DFunLike.congr_fun
    cuspRetraction_comp_targetToOpenRing a
  exact h.symm ▸ Iff.rfl

/-- The local ring of the image cusp on the explicit quotient chart. -/
abbrev TargetCuspLocalRing := Localization.AtPrime targetCuspPrime

/-- The quotient-side parameter `W-1` in the target cusp local ring. -/
def targetParameter : TargetCuspLocalRing :=
  algebraMap (TargetRing ResidueField) TargetCuspLocalRing
    (targetW ResidueField - 1)

/-- The local comorphism of the explicit quotient map at the selected
characteristic-eleven cusps. -/
def explicitLocalQuotientMap :
    TargetCuspLocalRing →+* CuspLocalRing :=
  Localization.localRingHom targetCuspPrime cuspPrime
    (targetToOpenRing ResidueField).toRingHom targetCuspPrime_eq_comap

/-- The exact linear coefficient of the quotient map in the source cusp
local ring. -/
def quotientLinearCoefficient : CuspLocalRing :=
  algebraMap (SourceOpenRing ResidueField) CuspLocalRing
    (-7 * denominatorInverse ResidueField)

/-- The quotient parameter pulls back to the source parameter with the
exact coefficient `-7/d`. -/
theorem explicitLocalQuotientMap_targetParameter :
    explicitLocalQuotientMap targetParameter =
      quotientLinearCoefficient * qParameter := by
  rw [targetParameter, explicitLocalQuotientMap,
    Localization.localRingHom_to_map]
  change algebraMap (SourceOpenRing ResidueField) CuspLocalRing
      (targetToOpenRing ResidueField
        (targetW ResidueField - 1)) = _
  rw [map_sub, targetToOpenRing_w, map_one]
  rw [openQuotientW_sub_one, map_mul]
  rfl

/-- The coefficient `-7/d` is a unit at the characteristic-eleven source
cusp. -/
theorem quotientLinearCoefficient_isUnit :
    IsUnit quotientLinearCoefficient := by
  have hseven : IsUnit (-7 : ResidueField) :=
    isUnit_iff_ne_zero.mpr (by decide)
  have hscalar :
      IsUnit (-7 : SourceOpenRing ResidueField) :=
    by simpa only [map_neg, map_ofNat] using
      hseven.map (algebraMap ResidueField
        (SourceOpenRing ResidueField))
  have hdenominator :
      IsUnit (denominatorInverse ResidueField) :=
    by
      change IsUnit
        ((((denominatorUnit ResidueField)⁻¹ :
          Units (SourceOpenRing ResidueField))) :
            SourceOpenRing ResidueField)
      exact Units.isUnit _
  exact (hscalar.mul hdenominator).map
    (algebraMap (SourceOpenRing ResidueField) CuspLocalRing)

/-- The quotient parameter belongs to the target cusp maximal ideal. -/
theorem targetParameter_mem_maximalIdeal :
    targetParameter ∈
      IsLocalRing.maximalIdeal TargetCuspLocalRing := by
  rw [← Localization.AtPrime.map_eq_maximalIdeal]
  apply Ideal.mem_map_of_mem
  change targetCuspEvaluation (targetW ResidueField - 1) = 0
  simp

/-! ## The local cotangent map -/

/-- Evaluation at the selected source cusp after localization. -/
def cuspLocalEvaluation : CuspLocalRing →+* ResidueField :=
  IsLocalization.lift (S := CuspLocalRing)
    (g := (cuspRetraction ResidueField).toRingHom)
    (fun a : cuspPrime.primeCompl ↦ by
      apply isUnit_iff_ne_zero.mpr
      change cuspRetraction ResidueField a ≠ 0
      exact a.property)

@[simp]
theorem cuspLocalEvaluation_algebraMap
    (a : SourceOpenRing ResidueField) :
    cuspLocalEvaluation
        (algebraMap (SourceOpenRing ResidueField) CuspLocalRing a) =
      cuspRetraction ResidueField a := by
  rw [cuspLocalEvaluation, IsLocalization.lift_eq]
  rfl

@[simp]
theorem cuspLocalEvaluation_commutes (a : ResidueField) :
    cuspLocalEvaluation (algebraMap ResidueField CuspLocalRing a) = a := by
  rw [IsScalarTower.algebraMap_apply ResidueField
    (SourceOpenRing ResidueField) CuspLocalRing,
    cuspLocalEvaluation_algebraMap]
  exact (cuspRetraction ResidueField).commutes a

theorem cuspLocalEvaluation_surjective :
    Function.Surjective cuspLocalEvaluation := by
  intro a
  exact ⟨algebraMap ResidueField CuspLocalRing a,
    cuspLocalEvaluation_commutes a⟩

/-- Every residue class at the source cusp has a representative in the
embedded coefficient field. -/
theorem cuspResidue_algebraMap_surjective :
    Function.Surjective
      ((IsLocalRing.residue CuspLocalRing).comp
        (algebraMap ResidueField CuspLocalRing)) := by
  have hkernel : RingHom.ker cuspLocalEvaluation =
      IsLocalRing.maximalIdeal CuspLocalRing :=
    IsLocalRing.ker_eq_maximalIdeal cuspLocalEvaluation
      cuspLocalEvaluation_surjective
  intro y
  obtain ⟨b, rfl⟩ := IsLocalRing.residue_surjective y
  refine ⟨cuspLocalEvaluation b, ?_⟩
  apply (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).mpr
  rw [← hkernel, RingHom.mem_ker, map_sub,
    cuspLocalEvaluation_commutes, sub_self]

/-- The explicit localized quotient map respects the common coefficient
field. -/
@[simp]
theorem explicitLocalQuotientMap_commutes (a : ResidueField) :
    explicitLocalQuotientMap
        (algebraMap ResidueField TargetCuspLocalRing a) =
      algebraMap ResidueField CuspLocalRing a := by
  change Localization.localAlgHom targetCuspPrime cuspPrime
      (targetToOpenRing ResidueField) targetCuspPrime_eq_comap
        (algebraMap ResidueField TargetCuspLocalRing a) = _
  exact (Localization.localAlgHom targetCuspPrime cuspPrime
    (targetToOpenRing ResidueField) targetCuspPrime_eq_comap).commutes a

instance explicitLocalQuotientMap_isLocalHom :
    IsLocalHom explicitLocalQuotientMap :=
  Localization.isLocalHom_localRingHom targetCuspPrime cuspPrime
    (targetToOpenRing ResidueField).toRingHom targetCuspPrime_eq_comap

/-- The local quotient map is onto on residue fields at the two rational
cusps. -/
theorem explicitLocalQuotientMap_residue_surjective :
    Function.Surjective
      (IsLocalRing.ResidueField.map explicitLocalQuotientMap) := by
  intro y
  obtain ⟨a, ha⟩ := cuspResidue_algebraMap_surjective y
  refine ⟨IsLocalRing.residue TargetCuspLocalRing
      (algebraMap ResidueField TargetCuspLocalRing a), ?_⟩
  rw [IsLocalRing.ResidueField.map_residue,
    explicitLocalQuotientMap_commutes]
  exact ha

/-- The source cusp cotangent space is exactly one-dimensional. -/
theorem cuspCotangent_finrank :
    Module.finrank (IsLocalRing.ResidueField CuspLocalRing)
      (IsLocalRing.CotangentSpace CuspLocalRing) = 1 := by
  have hprincipal :
      (IsLocalRing.maximalIdeal CuspLocalRing).IsPrincipal := by
    rw [maximalIdeal_eq_span_qParameter]
    infer_instance
  have hnotField : ¬ IsField CuspLocalRing := by
    intro hfield
    have hzero : qParameter = 0 := by
      have hmem : qParameter ∈ (⊥ : Ideal CuspLocalRing) := by
        rw [← IsLocalRing.isField_iff_maximalIdeal_eq.mp hfield]
        exact qParameter_mem_maximalIdeal
      simpa using hmem
    apply qParameter_not_mem_maximalIdeal_sq
    rw [hzero]
    exact (IsLocalRing.maximalIdeal CuspLocalRing ^ 2).zero_mem
  have hle : Module.finrank
      (IsLocalRing.ResidueField CuspLocalRing)
      (IsLocalRing.CotangentSpace CuspLocalRing) ≤ 1 :=
    IsLocalRing.finrank_cotangentSpace_le_one_iff.mpr hprincipal
  have hne : Module.finrank
      (IsLocalRing.ResidueField CuspLocalRing)
      (IsLocalRing.CotangentSpace CuspLocalRing) ≠ 0 := by
    intro hzero
    exact hnotField
      (IsLocalRing.finrank_cotangentSpace_eq_zero_iff.mp hzero)
  omega

/-- The cotangent class of the quotient parameter. -/
def targetCotangentVector :
    IsLocalRing.CotangentSpace TargetCuspLocalRing :=
  (IsLocalRing.maximalIdeal TargetCuspLocalRing).toCotangent
    ⟨targetParameter, targetParameter_mem_maximalIdeal⟩

/-- The quotient parameter has nonzero pullback in the source cotangent
space. -/
theorem explicitLocalQuotientMap_targetCotangentVector_ne_zero :
    IsLocalRing.cotangentMapAtResidue explicitLocalQuotientMap
      targetCotangentVector ≠ 0 := by
  intro hzero
  rw [IsLocalRing.cotangentMapAtResidue_apply] at hzero
  dsimp only [targetCotangentVector] at hzero
  rw [IsLocalRing.cotangentMap_toCotangent] at hzero
  have himageSquare :
      explicitLocalQuotientMap targetParameter ∈
        IsLocalRing.maximalIdeal CuspLocalRing ^ 2 := by
    rwa [Ideal.toCotangent_eq_zero] at hzero
  rw [explicitLocalQuotientMap_targetParameter] at himageSquare
  exact qParameter_not_mem_maximalIdeal_sq
    ((IsLocalRing.maximalIdeal CuspLocalRing ^ 2).unit_mul_mem_iff_mem
      quotientLinearCoefficient_isUnit |>.mp himageSquare)

/-- The explicit quotient map is surjective on cotangent spaces at the
selected characteristic-eleven cusp. -/
theorem explicitLocalQuotientMap_cotangent_surjective :
    Function.Surjective
      (IsLocalRing.cotangentMap explicitLocalQuotientMap) :=
  IsLocalRing.cotangentMap_surjective_of_degreeOne_of_apply_ne_zero
    explicitLocalQuotientMap
    explicitLocalQuotientMap_residue_surjective
    cuspCotangent_finrank targetCotangentVector
    explicitLocalQuotientMap_targetCotangentVector_ne_zero

/-- Consequently the explicit local quotient map is surjective after
completion at the selected characteristic-eleven cusps. -/
theorem explicitLocalQuotientMap_completion_surjective :
    Function.Surjective
      (LocalCompletion.map explicitLocalQuotientMap) :=
  LocalCompletion.map_surjective_of_residue_and_cotangent_of_finite_maximalIdeals
    explicitLocalQuotientMap
    explicitLocalQuotientMap_residue_surjective
    explicitLocalQuotientMap_cotangent_surjective

/-! ## Formal immersion of the represented characteristic-eleven chart -/

/-- The selected cusp as a point of the represented source affine scheme. -/
noncomputable abbrev cuspPoint :
    Spec (.of (SourceOpenRing ResidueField)) :=
  (⟨cuspPrime, cuspPrime_isPrime⟩ :
    PrimeSpectrum (SourceOpenRing ResidueField))

/-- The equality-induced equivalence between the target localization used
by `Spec.map` and the named target cusp local ring. -/
theorem targetCuspComap_eq_reflComap :
    cuspPrime.comap
        (targetToOpenRing ResidueField).toRingHom =
      targetCuspPrime.comap
        (RingEquiv.refl (TargetRing ResidueField)).toRingHom := by
  change cuspPrime.comap
      (targetToOpenRing ResidueField).toRingHom = targetCuspPrime
  exact targetCuspPrime_eq_comap.symm

noncomputable def targetLocalizationEquiv :
    Localization.AtPrime
        (cuspPrime.comap
          (targetToOpenRing ResidueField).toRingHom) ≃+*
      TargetCuspLocalRing :=
  Localization.localRingEquiv
    (cuspPrime.comap
      (targetToOpenRing ResidueField).toRingHom)
    targetCuspPrime (RingEquiv.refl (TargetRing ResidueField))
      targetCuspComap_eq_reflComap

@[simp]
theorem targetLocalizationEquiv_algebraMap
    (a : TargetRing ResidueField) :
    targetLocalizationEquiv
        (algebraMap (TargetRing ResidueField)
          (Localization.AtPrime
            (cuspPrime.comap
              (targetToOpenRing ResidueField).toRingHom)) a) =
      algebraMap (TargetRing ResidueField) TargetCuspLocalRing a := by
  unfold targetLocalizationEquiv
  change Localization.localRingHom
      (cuspPrime.comap
        (targetToOpenRing ResidueField).toRingHom)
      targetCuspPrime
        (RingEquiv.refl (TargetRing ResidueField)).toRingHom
        targetCuspComap_eq_reflComap
          (algebraMap (TargetRing ResidueField)
            (Localization.AtPrime
              (cuspPrime.comap
                (targetToOpenRing ResidueField).toRingHom)) a) = _
  exact Localization.localRingHom_to_map _ _ _ _ a

/-- After the equality transport on the target localization, Mathlib's
canonical affine local map is the explicit local quotient map above. -/
theorem explicitLocalQuotientMap_comp_targetLocalizationEquiv :
    explicitLocalQuotientMap.comp targetLocalizationEquiv.toRingHom =
      Localization.localRingHom
        (cuspPrime.comap
          (targetToOpenRing ResidueField).toRingHom)
        cuspPrime (targetToOpenRing ResidueField).toRingHom rfl := by
  symm
  apply Localization.localRingHom_unique
  intro a
  change explicitLocalQuotientMap
      (targetLocalizationEquiv
        (algebraMap (TargetRing ResidueField)
          (Localization.AtPrime
            (cuspPrime.comap
              (targetToOpenRing ResidueField).toRingHom)) a)) = _
  rw [targetLocalizationEquiv_algebraMap,
    explicitLocalQuotientMap,
    Localization.localRingHom_to_map]

/-- The canonical affine localization map and the named explicit local map
are isomorphic as arrows of commutative rings. -/
noncomputable def localQuotientMapArrowIso :
    Arrow.mk (CommRingCat.ofHom
        (Localization.localRingHom
          (cuspPrime.comap
            (targetToOpenRing ResidueField).toRingHom)
          cuspPrime (targetToOpenRing ResidueField).toRingHom rfl)) ≅
      Arrow.mk (CommRingCat.ofHom explicitLocalQuotientMap) :=
  Arrow.isoMk targetLocalizationEquiv.toCommRingCatIso (Iso.refl _) (by
    apply CommRingCat.hom_ext
    exact explicitLocalQuotientMap_comp_targetLocalizationEquiv)

/-- The actual stalk map of the represented quotient morphism is the
explicit local quotient map under the canonical affine stalk
identifications and `targetLocalizationEquiv`. -/
noncomputable def quotientStalkMapLocalIso :
    Arrow.mk
        ((quotientMorphism ResidueField).stalkMap cuspPoint) ≅
      Arrow.mk (CommRingCat.ofHom explicitLocalQuotientMap) :=
  (Scheme.arrowStalkMapSpecIso
      (CommRingCat.ofHom
        (targetToOpenRing ResidueField).toRingHom)
      (⟨cuspPrime, cuspPrime_isPrime⟩ :
        PrimeSpectrum (SourceOpenRing ResidueField))).trans
    localQuotientMapArrowIso

/-- The target-stalk component of `quotientStalkMapLocalIso`. -/
noncomputable abbrev quotientTargetStalkIso :
    (Spec (.of (TargetRing ResidueField))).presheaf.stalk
        ((quotientMorphism ResidueField) cuspPoint) ≅
      .of TargetCuspLocalRing :=
  Arrow.leftFunc.mapIso quotientStalkMapLocalIso

/-- The source-stalk component of `quotientStalkMapLocalIso`. -/
noncomputable abbrev quotientSourceStalkIso :
    (Spec (.of (SourceOpenRing ResidueField))).presheaf.stalk
        cuspPoint ≅
      .of CuspLocalRing :=
  Arrow.rightFunc.mapIso quotientStalkMapLocalIso

/-- Conjugating the explicit local quotient map by the two stalk
isomorphisms gives the actual stalk map. -/
theorem quotientMorphism_stalkMap_eq_explicitLocalQuotientMap :
    quotientTargetStalkIso.hom ≫
        CommRingCat.ofHom explicitLocalQuotientMap ≫
      quotientSourceStalkIso.inv =
        (quotientMorphism ResidueField).stalkMap cuspPoint := by
  let E := quotientStalkMapLocalIso
  have hw : quotientTargetStalkIso.hom ≫
        CommRingCat.ofHom explicitLocalQuotientMap =
      (quotientMorphism ResidueField).stalkMap cuspPoint ≫
        quotientSourceStalkIso.hom :=
    E.hom.w
  calc
    quotientTargetStalkIso.hom ≫
          CommRingCat.ofHom explicitLocalQuotientMap ≫
        quotientSourceStalkIso.inv =
      (quotientTargetStalkIso.hom ≫
          CommRingCat.ofHom explicitLocalQuotientMap) ≫
        quotientSourceStalkIso.inv :=
      (Category.assoc _ _ _).symm
    _ = ((quotientMorphism ResidueField).stalkMap cuspPoint ≫
          quotientSourceStalkIso.hom) ≫
        quotientSourceStalkIso.inv :=
      congrArg (fun h ↦ h ≫ quotientSourceStalkIso.inv) hw
    _ = (quotientMorphism ResidueField).stalkMap cuspPoint := by
      rw [Category.assoc, quotientSourceStalkIso.hom_inv_id,
        Category.comp_id]

private instance ringEquivToRingHom_isLocalHom
    {A B : Type*} [CommRing A] [CommRing B] (e : A ≃+* B) :
    IsLocalHom e.toRingHom :=
  ⟨fun x hx ↦ (isLocalHom_equiv e).map_nonunit x hx⟩

private theorem completionMap_congr
    {A B : Type*} [CommRing A] [CommRing B]
    [IsLocalRing A] [IsLocalRing B]
    (f g : A →+* B) [IsLocalHom f] [IsLocalHom g] (h : f = g) :
    LocalCompletion.map f = LocalCompletion.map g := by
  subst g
  rfl

private theorem completionMap_surjective_of_ringEquiv
    {A B : Type*} [CommRing A] [CommRing B]
    [IsLocalRing A] [IsLocalRing B] (e : A ≃+* B) :
    Function.Surjective (LocalCompletion.map e.toRingHom) := by
  letI : IsLocalHom e.toRingHom :=
    ⟨fun x hx ↦ (isLocalHom_equiv e).map_nonunit x hx⟩
  letI : IsLocalHom e.symm.toRingHom :=
    ⟨fun x hx ↦ (isLocalHom_equiv e.symm).map_nonunit x hx⟩
  intro y
  refine ⟨LocalCompletion.map e.symm.toRingHom y, ?_⟩
  change LocalCompletion.map e.toRingHom
      (LocalCompletion.map e.symm.toRingHom y) = y
  rw [← RingHom.comp_apply, ← LocalCompletion.map_comp]
  have he : e.toRingHom.comp e.symm.toRingHom = RingHom.id B := by
    ext b
    exact e.apply_symm_apply b
  have hmap := completionMap_congr
    (e.toRingHom.comp e.symm.toRingHom) (RingHom.id B) he
  rw [hmap, LocalCompletion.map_id]
  rfl

/-- The represented quotient morphism of characteristic-eleven affine
charts is a formal immersion at the selected infinity cusp. -/
theorem quotientMorphism_isFormalImmersionAt_cusp :
    IsFormalImmersionAt (quotientMorphism ResidueField) cuspPoint := by
  let eTarget :=
    quotientTargetStalkIso.commRingCatIsoToRingEquiv
  let eSource :=
    quotientSourceStalkIso.commRingCatIsoToRingEquiv
  letI : IsLocalRing
      ((Spec (.of (TargetRing ResidueField))).presheaf.stalk
        ((quotientMorphism ResidueField) cuspPoint)) :=
    eTarget.symm.isLocalRing
  letI : IsLocalRing
      ((Spec (.of (SourceOpenRing ResidueField))).presheaf.stalk
        cuspPoint) :=
    eSource.symm.isLocalRing
  letI : IsLocalHom eTarget.toRingHom :=
    ⟨fun x hx ↦ (isLocalHom_equiv eTarget).map_nonunit x hx⟩
  letI : IsLocalHom eSource.symm.toRingHom :=
    ⟨fun x hx ↦ (isLocalHom_equiv eSource.symm).map_nonunit x hx⟩
  letI hmiddle : IsLocalHom
      (explicitLocalQuotientMap.comp eTarget.toRingHom) :=
    RingHom.isLocalHom_comp _ _
  letI hfull : IsLocalHom
      (eSource.symm.toRingHom.comp
        (explicitLocalQuotientMap.comp eTarget.toRingHom)) :=
    RingHom.isLocalHom_comp _ _
  have htarget : Function.Surjective
      (LocalCompletion.map eTarget.toRingHom) :=
    completionMap_surjective_of_ringEquiv eTarget
  have hsource : Function.Surjective
      (LocalCompletion.map eSource.symm.toRingHom) :=
    completionMap_surjective_of_ringEquiv eSource.symm
  have hstalk :
      ((quotientMorphism ResidueField).stalkMap cuspPoint).hom =
        eSource.symm.toRingHom.comp
          (explicitLocalQuotientMap.comp eTarget.toRingHom) := by
    symm
    exact CommRingCat.hom_ext_iff.mp
      quotientMorphism_stalkMap_eq_explicitLocalQuotientMap
  letI hstalkLocal : IsLocalHom
      ((quotientMorphism ResidueField).stalkMap cuspPoint).hom := by
    exact hstalk.symm ▸ hfull
  change Function.Surjective
    (LocalCompletion.map
      ((quotientMorphism ResidueField).stalkMap cuspPoint).hom)
  have hcompletion :
      LocalCompletion.map
          ((quotientMorphism ResidueField).stalkMap cuspPoint).hom =
        LocalCompletion.map
          (eSource.symm.toRingHom.comp
            (explicitLocalQuotientMap.comp eTarget.toRingHom)) := by
    exact completionMap_congr _ _ hstalk
  have houter := LocalCompletion.map_comp
    (explicitLocalQuotientMap.comp eTarget.toRingHom)
    eSource.symm.toRingHom
  have hinner := LocalCompletion.map_comp eTarget.toRingHom
    explicitLocalQuotientMap
  intro y
  obtain ⟨ySource, hySource⟩ := hsource y
  obtain ⟨yLocal, hyLocal⟩ :=
    explicitLocalQuotientMap_completion_surjective ySource
  obtain ⟨x, hx⟩ := htarget yLocal
  refine ⟨x, ?_⟩
  calc
    LocalCompletion.map
        ((quotientMorphism ResidueField).stalkMap cuspPoint).hom x =
      LocalCompletion.map
        (eSource.symm.toRingHom.comp
          (explicitLocalQuotientMap.comp eTarget.toRingHom)) x :=
      congrArg (fun F ↦ F x) hcompletion
    _ = LocalCompletion.map eSource.symm.toRingHom
        (LocalCompletion.map
          (explicitLocalQuotientMap.comp eTarget.toRingHom) x) :=
      congrArg (fun F ↦ F x) houter
    _ = LocalCompletion.map eSource.symm.toRingHom
        (LocalCompletion.map explicitLocalQuotientMap
          (LocalCompletion.map eTarget.toRingHom x)) := by
      rw [congrArg (fun F ↦ F x) hinner]
      rfl
    _ = y := by rw [hx, hyLocal, hySource]

end MazurTorsion.OrderThirtyFive.InfinityChartCuspAtEleven
