/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.EllipticCurve.VariableChange
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Rational cyclic subgroups and the open `X₀(N)` datum

This file isolates the part of the `Γ₀(N)` moduli bridge that is already
available at the project's exact Mathlib pin.  A rational point of exact order
`N` generates a cyclic subgroup of the rational point group with exactly `N`
elements.  Forgetting the chosen generator gives the rational `Γ₀(N)`
datum `(E, C)`.

Constructing the elliptic quotient `E/C`, and proving that the resulting datum
is classified by the coarse open modular curve, are scheme-theoretic geometry
that is not present at the core package's exact pin.  The downstream theorem
`XZeroFortyNine.rationalPoint_addOrderOf_ne_fortyNine_of_classifyingMap`
therefore takes that genuine classifying map as its explicit remaining input
and lands in the already checked two-cusp model of `X₀(49)`.
-/

open scoped WeierstrassCurve.Affine

namespace MazurTorsion.ModularCurve.XZeroModuli

universe u

/-- A finite cyclic subgroup of order `N` in an additive commutative group.

When the ambient group is `E(K)`, every element of `carrier` is already
`K`-rational.  The structure forgets a chosen generator, as required by a
`Γ₀(N)` rather than a `Γ₁(N)` datum. -/
structure RationalCyclicSubgroup (A : Type u) [AddCommGroup A]
    (N : ℕ) [NeZero N] where
  /-- The subgroup of rational points. -/
  carrier : AddSubgroup A
  /-- The subgroup is cyclic. -/
  isAddCyclic : IsAddCyclic carrier
  /-- Its cardinality is the level `N`. -/
  card_eq : Nat.card carrier = N

namespace RationalCyclicSubgroup

variable {A B : Type*} [AddCommGroup A] [AddCommGroup B]
  {N : ℕ} [NeZero N]

instance (C : RationalCyclicSubgroup A N) : IsAddCyclic C.carrier :=
  C.isAddCyclic

noncomputable instance (C : RationalCyclicSubgroup A N) : Finite C.carrier :=
  Nat.finite_of_card_ne_zero <| by
    rw [C.card_eq]
    exact NeZero.ne N

@[ext]
theorem ext {C D : RationalCyclicSubgroup A N}
    (h : C.carrier = D.carrier) : C = D := by
  cases C
  cases D
  cases h
  rfl

/-- The subgroup generated by a point of exact order `N`, with its cardinality
proved from `Nat.card_zmultiples`. -/
def ofPoint (P : A) (hP : addOrderOf P = N) :
    RationalCyclicSubgroup A N where
  carrier := AddSubgroup.zmultiples P
  isAddCyclic := inferInstance
  card_eq := (Nat.card_zmultiples P).trans hP

@[simp]
theorem ofPoint_carrier (P : A) (hP : addOrderOf P = N) :
    (ofPoint P hP).carrier = AddSubgroup.zmultiples P :=
  rfl

theorem point_mem_ofPoint (P : A) (hP : addOrderOf P = N) :
    P ∈ (ofPoint P hP).carrier := by
  exact AddSubgroup.mem_zmultiples_iff.mpr ⟨1, by simp⟩

/-- Transport a rational cyclic subgroup along an isomorphism of point groups. -/
def map (C : RationalCyclicSubgroup A N) (e : A ≃+ B) :
    RationalCyclicSubgroup B N where
  carrier := C.carrier.map e.toAddMonoidHom
  isAddCyclic := (e.addSubgroupMap C.carrier).isAddCyclic.mp C.isAddCyclic
  card_eq := (Nat.card_congr (e.addSubgroupMap C.carrier).toEquiv).symm.trans C.card_eq

@[simp]
theorem map_carrier (C : RationalCyclicSubgroup A N) (e : A ≃+ B) :
    (C.map e).carrier = C.carrier.map e.toAddMonoidHom :=
  rfl

/-- Generating a subgroup commutes with transport along a point-group
isomorphism. -/
theorem map_ofPoint (P : A) (hP : addOrderOf P = N) (e : A ≃+ B) :
    (ofPoint P hP).map e =
      ofPoint (e P) ((e.addOrderOf_eq P).trans hP) := by
  apply ext
  exact e.toAddMonoidHom.map_zmultiples P

/-- A cyclic subgroup presented without a chosen generator still has one. -/
noncomputable def generator (C : RationalCyclicSubgroup A N) : C.carrier :=
  (isAddCyclic_iff_exists_addOrderOf_eq_natCard.mp C.isAddCyclic).choose

@[simp]
theorem addOrderOf_generator_subtype (C : RationalCyclicSubgroup A N) :
    addOrderOf C.generator = N :=
  (isAddCyclic_iff_exists_addOrderOf_eq_natCard.mp C.isAddCyclic).choose_spec.trans
    C.card_eq

/-- The chosen generator also has exact order `N` in the ambient rational
point group. -/
@[simp]
theorem addOrderOf_generator (C : RationalCyclicSubgroup A N) :
    addOrderOf (C.generator : A) = N :=
  (addOrderOf_injective (AddSubgroup.subtype C.carrier)
    C.carrier.subtype_injective C.generator).trans C.addOrderOf_generator_subtype

/-- The selected generator generates the supplied subgroup, not merely some
cyclic group of the same cardinality. -/
theorem zmultiples_generator (C : RationalCyclicSubgroup A N) :
    AddSubgroup.zmultiples (C.generator : A) = C.carrier := by
  ext x
  constructor
  · rintro ⟨k, rfl⟩
    exact C.carrier.zsmul_mem C.generator.property k
  · intro hx
    have htop : AddSubgroup.zmultiples C.generator = ⊤ := by
      apply AddSubgroup.eq_top_of_card_eq
      rw [Nat.card_zmultiples, C.addOrderOf_generator_subtype]
      exact C.card_eq.symm
    have hx' : (⟨x, hx⟩ : C.carrier) ∈ AddSubgroup.zmultiples C.generator := by
      rw [htop]
      trivial
    rcases AddSubgroup.mem_zmultiples_iff.mp hx' with ⟨k, hk⟩
    exact AddSubgroup.mem_zmultiples_iff.mpr ⟨k, congrArg Subtype.val hk⟩

/-- A cyclic subgroup of order different from one is nontrivial. -/
theorem carrier_ne_bot (C : RationalCyclicSubgroup A N) (hN : N ≠ 1) :
    C.carrier ≠ ⊥ := by
  intro hbot
  apply hN
  rw [← C.card_eq, hbot, AddSubgroup.card_bot]

end RationalCyclicSubgroup

universe v

/-- A raw rational `Γ₀(N)` classifying datum `(E, C)` over a field.

This is the object classified by the open modular curve.  The raw structure is
not itself an isomorphism class; below, `VariableChangeClass` quotients out the
admissible Weierstrass changes already available in checked code.  Constructing
the coarse moduli point remains the next geometric layer. -/
structure RationalDatum (K : Type v) [Field K] [DecidableEq K]
    (N : ℕ) [NeZero N] where
  /-- The Weierstrass model. -/
  curve : WeierstrassCurve K
  /-- Smoothness of the model. -/
  isElliptic : curve.IsElliptic
  /-- The rational cyclic subgroup of order `N`. -/
  subgroup : RationalCyclicSubgroup curve.toAffine.Point N

namespace RationalDatum

variable {K : Type*} [Field K] [DecidableEq K]
  {N : ℕ} [NeZero N]

instance (x : RationalDatum K N) : x.curve.IsElliptic :=
  x.isElliptic

/-- Package an elliptic curve and a rational cyclic subgroup as a raw
`Γ₀(N)` datum. -/
def datumOfRationalCyclicSubgroup (E : WeierstrassCurve K) [E.IsElliptic]
    (C : RationalCyclicSubgroup E.toAffine.Point N) : RationalDatum K N where
  curve := E
  isElliptic := inferInstance
  subgroup := C

/-- A rational point of exact order `N` supplies the open `Γ₀(N)` datum
by forgetting its choice of generator. -/
def datumOfTorsion (E : WeierstrassCurve K) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = N) : RationalDatum K N :=
  datumOfRationalCyclicSubgroup E (RationalCyclicSubgroup.ofPoint P hP)

@[simp]
theorem datumOfTorsion_curve (E : WeierstrassCurve K) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = N) :
    (datumOfTorsion E P hP).curve = E :=
  rfl

@[simp]
theorem datumOfTorsion_subgroup (E : WeierstrassCurve K) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = N) :
    (datumOfTorsion E P hP).subgroup.carrier = AddSubgroup.zmultiples P :=
  rfl

/-- Conversely, a raw rational `Γ₀(N)` datum contains a rational point
of exact order `N`, because its subgroup is finite cyclic of order `N`. -/
noncomputable def generator (x : RationalDatum K N) : x.curve.toAffine.Point :=
  x.subgroup.generator

@[simp]
theorem addOrderOf_generator (x : RationalDatum K N) :
    addOrderOf x.generator = N :=
  x.subgroup.addOrderOf_generator

/-! ### Independence of the Weierstrass presentation -/

/-- Transport a raw `Γ₀(N)` datum along an admissible change of Weierstrass
variables.  The inverse point-group equivalence transports the subgroup from
the old model to the changed model. -/
def variableChange (x : RationalDatum K N)
    (C : WeierstrassCurve.VariableChange K) : RationalDatum K N where
  curve := C • x.curve
  isElliptic := inferInstance
  subgroup := x.subgroup.map
    (WeierstrassCurve.Affine.Point.equivVariableChange x.curve C).symm

@[simp]
theorem variableChange_curve (x : RationalDatum K N)
    (C : WeierstrassCurve.VariableChange K) :
    (x.variableChange C).curve = C • x.curve :=
  rfl

@[simp]
theorem variableChange_subgroup_carrier (x : RationalDatum K N)
    (C : WeierstrassCurve.VariableChange K) :
    (x.variableChange C).subgroup.carrier =
      x.subgroup.carrier.map
        (WeierstrassCurve.Affine.Point.equivVariableChange x.curve C).symm.toAddMonoidHom :=
  rfl

/-- One-step equivalence of raw data under an admissible Weierstrass variable
change.  Its equivalence closure is used below, avoiding any claim that a
general coarse modular quotient has already been constructed. -/
def VariableChangeRelated (x y : RationalDatum K N) : Prop :=
  ∃ C : WeierstrassCurve.VariableChange K, x.variableChange C = y

/-- The equivalence relation generated by admissible changes of a Weierstrass
presentation and the induced transport of its cyclic subgroup. -/
def variableChangeSetoid : Setoid (RationalDatum K N) :=
  Relation.EqvGen.setoid VariableChangeRelated

/-- Raw rational `Γ₀(N)` data modulo the checked admissible changes of
Weierstrass presentation.  This is deliberately named a variable-change
class, not a coarse-moduli point: representability and the map to `X₀(N)`
remain geometric work. -/
def VariableChangeClass := Quotient (variableChangeSetoid (K := K) (N := N))

/-- Forget the chosen Weierstrass presentation of a raw rational datum. -/
def variableChangeClassOf (x : RationalDatum K N) :
    VariableChangeClass (K := K) (N := N) :=
  Quotient.mk (variableChangeSetoid (K := K) (N := N)) x

/-- The variable-change class is independent of one admissible change of
presentation. -/
theorem variableChangeClassOf_variableChange (x : RationalDatum K N)
    (C : WeierstrassCurve.VariableChange K) :
    variableChangeClassOf (x.variableChange C) = variableChangeClassOf x := by
  apply Quotient.sound (s := variableChangeSetoid (K := K) (N := N))
  have hrel : VariableChangeRelated x (x.variableChange C) := ⟨C, rfl⟩
  exact Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ hrel)

namespace VariableChangeClass

/-- Descend a function on raw rational data which is invariant under every
admissible change of Weierstrass presentation.  This is the checked API through
which a future coarse `X₀(N)` classifying map can be built. -/
def lift {P : Sort*} (f : RationalDatum K N → P)
    (h : ∀ x C, f (x.variableChange C) = f x) :
    VariableChangeClass (K := K) (N := N) → P :=
  Quotient.lift f fun x y hxy ↦ by
    induction hxy with
    | rel x y hxy =>
        obtain ⟨C, rfl⟩ := hxy
        exact (h x C).symm
    | refl => rfl
    | symm _ _ _ ih => exact ih.symm
    | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

@[simp]
theorem lift_variableChangeClassOf {P : Sort*} (f : RationalDatum K N → P)
    (h : ∀ x C, f (x.variableChange C) = f x) (x : RationalDatum K N) :
    lift f h (variableChangeClassOf x) = f x :=
  rfl

end VariableChangeClass

end RationalDatum

end MazurTorsion.ModularCurve.XZeroModuli
