/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, Chris Birkbeck, AINTLIB ModularCurves contributors,
  OpenAI Codex
-/

import MazurTorsion.ModularCurve.XZeroGammaOneTateBase
import MazurTorsion.Upstream.AINTLIB.ForMathlib.GradedQuotient
import Mathlib.AlgebraicGeometry.EllipticCurve.Projective.Basic
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Basic

/-!
# The universal projective Tate family and its two sections

This file constructs the scheme-theoretic projective hypersurface

`Proj (R[A, B][Δ⁻¹][X, Y, Z] / (F))`

for the universal Tate-normal cubic `F`.  Unlike the reduced field-fibre cubic
used by the elliptic-quotient lane, this construction retains nilpotents and is
valid over an arbitrary commutative base ring.  It also constructs the section
at infinity `[0 : 1 : 0]` and the marked section `[0 : 0 : 1]`, and proves that
both split the projective structure morphism.

The generic `Proj` construction and section proofs are adapted from AINTLIB's
`EllipticCurve/WeierstrassModel.lean` and
`EllipticCurve/AffinePointSection.lean`. Exact revisions and license evidence
are recorded in `PORTING.md`. No smoothness, group law, killed locus, or moduli
representability assertion is made here.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory MvPolynomial
open HomogeneousIdeal

namespace MazurTorsion.ModularCurve.XZeroModuli.GammaOneTate
namespace ProjectiveFamily

universe u

attribute [local instance] MvPolynomial.gradedAlgebra

section GenericModel

variable {A : Type u} [CommRing A]

/-- The homogeneous Weierstrass cubic has degree three. -/
theorem polynomial_isHomogeneous (W : WeierstrassCurve A) :
    W.toProjective.polynomial.IsHomogeneous 3 := by
  have hX : (MvPolynomial.X (0 : Fin 3) : MvPolynomial (Fin 3) A).IsHomogeneous 1 :=
    MvPolynomial.isHomogeneous_X _ _
  have hY : (MvPolynomial.X (1 : Fin 3) : MvPolynomial (Fin 3) A).IsHomogeneous 1 :=
    MvPolynomial.isHomogeneous_X _ _
  have hZ : (MvPolynomial.X (2 : Fin 3) : MvPolynomial (Fin 3) A).IsHomogeneous 1 :=
    MvPolynomial.isHomogeneous_X _ _
  refine MvPolynomial.IsHomogeneous.sub ?_ ?_
  · exact (((hY.pow 2).mul hZ).add
      ((((MvPolynomial.isHomogeneous_C _ _).mul hX).mul hY).mul hZ)).add
      (((MvPolynomial.isHomogeneous_C _ _).mul hY).mul (hZ.pow 2))
  · exact (((hX.pow 3).add
      (((MvPolynomial.isHomogeneous_C _ _).mul (hX.pow 2)).mul hZ)).add
      (((MvPolynomial.isHomogeneous_C _ _).mul hX).mul (hZ.pow 2))).add
      ((MvPolynomial.isHomogeneous_C _ _).mul (hZ.pow 3))

/-- The homogeneous principal ideal generated by a Weierstrass cubic. -/
noncomputable def ideal (W : WeierstrassCurve A) :
    HomogeneousIdeal (MvPolynomial.homogeneousSubmodule (Fin 3) A) :=
  ⟨Ideal.span {W.toProjective.polynomial}, Ideal.homogeneous_span _ _ (by
    rintro p hp
    rw [Set.mem_singleton_iff] at hp
    subst hp
    exact ⟨3, (MvPolynomial.mem_homogeneousSubmodule _ _).mpr
      (polynomial_isHomogeneous W)⟩)⟩

@[simp]
theorem ideal_toIdeal (W : WeierstrassCurve A) :
    (ideal W).toIdeal = Ideal.span {W.toProjective.polynomial} :=
  rfl

/-- The homogeneous coordinate ring of the projective cubic. -/
noncomputable abbrev coordinateRing (W : WeierstrassCurve A) : Type u :=
  MvPolynomial (Fin 3) A ⧸ (ideal W).toIdeal

/-- The scheme-theoretic projective Weierstrass hypersurface. -/
@[reducible]
noncomputable def model (W : WeierstrassCurve A) : Scheme.{u} :=
  Proj (quotientGrading (ideal W))

/-- The projective hypersurface structure morphism to `Spec A`. -/
noncomputable def projection (W : WeierstrassCurve A) :
    model W ⟶ Spec (.of A) :=
  Proj.toSpecZero _ ≫
    Spec.map (CommRingCat.ofHom (algebraMapGradeZero (ideal W)))

/-- Evaluation of the quotient coordinate ring at a homogeneous solution. -/
noncomputable def coordinateEval (W : WeierstrassCurve A) (P : Fin 3 → A)
    (hP : MvPolynomial.eval P W.toProjective.polynomial = 0) :
    coordinateRing W →+* A :=
  Ideal.Quotient.lift _ (MvPolynomial.eval P) (by
    intro p hp
    rw [ideal_toIdeal, Ideal.mem_span_singleton] at hp
    obtain ⟨q, rfl⟩ := hp
    rw [map_mul, hP, zero_mul])

@[simp]
theorem coordinateEval_mk (W : WeierstrassCurve A) (P : Fin 3 → A)
    (hP : MvPolynomial.eval P W.toProjective.polynomial = 0)
    (p : MvPolynomial (Fin 3) A) :
    coordinateEval W P hP (Ideal.Quotient.mk (ideal W).toIdeal p) =
      MvPolynomial.eval P p :=
  Ideal.Quotient.lift_mk _ _ _

/-- Every coordinate class has positive degree, hence lies in the irrelevant
ideal of the quotient grading. -/
theorem coordinateClass_mem_irrelevant (W : WeierstrassCurve A) (i : Fin 3) :
    Ideal.Quotient.mk (ideal W).toIdeal (MvPolynomial.X i) ∈
      (HomogeneousIdeal.irrelevant (quotientGrading (ideal W))).toIdeal := by
  exact HomogeneousIdeal.mem_irrelevant_of_mem
    (quotientGrading (ideal W)) (by omega)
    (mk_mem_quotientGrading (ideal W)
      ((MvPolynomial.mem_homogeneousSubmodule _ _).mpr
        (MvPolynomial.isHomogeneous_X _ _)))

/-- If one homogeneous coordinate evaluates to one, evaluation maps the
irrelevant ideal onto the unit ideal. -/
theorem coordinateEval_irrelevant_map_top
    (W : WeierstrassCurve A) (P : Fin 3 → A)
    (hP : MvPolynomial.eval P W.toProjective.polynomial = 0)
    (i : Fin 3) (hi : P i = 1) :
    (HomogeneousIdeal.irrelevant (quotientGrading (ideal W))).toIdeal.map
      ((Scheme.ΓSpecIso (.of A)).inv.hom.comp (coordinateEval W P hP)) = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  have h1 : ((Scheme.ΓSpecIso (.of A)).inv.hom.comp
      (coordinateEval W P hP))
      (Ideal.Quotient.mk (ideal W).toIdeal (MvPolynomial.X i)) = 1 := by
    rw [RingHom.comp_apply, coordinateEval_mk]
    simp [hi]
  rw [← h1]
  exact Ideal.mem_map_of_mem _ (coordinateClass_mem_irrelevant W i)

/-- A normalized homogeneous solution as a section of the projective model. -/
noncomputable def normalizedSection (W : WeierstrassCurve A) (P : Fin 3 → A)
    (hP : MvPolynomial.eval P W.toProjective.polynomial = 0)
    (i : Fin 3) (hi : P i = 1) : Spec (.of A) ⟶ model W :=
  Proj.fromOfGlobalSections _
    ((Scheme.ΓSpecIso (.of A)).inv.hom.comp (coordinateEval W P hP))
    (coordinateEval_irrelevant_map_top W P hP i hi)

/-- Evaluation of constants through a normalized homogeneous section is the
identity on the base ring. -/
@[simp]
theorem coordinateEval_algebraMapGradeZero
    (W : WeierstrassCurve A) (P : Fin 3 → A)
    (hP : MvPolynomial.eval P W.toProjective.polynomial = 0) (a : A) :
    coordinateEval W P hP
      (algebraMap (↥(quotientGrading (ideal W) 0)) (coordinateRing W)
        (algebraMapGradeZero (ideal W) a)) = a := by
  have hmk : algebraMap A (coordinateRing W) a =
      Ideal.Quotient.mk (ideal W).toIdeal (MvPolynomial.C a) := by
    rw [IsScalarTower.algebraMap_eq A (MvPolynomial (Fin 3) A)
      (coordinateRing W), RingHom.comp_apply, Ideal.Quotient.algebraMap_eq,
      MvPolynomial.algebraMap_eq]
  rw [show (algebraMap (↥(quotientGrading (ideal W) 0)) (coordinateRing W))
      (algebraMapGradeZero (ideal W) a) =
        algebraMap A (coordinateRing W) a from rfl,
    hmk, coordinateEval_mk]
  simp

/-- A normalized homogeneous solution splits the projective structure map. -/
@[reassoc (attr := simp)]
theorem normalizedSection_projection (W : WeierstrassCurve A) (P : Fin 3 → A)
    (hP : MvPolynomial.eval P W.toProjective.polynomial = 0)
    (i : Fin 3) (hi : P i = 1) :
    normalizedSection W P hP i hi ≫ projection W = 𝟙 _ := by
  have key : (((Scheme.ΓSpecIso (.of A)).inv.hom.comp
        (coordinateEval W P hP)).comp
          (algebraMap (↥(quotientGrading (ideal W) 0))
            (coordinateRing W))).comp
      (algebraMapGradeZero (ideal W)) =
        (Scheme.ΓSpecIso (.of A)).inv.hom := by
    ext a
    change (Scheme.ΓSpecIso (.of A)).inv.hom
      (coordinateEval W P hP
        (algebraMap _ (coordinateRing W)
          (algebraMapGradeZero (ideal W) a))) = _
    rw [coordinateEval_algebraMapGradeZero]
  rw [normalizedSection, projection]
  simp only [Proj.fromOfGlobalSections_toSpecZero_assoc]
  rw [← Spec.map_comp, ← CommRingCat.ofHom_comp, key,
    CommRingCat.ofHom_hom]
  exact toSpecΓ_SpecMap_ΓSpecIso_inv (.of A)

end GenericModel

section UniversalTate

variable (R : CommRingCat.{u})

/-- The actual universal projective Tate hypersurface over the affine Tate
parameter ring. -/
@[reducible]
noncomputable def family : Scheme.{u} :=
  model (tateCurveLocOver R)

/-- The universal projective Tate family over its parameter base. -/
noncomputable def familyProjection : family R ⟶ tateBase R :=
  projection (tateCurveLocOver R)

private theorem infinity_eval_polynomial :
    MvPolynomial.eval ![0, 1, 0]
      (tateCurveLocOver R).toProjective.polynomial = 0 := by
  change (tateCurveLocOver R).toProjective.Equation ![0, 1, 0]
  exact (tateCurveLocOver R).toProjective.equation_zero

/-- The zero section `[0 : 1 : 0]` of the universal Tate family. -/
noncomputable def zeroSection : tateBase R ⟶ family R :=
  normalizedSection (tateCurveLocOver R) ![0, 1, 0]
    (infinity_eval_polynomial R) 1 (by simp)

@[reassoc (attr := simp)]
theorem zeroSection_familyProjection :
    zeroSection R ≫ familyProjection R = 𝟙 _ :=
  normalizedSection_projection (tateCurveLocOver R) ![0, 1, 0]
    (infinity_eval_polynomial R) 1 (by simp)

/-- The affine origin lies on the universal Tate equation. -/
theorem markedOrigin_equation :
    (tateCurveLocOver R).toAffine.Equation 0 0 := by
  exact WeierstrassCurve.Affine.equation_zero.mpr (tateA₆_eq_zero R)

private theorem markedOrigin_eval_polynomial :
    MvPolynomial.eval ![0, 0, 1]
      (tateCurveLocOver R).toProjective.polynomial = 0 := by
  change (tateCurveLocOver R).toProjective.Equation ![0, 0, 1]
  exact (WeierstrassCurve.Projective.equation_some 0 0).mpr
    (markedOrigin_equation R)

/-- The marked section `[0 : 0 : 1]` of the universal Tate family. -/
noncomputable def markedSection : tateBase R ⟶ family R :=
  normalizedSection (tateCurveLocOver R) ![0, 0, 1]
    (markedOrigin_eval_polynomial R) 2 (by simp)

@[reassoc (attr := simp)]
theorem markedSection_familyProjection :
    markedSection R ≫ familyProjection R = 𝟙 _ :=
  normalizedSection_projection (tateCurveLocOver R) ![0, 0, 1]
    (markedOrigin_eval_polynomial R) 2 (by simp)

end UniversalTate

end ProjectiveFamily
end MazurTorsion.ModularCurve.XZeroModuli.GammaOneTate
