/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.EllipticCurve.VariableChange
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Split rational cyclic subgroups and the open `X₀(N)` source datum

This file isolates the part of the `Γ₀(N)` moduli bridge that is already
available at the project's exact Mathlib pin.  A rational point of exact order
`N` generates a cyclic subgroup of the rational point group with exactly `N`
elements.  Forgetting the chosen generator gives a **split** rational
`Γ₀(N)` source datum `(E, C)`.

This is the source data needed to send rational torsion to a modular curve,
but it is not the full functor of `X₀(N)`: a general rational `X₀(N)` point
has a Galois-stable finite cyclic subgroup scheme whose geometric points need
not all be rational.  In particular, the type below is not closed under an
Atkin--Lehner involution.  Constructing that involution requires the finite
flat subgroup-scheme moduli layer, not merely a subgroup of `E(K)`.

Constructing the elliptic quotient `E/C`, and proving that the resulting datum
is classified by the coarse open modular curve, are scheme-theoretic geometry
that is not present at the core package's exact pin.  The downstream theorem
`XZeroFortyNine.rationalPoint_addOrderOf_ne_fortyNine_of_classifyingMap`
therefore takes that genuine classifying map as its explicit remaining input
and lands in the already checked two-cusp model of `X₀(49)`.
-/

open scoped WeierstrassCurve.Affine

namespace MazurTorsion.ModularCurve.XZeroModuli

universe u

/-- A finite cyclic subgroup of order `N` in an additive commutative group.

When the ambient group is `E(K)`, every element of `carrier` is already
`K`-rational.  The structure forgets a chosen generator, as required by a
`Γ₀(N)` rather than a `Γ₁(N)` datum. -/
structure RationalCyclicSubgroup (A : Type u) [AddCommGroup A]
    (N : ℕ) [NeZero N] where
  /-- The subgroup of rational points. -/
  carrier : AddSubgroup A
  /-- The subgroup is cyclic. -/
  isAddCyclic : IsAddCyclic carrier
  /-- Its cardinality is the level `N`. -/
  card_eq : Nat.card carrier = N

namespace RationalCyclicSubgroup

variable {A B : Type*} [AddCommGroup A] [AddCommGroup B]
  {N : ℕ} [NeZero N]

instance (C : RationalCyclicSubgroup A N) : IsAddCyclic C.carrier :=
  C.isAddCyclic

noncomputable instance (C : RationalCyclicSubgroup A N) : Finite C.carrier :=
  Nat.finite_of_card_ne_zero <| by
    rw [C.card_eq]
    exact NeZero.ne N

@[ext]
theorem ext {C D : RationalCyclicSubgroup A N}
    (h : C.carrier = D.carrier) : C = D := by
  cases C
  cases D
  cases h
  rfl

/-- The subgroup generated by a point of exact order `N`, with its cardinality
proved from `Nat.card_zmultiples`. -/
def ofPoint (P : A) (hP : addOrderOf P = N) :
    RationalCyclicSubgroup A N where
  carrier := AddSubgroup.zmultiples P
  isAddCyclic := inferInstance
  card_eq := (Nat.card_zmultiples P).trans hP

@[simp]
theorem ofPoint_carrier (P : A) (hP : addOrderOf P = N) :
    (ofPoint P hP).carrier = AddSubgroup.zmultiples P :=
  rfl

theorem point_mem_ofPoint (P : A) (hP : addOrderOf P = N) :
    P ∈ (ofPoint P hP).carrier := by
  exact AddSubgroup.mem_zmultiples_iff.mpr ⟨1, by simp⟩

/-- Transport a rational cyclic subgroup along an isomorphism of point groups. -/
def map (C : RationalCyclicSubgroup A N) (e : A ≃+ B) :
    RationalCyclicSubgroup B N where
  carrier := C.carrier.map e.toAddMonoidHom
  isAddCyclic := (e.addSubgroupMap C.carrier).isAddCyclic.mp C.isAddCyclic
  card_eq := (Nat.card_congr (e.addSubgroupMap C.carrier).toEquiv).symm.trans C.card_eq

@[simp]
theorem map_carrier (C : RationalCyclicSubgroup A N) (e : A ≃+ B) :
    (C.map e).carrier = C.carrier.map e.toAddMonoidHom :=
  rfl

/-- Generating a subgroup commutes with transport along a point-group
isomorphism. -/
theorem map_ofPoint (P : A) (hP : addOrderOf P = N) (e : A ≃+ B) :
    (ofPoint P hP).map e =
      ofPoint (e P) ((e.addOrderOf_eq P).trans hP) := by
  apply ext
  exact e.toAddMonoidHom.map_zmultiples P

/-- A cyclic subgroup presented without a chosen generator still has one. -/
noncomputable def generator (C : RationalCyclicSubgroup A N) : C.carrier :=
  (isAddCyclic_iff_exists_addOrderOf_eq_natCard.mp C.isAddCyclic).choose

@[simp]
theorem addOrderOf_generator_subtype (C : RationalCyclicSubgroup A N) :
    addOrderOf C.generator = N :=
  (isAddCyclic_iff_exists_addOrderOf_eq_natCard.mp C.isAddCyclic).choose_spec.trans
    C.card_eq

/-- The chosen generator also has exact order `N` in the ambient rational
point group. -/
@[simp]
theorem addOrderOf_generator (C : RationalCyclicSubgroup A N) :
    addOrderOf (C.generator : A) = N :=
  (addOrderOf_injective (AddSubgroup.subtype C.carrier)
    C.carrier.subtype_injective C.generator).trans C.addOrderOf_generator_subtype

/-- The selected generator generates the supplied subgroup, not merely some
cyclic group of the same cardinality. -/
theorem zmultiples_generator (C : RationalCyclicSubgroup A N) :
    AddSubgroup.zmultiples (C.generator : A) = C.carrier := by
  ext x
  constructor
  · rintro ⟨k, rfl⟩
    exact C.carrier.zsmul_mem C.generator.property k
  · intro hx
    have htop : AddSubgroup.zmultiples C.generator = ⊤ := by
      apply AddSubgroup.eq_top_of_card_eq
      rw [Nat.card_zmultiples, C.addOrderOf_generator_subtype]
      exact C.card_eq.symm
    have hx' : (⟨x, hx⟩ : C.carrier) ∈ AddSubgroup.zmultiples C.generator := by
      rw [htop]
      trivial
    rcases AddSubgroup.mem_zmultiples_iff.mp hx' with ⟨k, hk⟩
    exact AddSubgroup.mem_zmultiples_iff.mpr ⟨k, congrArg Subtype.val hk⟩

/-- A cyclic subgroup of order different from one is nontrivial. -/
theorem carrier_ne_bot (C : RationalCyclicSubgroup A N) (hN : N ≠ 1) :
    C.carrier ≠ ⊥ := by
  intro hbot
  apply hN
  rw [← C.card_eq, hbot, AddSubgroup.card_bot]

/-! ### Canonical subgroups at divisor levels -/

/-- The canonical cyclic subgroup of order `d` inside a cyclic subgroup of
order `N`, for `d ∣ N`.

Its carrier is intrinsic: it consists of the elements of `C` killed by `d`.
The cardinality calculation uses the kernel of multiplication by `d` on the
finite cyclic group `C`.  This is the functor-of-points input for the
restriction of the degeneracy map `X₀(N) → X₀(d)` to split source data. -/
noncomputable def divisorSubgroup (C : RationalCyclicSubgroup A N)
    (d : ℕ) [NeZero d] (hd : d ∣ N) : RationalCyclicSubgroup A d := by
  let H : AddSubgroup C.carrier :=
    (nsmulAddMonoidHom (α := C.carrier) d).ker
  have hcarrier :
      H.map (AddSubgroup.subtype C.carrier) =
        C.carrier ⊓ (nsmulAddMonoidHom (α := A) d).ker := by
    ext x
    simp [H, and_comm]
  letI : IsAddCyclic H := AddSubgroup.isAddCyclic_of_le
    (show H ≤ (⊤ : AddSubgroup C.carrier) from le_top)
  let e : H ≃+ H.map (AddSubgroup.subtype C.carrier) :=
    AddSubgroup.equivMapOfInjective H (AddSubgroup.subtype C.carrier)
      C.carrier.subtype_injective
  refine
    { carrier := C.carrier ⊓ (nsmulAddMonoidHom (α := A) d).ker
      isAddCyclic := ?_
      card_eq := ?_ }
  · rw [← hcarrier]
    exact isAddCyclic_of_surjective e e.surjective
  · rw [← hcarrier]
    calc
      Nat.card ↥(H.map (AddSubgroup.subtype C.carrier)) = Nat.card H :=
        (Nat.card_congr e.toEquiv).symm
      _ = (Nat.card C.carrier).gcd d := by
        simpa only [H] using
          IsAddCyclic.card_nsmulAddMonoidHom_ker C.carrier d
      _ = N.gcd d := by rw [C.card_eq]
      _ = d := Nat.gcd_eq_right hd

@[simp]
theorem mem_divisorSubgroup (C : RationalCyclicSubgroup A N)
    (d : ℕ) [NeZero d] (hd : d ∣ N) (x : A) :
    x ∈ (C.divisorSubgroup d hd).carrier ↔
      x ∈ C.carrier ∧ d • x = 0 := by
  simp [divisorSubgroup]

/-- Taking the canonical divisor-level subgroup commutes with transport along
an isomorphism of ambient point groups. -/
theorem map_divisorSubgroup (C : RationalCyclicSubgroup A N)
    (d : ℕ) [NeZero d] (hd : d ∣ N) (e : A ≃+ B) :
    (C.divisorSubgroup d hd).map e = (C.map e).divisorSubgroup d hd := by
  apply ext
  ext x
  simp only [map_carrier, mem_divisorSubgroup, AddSubgroup.mem_map]
  constructor
  · rintro ⟨y, ⟨hyC, hyd⟩, rfl⟩
    exact ⟨⟨y, hyC, rfl⟩, by simpa using congrArg e hyd⟩
  · rintro ⟨⟨y, hyC, hyx⟩, hdx⟩
    subst x
    refine ⟨y, ⟨hyC, ?_⟩, rfl⟩
    exact e.injective (by simpa using hdx)

/-- Divisor-level subgroups compose as the corresponding degeneracy maps do. -/
theorem divisorSubgroup_divisorSubgroup (C : RationalCyclicSubgroup A N)
    (d e : ℕ) [NeZero d] [NeZero e]
    (hd : d ∣ N) (he : e ∣ d) :
    (C.divisorSubgroup d hd).divisorSubgroup e he =
      C.divisorSubgroup e (dvd_trans he hd) := by
  apply ext
  ext x
  simp only [mem_divisorSubgroup]
  constructor
  · rintro ⟨⟨hx, _⟩, hex⟩
    exact ⟨hx, hex⟩
  · rintro ⟨hx, hex⟩
    refine ⟨⟨hx, ?_⟩, hex⟩
    obtain ⟨k, hk⟩ := he
    rw [hk, mul_nsmul, hex, nsmul_zero]

/-- For a cyclic subgroup presented by a point `P` of exact order `N`, the
intrinsic divisor-level subgroup is generated by `(N / d) • P`. -/
theorem divisorSubgroup_ofPoint_carrier
    (P : A) (hP : addOrderOf P = N)
    (d : ℕ) [NeZero d] (hd : d ∣ N) :
    ((ofPoint P hP).divisorSubgroup d hd).carrier =
      AddSubgroup.zmultiples ((N / d) • P) := by
  have hNpos : 0 < N := Nat.pos_of_ne_zero (NeZero.ne N)
  have hdpos : 0 < d := Nat.pos_of_ne_zero (NeZero.ne d)
  have hdle : d ≤ N := Nat.le_of_dvd hNpos hd
  have hscale : N / d ≠ 0 := (Nat.div_pos hdle hdpos).ne'
  have hscaleDvd : N / d ∣ addOrderOf P := by
    rw [hP]
    exact Nat.div_dvd_of_dvd hd
  have hscaledOrder : addOrderOf ((N / d) • P) = d := by
    calc
      addOrderOf ((N / d) • P) = addOrderOf P / (N / d) :=
        addOrderOf_nsmul_of_dvd hscale hscaleDvd
      _ = N / (N / d) := by rw [hP]
      _ = d := Nat.div_div_self hd (NeZero.ne N)
  have hgeneratorMem :
      (N / d) • P ∈ ((ofPoint P hP).divisorSubgroup d hd).carrier := by
    rw [mem_divisorSubgroup]
    constructor
    · exact (ofPoint P hP).carrier.nsmul_mem (point_mem_ofPoint P hP) (N / d)
    · have horderZero := addOrderOf_nsmul_eq_zero ((N / d) • P)
      rw [hscaledOrder] at horderZero
      exact horderZero
  exact (AddSubgroup.eq_of_le_of_card_ge
    (AddSubgroup.zmultiples_le_of_mem hgeneratorMem)
    (by
      rw [(ofPoint P hP).divisorSubgroup d hd |>.card_eq,
        Nat.card_zmultiples, hscaledOrder])).symm

/-- The intrinsic divisor-level subgroup is generated by the corresponding
multiple of any selected generator of `C`. -/
theorem divisorSubgroup_generator_carrier (C : RationalCyclicSubgroup A N)
    (d : ℕ) [NeZero d] (hd : d ∣ N) :
    (C.divisorSubgroup d hd).carrier =
      AddSubgroup.zmultiples ((N / d) • (C.generator : A)) := by
  have hC : ofPoint (C.generator : A) C.addOrderOf_generator = C :=
    ext C.zmultiples_generator
  calc
    (C.divisorSubgroup d hd).carrier =
        ((ofPoint (C.generator : A) C.addOrderOf_generator).divisorSubgroup
          d hd).carrier := by rw [hC]
    _ = AddSubgroup.zmultiples ((N / d) • (C.generator : A)) :=
      divisorSubgroup_ofPoint_carrier
        (C.generator : A) C.addOrderOf_generator d hd

end RationalCyclicSubgroup

universe v

/-- A raw split rational `Γ₀(N)` source datum `(E, C)` over a field.

It is a restricted input to the open modular curve, not its full functor of
points: every element of `C` is required to lie in `E(K)`.  The raw structure
is not itself an isomorphism class; below, `VariableChangeClass` quotients out
the admissible Weierstrass changes already available in checked code.
Constructing the coarse moduli point and general Galois-stable subgroup
schemes remains the next geometric layer. -/
structure RationalDatum (K : Type v) [Field K] [DecidableEq K]
    (N : ℕ) [NeZero N] where
  /-- The Weierstrass model. -/
  curve : WeierstrassCurve K
  /-- Smoothness of the model. -/
  isElliptic : curve.IsElliptic
  /-- The rational cyclic subgroup of order `N`. -/
  subgroup : RationalCyclicSubgroup curve.toAffine.Point N

namespace RationalDatum

variable {K : Type*} [Field K] [DecidableEq K]
  {N : ℕ} [NeZero N]

instance (x : RationalDatum K N) : x.curve.IsElliptic :=
  x.isElliptic

/-- Package an elliptic curve and a split rational cyclic subgroup as a raw
`Γ₀(N)` source datum. -/
def datumOfRationalCyclicSubgroup (E : WeierstrassCurve K) [E.IsElliptic]
    (C : RationalCyclicSubgroup E.toAffine.Point N) : RationalDatum K N where
  curve := E
  isElliptic := inferInstance
  subgroup := C

/-- A rational point of exact order `N` supplies the open `Γ₀(N)` datum
by forgetting its choice of generator. -/
def datumOfTorsion (E : WeierstrassCurve K) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = N) : RationalDatum K N :=
  datumOfRationalCyclicSubgroup E (RationalCyclicSubgroup.ofPoint P hP)

@[simp]
theorem datumOfTorsion_curve (E : WeierstrassCurve K) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = N) :
    (datumOfTorsion E P hP).curve = E :=
  rfl

@[simp]
theorem datumOfTorsion_subgroup (E : WeierstrassCurve K) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = N) :
    (datumOfTorsion E P hP).subgroup.carrier = AddSubgroup.zmultiples P :=
  rfl

/-- Conversely, a raw split rational `Γ₀(N)` source datum contains a rational point
of exact order `N`, because its subgroup is finite cyclic of order `N`. -/
noncomputable def generator (x : RationalDatum K N) : x.curve.toAffine.Point :=
  x.subgroup.generator

@[simp]
theorem addOrderOf_generator (x : RationalDatum K N) :
    addOrderOf x.generator = N :=
  x.subgroup.addOrderOf_generator

/-- Forget part of a cyclic level structure along a divisor `d ∣ N`.
This is the divisor-level degeneracy map from split `Γ₀(N)` source data to
split `Γ₀(d)` source data. -/
noncomputable def forgetToDivisor (x : RationalDatum K N)
    (d : ℕ) [NeZero d] (hd : d ∣ N) : RationalDatum K d :=
  datumOfRationalCyclicSubgroup x.curve (x.subgroup.divisorSubgroup d hd)

@[simp]
theorem forgetToDivisor_curve (x : RationalDatum K N)
    (d : ℕ) [NeZero d] (hd : d ∣ N) :
    (x.forgetToDivisor d hd).curve = x.curve :=
  rfl

@[simp]
theorem forgetToDivisor_subgroup_mem (x : RationalDatum K N)
    (d : ℕ) [NeZero d] (hd : d ∣ N) (P : x.curve.toAffine.Point) :
    P ∈ (x.forgetToDivisor d hd).subgroup.carrier ↔
      P ∈ x.subgroup.carrier ∧ d • P = 0 :=
  x.subgroup.mem_divisorSubgroup d hd P

/-- Successive forgetting along `e ∣ d ∣ N` agrees with forgetting directly
to level `e`. -/
theorem forgetToDivisor_forgetToDivisor (x : RationalDatum K N)
    (d e : ℕ) [NeZero d] [NeZero e]
    (hd : d ∣ N) (he : e ∣ d) :
    (x.forgetToDivisor d hd).forgetToDivisor e he =
      x.forgetToDivisor e (dvd_trans he hd) := by
  unfold forgetToDivisor datumOfRationalCyclicSubgroup
  congr 1
  exact x.subgroup.divisorSubgroup_divisorSubgroup d e hd he

/-! ### Independence of the Weierstrass presentation -/

/-- Transport a raw `Γ₀(N)` datum along an admissible change of Weierstrass
variables.  The inverse point-group equivalence transports the subgroup from
the old model to the changed model. -/
def variableChange (x : RationalDatum K N)
    (C : WeierstrassCurve.VariableChange K) : RationalDatum K N where
  curve := C • x.curve
  isElliptic := inferInstance
  subgroup := x.subgroup.map
    (WeierstrassCurve.Affine.Point.equivVariableChange x.curve C).symm

@[simp]
theorem variableChange_curve (x : RationalDatum K N)
    (C : WeierstrassCurve.VariableChange K) :
    (x.variableChange C).curve = C • x.curve :=
  rfl

@[simp]
theorem variableChange_subgroup_carrier (x : RationalDatum K N)
    (C : WeierstrassCurve.VariableChange K) :
    (x.variableChange C).subgroup.carrier =
      x.subgroup.carrier.map
        (WeierstrassCurve.Affine.Point.equivVariableChange x.curve C).symm.toAddMonoidHom :=
  rfl

/-- The raw divisor-level degeneracy map is natural under admissible changes
of Weierstrass presentation. -/
theorem forgetToDivisor_variableChange (x : RationalDatum K N)
    (d : ℕ) [NeZero d] (hd : d ∣ N)
    (C : WeierstrassCurve.VariableChange K) :
    (x.variableChange C).forgetToDivisor d hd =
      (x.forgetToDivisor d hd).variableChange C := by
  cases x with
  | mk E hE subgroup =>
      simp only [forgetToDivisor, variableChange,
        datumOfRationalCyclicSubgroup]
      congr 1
      exact (subgroup.map_divisorSubgroup d hd
        (WeierstrassCurve.Affine.Point.equivVariableChange E C).symm).symm

/-- One-step equivalence of raw data under an admissible Weierstrass variable
change.  Its equivalence closure is used below, avoiding any claim that a
general coarse modular quotient has already been constructed. -/
def VariableChangeRelated (x y : RationalDatum K N) : Prop :=
  ∃ C : WeierstrassCurve.VariableChange K, x.variableChange C = y

/-- The equivalence relation generated by admissible changes of a Weierstrass
presentation and the induced transport of its cyclic subgroup. -/
def variableChangeSetoid : Setoid (RationalDatum K N) :=
  Relation.EqvGen.setoid VariableChangeRelated

/-- Raw split rational `Γ₀(N)` source data modulo the checked admissible changes of
Weierstrass presentation.  This is deliberately named a variable-change
class, not a coarse-moduli point: representability and the map to `X₀(N)`
remain geometric work. -/
def VariableChangeClass := Quotient (variableChangeSetoid (K := K) (N := N))

/-- Forget the chosen Weierstrass presentation of a raw rational datum. -/
def variableChangeClassOf (x : RationalDatum K N) :
    VariableChangeClass (K := K) (N := N) :=
  Quotient.mk (variableChangeSetoid (K := K) (N := N)) x

/-- The variable-change class is independent of one admissible change of
presentation. -/
theorem variableChangeClassOf_variableChange (x : RationalDatum K N)
    (C : WeierstrassCurve.VariableChange K) :
    variableChangeClassOf (x.variableChange C) = variableChangeClassOf x := by
  apply Quotient.sound (s := variableChangeSetoid (K := K) (N := N))
  have hrel : VariableChangeRelated x (x.variableChange C) := ⟨C, rfl⟩
  exact Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ hrel)

namespace VariableChangeClass

/-- Descend a function on raw rational data which is invariant under every
admissible change of Weierstrass presentation.  This is the checked API through
which a future coarse `X₀(N)` classifying map can be built. -/
def lift {P : Sort*} (f : RationalDatum K N → P)
    (h : ∀ x C, f (x.variableChange C) = f x) :
    VariableChangeClass (K := K) (N := N) → P :=
  Quotient.lift f fun x y hxy ↦ by
    induction hxy with
    | rel x y hxy =>
        obtain ⟨C, rfl⟩ := hxy
        exact (h x C).symm
    | refl => rfl
    | symm _ _ _ ih => exact ih.symm
    | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

@[simp]
theorem lift_variableChangeClassOf {P : Sort*} (f : RationalDatum K N → P)
    (h : ∀ x C, f (x.variableChange C) = f x) (x : RationalDatum K N) :
    lift f h (variableChangeClassOf x) = f x :=
  rfl

/-- The presentation-independent divisor-level degeneracy map on checked
variable-change classes. -/
noncomputable def forgetToDivisor
    (d : ℕ) [NeZero d] (hd : d ∣ N) :
    VariableChangeClass (K := K) (N := N) →
      VariableChangeClass (K := K) (N := d) :=
  lift
    (fun x ↦ variableChangeClassOf (x.forgetToDivisor d hd))
    (fun x C ↦ by
      rw [RationalDatum.forgetToDivisor_variableChange,
        variableChangeClassOf_variableChange])

@[simp]
theorem forgetToDivisor_variableChangeClassOf
    (d : ℕ) [NeZero d] (hd : d ∣ N) (x : RationalDatum K N) :
    forgetToDivisor d hd (variableChangeClassOf x) =
      variableChangeClassOf (x.forgetToDivisor d hd) :=
  rfl

end VariableChangeClass

end RationalDatum

end MazurTorsion.ModularCurve.XZeroModuli
