/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI Codex
-/

import MazurTorsion.ModularCurve.XZeroEllipticQuotientRepresentability
import MazurTorsion.ModularCurve.XZeroWeierstrassCanonicalFiniteFlatSubgroup

/-!
# Canonical cyclic quotient generated by an exact-torsion point

This module is the design boundary between an exact-order coordinate point on
a concrete projective Weierstrass cubic and its represented cyclic quotient.
It specializes the finite-translation representability construction to the
canonical projective group object, canonical coordinate-point comparison, and
canonical split finite-flat subgroup.  No group object, point equivalence,
subgroup, or quotient presentation is supplied by a caller.

The quotient is bundled as an abelian variety over `ℚ`.  Its projection is
finite étale and fppf, its scheme-theoretic kernel is the canonical subgroup,
and the kernel identification is retained after arbitrary base change.  The
named downstream consumer is
`MazurTorsion.XZeroFortyNine.orderFortyNineEllipticQuotientPresentation`.
-/

noncomputable section

open CategoryTheory CategoryTheory.MonoidalCategory CategoryTheory.MonObj
open _root_.AlgebraicGeometry

attribute [local instance] CategoryTheory.Over.cartesianMonoidalCategory
  CategoryTheory.Over.braidedCategory

namespace MazurTorsion.ModularCurve.XZeroFiniteFlatModuli
namespace WeierstrassProjectiveCubic

open XZeroModuli
open WeierstrassGroupSchemeInterface
open WeierstrassGroupSchemeInterface.EllipticQuotientRepresentability

variable {N : ℕ} [NeZero N]

/-- The represented commutative group-scheme quotient by the canonical
finite-flat subgroup generated by an exact-order point. -/
noncomputable def canonicalCyclicQuotientGroupScheme
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    CommGroupScheme (Spec (.of ℚ)) :=
  EllipticQuotientRepresentability.quotient
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

/-- The canonical cyclic quotient, bundled as an actual abelian variety. -/
noncomputable def canonicalCyclicQuotientAbelianVariety
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    TauCeti.AlgebraicGeometry.AbelianVariety ℚ :=
  EllipticQuotientRepresentability.quotientAbelianVariety
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

/-- The canonical finite étale projection to the represented cyclic
quotient. -/
noncomputable def canonicalCyclicQuotientProjection
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    (canonicalWeierstrassGroupSchemeInterface W).groupScheme ⟶
      CommGrp.mk (canonicalCyclicQuotientAbelianVariety W P hP).toOver :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVariety
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

/-- The canonical fppf quotient presentation whose kernel is the subgroup
generated by `P`. -/
noncomputable def canonicalCyclicQuotientPresentation
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    CommGroupScheme.FppfQuotientPresentation
      (canonicalSplitGammaZeroDatumOfTorsion W P hP).subgroup.inclusion :=
  EllipticQuotientRepresentability.geometricQuotientPresentation
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

@[simp]
theorem canonicalCyclicQuotientAbelianVariety_toOver
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    (canonicalCyclicQuotientAbelianVariety W P hP).toOver =
      (canonicalCyclicQuotientPresentation W P hP).quotient.X :=
  rfl

@[simp]
theorem canonicalCyclicQuotientProjection_eq_presentation
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    canonicalCyclicQuotientProjection W P hP =
      (canonicalCyclicQuotientPresentation W P hP).project :=
  rfl

/-- The canonical cyclic quotient projection is finite. -/
theorem canonicalCyclicQuotientProjection_isFinite
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    IsFinite (CommGroupScheme.underlyingHom
      (canonicalCyclicQuotientProjection W P hP)) :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVariety_isFinite
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

/-- The canonical cyclic quotient projection is étale. -/
theorem canonicalCyclicQuotientProjection_etale
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    Etale (CommGroupScheme.underlyingHom
      (canonicalCyclicQuotientProjection W P hP)) :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVariety_etale
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

/-- The canonical cyclic quotient projection is an fppf cover. -/
theorem canonicalCyclicQuotientProjection_is_fppf
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    Flat (CommGroupScheme.underlyingHom
        (canonicalCyclicQuotientProjection W P hP)) ∧
      Surjective (CommGroupScheme.underlyingHom
        (canonicalCyclicQuotientProjection W P hP)) ∧
      LocallyOfFinitePresentation (CommGroupScheme.underlyingHom
        (canonicalCyclicQuotientProjection W P hP)) :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVariety_is_fppf
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

/-- The represented cyclic quotient is smooth of relative dimension one. -/
theorem canonicalCyclicQuotient_structureMap_smoothOfRelativeDimension_one
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    SmoothOfRelativeDimension 1
      (canonicalCyclicQuotientAbelianVariety W P hP).toOver.hom := by
  change SmoothOfRelativeDimension 1
    (EllipticQuotientRepresentability.quotient
      (RationalDatum.datumOfTorsion W P hP)
      (canonicalProjectivePointMulEquiv W)).X.hom
  exact EllipticQuotientRepresentability.quotient_structureMap_smoothOfRelativeDimension_one
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

/-- The canonical subgroup is the scheme-theoretic kernel of the represented
quotient projection. -/
noncomputable def canonicalCyclicQuotientProjectionKernelIso
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    (canonicalSplitGammaZeroDatumOfTorsion W P hP).subgroup.carrier.obj ≅
      CommGroupScheme.kernel (canonicalCyclicQuotientProjection W P hP) :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVarietyKernelIso
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

@[reassoc]
theorem canonicalCyclicQuotientProjectionKernelIso_hom_kernelInclusion
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    (canonicalCyclicQuotientProjectionKernelIso W P hP).hom ≫
        CommGroupScheme.kernelInclusion
          (canonicalCyclicQuotientProjection W P hP) =
      (canonicalSplitGammaZeroDatumOfTorsion W P hP).subgroup.inclusion :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVarietyKernelIso_hom_kernelInclusion
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W)

/-- Exact kernel identity in the canonical fppf quotient presentation. -/
theorem canonicalCyclicQuotientPresentation_kernel_exact
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    (canonicalCyclicQuotientPresentation W P hP).kernelIso.hom ≫
        CommGroupScheme.kernelInclusion
          (canonicalCyclicQuotientPresentation W P hP).project =
      (canonicalSplitGammaZeroDatumOfTorsion W P hP).subgroup.inclusion :=
  (canonicalCyclicQuotientPresentation W P hP).kernelIso_hom_kernelInclusion

/-- The canonical quotient presentation after an arbitrary base change. -/
noncomputable def canonicalCyclicQuotientPresentationBaseChange
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    {T : Scheme} (t : T ⟶ Spec (.of ℚ)) :=
  (canonicalCyclicQuotientPresentation W P hP).baseChange t

@[simp]
theorem canonicalCyclicQuotientPresentationBaseChange_quotient
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    {T : Scheme} (t : T ⟶ Spec (.of ℚ)) :
    (canonicalCyclicQuotientPresentationBaseChange W P hP t).quotient =
      (Over.pullback t).mapCommGrp.obj
        (canonicalCyclicQuotientPresentation W P hP).quotient :=
  rfl

@[simp]
theorem canonicalCyclicQuotientPresentationBaseChange_project
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    {T : Scheme} (t : T ⟶ Spec (.of ℚ)) :
    (canonicalCyclicQuotientPresentationBaseChange W P hP t).project =
      (Over.pullback t).mapCommGrp.map
        (canonicalCyclicQuotientPresentation W P hP).project :=
  rfl

/-- Every base change of the canonical quotient projection remains finite. -/
theorem canonicalCyclicQuotientPresentationBaseChange_project_isFinite
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    {T : Scheme} (t : T ⟶ Spec (.of ℚ)) :
    IsFinite (CommGroupScheme.underlyingHom
      (canonicalCyclicQuotientPresentationBaseChange W P hP t).project) :=
  EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange_project_isFinite
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W) t

/-- Every base change of the canonical quotient projection remains étale. -/
theorem canonicalCyclicQuotientPresentationBaseChange_project_etale
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    {T : Scheme} (t : T ⟶ Spec (.of ℚ)) :
    Etale (CommGroupScheme.underlyingHom
      (canonicalCyclicQuotientPresentationBaseChange W P hP t).project) :=
  EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange_project_etale
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W) t

/-- The base-changed quotient remains smooth of relative dimension one. -/
theorem canonicalCyclicQuotientBaseChange_smoothOfRelativeDimension_one
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    {T : Scheme} (t : T ⟶ Spec (.of ℚ)) :
    SmoothOfRelativeDimension 1
      (canonicalCyclicQuotientPresentationBaseChange W P hP t).quotient.X.hom :=
  geometricQuotientPresentationBaseChange_quotient_structureMap_smoothOfRelativeDimension_one
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalProjectivePointMulEquiv W) t

@[simp]
theorem canonicalCyclicQuotientPresentationBaseChange_kernel_inclusion
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    {T : Scheme} (t : T ⟶ Spec (.of ℚ)) :
    (canonicalCyclicQuotientPresentationBaseChange W P hP t).kernelPresentation.inclusion =
      (Over.pullback t).mapCommGrp.map
        (canonicalSplitGammaZeroDatumOfTorsion W P hP).subgroup.inclusion :=
  rfl

/-- The canonical subgroup remains exactly the geometric kernel after every
base change. -/
theorem canonicalCyclicQuotientPresentationBaseChange_kernel_exact
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    {T : Scheme} (t : T ⟶ Spec (.of ℚ)) :
    (canonicalCyclicQuotientPresentationBaseChange W P hP t).kernelIso.hom ≫
        CommGroupScheme.kernelInclusion
          (canonicalCyclicQuotientPresentationBaseChange W P hP t).project =
      (Over.pullback t).mapCommGrp.map
        (canonicalSplitGammaZeroDatumOfTorsion W P hP).subgroup.inclusion :=
  (canonicalCyclicQuotientPresentationBaseChange W P hP t).kernelIso_hom_kernelInclusion

/-- For a field extension, the arbitrary-base-change kernel is the named
finite-flat base change of the canonical subgroup. -/
theorem canonicalCyclicQuotient_fieldBaseChange_kernel_inclusion
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N)
    (L : Type) [Field L] [Algebra ℚ L] :
    (canonicalCyclicQuotientPresentationBaseChange W P hP
      (Spec.map (CommRingCat.ofHom (algebraMap ℚ L)))).kernelPresentation.inclusion =
      ((canonicalSplitGammaZeroDatumOfTorsion W P hP).subgroup.baseChange).inclusion :=
  rfl

/-- The quotient of represented rational points by the canonical subgroup
injects into rational points of the represented quotient. -/
theorem canonicalCyclicQuotientPointQuotientMap_injective
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    Function.Injective
      ((canonicalCyclicQuotientPresentation W P hP).pointQuotientMap
        (AffineCommGroupScheme.testObject (R := ℚ) ℚ)) :=
  WeierstrassGroupSchemeInterface.rationalDatumGeometricPointQuotientMap_injective
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalWeierstrassGroupSchemeInterface W)
    (canonicalCyclicQuotientPresentation W P hP)

/-- The fppf connecting map for rational points of the canonical cyclic
quotient. -/
noncomputable def canonicalCyclicQuotientBoundaryHom
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :=
  WeierstrassGroupSchemeInterface.rationalDatumGeometricPointBoundaryHom
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalWeierstrassGroupSchemeInterface W)
    (canonicalCyclicQuotientPresentation W P hP)

/-- The rational-point image is the zero fibre of the genuine fppf boundary
map; no false rational-point surjectivity is asserted. -/
theorem canonicalCyclicQuotientPointQuotient_boundary_exact
    (W : WeierstrassCurve ℚ) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    Function.MulExact
      ((canonicalCyclicQuotientPresentation W P hP).pointQuotientMap
        (AffineCommGroupScheme.testObject (R := ℚ) ℚ))
      (canonicalCyclicQuotientBoundaryHom W P hP) :=
  WeierstrassGroupSchemeInterface.rationalDatumGeometricPointQuotient_boundary_exact
    (RationalDatum.datumOfTorsion W P hP)
    (canonicalWeierstrassGroupSchemeInterface W)
    (canonicalCyclicQuotientPresentation W P hP)

end WeierstrassProjectiveCubic
end MazurTorsion.ModularCurve.XZeroFiniteFlatModuli
