/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI Codex
-/

import MazurTorsion.ModularCurve.XZeroThirtyFiveLocalQuotientAtEleven
import MazurTorsion.ModularCurve.CompleteDVRStalk
import MazurTorsion.ModularCurve.OrderThirtyFiveQuotientQExpansion
import Mathlib.RingTheory.DualNumber
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.Tactic.FinCases

/-!
# The actual level-35 cusp local ring in characteristic eleven

This file works directly with the checked hyperelliptic source chart from
`XZeroThirtyFiveLocalQuotientAtEleven`.  Evaluation at the branch
`(t,y) = (0,1)` descends through the hypersurface quotient and the localization
away from the quotient-map denominator.  Its kernel is the genuine cusp prime.

The source equation gives

`(y - 1) * (y + 1) = t * H(t)`.

At the selected cusp `y + 1` has residue `2`, hence becomes a unit in the
local ring.  Thus the ordinate direction is a multiple of the abscissa
parameter.  This is the local algebra behind q-principality; no isomorphism
of the hyperelliptic germ with a polynomial coordinate ring is assumed.
-/

noncomputable section

namespace MazurTorsion.ModularCurve.XZeroThirtyFiveLocalQuotientAtEleven

open AlgebraicGeometry MvPolynomial
open MazurTorsion.OrderThirtyFive.QuotientQExpansion

local instance primeEleven : Fact (Nat.Prime 11) := ⟨by decide⟩

/-- Evaluation coordinates for the cusp branch `(t,y) = (0,1)`. -/
def cuspCoordinates : Fin 2 → ResidueField :=
  Fin.cases 0 (Fin.cases 1 Fin.elim0)

@[simp]
theorem cuspCoordinates_zero : cuspCoordinates 0 = 0 := rfl

@[simp]
theorem cuspCoordinates_one : cuspCoordinates 1 = 1 := rfl

/-- Evaluation of the ambient two-variable polynomial ring at the selected
cusp. -/
def cuspPolynomialEvaluation :
    MvPolynomial (Fin 2) ResidueField →+* ResidueField :=
  MvPolynomial.eval₂Hom (RingHom.id ResidueField) cuspCoordinates

@[simp]
theorem cuspPolynomialEvaluation_X_zero :
    cuspPolynomialEvaluation (X 0) = 0 := by
  simp [cuspPolynomialEvaluation]

@[simp]
theorem cuspPolynomialEvaluation_X_one :
    cuspPolynomialEvaluation (X 1) = 1 := by
  simp [cuspPolynomialEvaluation]

@[simp]
theorem cuspPolynomialEvaluation_C (a : ResidueField) :
    cuspPolynomialEvaluation (C a) = a := by
  simp [cuspPolynomialEvaluation]

/-- The selected cusp lies on the hyperelliptic source equation. -/
theorem cuspPolynomialEvaluation_sourceEquation :
    cuspPolynomialEvaluation sourceEquation = 0 := by
  simp [sourceEquation, sourcePolynomial, cuspPolynomialEvaluation]

/-- Evaluation at `(0,1)` descends to the source hypersurface coordinate
ring. -/
def sourceCuspRetraction : SourceCoordinateRing →+* ResidueField :=
  Ideal.Quotient.lift sourceIdeal cuspPolynomialEvaluation (by
    intro P hP
    have hle : sourceIdeal ≤ RingHom.ker cuspPolynomialEvaluation := by
      rw [sourceIdeal, Ideal.span_singleton_le_iff_mem, RingHom.mem_ker]
      exact cuspPolynomialEvaluation_sourceEquation
    exact RingHom.mem_ker.mp (hle hP))

@[simp]
theorem sourceCuspRetraction_sourceMk
    (P : MvPolynomial (Fin 2) ResidueField) :
    sourceCuspRetraction (sourceMk P) = cuspPolynomialEvaluation P := by
  simp [sourceCuspRetraction, sourceMk]

@[simp]
theorem sourceCuspRetraction_sourceX : sourceCuspRetraction sourceX = 0 := by
  simp [sourceX]

@[simp]
theorem sourceCuspRetraction_sourceY : sourceCuspRetraction sourceY = 1 := by
  simp [sourceY]

@[simp]
theorem sourceCuspRetraction_sourceDenominator :
    sourceCuspRetraction sourceDenominator = -1 := by
  simp [sourceDenominator]

/-- The kernel of source-hypersurface evaluation is generated by the two
coordinate differences `x` and `y-1`. -/
theorem sourceCuspRetraction_ker :
    RingHom.ker sourceCuspRetraction =
      Ideal.span ({sourceX, sourceY - 1} : Set SourceCoordinateRing) := by
  let J : Ideal SourceCoordinateRing :=
    Ideal.span ({sourceX, sourceY - 1} : Set SourceCoordinateRing)
  change RingHom.ker sourceCuspRetraction = J
  apply le_antisymm
  · intro a ha
    obtain ⟨P, rfl⟩ := Ideal.Quotient.mk_surjective a
    rw [RingHom.mem_ker, sourceCuspRetraction_sourceMk] at ha
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    let quotientMap : SourceCoordinateRing →+* SourceCoordinateRing ⧸ J :=
      Ideal.Quotient.mk J
    have hhom : quotientMap.comp sourceMk =
        (algebraMap ResidueField (SourceCoordinateRing ⧸ J)).comp
          cuspPolynomialEvaluation := by
      apply MvPolynomial.ringHom_ext
      · intro c
        simp [quotientMap, sourceMk, cuspPolynomialEvaluation]
      · intro i
        fin_cases i
        · have hx : sourceX ∈ J := Ideal.subset_span (by simp [J])
          change quotientMap sourceX = _
          rw [Ideal.Quotient.eq_zero_iff_mem.mpr hx]
          simp [cuspPolynomialEvaluation]
        · have hy : sourceY - 1 ∈ J := Ideal.subset_span (by simp [J])
          have hyzero : quotientMap (sourceY - 1) = 0 :=
            Ideal.Quotient.eq_zero_iff_mem.mpr hy
          rw [map_sub, map_one] at hyzero
          have hyone : quotientMap sourceY = 1 := sub_eq_zero.mp hyzero
          change quotientMap sourceY = _
          simpa [cuspPolynomialEvaluation] using hyone
    have hP := RingHom.congr_fun hhom P
    change quotientMap (sourceMk P) = _ at hP
    change quotientMap (sourceMk P) = 0
    rw [hP, ha, map_zero]
  · rw [Ideal.span_le]
    intro a ha
    rcases Set.mem_insert_iff.mp ha with rfl | ha
    · rw [RingHom.mem_ker]
      exact sourceCuspRetraction_sourceX
    · rw [Set.mem_singleton_iff] at ha
      subst a
      rw [RingHom.mem_ker, map_sub, map_one,
        sourceCuspRetraction_sourceY, sub_self]

/-- Evaluation extends across the open chart because its inverted denominator
has value `-1`. -/
def chartCuspRetraction : SourceChart →+* ResidueField :=
  IsLocalization.Away.lift sourceDenominator (by
    rw [sourceCuspRetraction_sourceDenominator]
    exact isUnit_neg.mpr isUnit_one)

@[simp]
theorem chartCuspRetraction_sourceChartMap (a : SourceCoordinateRing) :
    chartCuspRetraction (sourceChartMap a) = sourceCuspRetraction a := by
  rw [chartCuspRetraction, sourceChartMap, IsLocalization.Away.lift_eq]

@[simp]
theorem chartCuspRetraction_t : chartCuspRetraction t = 0 := by
  simp [t]

@[simp]
theorem chartCuspRetraction_y : chartCuspRetraction y = 1 := by
  simp [y]

@[simp]
theorem chartCuspRetraction_cuspParameter :
    chartCuspRetraction cuspParameter = 0 := by
  simp [cuspParameter]

/-- The chart evaluation is onto the residue field. -/
theorem chartCuspRetraction_surjective :
    Function.Surjective chartCuspRetraction := by
  intro a
  refine ⟨sourceChartMap (sourceMk (C a)), ?_⟩
  simp

/-- The chart cusp ideal is generated by the two coordinate differences.
Localizing away from the quotient-map denominator creates no additional
kernel because that denominator has cusp value `-1`. -/
theorem chartCuspRetraction_ker :
    RingHom.ker chartCuspRetraction =
      Ideal.span ({t, y - 1} : Set SourceChart) := by
  let J : Ideal SourceChart :=
    Ideal.span ({t, y - 1} : Set SourceChart)
  change RingHom.ker chartCuspRetraction = J
  apply le_antisymm
  · intro z hz
    obtain ⟨n, a, hza⟩ :=
      IsLocalization.Away.surj sourceDenominator z
    have haKer : a ∈ RingHom.ker sourceCuspRetraction := by
      rw [RingHom.mem_ker]
      have h := congrArg chartCuspRetraction hza
      rw [map_mul, map_pow, chartCuspRetraction_sourceChartMap,
        chartCuspRetraction_sourceChartMap, RingHom.mem_ker.mp hz,
        zero_mul] at h
      exact h.symm
    have haSource :
        a ∈ Ideal.span
          ({sourceX, sourceY - 1} : Set SourceCoordinateRing) := by
      rw [← sourceCuspRetraction_ker]
      exact haKer
    have hmap :
        Ideal.map sourceChartMap
            (Ideal.span
              ({sourceX, sourceY - 1} : Set SourceCoordinateRing)) ≤ J := by
      rw [Ideal.map_span, Ideal.span_le]
      rintro b ⟨a, ha, rfl⟩
      rcases Set.mem_insert_iff.mp ha with rfl | ha
      · exact Ideal.subset_span (by simp [J, t])
      · rw [Set.mem_singleton_iff] at ha
        subst a
        exact Ideal.subset_span (by simp [J, y])
    have haChart : sourceChartMap a ∈ J :=
      hmap (Ideal.mem_map_of_mem sourceChartMap haSource)
    have hprod :
        z * sourceChartMap sourceDenominator ^ n ∈ J := by
      rw [hza]
      exact haChart
    exact (J.mul_unit_mem_iff_mem
      ((IsLocalization.Away.algebraMap_isUnit sourceDenominator).pow n)).mp
        hprod
  · rw [Ideal.span_le]
    intro a ha
    rcases Set.mem_insert_iff.mp ha with rfl | ha
    · rw [RingHom.mem_ker]
      exact chartCuspRetraction_t
    · rw [Set.mem_singleton_iff] at ha
      subst a
      rw [RingHom.mem_ker, map_sub, map_one,
        chartCuspRetraction_y, sub_self]

/-- The actual cusp prime on the localized hyperelliptic chart. -/
def cuspPrime : Ideal SourceChart := RingHom.ker chartCuspRetraction

theorem cuspPrime_eq_span_coordinates :
    cuspPrime = Ideal.span ({t, y - 1} : Set SourceChart) :=
  chartCuspRetraction_ker

instance cuspPrime_isPrime : cuspPrime.IsPrime := RingHom.ker_isPrime _

theorem cuspPrime_isMaximal : cuspPrime.IsMaximal :=
  RingHom.ker_isMaximal_of_surjective chartCuspRetraction
    chartCuspRetraction_surjective

/-- The polynomial remaining after dividing `sourcePolynomial(t)-1` by `t`. -/
def sourcePolynomialTail (t : SourceChart) : SourceChart :=
  t ^ 7 - 4 * t ^ 6 - 6 * t ^ 5 - 4 * t ^ 4 - 9 * t ^ 3 +
    4 * t ^ 2 - 6 * t + 4

/-- The source equation factored at the cusp branch `y=1`. -/
theorem ordinate_factorization :
    (y - 1) * (y + 1) = t * sourcePolynomialTail t := by
  rw [show (y - 1) * (y + 1) = y ^ 2 - 1 by ring,
    source_relation_on_chart]
  simp only [sourcePolynomial, sourcePolynomialTail]
  ring

/-- The local ring of the actual hyperelliptic cusp. -/
abbrev CuspLocalRing := Localization.AtPrime cuspPrime

/-- The geometric q-parameter `q=-t` in the cusp local ring. -/
def qParameter : CuspLocalRing :=
  algebraMap SourceChart CuspLocalRing cuspParameter

/-- The ordinate difference `y-1` in the cusp local ring. -/
def ordinateDifference : CuspLocalRing :=
  algebraMap SourceChart CuspLocalRing (y - 1)

/-- The other local branch factor `y+1` is a unit at the selected cusp. -/
theorem ordinatePlusOne_isUnit :
    IsUnit (algebraMap SourceChart CuspLocalRing (y + 1)) := by
  rw [IsLocalization.AtPrime.isUnit_to_map_iff]
  change y + 1 ∉ cuspPrime
  rw [cuspPrime, RingHom.mem_ker]
  simp

/-- In the actual cusp local ring, the ordinate difference is divisible by
the q-parameter. -/
theorem qParameter_dvd_ordinateDifference :
    qParameter ∣ ordinateDifference := by
  have hrelation := congrArg (algebraMap SourceChart CuspLocalRing)
    ordinate_factorization
  have ht : algebraMap SourceChart CuspLocalRing t = -qParameter := by
    simp [qParameter, cuspParameter]
  have hdiv : qParameter ∣
      ordinateDifference *
        algebraMap SourceChart CuspLocalRing (y + 1) := by
    rw [map_mul, map_sub, map_one, map_add, map_one] at hrelation
    refine ⟨-algebraMap SourceChart CuspLocalRing
      (sourcePolynomialTail t), ?_⟩
    calc
      ordinateDifference *
          algebraMap SourceChart CuspLocalRing (y + 1) =
          algebraMap SourceChart CuspLocalRing t *
            algebraMap SourceChart CuspLocalRing (sourcePolynomialTail t) :=
        hrelation
      _ = qParameter *
          (-algebraMap SourceChart CuspLocalRing
            (sourcePolynomialTail t)) := by
        rw [ht]
        ring
  exact (ordinatePlusOne_isUnit.dvd_mul_right).mp hdiv

/-- The maximal ideal of the genuine hyperelliptic cusp local ring is
generated by the geometric parameter `q=-t`.  The second chart generator
`y-1` is eliminated using the hypersurface equation and the unit `y+1`. -/
theorem maximalIdeal_eq_span_qParameter :
    IsLocalRing.maximalIdeal CuspLocalRing =
      Ideal.span ({qParameter} : Set CuspLocalRing) := by
  let locMap : SourceChart →+* CuspLocalRing :=
    algebraMap SourceChart CuspLocalRing
  calc
    IsLocalRing.maximalIdeal CuspLocalRing =
        Ideal.map locMap cuspPrime :=
      Localization.AtPrime.map_eq_maximalIdeal.symm
    _ = Ideal.map locMap
        (Ideal.span ({t, y - 1} : Set SourceChart)) := by
      rw [cuspPrime_eq_span_coordinates]
    _ = Ideal.span
        ({locMap t, locMap (y - 1)} : Set CuspLocalRing) := by
      rw [Ideal.map_span]
      congr 1
      ext a
      simp
    _ = Ideal.span ({qParameter} : Set CuspLocalRing) := by
      apply le_antisymm
      · rw [Ideal.span_le]
        intro a ha
        rcases Set.mem_insert_iff.mp ha with rfl | ha
        · rw [Ideal.mem_span_singleton]
          simpa [locMap, qParameter, cuspParameter] using
            (dvd_neg.mpr (dvd_refl qParameter))
        · rw [Set.mem_singleton_iff] at ha
          subst a
          rw [Ideal.mem_span_singleton]
          simpa [locMap, ordinateDifference] using
            qParameter_dvd_ordinateDifference
      · rw [Ideal.span_le]
        intro a ha
        rw [Set.mem_singleton_iff] at ha
        subst a
        have ht : locMap t ∈
            Ideal.span
              ({locMap t, locMap (y - 1)} : Set CuspLocalRing) :=
          Ideal.subset_span (by simp)
        have hneg := (Ideal.span
          ({locMap t, locMap (y - 1)} : Set CuspLocalRing)).neg_mem ht
        simpa [locMap, qParameter, cuspParameter] using hneg

theorem qParameter_mem_maximalIdeal :
    qParameter ∈ IsLocalRing.maximalIdeal CuspLocalRing := by
  rw [maximalIdeal_eq_span_qParameter]
  exact Ideal.mem_span_singleton_self qParameter

/-- First-order coordinates of the cusp in the dual numbers.  The ordinate
has tangent `2*epsilon` because differentiating `y^2=P(t)` at `(0,1)` gives
`2 dy = 4 dt`. -/
def cuspTangentCoordinates : Fin 2 → DualNumber ResidueField :=
  Fin.cases DualNumber.eps
    (Fin.cases (1 + 2 * DualNumber.eps) Fin.elim0)

@[simp]
theorem cuspTangentCoordinates_zero :
    cuspTangentCoordinates 0 = DualNumber.eps := rfl

@[simp]
theorem cuspTangentCoordinates_one :
    cuspTangentCoordinates 1 = 1 + 2 * DualNumber.eps := rfl

/-- Evaluation of ambient polynomials on the nonconstant dual-number cusp
tangent. -/
def cuspTangentPolynomialEvaluation :
    MvPolynomial (Fin 2) ResidueField →+* DualNumber ResidueField :=
  MvPolynomial.eval₂Hom
    (algebraMap ResidueField (DualNumber ResidueField))
    cuspTangentCoordinates

@[simp]
theorem cuspTangentPolynomialEvaluation_X_zero :
    cuspTangentPolynomialEvaluation (X 0) = DualNumber.eps := by
  simp [cuspTangentPolynomialEvaluation]

@[simp]
theorem cuspTangentPolynomialEvaluation_X_one :
    cuspTangentPolynomialEvaluation (X 1) =
      1 + 2 * DualNumber.eps := by
  simp [cuspTangentPolynomialEvaluation]

@[simp]
theorem cuspTangentPolynomialEvaluation_C (a : ResidueField) :
    cuspTangentPolynomialEvaluation (C a) =
      algebraMap ResidueField (DualNumber ResidueField) a := by
  simp [cuspTangentPolynomialEvaluation]

/-- The explicit dual-number tangent lies on the source hypersurface. -/
theorem cuspTangentPolynomialEvaluation_sourceEquation :
    cuspTangentPolynomialEvaluation sourceEquation = 0 := by
  simp only [sourceEquation, sourcePolynomial, map_sub, map_pow, map_add,
    map_mul, map_one, map_ofNat,
    cuspTangentPolynomialEvaluation_X_zero,
    cuspTangentPolynomialEvaluation_X_one]
  have heps :
      (DualNumber.eps : DualNumber ResidueField) ^ 2 = 0 :=
    DualNumber.eps_pow_two
  linear_combination
    (-(DualNumber.eps : DualNumber ResidueField) ^ 6 +
      4 * DualNumber.eps ^ 5 + 6 * DualNumber.eps ^ 4 +
      4 * DualNumber.eps ^ 3 + 9 * DualNumber.eps ^ 2 -
      4 * DualNumber.eps + 10) * heps

/-- The nonconstant cusp tangent descends through the source equation. -/
def sourceCuspTangent :
    SourceCoordinateRing →+* DualNumber ResidueField :=
  Ideal.Quotient.lift sourceIdeal cuspTangentPolynomialEvaluation (by
    intro P hP
    have hle : sourceIdeal ≤
        RingHom.ker cuspTangentPolynomialEvaluation := by
      rw [sourceIdeal, Ideal.span_singleton_le_iff_mem, RingHom.mem_ker]
      exact cuspTangentPolynomialEvaluation_sourceEquation
    exact RingHom.mem_ker.mp (hle hP))

@[simp]
theorem sourceCuspTangent_sourceMk
    (P : MvPolynomial (Fin 2) ResidueField) :
    sourceCuspTangent (sourceMk P) =
      cuspTangentPolynomialEvaluation P := by
  simp [sourceCuspTangent, sourceMk]

@[simp]
theorem sourceCuspTangent_sourceX :
    sourceCuspTangent sourceX = DualNumber.eps := by
  simp [sourceX]

@[simp]
theorem sourceCuspTangent_sourceY :
    sourceCuspTangent sourceY = 1 + 2 * DualNumber.eps := by
  simp [sourceY]

@[simp]
theorem sourceCuspTangent_sourceDenominator :
    sourceCuspTangent sourceDenominator = DualNumber.eps - 1 := by
  simp [sourceDenominator, DualNumber.eps_pow_two]

/-- Projection from the dual numbers to their constant term. -/
def dualNumberResidue : DualNumber ResidueField →+* ResidueField :=
  (TrivSqZeroExt.fstHom ResidueField ResidueField ResidueField).toRingHom

/-- The constant term of the source tangent is the cusp retraction. -/
theorem dualNumberResidue_comp_sourceCuspTangent :
    dualNumberResidue.comp sourceCuspTangent = sourceCuspRetraction := by
  apply Ideal.Quotient.ringHom_ext
  apply MvPolynomial.ringHom_ext
  · intro a
    simp [dualNumberResidue, sourceCuspTangent,
      cuspTangentPolynomialEvaluation, sourceCuspRetraction,
      cuspPolynomialEvaluation]
  · intro i
    fin_cases i <;>
      simp [dualNumberResidue, sourceCuspTangent,
        cuspTangentPolynomialEvaluation, sourceCuspRetraction,
        cuspPolynomialEvaluation]

/-- The inverted chart denominator remains a unit on the dual-number
tangent because its constant term is `-1`. -/
theorem sourceCuspTangent_sourceDenominator_isUnit :
    IsUnit (sourceCuspTangent sourceDenominator) := by
  rw [sourceCuspTangent_sourceDenominator,
    TrivSqZeroExt.isUnit_iff_isUnit_fst]
  simp

/-- The dual-number cusp tangent on the localized source chart. -/
def chartCuspTangent : SourceChart →+* DualNumber ResidueField :=
  IsLocalization.Away.lift sourceDenominator
    sourceCuspTangent_sourceDenominator_isUnit

@[simp]
theorem chartCuspTangent_sourceChartMap (a : SourceCoordinateRing) :
    chartCuspTangent (sourceChartMap a) = sourceCuspTangent a := by
  rw [chartCuspTangent, sourceChartMap, IsLocalization.Away.lift_eq]

@[simp]
theorem chartCuspTangent_t :
    chartCuspTangent t = DualNumber.eps := by
  simp [t]

@[simp]
theorem chartCuspTangent_y :
    chartCuspTangent y = 1 + 2 * DualNumber.eps := by
  simp [y]

@[simp]
theorem chartCuspTangent_cuspParameter :
    chartCuspTangent cuspParameter = -DualNumber.eps := by
  simp [cuspParameter]

/-- The constant term of the chart tangent remains the cusp retraction. -/
theorem dualNumberResidue_comp_chartCuspTangent :
    dualNumberResidue.comp chartCuspTangent = chartCuspRetraction := by
  apply IsLocalization.ringHom_ext (Submonoid.powers sourceDenominator)
  simpa [chartCuspTangent, chartCuspRetraction, RingHom.comp_assoc] using
    dualNumberResidue_comp_sourceCuspTangent

/-- Every chart function nonvanishing at the cusp maps to a unit on the
dual-number tangent. -/
theorem chartCuspTangent_isUnit_of_not_mem_cuspPrime
    {a : SourceChart} (ha : a ∉ cuspPrime) :
    IsUnit (chartCuspTangent a) := by
  rw [TrivSqZeroExt.isUnit_iff_isUnit_fst]
  have hne : chartCuspRetraction a ≠ 0 := by
    intro hzero
    apply ha
    rw [cuspPrime, RingHom.mem_ker]
    exact hzero
  have hconstant :=
    RingHom.congr_fun dualNumberResidue_comp_chartCuspTangent a
  change (chartCuspTangent a).fst = chartCuspRetraction a at hconstant
  rw [hconstant]
  exact isUnit_iff_ne_zero.mpr hne

/-- The dual-number tangent extends to the actual cusp local ring. -/
def cuspLocalTangent : CuspLocalRing →+* DualNumber ResidueField :=
  IsLocalization.lift (S := CuspLocalRing)
    (fun a : cuspPrime.primeCompl ↦
      chartCuspTangent_isUnit_of_not_mem_cuspPrime a.property)

@[simp]
theorem cuspLocalTangent_algebraMap (a : SourceChart) :
    cuspLocalTangent (algebraMap SourceChart CuspLocalRing a) =
      chartCuspTangent a := by
  rw [cuspLocalTangent, IsLocalization.lift_eq]

@[simp]
theorem cuspLocalTangent_qParameter :
    cuspLocalTangent qParameter = -DualNumber.eps := by
  simp [qParameter]

theorem cuspLocalTangent_qParameter_ne_zero :
    cuspLocalTangent qParameter ≠ 0 := by
  rw [cuspLocalTangent_qParameter]
  intro hzero
  have hsnd := congrArg TrivSqZeroExt.snd hzero
  simpa using hsnd

/-- The geometric q-parameter has a nonzero cotangent class.  This proof does
not assume the source coordinate ring is a domain: the explicit tangent sends
`q` to `-epsilon`, while every square multiple of `q` maps to zero. -/
theorem qParameter_not_mem_maximalIdeal_sq :
    qParameter ∉ IsLocalRing.maximalIdeal CuspLocalRing ^ 2 := by
  intro hsq
  rw [maximalIdeal_eq_span_qParameter,
    Ideal.span_singleton_pow] at hsq
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton.mp hsq
  apply cuspLocalTangent_qParameter_ne_zero
  calc
    cuspLocalTangent qParameter =
        cuspLocalTangent (qParameter ^ 2 * c) := congrArg cuspLocalTangent hc
    _ = 0 := by
      simp [DualNumber.eps_pow_two]

/-- The explicit tangent also proves that the geometric parameter itself is
nonzero, without any global irreducibility input for the hyperelliptic
equation. -/
theorem qParameter_ne_zero : qParameter ≠ 0 := by
  intro hzero
  apply cuspLocalTangent_qParameter_ne_zero
  rw [hzero, map_zero]

/-- The actual cusp local ring is Noetherian: it is obtained from a quotient
of a finite-variable polynomial ring by two successive localizations. -/
instance cuspLocalRing_isNoetherianRing :
    IsNoetherianRing CuspLocalRing := inferInstance

/-- The nonzero maximal-ideal generator rules out the field case. -/
theorem cuspLocalRing_not_isField : ¬ IsField CuspLocalRing := by
  rw [IsLocalRing.isField_iff_maximalIdeal_eq]
  intro hbot
  have hmem := qParameter_mem_maximalIdeal
  rw [hbot] at hmem
  exact qParameter_ne_zero (by simpa using hmem)

/-- Once the represented source chart is known to be a domain, the checked
Noetherian local algebra and its principal nonzero maximal ideal give the DVR
instance.  `XZeroThirtyFiveSourceDomainAtEleven` supplies this domain input in
the integrated dependency graph. -/
instance cuspLocalRing_isDiscreteValuationRing [IsDomain SourceChart] :
    IsDiscreteValuationRing CuspLocalRing := by
  apply ((IsDiscreteValuationRing.TFAE CuspLocalRing
    cuspLocalRing_not_isField).out 4 0).mp
  rw [maximalIdeal_eq_span_qParameter]
  infer_instance

/-- The geometric parameter is the resulting uniformizer. -/
theorem qParameter_irreducible [IsDomain SourceChart] :
    Irreducible qParameter :=
  IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal
    qParameter qParameter_ne_zero maximalIdeal_eq_span_qParameter

@[simp]
theorem sourceCuspRetraction_algebraMap (c : ResidueField) :
    sourceCuspRetraction
        (algebraMap ResidueField SourceCoordinateRing c) = c := by
  simpa [sourceMk] using sourceCuspRetraction_sourceMk (C c)

@[simp]
theorem chartCuspRetraction_algebraMap (c : ResidueField) :
    chartCuspRetraction (algebraMap ResidueField SourceChart c) = c := by
  rw [IsScalarTower.algebraMap_apply ResidueField SourceCoordinateRing
    SourceChart]
  simp

/-- Evaluation at the cusp extends from the chart to its local ring. -/
def cuspLocalRetraction : CuspLocalRing →+* ResidueField :=
  IsLocalization.lift (S := CuspLocalRing) (g := chartCuspRetraction)
    (fun a : cuspPrime.primeCompl ↦ by
      apply isUnit_iff_ne_zero.mpr
      intro ha
      exact a.property (by
        change chartCuspRetraction a = 0
        exact ha))

@[simp]
theorem cuspLocalRetraction_algebraMap_sourceChart (a : SourceChart) :
    cuspLocalRetraction (algebraMap SourceChart CuspLocalRing a) =
      chartCuspRetraction a := by
  rw [cuspLocalRetraction, IsLocalization.lift_eq]

@[simp]
theorem cuspLocalRetraction_algebraMap (c : ResidueField) :
    cuspLocalRetraction
        (algebraMap ResidueField CuspLocalRing c) = c := by
  rw [IsScalarTower.algebraMap_apply ResidueField SourceChart CuspLocalRing]
  simp

theorem cuspLocalRetraction_surjective :
    Function.Surjective cuspLocalRetraction := by
  intro c
  exact ⟨algebraMap ResidueField CuspLocalRing c, by simp⟩

theorem cuspLocalRetraction_comp_algebraMap :
    cuspLocalRetraction.comp
        (algebraMap ResidueField CuspLocalRing) =
      RingHom.id ResidueField := by
  apply RingHom.ext
  intro c
  exact cuspLocalRetraction_algebraMap c

/-- The completed q-coordinate of the actual level-35 hyperelliptic cusp. -/
noncomputable def qCoordinate [IsDomain SourceChart] :
    LocalCompletion.Ring CuspLocalRing ≃+* PowerSeries ResidueField := by
  letI : IsLocalHom cuspLocalRetraction :=
    cuspLocalRetraction_surjective.isLocalHom
  exact CompleteDVRStalk.stalkCompletionRingEquivOfRetraction
    CuspLocalRing ResidueField cuspLocalRetraction
    cuspLocalRetraction_comp_algebraMap qParameter qParameter_irreducible

/-- The geometric parameter is sent to the power-series variable. -/
@[simp]
theorem qCoordinate_qParameter [IsDomain SourceChart] :
    qCoordinate
        (algebraMap CuspLocalRing (LocalCompletion.Ring CuspLocalRing)
          qParameter) =
      (PowerSeries.X : PowerSeries ResidueField) := by
  letI : IsLocalHom cuspLocalRetraction :=
    cuspLocalRetraction_surjective.isLocalHom
  change CompleteDVRStalk.stalkCompletionRingEquiv
      CuspLocalRing ResidueField qParameter qParameter_irreducible
      (CompleteDVRStalk.coefficientField_surjective_of_algebraMap_retraction
        cuspLocalRetraction cuspLocalRetraction_comp_algebraMap)
      (algebraMap CuspLocalRing (LocalCompletion.Ring CuspLocalRing)
        qParameter) = _
  exact CompleteDVRStalk.stalkCompletionRingEquiv_uniformizer
    CuspLocalRing ResidueField qParameter qParameter_irreducible
    (CompleteDVRStalk.coefficientField_surjective_of_algebraMap_retraction
      cuspLocalRetraction cuspLocalRetraction_comp_algebraMap)

/-- Residue-field constants become constant series in the actual cusp
coordinate. -/
@[simp]
theorem qCoordinate_algebraMap [IsDomain SourceChart]
    (c : ResidueField) :
    qCoordinate
        (algebraMap CuspLocalRing (LocalCompletion.Ring CuspLocalRing)
          (algebraMap ResidueField CuspLocalRing c)) =
      PowerSeries.C c := by
  letI : IsLocalHom cuspLocalRetraction :=
    cuspLocalRetraction_surjective.isLocalHom
  apply qCoordinate.symm.injective
  simp [qCoordinate, CompleteDVRStalk.stalkCompletionRingEquivOfRetraction,
    CompleteDVRStalk.stalkCompletionRingEquiv,
    CompleteDVRCoordinate.ringEquiv_symm_apply,
    IsScalarTower.algebraMap_apply ResidueField CuspLocalRing
      (LocalCompletion.Ring CuspLocalRing)]
  rfl

/-- The explicit quotient-coordinate map after localizing at the actual
source cusp. -/
def localizedQuotientCoordinateMap :
    TargetCoordinateRing →+* CuspLocalRing :=
  (algebraMap SourceChart CuspLocalRing).comp quotientCoordinateMap

/-- Pullback of the target parameter `W-1` to the actual source cusp local
ring. -/
def localizedQuotientParameter : CuspLocalRing :=
  localizedQuotientCoordinateMap (targetW - 1)

/-- The denominator-cleared quotient formula survives in the actual local
ring. -/
theorem localizedQuotientParameter_cleared :
    localizedQuotientParameter * (1 + qParameter - qParameter ^ 2) =
      algebraMap ResidueField CuspLocalRing (-7) * qParameter := by
  have h := congrArg (algebraMap SourceChart CuspLocalRing)
    quotientCoordinateMap_targetW_sub_one_cleared
  simpa [localizedQuotientParameter, localizedQuotientCoordinateMap,
    qParameter] using h

/-- The actual localized quotient parameter has the complete checked series
`-7 X / (1 + X - X^2)`, not merely a postulated first coefficient. -/
theorem qExpansion_localizedQuotientParameter [IsDomain SourceChart] :
    qCoordinate
        (algebraMap CuspLocalRing (LocalCompletion.Ring CuspLocalRing)
          localizedQuotientParameter) =
      quotientParameterExpansion := by
  have hseries := congrArg
    (fun z ↦ qCoordinate
      (algebraMap CuspLocalRing (LocalCompletion.Ring CuspLocalRing) z))
    localizedQuotientParameter_cleared
  have hseriesCleared :
      qCoordinate
          (algebraMap CuspLocalRing (LocalCompletion.Ring CuspLocalRing)
            localizedQuotientParameter) * denominator =
        PowerSeries.C (-7 : ResidueField) * PowerSeries.X := by
    simpa only [map_mul, map_add, map_one, map_sub, map_pow,
      qCoordinate_qParameter, qCoordinate_algebraMap, denominator] using
      hseries
  have hquotientCleared :
      quotientParameterExpansion (K := ResidueField) * denominator =
        PowerSeries.C (-7 : ResidueField) * PowerSeries.X := by
    rw [quotientParameterExpansion_eq, Algebra.smul_def]
    have hinv : (denominator (K := ResidueField))⁻¹ * denominator = 1 := by
      rw [mul_comm]
      exact PowerSeries.mul_inv_cancel denominator (by simp)
    calc
      PowerSeries.C (-7 : ResidueField) *
            (PowerSeries.X * denominator⁻¹) * denominator =
          PowerSeries.C (-7 : ResidueField) * PowerSeries.X *
            (denominator⁻¹ * denominator) := by ring
      _ = PowerSeries.C (-7 : ResidueField) * PowerSeries.X := by
        rw [hinv]
        exact _root_.mul_one _
  apply mul_right_cancel₀ (denominator_ne_zero (K := ResidueField))
  exact hseriesCleared.trans hquotientCleared.symm

/-- Consequently the localized quotient has the explicit nonzero tangent
coefficient `-7 = 4` in characteristic eleven. -/
theorem coeff_one_qExpansion_localizedQuotientParameter_ne_zero
    [IsDomain SourceChart] :
    PowerSeries.coeff 1
        (qCoordinate
          (algebraMap CuspLocalRing (LocalCompletion.Ring CuspLocalRing)
            localizedQuotientParameter)) ≠ 0 := by
  rw [qExpansion_localizedQuotientParameter,
    coeff_one_quotientParameterExpansion]
  decide

end MazurTorsion.ModularCurve.XZeroThirtyFiveLocalQuotientAtEleven
