/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, Chris Birkbeck, AINTLIB ModularCurves contributors,
  OpenAI Codex
-/

import MazurTorsion.ModularCurve.XZeroGammaOneTateProjectiveFamily
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# The three-coordinate cover of the projective Tate family

The images of `X`, `Y`, and `Z` in the homogeneous coordinate quotient have
degree one and generate its irrelevant ideal.  Consequently their three
standard basic opens cover the projective Weierstrass model.

This is the clean coordinate-cover slice adapted from AINTLIB's
`EllipticCurve/WeierstrassModel.lean` at commit
`1c1c74664e40071c2c2165bc55ca2616a67ccd6b`, exact source blob
`0cea4fbbcd8f0976b8cb0949755ecacec6e58b26` (Apache-2.0).  It does not
construct chart coordinate rings or a field-points dictionary.
-/

noncomputable section

open AlgebraicGeometry MvPolynomial
open HomogeneousIdeal

namespace MazurTorsion.ModularCurve.XZeroModuli.GammaOneTate
namespace ProjectiveFamily

universe u

attribute [local instance] MvPolynomial.gradedAlgebra

variable {A : Type u} [CommRing A]

/-- The image of each projective coordinate has degree one in the quotient
grading. -/
theorem coordinateClass_mem_degreeOne (W : WeierstrassCurve A) (i : Fin 3) :
    (quotientGradingHom (ideal W)) (MvPolynomial.X i) ∈
      quotientGrading (ideal W) 1 :=
  mk_mem_quotientGrading (ideal W)
    ((MvPolynomial.mem_homogeneousSubmodule 1 (MvPolynomial.X i)).mpr
      (MvPolynomial.isHomogeneous_X A i))

/-- Every positive-degree polynomial lies in the ideal generated by the three
coordinate variables. -/
theorem polynomialIrrelevant_le_coordinateIdeal :
    (HomogeneousIdeal.irrelevant
        (MvPolynomial.homogeneousSubmodule (Fin 3) A)).toIdeal ≤
      MvPolynomial.idealOfVars (Fin 3) A := by
  intro p hp
  have hp0 : MvPolynomial.coeff 0 p = 0 := by
    have hproj :
        GradedRing.proj (MvPolynomial.homogeneousSubmodule (Fin 3) A) 0 p = 0 :=
      hp
    rw [GradedRing.proj_apply] at hproj
    have hcomponent :
        (DirectSum.decompose (MvPolynomial.homogeneousSubmodule (Fin 3) A) p 0 :
            MvPolynomial (Fin 3) A) = MvPolynomial.homogeneousComponent 0 p :=
      MvPolynomial.decomposition.decompose'_apply p 0
    rw [hcomponent, MvPolynomial.homogeneousComponent_zero] at hproj
    exact MvPolynomial.C_injective _ _
      (hproj.trans (MvPolynomial.C_0).symm)
  rw [show MvPolynomial.idealOfVars (Fin 3) A =
      MvPolynomial.idealOfVars (Fin 3) A ^ 1 by rw [pow_one],
    MvPolynomial.mem_pow_idealOfVars_iff']
  intro x hx
  have hx0 : x = 0 := by
    have : Finsupp.degree x = 0 := by omega
    exact (Finsupp.degree_eq_zero_iff x).mp this
  rwa [hx0]

/-- The irrelevant ideal of the quotient grading is contained in the ideal
spanned by the three coordinate classes. -/
theorem quotientIrrelevant_le_coordinateSpan (W : WeierstrassCurve A) :
    (HomogeneousIdeal.irrelevant (quotientGrading (ideal W))).toIdeal ≤
      Ideal.span (Set.range fun i : Fin 3 =>
        Ideal.Quotient.mk (ideal W).toIdeal (MvPolynomial.X i)) := by
  intro z hz
  have hmap : z ∈ Ideal.map (quotientGradingHom (ideal W)).toRingHom
      (HomogeneousIdeal.irrelevant
        (MvPolynomial.homogeneousSubmodule (Fin 3) A)).toIdeal :=
    quotientGradingHom_irrelevant_le (ideal W) hz
  have hle : Ideal.map (quotientGradingHom (ideal W)).toRingHom
      (HomogeneousIdeal.irrelevant
        (MvPolynomial.homogeneousSubmodule (Fin 3) A)).toIdeal ≤
      Ideal.map (quotientGradingHom (ideal W)).toRingHom
        (MvPolynomial.idealOfVars (Fin 3) A) :=
    Ideal.map_mono polynomialIrrelevant_le_coordinateIdeal
  have himage : Ideal.map (quotientGradingHom (ideal W)).toRingHom
      (MvPolynomial.idealOfVars (Fin 3) A) =
      Ideal.span (Set.range fun i : Fin 3 =>
        Ideal.Quotient.mk (ideal W).toIdeal (MvPolynomial.X i)) := by
    rw [MvPolynomial.idealOfVars, Ideal.map_span, ← Set.range_comp]
    rfl
  exact himage ▸ hle hmap

/-- The three coordinate classes generate exactly the irrelevant ideal of the
quotient grading. -/
theorem coordinateSpan_eq_quotientIrrelevant (W : WeierstrassCurve A) :
    Ideal.span (Set.range fun i : Fin 3 =>
        Ideal.Quotient.mk (ideal W).toIdeal (MvPolynomial.X i)) =
      (HomogeneousIdeal.irrelevant (quotientGrading (ideal W))).toIdeal := by
  apply le_antisymm
  · rw [Ideal.span_le, Set.range_subset_iff]
    exact coordinateClass_mem_irrelevant W
  · exact quotientIrrelevant_le_coordinateSpan W

/-- The three standard coordinate basic opens cover the projective
Weierstrass model. -/
theorem iSup_coordinateBasicOpen_eq_top (W : WeierstrassCurve A) :
    ⨆ i : Fin 3, Proj.basicOpen (quotientGrading (ideal W))
      (Ideal.Quotient.mk (ideal W).toIdeal (MvPolynomial.X i)) = ⊤ := by
  exact Proj.iSup_basicOpen_eq_top (quotientGrading (ideal W)) _
    (quotientIrrelevant_le_coordinateSpan W)

end ProjectiveFamily
end MazurTorsion.ModularCurve.XZeroModuli.GammaOneTate
