/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.ModularCurve.XZeroModuli

/-!
# The squarefree level structure at level 35

This file specializes the checked split rational source data for `X₀(N)` to
level 35.  Every rational cyclic subgroup of order 35 has canonical subgroups
of orders 5 and 7.  These give the restrictions of the two divisor-level
degeneracy maps, commute with admissible changes of Weierstrass presentation,
and together recover the original subgroup.

This is a prerequisite for the order-35 modular quotient route, but it does
not identify the fixed model `OrderThirtyFive.optimalQuotientModel` with
`X₀(35)/w₅`.  That identification still requires a represented integral
`X₀(35)`, the quotient isogeny attached to the order-five subgroup, the
Atkin--Lehner involution, and the resulting quotient-map comparison.  The
present split-point type is intentionally not claimed to be closed under
`w₅`, whose dual order-five subgroup need not be pointwise rational.
-/

open scoped WeierstrassCurve.Affine

namespace MazurTorsion.ModularCurve.XZeroThirtyFive

open XZeroModuli

universe u

variable {K : Type u} [Field K] [DecidableEq K]

private theorem five_dvd_thirtyFive : 5 ∣ 35 := by norm_num

private theorem seven_dvd_thirtyFive : 7 ∣ 35 := by norm_num

/-- The order-five part of a rational cyclic subgroup of order 35. -/
noncomputable def forgetToFive (x : RationalDatum K 35) : RationalDatum K 5 :=
  x.forgetToDivisor 5 five_dvd_thirtyFive

/-- The order-seven part of a rational cyclic subgroup of order 35. -/
noncomputable def forgetToSeven (x : RationalDatum K 35) : RationalDatum K 7 :=
  x.forgetToDivisor 7 seven_dvd_thirtyFive

@[simp]
theorem forgetToFive_curve (x : RationalDatum K 35) :
    (forgetToFive x).curve = x.curve :=
  rfl

@[simp]
theorem forgetToSeven_curve (x : RationalDatum K 35) :
    (forgetToSeven x).curve = x.curve :=
  rfl

/-- The level-35 to level-5 degeneracy map is independent of an admissible
Weierstrass presentation. -/
theorem forgetToFive_variableChange (x : RationalDatum K 35)
    (C : WeierstrassCurve.VariableChange K) :
    forgetToFive (x.variableChange C) = (forgetToFive x).variableChange C :=
  RationalDatum.forgetToDivisor_variableChange x 5 five_dvd_thirtyFive C

/-- The level-35 to level-7 degeneracy map is independent of an admissible
Weierstrass presentation. -/
theorem forgetToSeven_variableChange (x : RationalDatum K 35)
    (C : WeierstrassCurve.VariableChange K) :
    forgetToSeven (x.variableChange C) = (forgetToSeven x).variableChange C :=
  RationalDatum.forgetToDivisor_variableChange x 7 seven_dvd_thirtyFive C

/-- The presentation-independent level-35 to level-5 degeneracy map. -/
noncomputable def forgetToFiveClass :
    RationalDatum.VariableChangeClass (K := K) (N := 35) →
      RationalDatum.VariableChangeClass (K := K) (N := 5) :=
  RationalDatum.VariableChangeClass.forgetToDivisor 5 five_dvd_thirtyFive

/-- The presentation-independent level-35 to level-7 degeneracy map. -/
noncomputable def forgetToSevenClass :
    RationalDatum.VariableChangeClass (K := K) (N := 35) →
      RationalDatum.VariableChangeClass (K := K) (N := 7) :=
  RationalDatum.VariableChangeClass.forgetToDivisor 7 seven_dvd_thirtyFive

@[simp]
theorem forgetToFiveClass_variableChangeClassOf (x : RationalDatum K 35) :
    forgetToFiveClass (RationalDatum.variableChangeClassOf x) =
      RationalDatum.variableChangeClassOf (forgetToFive x) :=
  rfl

@[simp]
theorem forgetToSevenClass_variableChangeClassOf (x : RationalDatum K 35) :
    forgetToSevenClass (RationalDatum.variableChangeClassOf x) =
      RationalDatum.variableChangeClassOf (forgetToSeven x) :=
  rfl

/-- On a datum presented by a point of exact order 35, the canonical
order-five subgroup is generated by `7 • P`. -/
theorem forgetToFive_datumOfTorsion_subgroup_carrier
    (E : WeierstrassCurve K) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 35) :
    (forgetToFive (RationalDatum.datumOfTorsion E P hP)).subgroup.carrier =
      AddSubgroup.zmultiples (7 • P) := by
  unfold forgetToFive RationalDatum.forgetToDivisor
    RationalDatum.datumOfTorsion
    RationalDatum.datumOfRationalCyclicSubgroup
  convert RationalCyclicSubgroup.divisorSubgroup_ofPoint_carrier
    P hP 5 five_dvd_thirtyFive using 1

/-- On a datum presented by a point of exact order 35, the canonical
order-seven subgroup is generated by `5 • P`. -/
theorem forgetToSeven_datumOfTorsion_subgroup_carrier
    (E : WeierstrassCurve K) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 35) :
    (forgetToSeven (RationalDatum.datumOfTorsion E P hP)).subgroup.carrier =
      AddSubgroup.zmultiples (5 • P) := by
  unfold forgetToSeven RationalDatum.forgetToDivisor
    RationalDatum.datumOfTorsion
    RationalDatum.datumOfRationalCyclicSubgroup
  convert RationalCyclicSubgroup.divisorSubgroup_ofPoint_carrier
    P hP 7 seven_dvd_thirtyFive using 1

/-- The order-five and order-seven divisor-level subgroups together recover
the original cyclic subgroup of order 35.  Thus the two degeneracy data lose
no subgroup information at this squarefree level. -/
theorem subgroup_five_sup_seven (x : RationalDatum K 35) :
    (forgetToFive x).subgroup.carrier ⊔
        (forgetToSeven x).subgroup.carrier = x.subgroup.carrier := by
  let P : x.curve.toAffine.Point := x.subgroup.generator
  have hfive : (forgetToFive x).subgroup.carrier =
      AddSubgroup.zmultiples (7 • P) := by
    unfold forgetToFive RationalDatum.forgetToDivisor
      RationalDatum.datumOfRationalCyclicSubgroup
    convert x.subgroup.divisorSubgroup_generator_carrier
      5 five_dvd_thirtyFive using 1
  have hseven : (forgetToSeven x).subgroup.carrier =
      AddSubgroup.zmultiples (5 • P) := by
    unfold forgetToSeven RationalDatum.forgetToDivisor
      RationalDatum.datumOfRationalCyclicSubgroup
    convert x.subgroup.divisorSubgroup_generator_carrier
      7 seven_dvd_thirtyFive using 1
  rw [hfive, hseven, ← x.subgroup.zmultiples_generator]
  apply le_antisymm
  · have hPmem : P ∈ AddSubgroup.zmultiples P :=
      AddSubgroup.mem_zmultiples_iff.mpr ⟨1, by simp⟩
    exact sup_le
      (AddSubgroup.zmultiples_le_of_mem
        ((AddSubgroup.zmultiples P).nsmul_mem hPmem 7))
      (AddSubgroup.zmultiples_le_of_mem
        ((AddSubgroup.zmultiples P).nsmul_mem hPmem 5))
  · apply AddSubgroup.zmultiples_le_of_mem
    let S : AddSubgroup x.curve.toAffine.Point :=
      AddSubgroup.zmultiples (7 • P) ⊔ AddSubgroup.zmultiples (5 • P)
    change P ∈ S
    have hfiveMem : 7 • P ∈ S :=
      AddSubgroup.mem_sup_left (AddSubgroup.mem_zmultiples_iff.mpr ⟨1, by simp⟩)
    have hsevenMem : 5 • P ∈ S :=
      AddSubgroup.mem_sup_right (AddSubgroup.mem_zmultiples_iff.mpr ⟨1, by simp⟩)
    have hcombination : P = (3 : ℕ) • (5 • P) - (2 : ℕ) • (7 • P) := by
      abel
    rw [hcombination]
    exact S.sub_mem (S.nsmul_mem hsevenMem 3) (S.nsmul_mem hfiveMem 2)

end MazurTorsion.ModularCurve.XZeroThirtyFive
