/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI Codex
-/

import MazurTorsion.ModularCurve.XZeroFiniteFlatClassifyingData
import MazurTorsion.ModularCurve.XZeroWeierstrassCubicChartDensity
import MazurTorsion.ModularCurve.XZeroWeierstrassProjectivePointAddition

/-!
# Canonical finite-flat subgroup generated by an exact-torsion point

This module is the design boundary between the canonical projective
Weierstrass group law and the existing constant finite-flat subgroup
construction.  The globally checked group object and coordinate-point
comparison determine a canonical `WeierstrassGroupSchemeInterface`; an affine
point of exact order `N` then determines a split finite-flat cyclic subgroup of
constant order `N`.

The construction deliberately stops at `SplitGammaZeroDatum`: it asserts
neither a represented cyclic quotient nor a coarse `X₀(N)` point.  Its named
downstream consumer is
`MazurTorsion.XZeroFortyNine.rationalDatumOfSplitFiniteFlatSourceOfOrderFortyNineTorsion`,
which no longer accepts an arbitrary group-scheme interface.
-/

noncomputable section

open CategoryTheory CategoryTheory.MonoidalCategory CategoryTheory.MonObj
open AlgebraicGeometry

namespace MazurTorsion.ModularCurve.XZeroFiniteFlatModuli
namespace WeierstrassProjectiveCubic

universe u

variable {K : Type u} [Field K] [DecidableEq K]

/-- Geometric integrality in the exact `Over` spelling consumed by the
abelian-variety constructor. -/
instance toOver_geometricallyIntegral (W : WeierstrassCurve K) :
    GeometricallyIntegral (toOver W).hom := by
  change GeometricallyIntegral (structureMap W)
  exact structureMap_geometricallyIntegral W

/-- The canonical multiplicative equivalence between projective coordinate
points and rational points of the concrete projective cubic. -/
noncomputable def canonicalProjectivePointMulEquiv
    (W : WeierstrassCurve K) [W.IsElliptic] :
    Multiplicative W.toProjective.Point ≃*
      AbelianVarietyRationalPoint (toAbelianVariety W) :=
  canonicalProjectivePointEquivOfGroupLaw W
    (canonicalPointGroupLawCompatibility W).map_zero
    (canonicalPointGroupLawCompatibility W).map_add

/-- The canonical point equivalence is the checked coordinate-to-scheme map. -/
@[simp]
theorem canonicalProjectivePointMulEquiv_apply
    (W : WeierstrassCurve K) [W.IsElliptic]
    (P : Multiplicative W.toProjective.Point) :
    canonicalProjectivePointMulEquiv W P =
      projectivePointToAbelianVarietyRationalPoint W P.toAdd :=
  canonicalProjectivePointEquivOfGroupLaw_apply W
    (canonicalPointGroupLawCompatibility W).map_zero
    (canonicalPointGroupLawCompatibility W).map_add P

/-- The canonical group-scheme interface on the concrete reduced projective
Weierstrass cubic. -/
noncomputable def canonicalWeierstrassGroupSchemeInterface
    (W : WeierstrassCurve K) [W.IsElliptic] :
    WeierstrassGroupSchemeInterface W :=
  (toAbelianVarietyComparison W
    (canonicalProjectivePointMulEquiv W)).toGroupSchemeInterface

/-- An exact-order coordinate point generates the canonical split finite-flat
cyclic subgroup of the concrete projective Weierstrass group scheme. -/
noncomputable def canonicalSplitGammaZeroDatumOfTorsion
    {N : ℕ} [NeZero N]
    (W : WeierstrassCurve K) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
  WeierstrassGroupSchemeInterface.SplitGammaZeroDatum
      (N := N) W (canonicalWeierstrassGroupSchemeInterface W) :=
  WeierstrassGroupSchemeInterface.splitGammaZeroDatumOfRationalDatum
    (XZeroModuli.RationalDatum.datumOfTorsion W P hP)
    (canonicalWeierstrassGroupSchemeInterface W)

/-- The canonical subgroup generated by an exact-order point has constant
geometric order `N`. -/
theorem canonicalSplitGammaZeroDatumOfTorsion_hasConstantOrder
    {N : ℕ} [NeZero N]
    (W : WeierstrassCurve K) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    (canonicalSplitGammaZeroDatumOfTorsion W P hP).subgroup.carrier.HasConstantOrder N :=
  WeierstrassGroupSchemeInterface.splitGammaZeroDatumOfRationalDatum_hasConstantOrder
    (XZeroModuli.RationalDatum.datumOfTorsion W P hP)
    (canonicalWeierstrassGroupSchemeInterface W)

/-- Forgetting the canonical finite-flat subgroup generated by `P` recovers
the original rational `Γ₀(N)` datum. -/
theorem rationalDatumOfCanonicalSplitGammaZeroDatumOfTorsion
    {N : ℕ} [NeZero N]
    (W : WeierstrassCurve K) [W.IsElliptic]
    (P : W.toAffine.Point) (hP : addOrderOf P = N) :
    WeierstrassGroupSchemeInterface.rationalDatumOfSplitGammaZeroDatum
        (canonicalWeierstrassGroupSchemeInterface W)
        (canonicalSplitGammaZeroDatumOfTorsion W P hP) =
      XZeroModuli.RationalDatum.datumOfTorsion W P hP :=
  WeierstrassGroupSchemeInterface.rationalDatumOfSplitGammaZeroDatum_ofRationalDatum
    (XZeroModuli.RationalDatum.datumOfTorsion W P hP)
    (canonicalWeierstrassGroupSchemeInterface W)

end WeierstrassProjectiveCubic
end MazurTorsion.ModularCurve.XZeroFiniteFlatModuli
