/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import Mathlib.NumberTheory.Cyclotomic.Gal
import Mathlib.NumberTheory.NumberField.Cyclotomic.Embeddings
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import Mathlib.NumberTheory.RamificationInertia.Unramified
import Mathlib.RingTheory.ClassGroup.Basic
import MazurTorsion.NumberTheory.UnramifiedArtin
import MazurTorsion.NumberTheory.WeakChebotarev

/-!
# Inverse-cyclotomic unramified extensions

This file isolates the number-theoretic interface used in Mazur's prime-order
argument.  It packages a cyclic degree-`p` extension of the `p`-th cyclotomic
field together with the inverse-cyclotomic conjugation law, expresses local
unramifiedness at actual finite places, and records the class-group quotient
that global class field theory must produce.

The pinned Mathlib supplies cyclotomic Galois theory, finite places,
ramification indices, ideal class groups, and the analytic class-number
formula. The local criteria and the finite-prime generation step are proved
below. The remaining global input is conductor-one principal Artin
reciprocity, isolated as `PrincipalReciprocityPrinciple` before the checked
assembly of `ClassFieldTheoryPrinciple`.
-/

open scoped NumberField Pointwise

namespace NumberTheory.CyclotomicCharacter

universe u

/-- The `p`-th cyclotomic field over the rationals. -/
abbrev PrimeCyclotomicField (p : ℕ) := CyclotomicField p ℚ

/-- A finite place in the ideal-theoretic ramification API: a nonzero prime
ideal in the ring of integers. -/
abbrev FinitePrime (K : Type*) [Field K] :=
  IsDedekindDomain.HeightOneSpectrum (NumberField.RingOfIntegers K)

/-- The unique finite prime of the prime cyclotomic field above `p`, written
as the ideal generated by `ζ_p - 1`. -/
noncomputable def cyclotomicPrime (p : ℕ) [Fact p.Prime] :
    FinitePrime (PrimeCyclotomicField p) := by
  letI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI : NeZero (p : ℚ) :=
    ⟨Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero⟩
  letI : IsCyclotomicExtension {p} ℚ (PrimeCyclotomicField p) :=
    CyclotomicField.isCyclotomicExtension p ℚ
  let hζ := IsCyclotomicExtension.zeta_spec p ℚ (PrimeCyclotomicField p)
  exact IsDedekindDomain.HeightOneSpectrum.ofPrime
    (Ideal.prime_span_singleton_iff.mpr hζ.zeta_sub_one_prime')

/-- The inverse of the mod-`p` cyclotomic character on the Galois group of
the `p`-th cyclotomic field. -/
noncomputable def inverseCharacter (p : ℕ) [Fact p.Prime] :
    Gal(PrimeCyclotomicField p/ℚ) →* (ZMod p)ˣ :=
  letI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI : NeZero (p : ℚ) :=
    ⟨Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero⟩
  letI : IsCyclotomicExtension {p} ℚ (PrimeCyclotomicField p) :=
    CyclotomicField.isCyclotomicExtension p ℚ
  invMonoidHom.comp
    (IsCyclotomicExtension.autEquivPow (PrimeCyclotomicField p)
      (Polynomial.cyclotomic.irreducible_rat (NeZero.pos p))).toMonoidHom

/-- For `p > 2`, the cyclotomic base is totally complex.  Thus the intended
prime-order range has no real places requiring a narrow-class-group
correction. -/
theorem primeCyclotomicField_isTotallyComplex
    {p : ℕ} [Fact p.Prime] (hp : 2 < p) :
    NumberField.IsTotallyComplex (PrimeCyclotomicField p) := by
  letI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI : NeZero (p : ℚ) :=
    ⟨Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero⟩
  letI : IsCyclotomicExtension {p} ℚ (PrimeCyclotomicField p) :=
    CyclotomicField.isCyclotomicExtension p ℚ
  exact IsCyclotomicExtension.Rat.isTotallyComplex (PrimeCyclotomicField p) hp

/-- A cyclic degree-`p` extension of `ℚ(ζ_p)` on which conjugation by
`Gal(ℚ(ζ_p)/ℚ)` acts through the inverse cyclotomic character.

The lifts and the conjugates are included as data, but both are tied to the
field operations by `lift_algebraMap` and `conjugate_apply`; in particular,
`inverse_action` is an assertion about actual conjugation in the field tower,
not an unrelated abstract action. -/
structure InverseExtension (p : ℕ) [Fact p.Prime]
    (L : Type u) [Field L] [NumberField L] [Algebra (PrimeCyclotomicField p) L]
    [IsScalarTower ℚ (PrimeCyclotomicField p) L] where
  /-- Galoisness over the cyclotomic base. -/
  isGalois : IsGalois (PrimeCyclotomicField p) L
  /-- Galoisness over the rationals, needed to lift cyclotomic automorphisms. -/
  isGaloisOverRat : IsGalois ℚ L
  /-- Identification of the relative Galois group with the cyclic group of order `p`. -/
  galEquiv : Gal(L/PrimeCyclotomicField p) ≃* Multiplicative (ZMod p)
  /-- A lift to `L` of each automorphism of the cyclotomic base. -/
  lift : Gal(PrimeCyclotomicField p/ℚ) → Gal(L/ℚ)
  /-- Each chosen lift restricts to the original cyclotomic automorphism. -/
  lift_algebraMap : ∀ σ x,
    lift σ (algebraMap (PrimeCyclotomicField p) L x) =
      algebraMap (PrimeCyclotomicField p) L (σ x)
  /-- Conjugation of the relative Galois group by a chosen lift. -/
  conjugate : Gal(PrimeCyclotomicField p/ℚ) →
    Gal(L/PrimeCyclotomicField p) → Gal(L/PrimeCyclotomicField p)
  /-- The packaged conjugation is the actual conjugation on field elements. -/
  conjugate_apply : ∀ σ τ x,
    conjugate σ τ x = lift σ (τ ((lift σ).symm x))
  /-- Conjugation acts on the cyclic relative group through the inverse character. -/
  inverse_action : ∀ σ τ,
    Multiplicative.toAdd (galEquiv (conjugate σ τ)) =
      (inverseCharacter p σ : ZMod p) *
        Multiplicative.toAdd (galEquiv τ)

/-- The roadmap-facing name for an inverse-cyclotomic extension. -/
abbrev inverseExtension := InverseExtension

namespace InverseExtension

variable {p : ℕ} [Fact p.Prime]
variable {L : Type u} [Field L] [NumberField L] [Algebra (PrimeCyclotomicField p) L]
variable [IsScalarTower ℚ (PrimeCyclotomicField p) L]

/-- Unramifiedness of an inverse-cyclotomic extension at a finite place of
the cyclotomic base field. -/
def IsUnramifiedAtFinitePlace (_E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p)) : Prop :=
  Algebra.IsUnramifiedIn (NumberField.RingOfIntegers L) v.asIdeal

/-- Unramifiedness at every finite place of the cyclotomic base field. -/
def IsUnramifiedAtFinitePlaces (E : InverseExtension p L) : Prop :=
  ∀ v : FinitePrime (PrimeCyclotomicField p), E.IsUnramifiedAtFinitePlace v

/-- For rings of integers in a number-field extension, global algebraic
unramifiedness is equivalent to unramifiedness at every nonzero prime of the
base.  The generic prime contributes no extra hypothesis in characteristic
zero. -/
theorem algebraUnramified_iff_isUnramifiedAtFinitePlaces
    (E : InverseExtension p L) :
    Algebra.Unramified
        (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        (NumberField.RingOfIntegers L) ↔
      E.IsUnramifiedAtFinitePlaces := by
  rw [Algebra.unramified_iff_forall]
  constructor
  · intro h v P hP _
    exact h ⟨P, hP⟩
  · intro h q
    by_cases hq : q.asIdeal = ⊥
    · simpa only [hq] using
        (Algebra.isUnramifiedAt_bot
          (R := NumberField.RingOfIntegers (PrimeCyclotomicField p))
          (S := NumberField.RingOfIntegers L))
    · let basePrime : Ideal
          (NumberField.RingOfIntegers (PrimeCyclotomicField p)) :=
        q.asIdeal.under (NumberField.RingOfIntegers (PrimeCyclotomicField p))
      have hqmax : q.asIdeal.IsMaximal := q.isPrime.isMaximal hq
      letI : q.asIdeal.IsMaximal := hqmax
      have hp : basePrime.IsMaximal :=
        Ideal.IsMaximal.under
          (NumberField.RingOfIntegers (PrimeCyclotomicField p)) q.asIdeal
      let v : FinitePrime (PrimeCyclotomicField p) :=
        ⟨basePrime, hp.isPrime,
          Ideal.IsMaximal.ne_bot_of_isIntegral_int basePrime⟩
      have hu : Algebra.IsUnramifiedIn
          (NumberField.RingOfIntegers L) basePrime := by
        simpa only [IsUnramifiedAtFinitePlace] using h v
      have hover : q.asIdeal.LiesOver basePrime := inferInstance
      exact hu q.asIdeal q.isPrime hover

/-- Mathlib's ramification-index criterion, specialized to an actual finite
place of the cyclotomic field. -/
theorem isUnramifiedAtFinitePlace_iff_ramificationIdx_eq_one
    (E : InverseExtension p L) (v : FinitePrime (PrimeCyclotomicField p)) :
    E.IsUnramifiedAtFinitePlace v ↔
      ∀ (P : Ideal (NumberField.RingOfIntegers L)) [P.IsPrime],
        P.LiesOver v.asIdeal →
          Ideal.ramificationIdx P
            (NumberField.RingOfIntegers (PrimeCyclotomicField p)) = 1 :=
  Algebra.isUnramifiedIn_iff_forall_ramificationIdx_eq_one

/-- The simultaneous ramification-index-one condition at all finite places. -/
def RamificationIndexOneAtFinitePlaces (_E : InverseExtension p L) : Prop :=
  ∀ (v : FinitePrime (PrimeCyclotomicField p))
    (P : Ideal (NumberField.RingOfIntegers L)) [P.IsPrime],
    P.LiesOver v.asIdeal →
      Ideal.ramificationIdx P
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)) = 1

/-- Everywhere finite-place unramifiedness is equivalent to ramification
index one above every finite place. -/
theorem isUnramifiedAtFinitePlaces_iff_ramificationIndexOne
    (E : InverseExtension p L) :
    E.IsUnramifiedAtFinitePlaces ↔ E.RamificationIndexOneAtFinitePlaces := by
  constructor
  · intro h v P hP hPover
    exact (E.isUnramifiedAtFinitePlace_iff_ramificationIdx_eq_one v).mp (h v) P hPover
  · intro h v
    exact (E.isUnramifiedAtFinitePlace_iff_ramificationIdx_eq_one v).mpr (h v)

/-- The full number-ring extension is unramified exactly when every
ramification index above every finite cyclotomic prime is one. -/
theorem algebraUnramified_iff_ramificationIndexOne
    (E : InverseExtension p L) :
    Algebra.Unramified
        (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        (NumberField.RingOfIntegers L) ↔
      E.RamificationIndexOneAtFinitePlaces :=
  E.algebraUnramified_iff_isUnramifiedAtFinitePlaces.trans
    E.isUnramifiedAtFinitePlaces_iff_ramificationIndexOne

/-- A chosen prime of `L` above the finite prime `v` of the cyclotomic base. -/
noncomputable def primeAbove (_E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p)) :
    Ideal.primesOver v.asIdeal (NumberField.RingOfIntegers L) := by
  letI : IsGalois (PrimeCyclotomicField p) L := _E.isGalois
  exact NumberTheory.UnramifiedArtin.primeAbove v

/-- The arithmetic Frobenius of an inverse-cyclotomic extension at a finite
prime of the cyclotomic base. -/
noncomputable def frobeniusAt (E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p)) :
    Gal(L/PrimeCyclotomicField p) := by
  letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
  exact NumberTheory.UnramifiedArtin.frobeniusAt v

/-- The selected Frobenius satisfies the defining residue-field congruence at
the selected prime above `v`. -/
theorem frobeniusAt_isArithFrobAt (E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p)) :
    letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
    IsArithFrobAt
        (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        (E.frobeniusAt v) (E.primeAbove v).1 := by
  letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
  exact NumberTheory.UnramifiedArtin.frobeniusAt_isArithFrobAt v

/-- Since the relative Galois group is cyclic, the selected Frobenius is
independent of the prime of `L` chosen above `v`. -/
theorem frobeniusAt_eq_arithFrobAt (E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p))
    (Q : Ideal.primesOver v.asIdeal (NumberField.RingOfIntegers L)) :
    letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
    E.frobeniusAt v =
      arithFrobAt
        (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        Gal(L/PrimeCyclotomicField p) Q.1 := by
  letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
  letI : IsMulCommutative Gal(L/PrimeCyclotomicField p) :=
    IsMulCommutative.of_comm fun τ υ => by
      apply E.galEquiv.injective
      simp only [map_mul]
      exact mul_comm _ _
  exact NumberTheory.UnramifiedArtin.frobeniusAt_eq_arithFrobAt v Q

/-- At an unramified finite prime, the Frobenius congruence characterizes the
Frobenius element at every prime above it. -/
theorem isArithFrobAt_iff_eq_frobeniusAt
    (E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p))
    (hunramified : E.IsUnramifiedAtFinitePlace v)
    (Q : Ideal.primesOver v.asIdeal (NumberField.RingOfIntegers L))
    (τ : Gal(L/PrimeCyclotomicField p)) :
    letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
    IsArithFrobAt
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)) τ Q.1 ↔
      τ = E.frobeniusAt v := by
  letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
  letI : IsMulCommutative Gal(L/PrimeCyclotomicField p) :=
    IsMulCommutative.of_comm fun τ υ => by
      apply E.galEquiv.injective
      simp only [map_mul]
      exact mul_comm _ _
  constructor
  · intro hτ
    exact (NumberTheory.UnramifiedArtin.arithFrobAt_unique_of_unramified
      v hunramified Q τ hτ).trans (E.frobeniusAt_eq_arithFrobAt v Q).symm
  · rintro rfl
    rw [E.frobeniusAt_eq_arithFrobAt v Q]
    exact IsArithFrobAt.arithFrobAt
      (NumberField.RingOfIntegers (PrimeCyclotomicField p))
      Gal(L/PrimeCyclotomicField p) Q.1

/-- The automorphism induced by a cyclotomic Galois element on the ring of
integers of the cyclotomic field. -/
noncomputable def baseIntegerEquiv
    (σ : Gal(PrimeCyclotomicField p/ℚ)) :
    NumberField.RingOfIntegers (PrimeCyclotomicField p) ≃+*
      NumberField.RingOfIntegers (PrimeCyclotomicField p) :=
  NumberField.RingOfIntegers.mapRingEquiv σ.toRingEquiv

/-- The automorphism induced by the chosen lift on the ring of integers of
the extension field. -/
noncomputable def liftIntegerEquiv (E : InverseExtension p L)
    (σ : Gal(PrimeCyclotomicField p/ℚ)) :
    NumberField.RingOfIntegers L ≃+* NumberField.RingOfIntegers L :=
  NumberField.RingOfIntegers.mapRingEquiv (E.lift σ).toRingEquiv

/-- The two induced automorphisms of the rings of integers form a semilinear
square over the chosen lift. -/
theorem liftIntegerEquiv_algebraMap (E : InverseExtension p L)
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (x : NumberField.RingOfIntegers (PrimeCyclotomicField p)) :
    E.liftIntegerEquiv σ
        (algebraMap
          (NumberField.RingOfIntegers (PrimeCyclotomicField p))
          (NumberField.RingOfIntegers L) x) =
      algebraMap
        (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        (NumberField.RingOfIntegers L) (baseIntegerEquiv σ x) := by
  apply NumberField.RingOfIntegers.ext
  change E.lift σ
      (algebraMap (PrimeCyclotomicField p) L
        (x : PrimeCyclotomicField p)) =
    algebraMap (PrimeCyclotomicField p) L
      (σ (x : PrimeCyclotomicField p))
  exact E.lift_algebraMap σ (x : PrimeCyclotomicField p)

omit [Fact p.Prime] in
/-- Extending the ring-of-integers action to the fraction field recovers the
original cyclotomic Galois automorphism. -/
theorem inducedBaseIntegerEquiv_eq
    (σ : Gal(PrimeCyclotomicField p/ℚ)) :
    IsFractionRing.ringEquivOfRingEquiv (baseIntegerEquiv σ) =
      σ.toRingEquiv := by
  apply RingEquiv.toRingHom_injective
  apply IsFractionRing.ringHom_ext
    (A := NumberField.RingOfIntegers (PrimeCyclotomicField p))
  intro x
  change IsFractionRing.ringEquivOfRingEquiv (baseIntegerEquiv σ)
      (algebraMap (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        (PrimeCyclotomicField p) x) =
    σ (algebraMap (NumberField.RingOfIntegers (PrimeCyclotomicField p))
      (PrimeCyclotomicField p) x)
  rw [IsFractionRing.ringEquivOfRingEquiv_algebraMap]
  rfl

/-- The action of a cyclotomic Galois element on finite primes. -/
noncomputable def mapFinitePrime
    (σ : Gal(PrimeCyclotomicField p/ℚ)) :
    FinitePrime (PrimeCyclotomicField p) ≃
      FinitePrime (PrimeCyclotomicField p) :=
  IsDedekindDomain.HeightOneSpectrum.equivOfRingEquiv (baseIntegerEquiv σ)

omit [Fact p.Prime] in
/-- The ideal underlying the transported finite prime is the usual ideal
map. -/
theorem mapFinitePrime_asIdeal
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (v : FinitePrime (PrimeCyclotomicField p)) :
    (mapFinitePrime σ v).asIdeal = Ideal.map (baseIntegerEquiv σ) v.asIdeal :=
  NumberTheory.UnramifiedArtin.asIdeal_equivOfRingEquiv _ _

/-- Every cyclotomic automorphism fixes the unique finite prime above `p`. -/
theorem mapFinitePrime_cyclotomicPrime
    (p : ℕ) [Fact p.Prime]
    (sigma : Gal(PrimeCyclotomicField p/ℚ)) :
    mapFinitePrime sigma (cyclotomicPrime p) = cyclotomicPrime p := by
  letI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI : NeZero (p : ℚ) :=
    ⟨Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero⟩
  letI : IsCyclotomicExtension {p} ℚ (PrimeCyclotomicField p) :=
    CyclotomicField.isCyclotomicExtension p ℚ
  let hζ := IsCyclotomicExtension.zeta_spec p ℚ (PrimeCyclotomicField p)
  apply IsDedekindDomain.HeightOneSpectrum.asIdeal_injective
  rw [mapFinitePrime_asIdeal]
  dsimp only [cyclotomicPrime]
  change Ideal.map (baseIntegerEquiv sigma)
      (Ideal.span {hζ.toInteger - 1}) =
    Ideal.span {hζ.toInteger - 1}
  rw [Ideal.map_span, Set.image_singleton]
  apply Ideal.span_singleton_eq_span_singleton.mpr
  let e : NumberField.RingOfIntegers (PrimeCyclotomicField p) ≃ₐ[ℤ]
      NumberField.RingOfIntegers (PrimeCyclotomicField p) :=
    AlgEquiv.ofRingEquiv
      (f := baseIntegerEquiv sigma)
      (fun z ↦ by simp)
  have hassoc :=
    hζ.toInteger_isPrimitiveRoot.associated_sub_one_map_sub_one e
  exact hassoc.symm

/-- Actual conjugation by a chosen lift agrees with semilinear conjugation on
the rings of integers. -/
theorem conjugate_toAlgHom_eq_semilinearConjugate
    (E : InverseExtension p L)
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (τ : Gal(L/PrimeCyclotomicField p)) :
    letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
    MulSemiringAction.toAlgHom
        (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        (NumberField.RingOfIntegers L) (E.conjugate σ τ) =
      NumberTheory.UnramifiedArtin.semilinearConjugate
        (baseIntegerEquiv σ) (E.liftIntegerEquiv σ)
        (E.liftIntegerEquiv_algebraMap σ)
        (MulSemiringAction.toAlgHom
          (NumberField.RingOfIntegers (PrimeCyclotomicField p))
          (NumberField.RingOfIntegers L) τ) := by
  letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
  apply AlgHom.ext
  intro x
  apply NumberField.RingOfIntegers.ext
  change E.conjugate σ τ (x : L) =
    E.lift σ (τ ((E.lift σ).symm (x : L)))
  exact E.conjugate_apply σ τ (x : L)

/-- Arithmetic Frobenius congruences are preserved by semilinear
conjugation. -/
theorem conjugate_isArithFrobAt
    (E : InverseExtension p L)
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (τ : Gal(L/PrimeCyclotomicField p))
    (Q : Ideal (NumberField.RingOfIntegers L)) :
    letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
    IsArithFrobAt
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)) τ Q →
      IsArithFrobAt
        (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        (E.conjugate σ τ) (Q.map (E.liftIntegerEquiv σ)) := by
  letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
  intro hτ
  change (MulSemiringAction.toAlgHom
    (NumberField.RingOfIntegers (PrimeCyclotomicField p))
    (NumberField.RingOfIntegers L) (E.conjugate σ τ)).IsArithFrobAt _
  rw [E.conjugate_toAlgHom_eq_semilinearConjugate σ τ]
  exact NumberTheory.UnramifiedArtin.isArithFrobAt_semilinearConjugate
    (baseIntegerEquiv σ) (E.liftIntegerEquiv σ)
      (E.liftIntegerEquiv_algebraMap σ) hτ

/-- A canonical prime over the transported base prime, obtained by mapping
the selected prime upstairs by the chosen lift. -/
noncomputable def mappedPrimeAbove (E : InverseExtension p L)
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (v : FinitePrime (PrimeCyclotomicField p)) :
    Ideal.primesOver (mapFinitePrime σ v).asIdeal
      (NumberField.RingOfIntegers L) := by
  refine ⟨(E.primeAbove v).1.map (E.liftIntegerEquiv σ), inferInstance, ?_⟩
  constructor
  rw [mapFinitePrime_asIdeal,
    NumberTheory.UnramifiedArtin.under_map_semilinear
      (baseIntegerEquiv σ) (E.liftIntegerEquiv σ)
      (E.liftIntegerEquiv_algebraMap σ),
    ← Ideal.over_def (p := v.asIdeal) (P := (E.primeAbove v).1)]

/-- At unramified finite primes, Frobenius transforms by actual conjugation
under the cyclotomic Galois action. -/
theorem conjugate_frobeniusAt (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (v : FinitePrime (PrimeCyclotomicField p)) :
    E.conjugate σ (E.frobeniusAt v) =
      E.frobeniusAt (mapFinitePrime σ v) := by
  apply (E.isArithFrobAt_iff_eq_frobeniusAt
    (mapFinitePrime σ v) (hunramified (mapFinitePrime σ v))
      (E.mappedPrimeAbove σ v) _).mp
  exact E.conjugate_isArithFrobAt σ (E.frobeniusAt v)
    (E.primeAbove v).1 (E.frobeniusAt_isArithFrobAt v)

/-- The local Artin symbol, expressed in the fixed cyclic coordinate
`Multiplicative (ZMod p)`. -/
noncomputable def artinSymbol (E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p)) :
    Multiplicative (ZMod p) :=
  E.galEquiv (E.frobeniusAt v)

/-- Multiplication by the inverse-cyclotomic character, viewed as an
endomorphism of the additive cyclic coordinate. -/
noncomputable def inverseCharacterAction
    (σ : Gal(PrimeCyclotomicField p/ℚ)) :
    Multiplicative (ZMod p) →* Multiplicative (ZMod p) where
  toFun z := Multiplicative.ofAdd
    ((inverseCharacter p σ : ZMod p) * Multiplicative.toAdd z)
  map_one' := by
    apply Multiplicative.toAdd.injective
    simp
  map_mul' x y := by
    apply Multiplicative.toAdd.injective
    change (inverseCharacter p σ : ZMod p) *
        (Multiplicative.toAdd x + Multiplicative.toAdd y) =
      (inverseCharacter p σ : ZMod p) * Multiplicative.toAdd x +
        (inverseCharacter p σ : ZMod p) * Multiplicative.toAdd y
    exact mul_add _ _ _

/-- Evaluation of the inverse-character action in the additive cyclic
coordinate. -/
@[simp]
theorem inverseCharacterAction_toAdd
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (z : Multiplicative (ZMod p)) :
    Multiplicative.toAdd (inverseCharacterAction σ z) =
      (inverseCharacter p σ : ZMod p) * Multiplicative.toAdd z :=
  rfl

/-- The finite-prime Artin symbol transforms by the inverse cyclotomic
character. -/
theorem artinSymbol_mapFinitePrime (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (v : FinitePrime (PrimeCyclotomicField p)) :
    E.artinSymbol (mapFinitePrime σ v) =
      inverseCharacterAction σ (E.artinSymbol v) := by
  apply Multiplicative.toAdd.injective
  change Multiplicative.toAdd
      (E.galEquiv (E.frobeniusAt (mapFinitePrime σ v))) = _
  rw [← E.conjugate_frobeniusAt hunramified σ v]
  exact E.inverse_action σ (E.frobeniusAt v)

/-- The semilinear action of a cyclotomic Galois element on nonzero
fractional ideals. -/
noncomputable def fractionalIdealEquiv
    (σ : Gal(PrimeCyclotomicField p/ℚ)) :
    (FractionalIdeal
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (PrimeCyclotomicField p))ˣ ≃*
    (FractionalIdeal
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (PrimeCyclotomicField p))ˣ :=
  Units.mapEquiv
    (FractionalIdeal.ringEquivOfRingEquiv
      (PrimeCyclotomicField p) (PrimeCyclotomicField p)
      (baseIntegerEquiv σ)).toMulEquiv

omit [Fact p.Prime] in
/-- The fractional-ideal action sends a prime ideal to the transported finite
prime. -/
theorem fractionalIdealEquiv_prime
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (v : FinitePrime (PrimeCyclotomicField p)) :
    fractionalIdealEquiv σ
        (NumberTheory.UnramifiedArtin.primeFractionalIdealUnit
          (K := PrimeCyclotomicField p) v) =
      NumberTheory.UnramifiedArtin.primeFractionalIdealUnit
        (K := PrimeCyclotomicField p) (mapFinitePrime σ v) := by
  apply Units.ext
  change FractionalIdeal.ringEquivOfRingEquiv
      (PrimeCyclotomicField p) (PrimeCyclotomicField p)
      (baseIntegerEquiv σ)
      (v.asIdeal : FractionalIdeal
        (nonZeroDivisors
          (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
        (PrimeCyclotomicField p)) =
    ((mapFinitePrime σ v).asIdeal : FractionalIdeal
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (PrimeCyclotomicField p))
  rw [NumberTheory.UnramifiedArtin.ringEquivOfRingEquiv_coeIdeal,
    mapFinitePrime_asIdeal]

/-- The ideal-theoretic Artin homomorphism obtained by extending the finite
prime symbols multiplicatively to all nonzero fractional ideals. -/
noncomputable def fractionalArtin (E : InverseExtension p L) :
    (FractionalIdeal
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (PrimeCyclotomicField p))ˣ →* Multiplicative (ZMod p) :=
  NumberTheory.UnramifiedArtin.fractionalIdealHom E.artinSymbol

/-- On a prime fractional ideal, `fractionalArtin` is the selected local
arithmetic Frobenius in the cyclic coordinate. -/
@[simp]
theorem fractionalArtin_prime (E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p)) :
    E.fractionalArtin
      (Units.mk0
        (v.asIdeal : FractionalIdeal
          (nonZeroDivisors
            (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
          (PrimeCyclotomicField p))
        (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)) =
      E.artinSymbol v :=
  NumberTheory.UnramifiedArtin.fractionalIdealHom_prime _ v

/-- The fractional Artin map is inverse-cyclotomic equivariant. -/
theorem fractionalArtin_equivariant (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (I : (FractionalIdeal
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (PrimeCyclotomicField p))ˣ) :
    E.fractionalArtin (fractionalIdealEquiv σ I) =
      inverseCharacterAction σ (E.fractionalArtin I) := by
  have hhom : E.fractionalArtin.comp
        (fractionalIdealEquiv σ).toMonoidHom =
      (inverseCharacterAction σ).comp E.fractionalArtin := by
    apply NumberTheory.UnramifiedArtin.fractionalIdealMonoidHom_ext
    intro v
    change E.fractionalArtin (fractionalIdealEquiv σ
        (NumberTheory.UnramifiedArtin.primeFractionalIdealUnit
          (K := PrimeCyclotomicField p) v)) =
      inverseCharacterAction σ
        (E.fractionalArtin
          (NumberTheory.UnramifiedArtin.primeFractionalIdealUnit
            (K := PrimeCyclotomicField p) v))
    rw [fractionalIdealEquiv_prime]
    unfold NumberTheory.UnramifiedArtin.primeFractionalIdealUnit
    rw [E.fractionalArtin_prime, E.fractionalArtin_prime]
    exact E.artinSymbol_mapFinitePrime hunramified σ v
  exact DFunLike.congr_fun hhom I

/-- Equivariance kills the Artin symbol of a finite prime fixed by a
cyclotomic automorphism whose inverse character is nontrivial. -/
theorem artinSymbol_eq_one_of_fixed
    (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (sigma : Gal(PrimeCyclotomicField p/ℚ))
    (hsigma : (inverseCharacter p sigma : ZMod p) ≠ 1)
    (v : FinitePrime (PrimeCyclotomicField p))
    (hv : mapFinitePrime sigma v = v) :
    E.artinSymbol v = 1 := by
  have hequiv := E.artinSymbol_mapFinitePrime hunramified sigma v
  rw [hv] at hequiv
  apply Multiplicative.toAdd.injective
  change Multiplicative.toAdd (E.artinSymbol v) = 0
  have hadd := congrArg Multiplicative.toAdd hequiv
  rw [inverseCharacterAction_toAdd] at hadd
  let z := Multiplicative.toAdd (E.artinSymbol v)
  let c : ZMod p := inverseCharacter p sigma
  change z = c * z at hadd
  have hzero : (1 - c) * z = 0 := by
    rw [sub_mul, one_mul]
    exact sub_eq_zero.mpr hadd
  exact (mul_eq_zero.mp hzero).resolve_left
    (sub_ne_zero.mpr (Ne.symm hsigma))

/-- Equivariance kills any fractional ideal fixed by a cyclotomic
automorphism whose inverse character is nontrivial. -/
theorem fractionalArtin_eq_one_of_fixed
    (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (sigma : Gal(PrimeCyclotomicField p/ℚ))
    (hsigma : (inverseCharacter p sigma : ZMod p) ≠ 1)
    (I : (FractionalIdeal
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (PrimeCyclotomicField p))ˣ)
    (hI : fractionalIdealEquiv sigma I = I) :
    E.fractionalArtin I = 1 := by
  have hequiv := E.fractionalArtin_equivariant hunramified sigma I
  rw [hI] at hequiv
  apply Multiplicative.toAdd.injective
  change Multiplicative.toAdd (E.fractionalArtin I) = 0
  have hadd := congrArg Multiplicative.toAdd hequiv
  rw [inverseCharacterAction_toAdd] at hadd
  let z := Multiplicative.toAdd (E.fractionalArtin I)
  let c : ZMod p := inverseCharacter p sigma
  change z = c * z at hadd
  have hzero : (1 - c) * z = 0 := by
    rw [sub_mul, one_mul]
    exact sub_eq_zero.mpr hadd
  exact (mul_eq_zero.mp hzero).resolve_left
    (sub_ne_zero.mpr (Ne.symm hsigma))

/-- Consequently, the fractional Artin map kills a principal ideal whose
generator is fixed by such a cyclotomic automorphism. This is a checked
fragment of principal reciprocity; an arbitrary generator need not have a
nontrivial stabilizer. -/
theorem fractionalArtin_toPrincipalIdeal_eq_one_of_fixed
    (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (sigma : Gal(PrimeCyclotomicField p/ℚ))
    (hsigma : (inverseCharacter p sigma : ZMod p) ≠ 1)
    (x : (PrimeCyclotomicField p)ˣ)
    (hx : sigma (x : PrimeCyclotomicField p) = x) :
    E.fractionalArtin
      (toPrincipalIdeal
        (NumberField.RingOfIntegers (PrimeCyclotomicField p))
        (PrimeCyclotomicField p) x) = 1 := by
  apply E.fractionalArtin_eq_one_of_fixed hunramified sigma hsigma
  have hfrac : FractionalIdeal.ringEquivOfRingEquiv
      (PrimeCyclotomicField p) (PrimeCyclotomicField p)
      (baseIntegerEquiv sigma)
      (FractionalIdeal.spanSingleton
        (nonZeroDivisors
          (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
        (x : PrimeCyclotomicField p)) =
    FractionalIdeal.spanSingleton
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (x : PrimeCyclotomicField p) := by
    rw [FractionalIdeal.ringEquivOfRingEquiv_spanSingleton,
      inducedBaseIntegerEquiv_eq sigma]
    exact congrArg
      (FractionalIdeal.spanSingleton
        (nonZeroDivisors
          (NumberField.RingOfIntegers (PrimeCyclotomicField p)))) hx
  rw [Units.ext_iff]
  dsimp only [fractionalIdealEquiv]
  simp only [Units.coe_mapEquiv, RingEquiv.toMulEquiv_eq_coe,
    coe_toPrincipalIdeal]
  exact hfrac

/-- Conductor-one principal reciprocity for the ideal Artin map: every
principal fractional ideal maps trivially. -/
def SatisfiesPrincipalReciprocity (E : InverseExtension p L) : Prop :=
  NumberTheory.UnramifiedArtin.KillsPrincipalIdeals
    (NumberField.RingOfIntegers (PrimeCyclotomicField p))
    (PrimeCyclotomicField p) E.fractionalArtin

/-- The weak Chebotarev input needed here, stated exactly as generation of the
cyclic relative Galois group by finite-prime Artin symbols. -/
def FrobeniusSymbolsGenerate (E : InverseExtension p L) : Prop :=
  Subgroup.closure (Set.range E.artinSymbol) = ⊤

/-- If the selected Frobenius is trivial at an unramified finite prime, that
prime splits completely: the number of primes above it equals the relative
degree. -/
theorem ncard_primesOver_eq_finrank_of_frobeniusAt_eq_one
    (E : InverseExtension p L)
    (v : FinitePrime (PrimeCyclotomicField p))
    (hunramified : E.IsUnramifiedAtFinitePlace v)
    (hfrob : E.frobeniusAt v = 1) :
    (Ideal.primesOver v.asIdeal
      (NumberField.RingOfIntegers L)).ncard =
        Module.finrank (PrimeCyclotomicField p) L := by
  letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
  let Q := (E.primeAbove v).1
  letI : Q.IsPrime := (E.primeAbove v).2.1
  letI : Q.LiesOver v.asIdeal := (E.primeAbove v).2.2
  letI : Algebra.IsUnramifiedAt
      (NumberField.RingOfIntegers (PrimeCyclotomicField p)) Q :=
    hunramified Q inferInstance inferInstance
  have hstabilizer :
      MulAction.stabilizer Gal(L/PrimeCyclotomicField p) Q = ⊥ := by
    rw [← NumberTheory.UnramifiedArtin.stabilizer_eq_zpowers_of_isArithFrobAt
      v.asIdeal Q (E.frobeniusAt_isArithFrobAt v), hfrob]
    simp
  have horbit :
      MulAction.orbit Gal(L/PrimeCyclotomicField p) Q =
        Ideal.primesOver v.asIdeal (NumberField.RingOfIntegers L) :=
    Algebra.IsInvariant.orbit_eq_primesOver
      (NumberField.RingOfIntegers (PrimeCyclotomicField p))
      (NumberField.RingOfIntegers L)
      Gal(L/PrimeCyclotomicField p) v.asIdeal Q
  have hkey :
      (Ideal.primesOver v.asIdeal
          (NumberField.RingOfIntegers L)).ncard *
        Nat.card (MulAction.stabilizer
          Gal(L/PrimeCyclotomicField p) Q) =
        Module.finrank (PrimeCyclotomicField p) L := by
    rw [← Nat.card_coe_set_eq, ← horbit, ← Nat.card_prod,
      Nat.card_congr
        (MulAction.orbitProdStabilizerEquivGroup
          Gal(L/PrimeCyclotomicField p) Q),
      IsGalois.card_aut_eq_finrank]
  rw [hstabilizer] at hkey
  simpa using hkey

/-- The unique prime above `p` splits completely in an everywhere-unramified
inverse-cyclotomic extension. This is stronger than merely saying that the
prime is unramified: the inverse-character action forces its decomposition
Frobenius to be trivial. -/
theorem cyclotomicPrime_splitsCompletely
    (hp : 2 < p)
    (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces) :
    (Ideal.primesOver (cyclotomicPrime p).asIdeal
      (NumberField.RingOfIntegers L)).ncard =
        Module.finrank (PrimeCyclotomicField p) L := by
  letI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI : NeZero (p : ℚ) :=
    ⟨Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero⟩
  letI : IsCyclotomicExtension {p} ℚ (PrimeCyclotomicField p) :=
    CyclotomicField.isCyclotomicExtension p ℚ
  letI : Fact (2 < p) := ⟨hp⟩
  let e : Gal(PrimeCyclotomicField p/ℚ) ≃* (ZMod p)ˣ :=
    IsCyclotomicExtension.autEquivPow (PrimeCyclotomicField p)
      (Polynomial.cyclotomic.irreducible_rat (NeZero.pos p))
  let sigma : Gal(PrimeCyclotomicField p/ℚ) := e.symm (-1)
  have hcharacter : inverseCharacter p sigma = (-1 : (ZMod p)ˣ) := by
    change (e sigma)⁻¹ = -1
    rw [e.apply_symm_apply]
    simp
  have hsigma : (inverseCharacter p sigma : ZMod p) ≠ 1 := by
    rw [hcharacter]
    exact ZMod.neg_one_ne_one
  have hartin : E.artinSymbol (cyclotomicPrime p) = 1 :=
    E.artinSymbol_eq_one_of_fixed hunramified sigma hsigma
      (cyclotomicPrime p) (mapFinitePrime_cyclotomicPrime p sigma)
  have hfrob : E.frobeniusAt (cyclotomicPrime p) = 1 := by
    apply E.galEquiv.injective
    simpa only [artinSymbol, map_one] using hartin
  exact E.ncard_primesOver_eq_finrank_of_frobeniusAt_eq_one
    (cyclotomicPrime p) (hunramified (cyclotomicPrime p)) hfrob

/-- The weak global arithmetic input needed in the prime-degree case: at
least one finite prime does not split completely. -/
def HasNonSplitFinitePrime (_E : InverseExtension p L) : Prop :=
  ∃ v : FinitePrime (PrimeCyclotomicField p),
    (Ideal.primesOver v.asIdeal
      (NumberField.RingOfIntegers L)).ncard ≠
        Module.finrank (PrimeCyclotomicField p) L

/-- Every inverse extension has a nonsplit finite prime. The proof is the
Dedekind-zeta pole argument in `NumberTheory.WeakChebotarev`; the unramifiedness
hypothesis is retained here because this is the exact interface used by the
Artin-symbol construction. -/
theorem hasNonSplitFinitePrime
    (E : InverseExtension p L)
    (_hunramified : E.IsUnramifiedAtFinitePlaces) :
    E.HasNonSplitFinitePrime := by
  letI : IsGalois (PrimeCyclotomicField p) L := E.isGalois
  apply NumberTheory.WeakChebotarev.exists_nonSplitFinitePrime
  have hfinrank : Module.finrank (PrimeCyclotomicField p) L = p := by
    calc
      Module.finrank (PrimeCyclotomicField p) L =
          Nat.card Gal(L/PrimeCyclotomicField p) :=
        (IsGalois.card_aut_eq_finrank (PrimeCyclotomicField p) L).symm
      _ = Nat.card (Multiplicative (ZMod p)) :=
        Nat.card_congr E.galEquiv.toEquiv
      _ = p := by simp
  rw [hfinrank]
  exact (Fact.out : p.Prime).one_lt

/-- For a relative Galois group of prime order, one nonsplit unramified finite
prime already makes the Frobenius symbols generate the whole group. -/
theorem frobeniusSymbolsGenerate_of_hasNonSplitFinitePrime
    (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (hnonsplit : E.HasNonSplitFinitePrime) :
    E.FrobeniusSymbolsGenerate := by
  obtain ⟨v, hv⟩ := hnonsplit
  have hfrob : E.frobeniusAt v ≠ 1 := fun h =>
    hv (E.ncard_primesOver_eq_finrank_of_frobeniusAt_eq_one
      v (hunramified v) h)
  have hartin : E.artinSymbol v ≠ 1 :=
    (map_ne_one_iff E.galEquiv E.galEquiv.injective).mpr hfrob
  have hcard : Nat.card (Multiplicative (ZMod p)) = p := by simp
  have hzp : Subgroup.zpowers (E.artinSymbol v) = ⊤ :=
    zpowers_eq_top_of_prime_card hcard hartin
  apply top_unique
  rw [← hzp]
  exact Subgroup.zpowers_le_of_mem
    (Subgroup.subset_closure (Set.mem_range_self v))

/-- Once principal reciprocity is known, the ideal Artin map descends to the
ordinary ideal class group. -/
noncomputable def classGroupArtin (E : InverseExtension p L)
    (hprincipal : E.SatisfiesPrincipalReciprocity) :
    ClassGroup
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)) →*
      Multiplicative (ZMod p) :=
  NumberTheory.UnramifiedArtin.classGroupHom
    (NumberField.RingOfIntegers (PrimeCyclotomicField p))
    (PrimeCyclotomicField p) E.fractionalArtin hprincipal

/-- The class-group Artin map agrees with the fractional-ideal Artin map on a
represented ideal class. -/
theorem classGroupArtin_mk (E : InverseExtension p L)
    (hprincipal : E.SatisfiesPrincipalReciprocity)
    (I : (FractionalIdeal
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (PrimeCyclotomicField p))ˣ) :
    E.classGroupArtin hprincipal
        (ClassGroup.mk (PrimeCyclotomicField p) I) =
      E.fractionalArtin I :=
  NumberTheory.UnramifiedArtin.classGroupHom_mk
    (NumberField.RingOfIntegers (PrimeCyclotomicField p))
    (PrimeCyclotomicField p) E.fractionalArtin hprincipal I

/-- The descended class-group Artin map is onto exactly when the finite-prime
Frobenius symbols generate the cyclic target. -/
theorem classGroupArtin_surjective_iff (E : InverseExtension p L)
    (hprincipal : E.SatisfiesPrincipalReciprocity) :
    Function.Surjective (E.classGroupArtin hprincipal) ↔
      E.FrobeniusSymbolsGenerate :=
  NumberTheory.UnramifiedArtin.classGroupHom_surjective_iff_generators
    (NumberField.RingOfIntegers (PrimeCyclotomicField p))
    (PrimeCyclotomicField p) E.artinSymbol hprincipal

/-- Frobenius generation makes the descended class-group Artin map
surjective. -/
theorem classGroupArtin_surjective (E : InverseExtension p L)
    (hprincipal : E.SatisfiesPrincipalReciprocity)
    (hgenerate : E.FrobeniusSymbolsGenerate) :
    Function.Surjective (E.classGroupArtin hprincipal) :=
  (E.classGroupArtin_surjective_iff hprincipal).mpr hgenerate

end InverseExtension

/-- The strongest unconditional finite-place bridge currently supported by
the pinned library: local ramification indices equal to one imply
unramifiedness at every finite place. -/
theorem unramifiedAtFinitePlaces
    {p : ℕ} [Fact p.Prime]
    {L : Type u} [Field L] [NumberField L] [Algebra (PrimeCyclotomicField p) L]
    [IsScalarTower ℚ (PrimeCyclotomicField p) L]
    (E : InverseExtension p L) (h : E.RamificationIndexOneAtFinitePlaces) :
    E.IsUnramifiedAtFinitePlaces :=
  E.isUnramifiedAtFinitePlaces_iff_ramificationIndexOne.mpr h

/-- The action of a cyclotomic Galois automorphism on the class group of the
ring of integers. -/
noncomputable def classGroupAutomorphism (p : ℕ)
    (σ : Gal(PrimeCyclotomicField p/ℚ)) :
    ClassGroup (NumberField.RingOfIntegers (PrimeCyclotomicField p)) ≃*
      ClassGroup (NumberField.RingOfIntegers (PrimeCyclotomicField p)) :=
  NumberTheory.UnramifiedArtin.classGroupEquiv
    (NumberField.RingOfIntegers (PrimeCyclotomicField p))
    (PrimeCyclotomicField p) (InverseExtension.baseIntegerEquiv σ)

/-- Formula for the cyclotomic action on an ideal-class representative. -/
theorem classGroupAutomorphism_mk {p : ℕ}
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (I : (FractionalIdeal
      (nonZeroDivisors
        (NumberField.RingOfIntegers (PrimeCyclotomicField p)))
      (PrimeCyclotomicField p))ˣ) :
    classGroupAutomorphism p σ (ClassGroup.mk (PrimeCyclotomicField p) I) =
      ClassGroup.mk (PrimeCyclotomicField p)
        (InverseExtension.fractionalIdealEquiv σ I) :=
  NumberTheory.UnramifiedArtin.classGroupEquiv_mk
    (NumberField.RingOfIntegers (PrimeCyclotomicField p))
    (PrimeCyclotomicField p) (InverseExtension.baseIntegerEquiv σ) I

namespace InverseExtension

/-- The descended class-group Artin map is inverse-cyclotomic equivariant. -/
theorem classGroupArtin_equivariant
    {p : ℕ} [Fact p.Prime]
    {L : Type u} [Field L] [NumberField L]
    [Algebra (PrimeCyclotomicField p) L]
    [IsScalarTower ℚ (PrimeCyclotomicField p) L]
    (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (hprincipal : E.SatisfiesPrincipalReciprocity)
    (σ : Gal(PrimeCyclotomicField p/ℚ))
    (c : ClassGroup
      (NumberField.RingOfIntegers (PrimeCyclotomicField p))) :
    E.classGroupArtin hprincipal (classGroupAutomorphism p σ c) =
      inverseCharacterAction σ (E.classGroupArtin hprincipal c) := by
  refine ClassGroup.induction
    (R := NumberField.RingOfIntegers (PrimeCyclotomicField p))
    (PrimeCyclotomicField p) ?_ c
  intro I
  rw [classGroupAutomorphism_mk, E.classGroupArtin_mk,
    E.classGroupArtin_mk, E.fractionalArtin_equivariant hunramified]

end InverseExtension

/-- The quotient supplied by the unramified abelian correspondence, before
recording its Galois eigenspace. -/
structure UnramifiedClassGroupQuotient (p : ℕ) [Fact p.Prime] where
  /-- The cyclic order-`p` quotient map from the ideal class group. -/
  quotient : ClassGroup (NumberField.RingOfIntegers (PrimeCyclotomicField p)) →*
    Multiplicative (ZMod p)
  /-- The quotient map is onto. -/
  surjective : Function.Surjective quotient

/-- The assertion that a class-group quotient transforms through the inverse
cyclotomic character. -/
def UnramifiedClassGroupQuotient.IsInverseCyclotomic
    {p : ℕ} [Fact p.Prime] (Q : UnramifiedClassGroupQuotient p) : Prop :=
  ∀ (σ : Gal(PrimeCyclotomicField p/ℚ))
    (c : ClassGroup (NumberField.RingOfIntegers (PrimeCyclotomicField p))),
    Multiplicative.toAdd (Q.quotient (classGroupAutomorphism p σ c)) =
      (inverseCharacter p σ : ZMod p) *
        Multiplicative.toAdd (Q.quotient c)

/-- A nonzero inverse-cyclotomic quotient of the ideal class group.  Its
existence is the precise class-group obstruction forced by a cyclic
everywhere-unramified inverse-cyclotomic extension. -/
structure InverseClassGroupQuotient (p : ℕ) [Fact p.Prime]
    extends UnramifiedClassGroupQuotient p where
  /-- The quotient transforms through the inverse cyclotomic character. -/
  inverseCyclotomic : toUnramifiedClassGroupQuotient.IsInverseCyclotomic

namespace InverseExtension

/-- Principal reciprocity and finite-prime Frobenius generation construct the
required surjective inverse-cyclotomic quotient of the ordinary ideal class
group. -/
noncomputable def inverseClassGroupQuotient
    {p : ℕ} [Fact p.Prime]
    {L : Type u} [Field L] [NumberField L]
    [Algebra (PrimeCyclotomicField p) L]
    [IsScalarTower ℚ (PrimeCyclotomicField p) L]
    (E : InverseExtension p L)
    (hunramified : E.IsUnramifiedAtFinitePlaces)
    (hprincipal : E.SatisfiesPrincipalReciprocity)
    (hgenerate : E.FrobeniusSymbolsGenerate) :
    InverseClassGroupQuotient p where
  quotient := E.classGroupArtin hprincipal
  surjective := E.classGroupArtin_surjective hprincipal hgenerate
  inverseCyclotomic σ c := by
    rw [E.classGroupArtin_equivariant hunramified hprincipal σ c]
    rfl

end InverseExtension

/-- The missing class-field-theory statement: over a totally complex base,
every everywhere-unramified inverse-cyclotomic extension produces the
corresponding ordinary ideal-class-group quotient. -/
def ClassFieldTheoryPrinciple (p : ℕ) [Fact p.Prime] : Prop :=
  NumberField.IsTotallyComplex (PrimeCyclotomicField p) →
    ∀ {L : Type u} [Field L] [NumberField L] [Algebra (PrimeCyclotomicField p) L]
    [IsScalarTower ℚ (PrimeCyclotomicField p) L] (E : InverseExtension p L),
    E.IsUnramifiedAtFinitePlaces → Nonempty (InverseClassGroupQuotient p)

/-- The exact conductor-one reciprocity input: over the totally complex
cyclotomic base, the finite-prime Artin product kills every principal
fractional ideal. -/
def PrincipalReciprocityPrinciple (p : ℕ) [Fact p.Prime] : Prop :=
  NumberField.IsTotallyComplex (PrimeCyclotomicField p) →
    ∀ {L : Type u} [Field L] [NumberField L]
    [Algebra (PrimeCyclotomicField p) L]
    [IsScalarTower ℚ (PrimeCyclotomicField p) L]
    (E : InverseExtension p L),
    E.IsUnramifiedAtFinitePlaces → E.SatisfiesPrincipalReciprocity

/-- The exact weak-Chebotarev input in prime degree: an everywhere
finite-place-unramified inverse extension has at least one finite prime that
does not split completely. -/
def NonSplitFinitePrimePrinciple (p : ℕ) [Fact p.Prime] : Prop :=
  ∀ {L : Type u} [Field L] [NumberField L]
    [Algebra (PrimeCyclotomicField p) L]
    [IsScalarTower ℚ (PrimeCyclotomicField p) L]
    (E : InverseExtension p L),
    E.IsUnramifiedAtFinitePlaces → E.HasNonSplitFinitePrime

/-- The weak nonsplitting input is a theorem: the zeta function of a
nontrivial number-field extension cannot dominate the square of the base zeta
function near its simple pole. -/
theorem nonSplitFinitePrimePrinciple
    (p : ℕ) [Fact p.Prime] :
    NonSplitFinitePrimePrinciple.{u} p := by
  intro L _ _ _ _ E hunramified
  exact E.hasNonSplitFinitePrime hunramified

/-- Principal reciprocity implies the required unramified inverse-character
class-group quotient. Finite-prime nonsplitting, ideal-theoretic descent,
surjectivity, and Galois equivariance in this assembly are all checked. -/
theorem classFieldTheoryPrinciple_of_principalReciprocity
    {p : ℕ} [Fact p.Prime]
    (hprincipal : PrincipalReciprocityPrinciple.{u} p) :
    ClassFieldTheoryPrinciple.{u} p := by
  intro hcomplex L _ _ _ _ E hunramified
  exact ⟨E.inverseClassGroupQuotient hunramified
    (hprincipal hcomplex E hunramified)
    (E.frobeniusSymbolsGenerate_of_hasNonSplitFinitePrime
      hunramified (E.hasNonSplitFinitePrime hunramified))⟩

/-- If global reciprocity produces the class-group quotient and the relevant
inverse-cyclotomic quotient is known not to exist, then no such extension can
be everywhere unramified. -/
theorem noEverywhereUnramified
    {p : ℕ} [Fact p.Prime]
    (hp : 2 < p)
    (hclassField : ClassFieldTheoryPrinciple.{u} p)
    (hclassGroup : ¬ Nonempty (InverseClassGroupQuotient p))
    {L : Type u} [Field L] [NumberField L] [Algebra (PrimeCyclotomicField p) L]
    [IsScalarTower ℚ (PrimeCyclotomicField p) L] (E : InverseExtension p L) :
    ¬ E.IsUnramifiedAtFinitePlaces := by
  intro hunramified
  exact hclassGroup
    (hclassField (primeCyclotomicField_isTotallyComplex hp) E hunramified)

end NumberTheory.CyclotomicCharacter
