/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenCuspClassArithmetic
import Mathlib.Algebra.BigOperators.Finsupp.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum

/-!
# The universal cusp-relation group for `X₁(13)`

This file computes the abelian group presented by the five formal cusp
differences `D`, `A`, `Abar`, `B`, and `C`, modulo the five relations used in
`XOneThirteenCuspClassArithmetic`.  It is a universal relation group: no claim
is made here that it is the full divisor-class group of `X₁(13)`.

The presentation is implemented as a quotient of the free abelian group
`Fin 5 →₀ ℤ`.  Explicit mutually inverse homomorphisms identify the quotient
with `ZMod 19`; under this identification the five generators map to
`1, 6, 14, 16, 4`.
-/

namespace MazurTorsion.XOneThirteenUniversalCuspRelationGroup

open MazurTorsion.XOneThirteenCuspClassArithmetic

noncomputable section

/-- Indices for the formal generators `D`, `A`, `Abar`, `B`, and `C`, in that
order. -/
abbrev CuspGenerator := Fin 5

/-- The free abelian group on the five formal cusp differences. -/
abbrev FreeCuspGroup := CuspGenerator →₀ ℤ

/-- A basis vector in the free cusp group. -/
def freeGenerator (i : CuspGenerator) : FreeCuspGroup :=
  Finsupp.single i 1

def freeD : FreeCuspGroup := freeGenerator 0
def freeA : FreeCuspGroup := freeGenerator 1
def freeAbar : FreeCuspGroup := freeGenerator 2
def freeB : FreeCuspGroup := freeGenerator 3
def freeC : FreeCuspGroup := freeGenerator 4

/-- The five rows of the integral relation matrix. -/
def relationVector : Fin 5 → FreeCuspGroup :=
  ![freeA + freeB - 3 • freeD,
    3 • freeA + freeC - 3 • freeD,
    freeA + 4 • freeC - 3 • freeD,
    freeA + freeAbar - freeD,
    freeB + freeC - freeD]

/-- The subgroup generated by the five formal principal-divisor relations. -/
def relationSubgroup : AddSubgroup FreeCuspGroup :=
  AddSubgroup.closure (Set.range relationVector)

/-- The universal abelian group subject only to the five cusp relations. -/
abbrev UniversalCuspRelationGroup :=
  FreeCuspGroup ⧸ relationSubgroup

/-- The class of a free generator in the universal relation group. -/
def generatorClass (i : CuspGenerator) : UniversalCuspRelationGroup :=
  (freeGenerator i : UniversalCuspRelationGroup)

def D : UniversalCuspRelationGroup := generatorClass 0
def A : UniversalCuspRelationGroup := generatorClass 1
def Abar : UniversalCuspRelationGroup := generatorClass 2
def B : UniversalCuspRelationGroup := generatorClass 3
def C : UniversalCuspRelationGroup := generatorClass 4

theorem relationVector_mem (i : Fin 5) :
    relationVector i ∈ relationSubgroup :=
  AddSubgroup.subset_closure ⟨i, rfl⟩

/-- The quotient generators satisfy exactly the five defining relations. -/
theorem universalCertificate : Certificate UniversalCuspRelationGroup D A Abar B C := by
  constructor
  · change ((freeA + freeB : FreeCuspGroup) : UniversalCuspRelationGroup) =
      ((3 • freeD : FreeCuspGroup) : UniversalCuspRelationGroup)
    rw [QuotientAddGroup.eq_iff_sub_mem]
    simpa [relationVector] using relationVector_mem 0
  · change ((3 • freeA + freeC : FreeCuspGroup) : UniversalCuspRelationGroup) =
      ((3 • freeD : FreeCuspGroup) : UniversalCuspRelationGroup)
    rw [QuotientAddGroup.eq_iff_sub_mem]
    simpa [relationVector] using relationVector_mem 1
  · change ((freeA + 4 • freeC : FreeCuspGroup) : UniversalCuspRelationGroup) =
      ((3 • freeD : FreeCuspGroup) : UniversalCuspRelationGroup)
    rw [QuotientAddGroup.eq_iff_sub_mem]
    simpa [relationVector] using relationVector_mem 2
  · change ((freeA + freeAbar : FreeCuspGroup) : UniversalCuspRelationGroup) =
      (freeD : UniversalCuspRelationGroup)
    rw [QuotientAddGroup.eq_iff_sub_mem]
    simpa [relationVector] using relationVector_mem 3
  · change ((freeB + freeC : FreeCuspGroup) : UniversalCuspRelationGroup) =
      (freeD : UniversalCuspRelationGroup)
    rw [QuotientAddGroup.eq_iff_sub_mem]
    simpa [relationVector] using relationVector_mem 4

/-- Natural-number representatives of the five classes in the cyclic presentation. -/
def generatorCoefficient : CuspGenerator → ℕ :=
  ![1, 6, 14, 16, 4]

@[simp] theorem generatorCoefficient_zero : generatorCoefficient 0 = 1 := by decide
@[simp] theorem generatorCoefficient_one : generatorCoefficient 1 = 6 := by decide
@[simp] theorem generatorCoefficient_two : generatorCoefficient 2 = 14 := by decide
@[simp] theorem generatorCoefficient_three : generatorCoefficient 3 = 16 := by decide
@[simp] theorem generatorCoefficient_four : generatorCoefficient 4 = 4 := by decide

/-- The value of each formal generator in `ZMod 19`. -/
def generatorWeight (i : CuspGenerator) : ZMod 19 :=
  (generatorCoefficient i : ZMod 19)

/-- The homomorphism from the free group determined by the five displayed
weights. -/
def freeExponentMap : FreeCuspGroup →+ ZMod 19 :=
  Finsupp.liftAddHom fun i => zmultiplesHom (ZMod 19) (generatorWeight i)

@[simp] theorem freeExponentMap_freeGenerator (i : CuspGenerator) :
    freeExponentMap (freeGenerator i) = generatorWeight i := by
  simp [freeExponentMap, freeGenerator]

@[simp] theorem freeExponentMap_single (i : CuspGenerator) (z : ℤ) :
    freeExponentMap (Finsupp.single i z) = z • generatorWeight i := by
  simp [freeExponentMap]

@[simp]
theorem freeExponentMap_relationVector (i : Fin 5) :
    freeExponentMap (relationVector i) = 0 := by
  fin_cases i <;>
    norm_num [relationVector, generatorWeight,
      freeD, freeA, freeAbar, freeB, freeC] <;>
    exact ZMod.natCast_self 19

theorem relationSubgroup_le_kernel :
    relationSubgroup ≤ freeExponentMap.ker := by
  rw [relationSubgroup, AddSubgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  change freeExponentMap (relationVector i) = 0
  exact freeExponentMap_relationVector i

/-- Evaluation of the presentation in `ZMod 19`. -/
def quotientToZMod : UniversalCuspRelationGroup →+ ZMod 19 :=
  QuotientAddGroup.lift relationSubgroup freeExponentMap relationSubgroup_le_kernel

@[simp] theorem quotientToZMod_generatorClass (i : CuspGenerator) :
    quotientToZMod (generatorClass i) = generatorWeight i := by
  simp [quotientToZMod, generatorClass, freeExponentMap, freeGenerator]

@[simp] theorem quotientToZMod_D : quotientToZMod D = 1 := by
  norm_num [D, generatorWeight, generatorCoefficient]

@[simp] theorem quotientToZMod_A : quotientToZMod A = 6 := by
  norm_num [A, generatorWeight, generatorCoefficient]

@[simp] theorem quotientToZMod_Abar : quotientToZMod Abar = 14 := by
  rw [Abar, quotientToZMod_generatorClass]
  decide

@[simp] theorem quotientToZMod_B : quotientToZMod B = 16 := by
  rw [B, quotientToZMod_generatorClass]
  decide

@[simp] theorem quotientToZMod_C : quotientToZMod C = 4 := by
  rw [C, quotientToZMod_generatorClass]
  decide

/-- The inverse cyclic-generator map, sending `1 : ZMod 19` to `D`. -/
def zmodToQuotient : ZMod 19 →+ UniversalCuspRelationGroup :=
  ZMod.lift 19
    ⟨
      { toFun := fun z : ℤ => z • D
        map_zero' := zero_zsmul D
        map_add' := fun a b => add_zsmul D a b },
      by
        change ((19 : ℕ) : ℤ) • D = 0
        simpa only [natCast_zsmul] using universalCertificate.nineteen_nsmul_D⟩

@[simp] theorem zmodToQuotient_intCast (z : ℤ) :
    zmodToQuotient (z : ZMod 19) = z • D := by
  simp [zmodToQuotient]

@[simp] theorem zmodToQuotient_one : zmodToQuotient 1 = D := by
  simpa using zmodToQuotient_intCast 1

@[simp] theorem zmodToQuotient_natCast (n : ℕ) :
    zmodToQuotient (n : ZMod 19) = n • D := by
  simpa using zmodToQuotient_intCast (n : ℤ)

theorem generatorClass_eq (i : CuspGenerator) :
    generatorClass i = generatorCoefficient i • D := by
  fin_cases i
  · simp [generatorClass, generatorCoefficient, D]
  · simpa [generatorClass, generatorCoefficient, A] using universalCertificate.A_eq
  · simpa [generatorClass, generatorCoefficient, Abar] using universalCertificate.Abar_eq
  · simpa [generatorClass, generatorCoefficient, B] using universalCertificate.B_eq
  · simpa [generatorClass, generatorCoefficient, C] using universalCertificate.C_eq

@[simp] theorem zmodToQuotient_generatorWeight (i : CuspGenerator) :
    zmodToQuotient (generatorWeight i) = generatorClass i := by
  rw [generatorWeight, zmodToQuotient_natCast, ← generatorClass_eq]

private theorem freeGenerator_zsmul (i : CuspGenerator) (z : ℤ) :
    z • freeGenerator i = Finsupp.single i z := by
  ext j
  by_cases h : i = j
  · subst j
    simp [freeGenerator]
  · simp [freeGenerator, h]

private theorem inverse_on_single (i : CuspGenerator) (z : ℤ) :
    zmodToQuotient (freeExponentMap (Finsupp.single i z)) =
      ((Finsupp.single i z : FreeCuspGroup) : UniversalCuspRelationGroup) := by
  calc
    zmodToQuotient (freeExponentMap (Finsupp.single i z)) =
        z • zmodToQuotient (generatorWeight i) := by
          rw [freeExponentMap_single, map_zsmul]
    _ = z • generatorClass i := by rw [zmodToQuotient_generatorWeight]
    _ = ((z • freeGenerator i : FreeCuspGroup) : UniversalCuspRelationGroup) := by
      simp [generatorClass]
    _ = ((Finsupp.single i z : FreeCuspGroup) : UniversalCuspRelationGroup) := by
      rw [freeGenerator_zsmul]

private theorem inverse_on_free_group :
    zmodToQuotient.comp freeExponentMap =
      QuotientAddGroup.mk' relationSubgroup := by
  apply (Finsupp.liftAddHom (α := CuspGenerator)
    (M := ℤ) (N := UniversalCuspRelationGroup)).symm.injective
  funext i
  apply AddMonoidHom.ext
  intro z
  exact inverse_on_single i z

theorem zmodToQuotient_quotientToZMod (q : UniversalCuspRelationGroup) :
    zmodToQuotient (quotientToZMod q) = q := by
  refine Quotient.inductionOn' q fun f => ?_
  simpa [quotientToZMod] using
    DFunLike.congr_fun inverse_on_free_group f

theorem quotientToZMod_zmodToQuotient (z : ZMod 19) :
    quotientToZMod (zmodToQuotient z) = z := by
  obtain ⟨k, rfl⟩ := ZMod.intCast_surjective z
  simp

/-- The actual computation of the five-generator, five-relation abelian
presentation. -/
def universalCuspRelationGroupEquivZMod :
    UniversalCuspRelationGroup ≃+ ZMod 19 where
  toFun := quotientToZMod
  invFun := zmodToQuotient
  left_inv := zmodToQuotient_quotientToZMod
  right_inv := quotientToZMod_zmodToQuotient
  map_add' := quotientToZMod.map_add

@[simp] theorem universalCuspRelationGroupEquivZMod_D :
    universalCuspRelationGroupEquivZMod D = 1 := quotientToZMod_D

@[simp] theorem universalCuspRelationGroupEquivZMod_A :
    universalCuspRelationGroupEquivZMod A = 6 := quotientToZMod_A

@[simp] theorem universalCuspRelationGroupEquivZMod_Abar :
    universalCuspRelationGroupEquivZMod Abar = 14 := quotientToZMod_Abar

@[simp] theorem universalCuspRelationGroupEquivZMod_B :
    universalCuspRelationGroupEquivZMod B = 16 := quotientToZMod_B

@[simp] theorem universalCuspRelationGroupEquivZMod_C :
    universalCuspRelationGroupEquivZMod C = 4 := quotientToZMod_C

end

end MazurTorsion.XOneThirteenUniversalCuspRelationGroup
