/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenFiniteField
import Mathlib.RingTheory.Polynomial.RationalRoot

/-!
# Explicit descent interfaces for `X₁(13)`

The order-thirteen parameter curve is the genus-two sextic

`y² = x⁶ + 2x⁵ + x⁴ + 2x³ + 6x² + 4x + 1`.

This file records algebraic inputs to the classical Mazur--Tate
`19`-isogeny descent which can be checked without a genus-two Jacobian
implementation.

The rational transformation

`(x,y) ↦ (-1/(x+1), y/(x+1)³)`

preserves the sextic and has cube equal to the hyperelliptic involution.
The quotient by its order-three square is the conic

`v² = u² + 2u + 5`.

We parameterize this conic, identify the cyclic cubic fiber, and
homogenize its square discriminant.  The discriminant factor is an
explicit norm in the quadratic order generated by a primitive sixth
root.  In that order, `19=(3+2ρ)(5-2ρ)`; coordinate divisibility
criteria for both primes above `19` are proved below.

We also give an explicit polynomial Pell identity of degrees `19` and
`16`.  It is the algebraic function-field certificate underlying the
order-`19` difference of the two rational points at infinity.

The file does not construct the Jacobian, divisor classes, the induced
endomorphism `π`, fppf cohomology, or the Abel--Jacobi embedding.
Consequently it does not assert rank zero or a classification of
rational points.
-/

namespace MazurTorsion.XOneThirteenDescent

open MazurTorsion.Kubert

private lemma add_one_ne_zero {x : ℚ} (hx : x ≠ -1) :
    x + 1 ≠ 0 := by
  intro hzero
  apply hx
  linarith

/-! ## The rational order-six symmetry -/

/-- The abscissa of the diamond-operator symmetry. -/
def diamondX (x : ℚ) : ℚ :=
  -1 / (x + 1)

/-- The corresponding ordinate transformation. -/
def diamondY (x y : ℚ) : ℚ :=
  y / (x + 1) ^ 3

/-- Covariance of the sextic under the fractional-linear abscissa
transformation. -/
theorem diamond_sextic_covariance
    (x : ℚ) (hxneg : x ≠ -1) :
    (x + 1) ^ 6 *
        orderThirteenHyperellipticPolynomial (diamondX x) =
      orderThirteenHyperellipticPolynomial x := by
  have hden : x + 1 ≠ 0 := by
    exact add_one_ne_zero hxneg
  simp only [diamondX, orderThirteenHyperellipticPolynomial]
  field_simp [hden]
  ring

/-- The diamond operator preserves the affine sextic away from the
chart boundary `x=-1`. -/
theorem diamond_preserves_curve
    (x y : ℚ) (hxneg : x ≠ -1)
    (hcurve :
      y ^ 2 = orderThirteenHyperellipticPolynomial x) :
    diamondY x y ^ 2 =
      orderThirteenHyperellipticPolynomial (diamondX x) := by
  have hden : x + 1 ≠ 0 := by
    exact add_one_ne_zero hxneg
  have hcov := diamond_sextic_covariance x hxneg
  simp only [diamondY]
  field_simp [hden]
  rw [hcurve]
  exact hcov.symm

/-- The second abscissa iterate in denominator-safe form. -/
theorem diamondX_sq
    (x : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    diamondX (diamondX x) = -(x + 1) / x := by
  have hden : x + 1 ≠ 0 := by
    exact add_one_ne_zero hxneg
  simp only [diamondX]
  field_simp [hden, hx0]
  ring

/-- The fractional-linear abscissa has order three. -/
theorem diamondX_cube
    (x : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    diamondX (diamondX (diamondX x)) = x := by
  rw [diamondX_sq x hx0 hxneg]
  simp only [diamondX]
  field_simp [hx0]
  ring

/-- The second ordinate iterate in denominator-safe form. -/
theorem diamondY_sq
    (x y : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    diamondY (diamondX x) (diamondY x y) = y / x ^ 3 := by
  have hden : x + 1 ≠ 0 := by
    exact add_one_ne_zero hxneg
  simp only [diamondY, diamondX]
  field_simp [hden, hx0]
  ring

/-- The cube of the lifted symmetry is the hyperelliptic involution. -/
theorem diamondY_cube
    (x y : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    diamondY (diamondX (diamondX x))
        (diamondY (diamondX x) (diamondY x y)) = -y := by
  rw [diamondX_sq x hx0 hxneg, diamondY_sq x y hx0 hxneg]
  simp only [diamondY]
  field_simp [hx0]
  ring

/-- At a point with nonzero ordinate, the third iterate is not the
identity; together with the preceding formulas this certifies the
order-six lift. -/
theorem diamondY_cube_ne
    (x y : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) (hy : y ≠ 0) :
    diamondY (diamondX (diamondX x))
        (diamondY (diamondX x) (diamondY x y)) ≠ y := by
  rw [diamondY_cube x y hx0 hxneg]
  intro h
  apply hy
  linarith

/-! ## Quotient conic and cyclic cubic fiber -/

/-- The trace invariant of the three-element abscissa orbit. -/
def quotientU (x : ℚ) : ℚ :=
  (x ^ 3 - 3 * x - 1) / (x * (x + 1))

/-- The ordinate invariant for the order-three square. -/
def quotientV (x y : ℚ) : ℚ :=
  y / (x * (x + 1))

/-- The abscissa invariant is fixed by the order-six symmetry. -/
theorem quotientU_diamond
    (x : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    quotientU (diamondX x) = quotientU x := by
  have hden : x + 1 ≠ 0 := by
    exact add_one_ne_zero hxneg
  simp only [quotientU, diamondX]
  field_simp [hden, hx0]
  ring

/-- The ordinate invariant changes sign under the order-six lift and is
therefore fixed by its square. -/
theorem quotientV_diamond
    (x y : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    quotientV (diamondX x) (diamondY x y) =
      -quotientV x y := by
  have hden : x + 1 ≠ 0 := by
    exact add_one_ne_zero hxneg
  simp only [quotientV, diamondX, diamondY]
  field_simp [hden, hx0]
  ring

/-- On the sextic, the two invariant functions lie on a rational conic. -/
theorem quotient_conic_equation
    (x y : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1)
    (hcurve :
      y ^ 2 = orderThirteenHyperellipticPolynomial x) :
    quotientV x y ^ 2 =
      quotientU x ^ 2 + 2 * quotientU x + 5 := by
  have hden : x + 1 ≠ 0 := by
    exact add_one_ne_zero hxneg
  simp only [quotientU, quotientV,
    orderThirteenHyperellipticPolynomial] at hcurve ⊢
  field_simp [hx0, hden]
  linear_combination hcurve

/-- The conic abscissa obtained from a line through `(u,v)=(-1,2)`. -/
def conicU (t : ℚ) : ℚ :=
  (t ^ 2 + 4 * t - 1) / (1 - t ^ 2)

/-- The corresponding conic ordinate. -/
def conicV (t : ℚ) : ℚ :=
  2 * (1 + t ^ 2) / (1 - t ^ 2)

/-- The displayed parametrization lies on the quotient conic. -/
theorem conic_parameter_equation
    (t : ℚ) (ht : t ^ 2 ≠ 1) :
    conicV t ^ 2 = conicU t ^ 2 + 2 * conicU t + 5 := by
  have hden : 1 - t ^ 2 ≠ 0 := sub_ne_zero.mpr (Ne.symm ht)
  simp only [conicU, conicV]
  field_simp [hden]
  ring

/-- The slope recovering the conic parameter away from `u=-1`. -/
def conicSlope (u v : ℚ) : ℚ :=
  (v - 2) / (u + 1)

private lemma conicSlope_sq_ne_one
    (u v : ℚ) (hu : u ≠ -1)
    (hconic : v ^ 2 = u ^ 2 + 2 * u + 5) :
    conicSlope u v ^ 2 ≠ 1 := by
  intro ht
  have hden : u + 1 ≠ 0 := by
    exact add_one_ne_zero hu
  have hfactor :
      (conicSlope u v - 1) * (conicSlope u v + 1) = 0 := by
    nlinarith
  rcases mul_eq_zero.mp hfactor with hpos | hneg
  · have hslope : conicSlope u v = 1 := by
      linarith
    simp only [conicSlope] at hslope
    field_simp [hden] at hslope
    apply hu
    nlinarith
  · have hslope : conicSlope u v = -1 := by
      linarith
    simp only [conicSlope] at hslope
    field_simp [hden] at hslope
    apply hu
    nlinarith

/-- The slope construction recovers both conic coordinates away from
the exceptional fiber `u=-1`. -/
theorem conic_parameter_inverse
    (u v : ℚ) (hu : u ≠ -1)
    (hconic : v ^ 2 = u ^ 2 + 2 * u + 5) :
    let t := conicSlope u v
    t ^ 2 ≠ 1 ∧ conicU t = u ∧ conicV t = v := by
  let t := conicSlope u v
  have ht : t ^ 2 ≠ 1 :=
    conicSlope_sq_ne_one u v hu hconic
  have huden : u + 1 ≠ 0 := by
    exact add_one_ne_zero hu
  have hteq : t = (v - 2) / (u + 1) := rfl
  have hraw : (u + 1) ^ 2 - (v - 2) ^ 2 ≠ 0 := by
    intro hzero
    apply ht
    rw [hteq]
    field_simp [huden]
    nlinarith
  have hU : conicU t = u := by
    simp only [conicU]
    rw [hteq]
    field_simp [huden, hraw]
    nlinarith
  have hV : conicV t = v := by
    simp only [conicV]
    rw [hteq]
    field_simp [huden, hraw]
    nlinarith
  exact ⟨ht, hU, hV⟩

/-- The exceptional conic fiber over `u=-1` consists of `v=±2`. -/
theorem conic_at_neg_one_iff (v : ℚ) :
    v ^ 2 = (-1 : ℚ) ^ 2 + 2 * (-1) + 5 ↔
      v = 2 ∨ v = -2 := by
  constructor
  · intro h
    have hfactor : (v - 2) * (v + 2) = 0 := by
      nlinarith
    rcases mul_eq_zero.mp hfactor with hpos | hneg
    · exact Or.inl (by linarith)
    · exact Or.inr (by linarith)
  · rintro (rfl | rfl) <;> norm_num

/-- Every rational affine point on the quotient conic is either one of
the two exceptional points over `u=-1` or lies in the displayed
one-parameter family. -/
theorem conic_rational_parameterization
    (u v : ℚ)
    (hconic : v ^ 2 = u ^ 2 + 2 * u + 5) :
    (u = -1 ∧ (v = 2 ∨ v = -2)) ∨
      ∃ t : ℚ,
        t ^ 2 ≠ 1 ∧ conicU t = u ∧ conicV t = v := by
  by_cases hu : u = -1
  · left
    subst u
    exact ⟨rfl, (conic_at_neg_one_iff v).mp hconic⟩
  · right
    exact ⟨conicSlope u v,
      conic_parameter_inverse u v hu hconic⟩

/-- The cyclic cubic above a quotient abscissa. -/
def fiberCubic (u z : ℚ) : ℚ :=
  z ^ 3 - u * z ^ 2 - (u + 3) * z - 1

private noncomputable def exceptionalFiberPolynomial : Polynomial ℤ :=
  Polynomial.X ^ 3 +
    Polynomial.X ^ 2 -
    Polynomial.C 2 * Polynomial.X -
    Polynomial.C 1

private lemma exceptionalFiberPolynomial_monic :
    Polynomial.Monic exceptionalFiberPolynomial := by
  unfold exceptionalFiberPolynomial
  monicity!

private lemma exceptionalFiberPolynomial_no_root_mod_two :
    ∀ z : ZMod 2, z ^ 3 + z ^ 2 - 2 * z - 1 ≠ 0 := by
  decide

/-- The exceptional quotient fiber `u=-1` has no rational abscissa. -/
theorem fiberCubic_neg_one_ne_zero (x : ℚ) :
    fiberCubic (-1) x ≠ 0 := by
  intro hx
  simp only [fiberCubic] at hx
  have hroot :
      Polynomial.aeval x exceptionalFiberPolynomial = 0 := by
    rw [Polynomial.aeval_def]
    norm_num [exceptionalFiberPolynomial]
    linear_combination hx
  obtain ⟨z, hxz, -⟩ :=
    exists_integer_of_is_root_of_monic
      exceptionalFiberPolynomial_monic hroot
  have hzrat :
      (z : ℚ) ^ 3 + (z : ℚ) ^ 2 -
          2 * (z : ℚ) - 1 = 0 := by
    have hzcast : (z : ℚ) = x := by
      simpa using hxz.symm
    rw [hzcast]
    linear_combination hx
  have hzint :
      z ^ 3 + z ^ 2 - 2 * z - 1 = 0 := by
    exact_mod_cast hzrat
  apply exceptionalFiberPolynomial_no_root_mod_two (z : ZMod 2)
  simpa using congrArg (fun n : ℤ ↦ (n : ZMod 2)) hzint

/-- The invariant abscissa of a noncuspidal point satisfies its cubic
fiber equation. -/
theorem fiberCubic_quotientU
    (x : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    fiberCubic (quotientU x) x = 0 := by
  have hden : x + 1 ≠ 0 := by
    exact add_one_ne_zero hxneg
  simp only [fiberCubic, quotientU]
  field_simp [hx0, hden]
  ring

/-- A noncuspidal rational abscissa does not lie over the exceptional
quotient value `u=-1`. -/
theorem quotientU_ne_neg_one
    (x : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    quotientU x ≠ -1 := by
  intro hu
  have hroot := fiberCubic_quotientU x hx0 hxneg
  rw [hu] at hroot
  exact fiberCubic_neg_one_ne_zero x hroot

/-- Product over the three-element abscissa orbit. -/
def orbitNorm (x z : ℚ) : ℚ :=
  (z - x) *
    (z - diamondX x) *
    (z - diamondX (diamondX x))

/-- The orbit norm is the cyclic cubic fiber polynomial. -/
theorem orbitNorm_eq_fiberCubic
    (x z : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1) :
    orbitNorm x z = fiberCubic (quotientU x) z := by
  simp only [orbitNorm]
  rw [show diamondX (diamondX x) = -(x + 1) / x by
    exact diamondX_sq x hx0 hxneg]
  have hden := add_one_ne_zero hxneg
  simp only [fiberCubic, quotientU, diamondX]
  field_simp [hx0, hden]
  ring

/-- The standard coefficient discriminant of a cubic
`a z³+b z²+c z+d`. -/
def cubicDiscriminant (a b c d : ℚ) : ℚ :=
  b ^ 2 * c ^ 2 - 4 * a * c ^ 3 - 4 * b ^ 3 * d -
    27 * a ^ 2 * d ^ 2 + 18 * a * b * c * d

/-- The cyclic cubic fiber has square discriminant. -/
theorem fiberCubic_discriminant (u : ℚ) :
    cubicDiscriminant 1 (-u) (-(u + 3)) (-1) =
      (u ^ 2 + 3 * u + 9) ^ 2 := by
  simp only [cubicDiscriminant]
  ring

/-- The conic-parameterized cubic with its denominator cleared. -/
def clearedFiber (t z : ℚ) : ℚ :=
  (1 - t ^ 2) * z ^ 3 -
    (t ^ 2 + 4 * t - 1) * z ^ 2 +
    (2 * t ^ 2 - 4 * t - 2) * z +
    (t ^ 2 - 1)

/-- Clearing the conic denominator produces `clearedFiber`. -/
theorem clearedFiber_eq_mul_fiberCubic
    (t z : ℚ) (ht : t ^ 2 ≠ 1) :
    clearedFiber t z =
      (1 - t ^ 2) * fiberCubic (conicU t) z := by
  have hden : 1 - t ^ 2 ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm ht)
  simp only [clearedFiber, fiberCubic, conicU]
  field_simp [hden]
  ring

/-- A root of the parameterized fiber is a root of the cleared cubic. -/
theorem clearedFiber_eq_zero
    (t z : ℚ) (ht : t ^ 2 ≠ 1)
    (hroot : fiberCubic (conicU t) z = 0) :
    clearedFiber t z = 0 := by
  rw [clearedFiber_eq_mul_fiberCubic t z ht, hroot, mul_zero]

/-- The square root of the cleared cubic discriminant. -/
def parameterDiscriminant (t : ℚ) : ℚ :=
  7 * t ^ 4 - 4 * t ^ 3 + 2 * t ^ 2 + 4 * t + 7

/-- The cleared cubic still has square discriminant, now with an
integral quartic square root. -/
theorem clearedFiber_discriminant (t : ℚ) :
    cubicDiscriminant
        (1 - t ^ 2)
        (-(t ^ 2 + 4 * t - 1))
        (2 * t ^ 2 - 4 * t - 2)
        (t ^ 2 - 1) =
      parameterDiscriminant t ^ 2 := by
  simp only [cubicDiscriminant, parameterDiscriminant]
  ring

/-- The unscaled discriminant factor after conic parametrization. -/
theorem fiber_discriminant_parameter_factorization
    (t : ℚ) (ht : t ^ 2 ≠ 1) :
    conicU t ^ 2 + 3 * conicU t + 9 =
      parameterDiscriminant t / (1 - t ^ 2) ^ 2 := by
  have hden : 1 - t ^ 2 ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm ht)
  simp only [conicU, parameterDiscriminant]
  field_simp [hden]
  ring

/-- Homogeneous form of the parameterized cyclic cubic. -/
def homogeneousFiber (m n z : ℚ) : ℚ :=
  (n ^ 2 - m ^ 2) * z ^ 3 -
    (m ^ 2 + 4 * m * n - n ^ 2) * z ^ 2 +
    (2 * m ^ 2 - 4 * m * n - 2 * n ^ 2) * z +
    (m ^ 2 - n ^ 2)

/-- Substitution `t=m/n` turns the cleared cubic into its homogeneous
form after multiplication by `n²`. -/
theorem homogeneousFiber_eq_den_sq_mul
    (m n z : ℚ) (hn : n ≠ 0) :
    homogeneousFiber m n z =
      n ^ 2 * clearedFiber (m / n) z := by
  simp only [homogeneousFiber, clearedFiber]
  field_simp [hn]

/-- The homogeneous quartic discriminant factor. -/
def homogeneousDiscriminant (m n : ℚ) : ℚ :=
  7 * m ^ 4 - 4 * m ^ 3 * n + 2 * m ^ 2 * n ^ 2 +
    4 * m * n ^ 3 + 7 * n ^ 4

/-- Discriminant of the homogeneous cubic. -/
theorem homogeneousFiber_discriminant (m n : ℚ) :
    cubicDiscriminant
        (n ^ 2 - m ^ 2)
        (-(m ^ 2 + 4 * m * n - n ^ 2))
        (2 * m ^ 2 - 4 * m * n - 2 * n ^ 2)
        (m ^ 2 - n ^ 2) =
      homogeneousDiscriminant m n ^ 2 := by
  simp only [cubicDiscriminant, homogeneousDiscriminant]
  ring

/-- Every noncuspidal rational point on the sextic admits an explicit
conic parameter and satisfies the cleared cyclic cubic. -/
theorem noncuspidal_curve_parameterization
    (x y : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1)
    (hcurve :
      y ^ 2 = orderThirteenHyperellipticPolynomial x) :
    ∃ t : ℚ,
      t ^ 2 ≠ 1 ∧
      conicU t = quotientU x ∧
      conicV t = quotientV x y ∧
      clearedFiber t x = 0 := by
  have hconic :=
    quotient_conic_equation x y hx0 hxneg hcurve
  have hu := quotientU_ne_neg_one x hx0 hxneg
  let t := conicSlope (quotientU x) (quotientV x y)
  obtain ⟨ht, hU, hV⟩ :=
    conic_parameter_inverse
      (quotientU x) (quotientV x y) hu hconic
  refine ⟨t, ht, hU, hV, ?_⟩
  apply clearedFiber_eq_zero t x ht
  rw [hU]
  exact fiberCubic_quotientU x hx0 hxneg

/-- The canonical numerator and denominator of the conic parameter give
primitive homogeneous integer data. -/
theorem noncuspidal_curve_primitive_parameterization
    (x y : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1)
    (hcurve :
      y ^ 2 = orderThirteenHyperellipticPolynomial x) :
    ∃ m n : ℤ,
      0 < n ∧
      IsCoprime m n ∧
      ((m : ℚ) / (n : ℚ)) ^ 2 ≠ 1 ∧
      conicU ((m : ℚ) / (n : ℚ)) = quotientU x ∧
      conicV ((m : ℚ) / (n : ℚ)) = quotientV x y ∧
      homogeneousFiber (m : ℚ) (n : ℚ) x = 0 := by
  obtain ⟨t, ht, hU, hV, hroot⟩ :=
    noncuspidal_curve_parameterization x y hx0 hxneg hcurve
  refine ⟨t.num, (t.den : ℤ), ?_, Rat.isCoprime_num_den t,
    ?_, ?_, ?_, ?_⟩
  · exact_mod_cast t.den_pos
  · simpa only [Int.cast_natCast, Rat.num_div_den] using ht
  · simpa only [Int.cast_natCast, Rat.num_div_den] using hU
  · simpa only [Int.cast_natCast, Rat.num_div_den] using hV
  · have hn : (t.den : ℚ) ≠ 0 := by
      exact_mod_cast t.den_ne_zero
    have hhom :
        homogeneousFiber (t.num : ℚ) (t.den : ℚ) x = 0 := by
      rw [homogeneousFiber_eq_den_sq_mul
        (t.num : ℚ) (t.den : ℚ) x hn, Rat.num_div_den t,
        hroot, mul_zero]
    simpa only [Int.cast_natCast] using hhom

/-! ## The split prime above `19` -/

/-- Multiplication in coordinates `a+bρ`, where `ρ²-ρ+1=0`. -/
def sixthRootMul (z w : ℤ × ℤ) : ℤ × ℤ :=
  (z.1 * w.1 - z.2 * w.2,
    z.1 * w.2 + z.2 * w.1 + z.2 * w.2)

/-- The norm in the quadratic order generated by `ρ`. -/
def sixthRootNorm (z : ℤ × ℤ) : ℤ :=
  z.1 ^ 2 + z.1 * z.2 + z.2 ^ 2

/-- The distinguished primitive sixth root in coordinates. -/
def sixthRootRho : ℤ × ℤ :=
  (0, 1)

/-- Coordinate form of the relation `ρ²-ρ+1=0`. -/
theorem sixthRootRho_relation :
    sixthRootMul sixthRootRho sixthRootRho -
        sixthRootRho + (1, 0) = (0, 0) := by
  norm_num [sixthRootMul, sixthRootRho]

/-- The coordinate norm is multiplicative. -/
theorem sixthRootNorm_mul (z w : ℤ × ℤ) :
    sixthRootNorm (sixthRootMul z w) =
      sixthRootNorm z * sixthRootNorm w := by
  rcases z with ⟨a, b⟩
  rcases w with ⟨c, d⟩
  simp only [sixthRootNorm, sixthRootMul]
  ring

/-- Conjugation sends `ρ` to `1-ρ`. -/
def sixthRootConj (z : ℤ × ℤ) : ℤ × ℤ :=
  (z.1 + z.2, -z.2)

/-- Multiplication by the conjugate gives the rational integer norm. -/
theorem sixthRootMul_conj (z : ℤ × ℤ) :
    sixthRootMul z (sixthRootConj z) =
      (sixthRootNorm z, 0) := by
  rcases z with ⟨a, b⟩
  simp only [sixthRootMul, sixthRootConj, sixthRootNorm]
  ext <;> simp <;> ring

/-- Conjugation preserves the norm. -/
theorem sixthRootNorm_conj (z : ℤ × ℤ) :
    sixthRootNorm (sixthRootConj z) = sixthRootNorm z := by
  rcases z with ⟨a, b⟩
  simp only [sixthRootNorm, sixthRootConj]
  ring

/-- A prime above `19`, represented by `π=3+2ρ`. -/
def sixthRootPi : ℤ × ℤ :=
  (3, 2)

/-- Its norm is `19`. -/
theorem sixthRootNorm_pi :
    sixthRootNorm sixthRootPi = 19 := by
  norm_num [sixthRootNorm, sixthRootPi]

/-- The conjugate prime is `π̄=5-2ρ`. -/
theorem sixthRootConj_pi :
    sixthRootConj sixthRootPi = (5, -2) := by
  norm_num [sixthRootConj, sixthRootPi]

/-- Coordinate factorization `19=ππ̄`. -/
theorem nineteen_eq_pi_mul_conj :
    sixthRootMul sixthRootPi (sixthRootConj sixthRootPi) =
      (19, 0) := by
  rw [sixthRootMul_conj, sixthRootNorm_pi]

/-- Divisibility by `π` in sixth-root coordinates. -/
def SixthRootPiDivides (z : ℤ × ℤ) : Prop :=
  ∃ w : ℤ × ℤ, sixthRootMul sixthRootPi w = z

/-- Multiplication by `π` cuts out the index-`19` lattice
`5a+2b ≡ 0 mod 19`. -/
theorem sixthRootPiDivides_iff (a b : ℤ) :
    SixthRootPiDivides (a, b) ↔
      (19 : ℤ) ∣ 5 * a + 2 * b := by
  constructor
  · rintro ⟨⟨c, d⟩, h⟩
    have ha : 3 * c - 2 * d = a := by
      simpa [sixthRootMul, sixthRootPi] using congrArg Prod.fst h
    have hb : 3 * d + 2 * c + 2 * d = b := by
      simpa [sixthRootMul, sixthRootPi] using congrArg Prod.snd h
    refine ⟨c, ?_⟩
    nlinarith
  · rintro ⟨c, hc⟩
    refine ⟨(c, 11 * c - 3 * a - b), ?_⟩
    ext
    · simp only [sixthRootMul, sixthRootPi]
      nlinarith
    · simp only [sixthRootMul, sixthRootPi]
      nlinarith

/-- Divisibility by the conjugate prime. -/
def SixthRootPiConjDivides (z : ℤ × ℤ) : Prop :=
  ∃ w : ℤ × ℤ,
    sixthRootMul (sixthRootConj sixthRootPi) w = z

/-- Multiplication by `π̄` cuts out the conjugate index-`19` lattice
`3a-2b ≡ 0 mod 19`. -/
theorem sixthRootPiConjDivides_iff (a b : ℤ) :
    SixthRootPiConjDivides (a, b) ↔
      (19 : ℤ) ∣ 3 * a - 2 * b := by
  simp only [SixthRootPiConjDivides]
  rw [sixthRootConj_pi]
  constructor
  · rintro ⟨⟨c, d⟩, h⟩
    have ha : 5 * c + 2 * d = a := by
      simpa [sixthRootMul] using congrArg Prod.fst h
    have hb : 5 * d + -(2 * c) + -(2 * d) = b := by
      simpa [sixthRootMul] using congrArg Prod.snd h
    refine ⟨c, ?_⟩
    nlinarith
  · rintro ⟨c, hc⟩
    refine ⟨(c, 7 * c - a + b), ?_⟩
    ext
    · simp only [sixthRootMul]
      nlinarith
    · simp only [sixthRootMul]
      nlinarith

/-- A factor of `π` forces a factor of `19` in the norm. -/
theorem nineteen_dvd_sixthRootNorm_of_piDivides
    (z : ℤ × ℤ) (hz : SixthRootPiDivides z) :
    (19 : ℤ) ∣ sixthRootNorm z := by
  obtain ⟨w, rfl⟩ := hz
  rw [sixthRootNorm_mul, sixthRootNorm_pi]
  exact ⟨sixthRootNorm w, by ring⟩

/-- The same norm consequence for `π̄`. -/
theorem nineteen_dvd_sixthRootNorm_of_piConjDivides
    (z : ℤ × ℤ) (hz : SixthRootPiConjDivides z) :
    (19 : ℤ) ∣ sixthRootNorm z := by
  obtain ⟨w, rfl⟩ := hz
  rw [sixthRootNorm_mul, sixthRootNorm_conj,
    sixthRootNorm_pi]
  exact ⟨sixthRootNorm w, by ring⟩

private lemma norm_split_mod_nineteen :
    ∀ a b : ZMod 19,
      a ^ 2 + a * b + b ^ 2 = 0 →
        5 * a + 2 * b = 0 ∨ 3 * a - 2 * b = 0 := by
  decide

/-- Conversely, every factor of `19` in a sixth-root norm comes from
one of the two primes above `19`. -/
theorem piDivides_or_piConjDivides_of_nineteen_dvd_norm
    (a b : ℤ)
    (hnorm : (19 : ℤ) ∣ sixthRootNorm (a, b)) :
    SixthRootPiDivides (a, b) ∨
      SixthRootPiConjDivides (a, b) := by
  have hnormMod :
      (a : ZMod 19) ^ 2 +
          (a : ZMod 19) * (b : ZMod 19) +
          (b : ZMod 19) ^ 2 = 0 := by
    have hcast :
        ((sixthRootNorm (a, b) : ℤ) : ZMod 19) = 0 :=
      (ZMod.intCast_zmod_eq_zero_iff_dvd
        (sixthRootNorm (a, b)) 19).2 hnorm
    simpa [sixthRootNorm] using hcast
  rcases norm_split_mod_nineteen
      (a : ZMod 19) (b : ZMod 19) hnormMod with hpi | hpibar
  · left
    rw [sixthRootPiDivides_iff]
    apply (ZMod.intCast_zmod_eq_zero_iff_dvd
      (5 * a + 2 * b) 19).mp
    simpa using hpi
  · right
    rw [sixthRootPiConjDivides_iff]
    apply (ZMod.intCast_zmod_eq_zero_iff_dvd
      (3 * a - 2 * b) 19).mp
    simpa using hpibar

/-! ## The homogeneous discriminant as a split norm -/

/-- Sixth-root coordinates for the homogeneous discriminant factor. -/
def parameterNormCoordinates (m n : ℤ) : ℤ × ℤ :=
  (m ^ 2 + 4 * m * n - n ^ 2,
    3 * (n ^ 2 - m ^ 2))

/-- Integral homogeneous discriminant factor. -/
def integerHomogeneousDiscriminant (m n : ℤ) : ℤ :=
  7 * m ^ 4 - 4 * m ^ 3 * n + 2 * m ^ 2 * n ^ 2 +
    4 * m * n ^ 3 + 7 * n ^ 4

/-- The homogeneous discriminant factor is a sixth-root norm. -/
theorem parameter_discriminant_is_norm (m n : ℤ) :
    sixthRootNorm (parameterNormCoordinates m n) =
      integerHomogeneousDiscriminant m n := by
  simp only [sixthRootNorm, parameterNormCoordinates,
    integerHomogeneousDiscriminant]
  ring

/-- The rational and integral presentations of the homogeneous
discriminant agree under coercion. -/
theorem integerHomogeneousDiscriminant_cast (m n : ℤ) :
    (integerHomogeneousDiscriminant m n : ℚ) =
      homogeneousDiscriminant (m : ℚ) (n : ℚ) := by
  simp only [integerHomogeneousDiscriminant,
    homogeneousDiscriminant]
  push_cast
  ring

private lemma parameter_both_branches_mod_nineteen :
    ∀ m n : ZMod 19,
      5 * (m ^ 2 + 4 * m * n - n ^ 2) +
          2 * (3 * (n ^ 2 - m ^ 2)) = 0 →
      3 * (m ^ 2 + 4 * m * n - n ^ 2) -
          2 * (3 * (n ^ 2 - m ^ 2)) = 0 →
      m = 0 ∧ n = 0 := by
  decide

/-- For primitive integer parameters, the discriminant norm coordinate
cannot be divisible by both primes above `19`. -/
theorem primitive_parameter_not_both_pi_factors
    (m n : ℤ) (hcoprime : IsCoprime m n) :
    ¬(SixthRootPiDivides (parameterNormCoordinates m n) ∧
      SixthRootPiConjDivides (parameterNormCoordinates m n)) := by
  rintro ⟨hpi, hpibar⟩
  have hpiDvd :
      (19 : ℤ) ∣
        5 * (m ^ 2 + 4 * m * n - n ^ 2) +
          2 * (3 * (n ^ 2 - m ^ 2)) := by
    simpa [parameterNormCoordinates] using
      (sixthRootPiDivides_iff
        (m ^ 2 + 4 * m * n - n ^ 2)
        (3 * (n ^ 2 - m ^ 2))).mp hpi
  have hpibarDvd :
      (19 : ℤ) ∣
        3 * (m ^ 2 + 4 * m * n - n ^ 2) -
          2 * (3 * (n ^ 2 - m ^ 2)) := by
    simpa [parameterNormCoordinates] using
      (sixthRootPiConjDivides_iff
        (m ^ 2 + 4 * m * n - n ^ 2)
        (3 * (n ^ 2 - m ^ 2))).mp hpibar
  have hpiMod :
      5 * ((m : ZMod 19) ^ 2 +
            4 * (m : ZMod 19) * (n : ZMod 19) -
            (n : ZMod 19) ^ 2) +
          2 * (3 * ((n : ZMod 19) ^ 2 -
            (m : ZMod 19) ^ 2)) = 0 := by
    have hcast :=
      (ZMod.intCast_zmod_eq_zero_iff_dvd
        (5 * (m ^ 2 + 4 * m * n - n ^ 2) +
          2 * (3 * (n ^ 2 - m ^ 2))) 19).2 hpiDvd
    simpa using hcast
  have hpibarMod :
      3 * ((m : ZMod 19) ^ 2 +
            4 * (m : ZMod 19) * (n : ZMod 19) -
            (n : ZMod 19) ^ 2) -
          2 * (3 * ((n : ZMod 19) ^ 2 -
            (m : ZMod 19) ^ 2)) = 0 := by
    have hcast :=
      (ZMod.intCast_zmod_eq_zero_iff_dvd
        (3 * (m ^ 2 + 4 * m * n - n ^ 2) -
          2 * (3 * (n ^ 2 - m ^ 2))) 19).2 hpibarDvd
    simpa using hcast
  obtain ⟨hmMod, hnMod⟩ :=
    parameter_both_branches_mod_nineteen
      (m : ZMod 19) (n : ZMod 19) hpiMod hpibarMod
  have hm : (19 : ℤ) ∣ m :=
    (ZMod.intCast_zmod_eq_zero_iff_dvd m 19).mp hmMod
  have hn : (19 : ℤ) ∣ n :=
    (ZMod.intCast_zmod_eq_zero_iff_dvd n 19).mp hnMod
  have hunit : IsUnit (19 : ℤ) :=
    hcoprime.isUnit_of_dvd' hm hn
  norm_num [Int.isUnit_iff] at hunit

/-- The complete explicit descent data obtained here from a noncuspidal
rational point. -/
theorem noncuspidal_curve_primitive_descent_data
    (x y : ℚ) (hx0 : x ≠ 0) (hxneg : x ≠ -1)
    (hcurve :
      y ^ 2 = orderThirteenHyperellipticPolynomial x) :
    ∃ m n : ℤ,
      0 < n ∧
      IsCoprime m n ∧
      ((m : ℚ) / (n : ℚ)) ^ 2 ≠ 1 ∧
      conicU ((m : ℚ) / (n : ℚ)) = quotientU x ∧
      conicV ((m : ℚ) / (n : ℚ)) = quotientV x y ∧
      homogeneousFiber (m : ℚ) (n : ℚ) x = 0 ∧
      ¬(SixthRootPiDivides (parameterNormCoordinates m n) ∧
        SixthRootPiConjDivides
          (parameterNormCoordinates m n)) := by
  obtain ⟨m, n, hn, hcoprime, ht, hU, hV, hroot⟩ :=
    noncuspidal_curve_primitive_parameterization
      x y hx0 hxneg hcurve
  exact ⟨m, n, hn, hcoprime, ht, hU, hV, hroot,
    primitive_parameter_not_both_pi_factors m n hcoprime⟩

/-! ## A degree-`19` polynomial Pell certificate -/

/-- Degree-`19` numerator in the polynomial Pell solution. -/
def pellH (x : ℚ) : ℚ :=
  x ^ 19 + 3 * x ^ 18 + 2 * x ^ 17 + 5 * x ^ 16 +
    22 * x ^ 15 + 22 * x ^ 14 + 10 * x ^ 13 +
    54 * x ^ 12 + 78 * x ^ 11 + 20 * x ^ 10 +
    51 * x ^ 9 + 113 * x ^ 8 + 36 * x ^ 7 +
    13 * x ^ 6 + 66 * x ^ 5 + 26 * x ^ 4 -
    2 * x ^ 3 + 12 * x ^ 2 + 4 * x

/-- Degree-`16` denominator in the polynomial Pell solution. -/
def pellK (x : ℚ) : ℚ :=
  x ^ 16 + 2 * x ^ 15 + 4 * x ^ 13 + 14 * x ^ 12 +
    4 * x ^ 11 + 2 * x ^ 10 + 32 * x ^ 9 +
    18 * x ^ 8 - 8 * x ^ 7 + 29 * x ^ 6 +
    24 * x ^ 5 - 10 * x ^ 4 + 10 * x ^ 3 +
    10 * x ^ 2 - 4 * x + 2

/-- Exact polynomial Pell identity for the order-thirteen sextic. -/
theorem pell_identity (x : ℚ) :
    pellH x ^ 2 -
        orderThirteenHyperellipticPolynomial x * pellK x ^ 2 =
      -4 := by
  simp only [pellH, pellK,
    orderThirteenHyperellipticPolynomial]
  ring

/-- On the curve, the two conjugate Pell functions multiply to the
constant `-4`; in particular, they are units on the affine chart. -/
theorem pell_unit_factorization
    (x y : ℚ)
    (hcurve :
      y ^ 2 = orderThirteenHyperellipticPolynomial x) :
    (pellH x + y * pellK x) *
        (pellH x - y * pellK x) = -4 := by
  calc
    (pellH x + y * pellK x) *
          (pellH x - y * pellK x) =
        pellH x ^ 2 - y ^ 2 * pellK x ^ 2 := by ring
    _ = pellH x ^ 2 -
        orderThirteenHyperellipticPolynomial x *
          pellK x ^ 2 := by rw [hcurve]
    _ = -4 := pell_identity x

/-- Neither conjugate Pell factor vanishes at an affine rational point
of the curve. -/
theorem pell_factors_ne_zero
    (x y : ℚ)
    (hcurve :
      y ^ 2 = orderThirteenHyperellipticPolynomial x) :
    pellH x + y * pellK x ≠ 0 ∧
      pellH x - y * pellK x ≠ 0 := by
  have hproduct := pell_unit_factorization x y hcurve
  constructor
  · intro hzero
    rw [hzero, zero_mul] at hproduct
    norm_num at hproduct
  · intro hzero
    rw [hzero, mul_zero] at hproduct
    norm_num at hproduct

/-- Values of the sextic and Pell solution at the four affine rational
cusp points. -/
theorem pell_affine_cusp_values :
    orderThirteenHyperellipticPolynomial 0 = 1 ∧
    orderThirteenHyperellipticPolynomial (-1) = 1 ∧
    pellH 0 = 0 ∧ pellH (-1) = 0 ∧
    pellK 0 = 2 ∧ pellK (-1) = 2 := by
  norm_num [orderThirteenHyperellipticPolynomial, pellH, pellK]

/-- The normalized sextic in the local coordinate `z=1/x` at infinity. -/
def infinitySextic (z : ℚ) : ℚ :=
  1 + 2 * z + z ^ 2 + 2 * z ^ 3 +
    6 * z ^ 4 + 4 * z ^ 5 + z ^ 6

/-- Reversal of the degree-`19` Pell numerator. -/
def infinityPellH (z : ℚ) : ℚ :=
  1 + 3 * z + 2 * z ^ 2 + 5 * z ^ 3 +
    22 * z ^ 4 + 22 * z ^ 5 + 10 * z ^ 6 +
    54 * z ^ 7 + 78 * z ^ 8 + 20 * z ^ 9 +
    51 * z ^ 10 + 113 * z ^ 11 + 36 * z ^ 12 +
    13 * z ^ 13 + 66 * z ^ 14 + 26 * z ^ 15 -
    2 * z ^ 16 + 12 * z ^ 17 + 4 * z ^ 18

/-- Reversal of the degree-`16` Pell denominator. -/
def infinityPellK (z : ℚ) : ℚ :=
  1 + 2 * z + 4 * z ^ 3 + 14 * z ^ 4 +
    4 * z ^ 5 + 2 * z ^ 6 + 32 * z ^ 7 +
    18 * z ^ 8 - 8 * z ^ 9 + 29 * z ^ 10 +
    24 * z ^ 11 - 10 * z ^ 12 + 10 * z ^ 13 +
    10 * z ^ 14 - 4 * z ^ 15 + 2 * z ^ 16

/-- The reciprocal chart formula for the sextic. -/
theorem infinitySextic_eq_reciprocal
    (z : ℚ) (hz : z ≠ 0) :
    infinitySextic z =
      z ^ 6 *
        orderThirteenHyperellipticPolynomial (1 / z) := by
  simp only [infinitySextic,
    orderThirteenHyperellipticPolynomial]
  field_simp [hz]

/-- Reciprocal chart formula for the degree-`19` Pell numerator. -/
theorem infinityPellH_eq_reciprocal
    (z : ℚ) (hz : z ≠ 0) :
    infinityPellH z = z ^ 19 * pellH (1 / z) := by
  simp only [infinityPellH, pellH]
  field_simp [hz]

/-- Reciprocal chart formula for the degree-`16` Pell denominator. -/
theorem infinityPellK_eq_reciprocal
    (z : ℚ) (hz : z ≠ 0) :
    infinityPellK z = z ^ 16 * pellK (1 / z) := by
  simp only [infinityPellK, pellK]
  field_simp [hz]

/-- Reversed Pell identity.  Its right side records total vanishing
order `38`, the algebraic precursor of a divisor difference of order
`19` between the two infinity branches. -/
theorem infinity_pell_identity (z : ℚ) :
    infinityPellH z ^ 2 -
        infinitySextic z * infinityPellK z ^ 2 =
      -4 * z ^ 38 := by
  simp only [infinityPellH, infinityPellK,
    infinitySextic]
  ring

/-- Factorization on the normalized infinity chart `η²=F∞(z)`. -/
theorem infinity_pell_factorization
    (z η : ℚ) (hchart : η ^ 2 = infinitySextic z) :
    (infinityPellH z + η * infinityPellK z) *
        (infinityPellH z - η * infinityPellK z) =
      -4 * z ^ 38 := by
  calc
    (infinityPellH z + η * infinityPellK z) *
          (infinityPellH z - η * infinityPellK z) =
        infinityPellH z ^ 2 -
          η ^ 2 * infinityPellK z ^ 2 := by ring
    _ = infinityPellH z ^ 2 -
        infinitySextic z * infinityPellK z ^ 2 := by rw [hchart]
    _ = -4 * z ^ 38 := infinity_pell_identity z

/-- Values of the reversed Pell data at the two normalized infinity
directions. -/
theorem infinity_pell_boundary_values :
    infinitySextic 0 = 1 ∧
    infinityPellH 0 = 1 ∧
    infinityPellK 0 = 1 ∧
    infinityPellH 0 + 1 * infinityPellK 0 = 2 ∧
    infinityPellH 0 - (-1) * infinityPellK 0 = 2 := by
  norm_num [infinitySextic, infinityPellH, infinityPellK]

/-- Once a divisor implementation turns the Pell identity into
`19 • D = 0`, distinctness of the two infinity branches is the only
remaining group-theoretic input needed to certify exact order `19`. -/
theorem exact_order_nineteen_of_divisor_certificate
    {G : Type*} [AddMonoid G] (D : G)
    (hD : (19 : ℕ) • D = 0) (hne : D ≠ 0) :
    addOrderOf D = 19 := by
  letI : Fact (Nat.Prime 19) := ⟨by decide⟩
  exact addOrderOf_eq_prime hD hne

end MazurTorsion.XOneThirteenDescent
