/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenPicardMumford

/-!
# Explicit Hao--Ogg functions on the affine `X₁(13)` model

For the fixed even-degree sextic model, put

`p(X) = X³ + X² + 1`,  `w = (Y - p(X)) / 2`.

The checked norm identity `f - p² = 4 X (X + 1)` makes the principal
affine ideal of `w` equal to the product of the point ideals at `(0,1)` and
`(-1,1)`.  This file proves that identity in the explicit coordinate ring,
lifts it to fractional ideals, and records the resulting affine Picard-class
relation.  No projective divisor or general Jacobian infrastructure is used.
-/

namespace MazurTorsion.XOneThirteenHaoFunctions

open Ideal IsFractionRing Polynomial
open scoped nonZeroDivisors

open XOneThirteenMumford
open XOneThirteenPicard
open XOneThirteenPicard.CoordinateRing

noncomputable section

/-- The cubic polynomial occurring in Hao's generalized ordinate. -/
def haoPolynomial : ℚ[X] :=
  X ^ 3 + X ^ 2 + 1

/-- The support polynomial of the two affine cusps `(0,1)` and `(-1,1)`. -/
def cuspSupportPolynomial : ℚ[X] :=
  monicQuadratic 0 1

/-- The image of `1/2` in the affine coordinate ring. -/
def halfClass : CoordinateRing :=
  algebraMap ℚ[X] CoordinateRing (C (1 / 2 : ℚ))

/-- Hao's generalized ordinate `w = (Y - (X³+X²+1))/2`. -/
def haoW : CoordinateRing :=
  halfClass * ordinateClass haoPolynomial

/-- Its hyperelliptic conjugate `(Y + (X³+X²+1))/2`. -/
def haoWConjugate : CoordinateRing :=
  halfClass * ordinateClass (-haoPolynomial)

@[simp]
theorem halfClass_mul_two : halfClass * 2 = 1 := by
  rw [halfClass, show (2 : CoordinateRing) =
      algebraMap ℚ[X] CoordinateRing (C 2) by
    rw [C_ofNat, map_ofNat]]
  rw [← map_mul, ← C_mul]
  norm_num

/-- The exact polynomial norm certificate for the generalized ordinate. -/
theorem haoPolynomial_norm_identity :
    sexticPolynomial - haoPolynomial ^ 2 =
      C 4 * cuspSupportPolynomial := by
  apply Polynomial.funext
  intro x
  simp only [sexticPolynomial, haoPolynomial, cuspSupportPolynomial,
    monicQuadratic, eval_sub, eval_add, eval_mul, eval_pow, eval_X,
    eval_C, eval_one, eval_ofNat]
  ring

/-- The correction from `p(X)` to the cusp ordinate `1` is a multiple of the
two-cusp support. -/
theorem haoPolynomial_sub_one :
    haoPolynomial - C 1 = X * cuspSupportPolynomial := by
  simp [haoPolynomial, cuspSupportPolynomial, monicQuadratic]
  ring

/-- Clearing the denominator in the definition of `w`. -/
theorem two_mul_haoW :
    (2 : CoordinateRing) * haoW = ordinateClass haoPolynomial := by
  rw [haoW]
  calc
    (2 : CoordinateRing) * (halfClass * ordinateClass haoPolynomial) =
        (halfClass * 2) * ordinateClass haoPolynomial := by ring
    _ = ordinateClass haoPolynomial := by rw [halfClass_mul_two, one_mul]

/-- The product of `w` with its conjugate is the two-cusp support polynomial. -/
theorem haoW_mul_conjugate :
    haoW * haoWConjugate = supportClass cuspSupportPolynomial := by
  rw [haoW, haoWConjugate]
  calc
    halfClass * ordinateClass haoPolynomial *
        (halfClass * ordinateClass (-haoPolynomial)) =
      halfClass ^ 2 *
        (ordinateClass (-haoPolynomial) * ordinateClass haoPolynomial) := by
      ring
    _ = halfClass ^ 2 *
        algebraMap ℚ[X] CoordinateRing
          (sexticPolynomial - haoPolynomial ^ 2) := by
      rw [ordinateClass_neg_mul_ordinateClass]
    _ = halfClass ^ 2 *
        (4 * supportClass cuspSupportPolynomial) := by
      rw [haoPolynomial_norm_identity, map_mul]
      simp only [map_ofNat, supportClass]
    _ = supportClass cuspSupportPolynomial := by
      calc
        halfClass ^ 2 * (4 * supportClass cuspSupportPolynomial) =
            (halfClass * 2) ^ 2 * supportClass cuspSupportPolynomial := by
          ring
        _ = supportClass cuspSupportPolynomial := by
          rw [halfClass_mul_two]
          ring

/-- In cusp coordinates, `Y-1 = 2w + X·X(X+1)`. -/
theorem ordinateClass_one :
    ordinateClass (C 1) =
      2 * haoW + supportClass X * supportClass cuspSupportPolynomial := by
  calc
    ordinateClass (C 1) = ordinateClass haoPolynomial +
        algebraMap ℚ[X] CoordinateRing (haoPolynomial - C 1) := by
      simp only [ordinateClass, map_sub]
      ring
    _ = 2 * haoW +
        algebraMap ℚ[X] CoordinateRing (X * cuspSupportPolynomial) := by
      rw [haoPolynomial_sub_one, ← two_mul_haoW]
    _ = 2 * haoW + supportClass X * supportClass cuspSupportPolynomial := by
      rw [map_mul]
      rfl

/-- Conversely, `w` is generated by the two-cusp Mumford ideal. -/
theorem haoW_eq_cusp_generators :
    haoW = halfClass *
      (ordinateClass (C 1) -
        supportClass X * supportClass cuspSupportPolynomial) := by
  rw [ordinateClass_one]
  calc
    haoW = (halfClass * 2) * haoW := by rw [halfClass_mul_two, one_mul]
    _ = halfClass *
        (2 * haoW + supportClass X * supportClass cuspSupportPolynomial -
          supportClass X * supportClass cuspSupportPolynomial) := by
      ring

/-- Exact affine principal-ideal factorization of Hao's generalized
ordinate. -/
theorem span_haoW_eq_cuspCompositionIdeal :
    Ideal.span {haoW} =
      mumfordIdeal AffineMumford.cuspComposition.u
        AffineMumford.cuspComposition.v := by
  rw [AffineMumford.cuspComposition_u, AffineMumford.cuspComposition_v]
  rw [show linearPolynomial 1 0 = C 1 by simp [linearPolynomial]]
  change Ideal.span {haoW} =
    Ideal.span {supportClass cuspSupportPolynomial, ordinateClass (C 1)}
  apply le_antisymm
  · rw [Ideal.span_singleton_le_iff_mem, haoW_eq_cusp_generators]
    apply Ideal.mul_mem_left
    apply Ideal.sub_mem
    · exact Ideal.subset_span (by simp)
    · have hsupport : supportClass cuspSupportPolynomial ∈
          Ideal.span {supportClass cuspSupportPolynomial,
            ordinateClass (C 1)} := by
        exact Ideal.subset_span (by simp)
      exact (Ideal.span {supportClass cuspSupportPolynomial,
        ordinateClass (C 1)}).mul_mem_left (supportClass X) hsupport
  · rw [Ideal.span_le]
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · rw [← haoW_mul_conjugate]
      exact (Ideal.span {haoW}).mul_mem_right haoWConjugate
        (Ideal.mem_span_singleton_self haoW)
    · rw [ordinateClass_one]
      apply Ideal.add_mem
      · exact (Ideal.span {haoW}).mul_mem_left 2
          (Ideal.mem_span_singleton_self haoW)
      · exact (Ideal.span {haoW}).mul_mem_left (supportClass X)
          (by
            rw [← haoW_mul_conjugate]
            exact (Ideal.span {haoW}).mul_mem_right haoWConjugate
              (Ideal.mem_span_singleton_self haoW))

/-- The requested integral-ideal form `(w) = I(0,1) I(-1,1)`. -/
theorem span_haoW_eq_cuspPointIdealProduct :
    Ideal.span {haoW} = pointIdeal 0 1 * pointIdeal (-1) 1 := by
  rw [cuspZeroIdeal_mul_cuspNegOneIdeal]
  exact span_haoW_eq_cuspCompositionIdeal

/-- Fractional-ideal form of `(w) = I(0,1) I(-1,1)`. -/
theorem fractionalIdeal_haoW_eq_cuspPointProduct :
    FractionalIdeal.spanSingleton CoordinateRing⁰
        (algebraMap CoordinateRing FractionField haoW) =
      pointFractionalIdeal 0 1 * pointFractionalIdeal (-1) 1 := by
  simp only [pointFractionalIdeal]
  rw [← FractionalIdeal.coeIdeal_mul,
    ← span_haoW_eq_cuspPointIdealProduct,
    FractionalIdeal.coeIdeal_span_singleton]

/-- The degree-two cusp Mumford ideal is the principal fractional ideal of
`w`. -/
theorem fractionalIdeal_haoW_eq_cuspComposition :
    FractionalIdeal.spanSingleton CoordinateRing⁰
        (algebraMap CoordinateRing FractionField haoW) =
      mumfordFractionalIdeal AffineMumford.cuspComposition := by
  simp only [mumfordFractionalIdeal]
  rw [← span_haoW_eq_cuspCompositionIdeal,
    FractionalIdeal.coeIdeal_span_singleton]

/-- Named affine Picard consumer: the two-cusp composition class is
principal. -/
theorem cuspCompositionClass_eq_one : cuspCompositionClass = 1 := by
  simp only [cuspCompositionClass, mumfordClass]
  apply (ClassGroup.mk_eq_one_iff).2
  rw [show (mumfordFractionalIdealUnit AffineMumford.cuspComposition
      cuspComposition_isCoprime : FractionalIdeal CoordinateRing⁰ FractionField) =
      FractionalIdeal.spanSingleton CoordinateRing⁰
        (algebraMap CoordinateRing FractionField haoW) by
    change mumfordFractionalIdeal AffineMumford.cuspComposition = _
    exact fractionalIdeal_haoW_eq_cuspComposition.symm]
  rw [FractionalIdeal.coe_spanSingleton]
  exact ⟨⟨_, rfl⟩⟩

/-- Consequently the product of the two affine cusp point classes is
trivial. -/
theorem cuspZeroClass_mul_cuspNegOneClass_eq_one :
    cuspZeroClass * cuspNegOneClass = 1 := by
  rw [cuspZeroClass_mul_cuspNegOneClass, cuspCompositionClass_eq_one]

end

end MazurTorsion.XOneThirteenHaoFunctions
