/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI
-/

import MazurTorsion.NumberTheory.XOneEighteenTwoDivisionPrincipalSmallPrimes
import MazurTorsion.NumberTheory.XOneEighteenUnitSquareclasses

/-!
# Arithmetic of the real cubic coefficient field for the `X₁(18)` descent

The coefficient field is generated by a root of `T³ - 3T - 1`.  Its
integral power basis has discriminant `81`.  Comparing that basis with an
integral basis gives a Minkowski bound at most `2`; since `2` is inert, the
ring of integers is principal.  The same comparison proves that the field
is totally real and hence has eight unit square classes.
-/

open Module NumberField NumberField.InfinitePlace Polynomial

namespace MazurTorsion.XOneEighteenCoefficientFieldArithmetic

noncomputable section

open MazurTorsion.XOneEighteenTwoDivisionArithmetic
open MazurTorsion.XOneEighteenTwoDivisionSmallPrimes
open MazurTorsion.XOneEighteenTwoDivisionPrincipalSmallPrimes

abbrev K := MazurTorsion.XOneEighteenRealCubicQuotient.K

/-- The real cubic coefficient field has degree three. -/
theorem finrank_K_over_rat : Module.finrank ℚ K = 3 := by
  rw [coefficientPowerBasis.finrank, coefficientPowerBasis_dim]

private def coefficientDiscriminantBasis : Basis (Fin 3) ℚ K :=
  coefficientPowerBasis.basis.reindex (finCongr coefficientPowerBasis_dim)

private theorem coefficientDiscriminantBasis_discriminant :
    Algebra.discr ℚ coefficientDiscriminantBasis = 81 := by
  rw [coefficientDiscriminantBasis, Basis.coe_reindex,
    Algebra.discr_reindex, coefficientPowerBasis_discriminant]

private theorem coefficientDiscriminantBasis_isIntegral (i : Fin 3) :
    IsIntegral ℤ (coefficientDiscriminantBasis i) := by
  rw [coefficientDiscriminantBasis, Basis.reindex_apply,
    coefficientPowerBasis.basis_eq_pow]
  change IsIntegral ℤ
    (MazurTorsion.XOneEighteenRealCubicQuotient.tau ^
      ((finCongr coefficientPowerBasis_dim).symm i : ℕ))
  exact coefficientInteger.isIntegral_coe.pow _

private def reindexedIntegralBasis : Basis (Fin 3) ℚ K :=
  (integralBasis K).reindex
    ((integralBasis K).indexEquiv coefficientDiscriminantBasis)

private theorem reindexedIntegralBasis_discriminant :
    Algebra.discr ℚ reindexedIntegralBasis =
      (NumberField.discr K : ℚ) := by
  simp only [reindexedIntegralBasis, Basis.coe_reindex,
    Algebra.discr_reindex, NumberField.coe_discr]

private theorem changeMatrix_entry_isIntegral (i j : Fin 3) :
    IsIntegral ℤ
      (reindexedIntegralBasis.toMatrix coefficientDiscriminantBasis i j) := by
  let x : NumberField.RingOfIntegers K :=
    ⟨coefficientDiscriminantBasis j,
      coefficientDiscriminantBasis_isIntegral j⟩
  let e := (integralBasis K).indexEquiv coefficientDiscriminantBasis
  have hrepr := NumberField.integralBasis_repr_apply (K := K) x (e.symm i)
  rw [Basis.toMatrix_apply]
  change IsIntegral ℤ (reindexedIntegralBasis.repr (x : K) i)
  rw [show reindexedIntegralBasis.repr (x : K) i =
      (integralBasis K).repr (x : K) (e.symm i) by
    simp only [reindexedIntegralBasis, Basis.repr_reindex_apply]
    rfl]
  rw [hrepr]
  exact isIntegral_algebraMap

private theorem coefficient_discriminant_factorization :
    ∃ z : ℤ, (81 : ℤ) = z ^ 2 * NumberField.discr K := by
  have hchange :
      Algebra.discr ℚ coefficientDiscriminantBasis =
        (reindexedIntegralBasis.toMatrix coefficientDiscriminantBasis).det ^ 2 *
          Algebra.discr ℚ reindexedIntegralBasis := by
    nth_rw 1 [← reindexedIntegralBasis.toMatrix_map_vecMul
      coefficientDiscriminantBasis]
    rw [Algebra.discr_of_matrix_vecMul]
  rw [coefficientDiscriminantBasis_discriminant,
    reindexedIntegralBasis_discriminant] at hchange
  have hdet : IsIntegral ℤ
      (reindexedIntegralBasis.toMatrix coefficientDiscriminantBasis).det :=
    IsIntegral.det changeMatrix_entry_isIntegral
  obtain ⟨z, hz⟩ := IsIntegrallyClosed.isIntegral_iff.mp hdet
  rw [← hz] at hchange
  refine ⟨z, ?_⟩
  apply Rat.intCast_inj.mp
  norm_num
  exact hchange

/-- The absolute field discriminant is at most the integral power-basis
discriminant `81`. -/
theorem field_discriminant_natAbs_le :
    (NumberField.discr K).natAbs ≤ 81 := by
  obtain ⟨z, hz⟩ := coefficient_discriminant_factorization
  have hdvd : NumberField.discr K ∣ (81 : ℤ) :=
    ⟨z ^ 2, by rw [hz]; ring⟩
  exact Int.natAbs_le_of_dvd_ne_zero hdvd (by norm_num)

/-- The coefficient field discriminant is positive. -/
theorem field_discriminant_pos : 0 < NumberField.discr K := by
  obtain ⟨z, hz⟩ := coefficient_discriminant_factorization
  have hz0 : z ≠ 0 := by
    intro hz0
    rw [hz0] at hz
    norm_num at hz
  nlinarith [sq_pos_of_ne_zero hz0]

/-- The coefficient field has no complex places. -/
theorem nrComplexPlaces_eq_zero : nrComplexPlaces K = 0 := by
  have hsign := NumberField.sign_discr K
  rw [Int.sign_eq_one_of_pos field_discriminant_pos] at hsign
  have heven : Even (nrComplexPlaces K) :=
    (neg_one_pow_eq_one_iff_even (R := ℤ) (by norm_num)).mp hsign.symm
  have hsignature := card_add_two_mul_card_eq_rank K
  rw [finrank_K_over_rat] at hsignature
  obtain ⟨n, hn⟩ := heven
  omega

/-- The coefficient field is totally real. -/
theorem nrRealPlaces_eq_three : nrRealPlaces K = 3 := by
  have hsignature := card_add_two_mul_card_eq_rank K
  rw [finrank_K_over_rat, nrComplexPlaces_eq_zero] at hsignature
  omega

/-- The classical Minkowski expression for the coefficient field. -/
def minkowskiBound : ℝ :=
  (4 / Real.pi) ^ nrComplexPlaces K *
    (Nat.factorial (Module.finrank ℚ K) /
      (Module.finrank ℚ K) ^ (Module.finrank ℚ K) *
        Real.sqrt |NumberField.discr K|)

private theorem abs_discr_cast_le :
    (((|NumberField.discr K| : ℤ) : ℝ)) ≤ 81 := by
  have hInt : |NumberField.discr K| ≤ (81 : ℤ) := by
    rw [← Int.natCast_natAbs]
    exact_mod_cast field_discriminant_natAbs_le
  exact_mod_cast hInt

private theorem sqrt_abs_discr_le_nine :
    Real.sqrt (((|NumberField.discr K| : ℤ) : ℝ)) ≤ 9 := by
  rw [Real.sqrt_le_iff]
  constructor
  · norm_num
  · nlinarith [abs_discr_cast_le]

/-- The coefficient-field Minkowski bound is at most `2`. -/
theorem minkowskiBound_le_two : minkowskiBound ≤ 2 := by
  rw [minkowskiBound, nrComplexPlaces_eq_zero, finrank_K_over_rat]
  norm_num [Nat.factorial]
  rw [← Int.cast_abs]
  nlinarith [sqrt_abs_discr_le_nine]

/-- The coefficient-field ring of integers is principal. -/
theorem coefficientRingOfIntegers_isPrincipal :
    IsPrincipalIdealRing (𝓞 K) := by
  apply
    RingOfIntegers.isPrincipalIdealRing_of_isPrincipal_of_pow_le_of_mem_primesOver_of_mem_Icc
  intro p hpRange hpPrime P hP hpow
  have hfloor :
      ⌊(4 / Real.pi) ^ nrComplexPlaces K *
          (Nat.factorial (Module.finrank ℚ K) /
            (Module.finrank ℚ K) ^ (Module.finrank ℚ K) *
              Real.sqrt |NumberField.discr K|)⌋₊ ≤ 2 := by
    change ⌊minkowskiBound⌋₊ ≤ 2
    exact Nat.floor_le_of_le minkowskiBound_le_two
  have hpLe : p ≤ 2 := (Finset.mem_Icc.mp hpRange).2.trans hfloor
  have hpTwo : p = 2 := by
    have hpGe : 2 ≤ p := hpPrime.two_le
    omega
  subst p
  have hinertia : P.inertiaDeg ℤ = 3 :=
    coefficient_inertiaDeg_eq_three_at_two P hP
  rw [hinertia] at hpow
  norm_num at hpow
  omega

/-- The coefficient field has exactly eight integral-unit squareclasses. -/
theorem natCard_coefficientUnitsModSq :
    Nat.card (Units.modPow (𝓞 K) 2) = 8 :=
  MazurTorsion.XOneEighteenDescent.natCard_unitsModSq_of_degree_three_of_nrRealPlaces_eq_three
    K finrank_K_over_rat nrRealPlaces_eq_three

end

end MazurTorsion.XOneEighteenCoefficientFieldArithmetic
