/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenPiFiniteGeneration
import Mathlib.Algebra.QuadraticAlgebra.NormDeterminant
import Mathlib.LinearAlgebra.Charpoly.BaseChange
import Mathlib.LinearAlgebra.Dimension.Torsion.Basic
import Mathlib.LinearAlgebra.FreeModule.PID
import Mathlib.RingTheory.Norm.Transitivity

/-!
# The one-prime finitely generated endpoint for `X₁(13)`

The quadratic diamond action satisfies `γ²-γ+1=0`.  Consequently a
rational representation carrying that action is a vector space over the
quadratic algebra with `ω²=ω-1`.  The element `3+2ω` has norm `19`.

This is the determinant input needed for the Mazur--Tate rank argument: on a
positive-rank integral lattice, `3+2γ` has determinant a positive power of
`19`, so it cannot be surjective.  In particular, this argument uses only the
single prime-over-`19` endomorphism.  It does not assume surjectivity of the
conjugate prime.
-/

namespace MazurTorsion.XOneThirteenPrimeSurjectiveRank

open Module
open scoped TensorProduct
open XOneThirteenEndomorphismArithmetic

noncomputable section

/-- The quadratic coefficient field generated by the order-six diamond
operator.  Its distinguished element satisfies `ω²=ω-1`. -/
abbrev DiamondField := QuadraticAlgebra ℚ (-1) 1

private theorem diamondPolynomial_has_no_rational_root
    (r : ℚ) : r ^ 2 ≠ (-1 : ℚ) + 1 * r := by
  intro h
  have hsquare : 0 ≤ (2 * r - 1) ^ 2 := sq_nonneg (2 * r - 1)
  nlinarith

instance diamondFieldNoRoot :
    Fact (∀ r : ℚ, r ^ 2 ≠ (-1 : ℚ) + 1 * r) :=
  ⟨diamondPolynomial_has_no_rational_root⟩

/-- The prime-over-`19` scalar `3+2ω`. -/
def diamondPrime : DiamondField :=
  ⟨3, 2⟩

theorem diamondPrime_eq :
    diamondPrime = 3 + 2 * QuadraticAlgebra.omega := by
  ext <;>
    norm_num [diamondPrime, QuadraticAlgebra.omega,
      QuadraticAlgebra.re_ofNat, QuadraticAlgebra.im_ofNat]

/-- The explicit quadratic norm certificate `N(3+2ω)=19`. -/
theorem diamondPrime_quadraticNorm :
    QuadraticAlgebra.norm diamondPrime = 19 := by
  norm_num [diamondPrime, QuadraticAlgebra.norm_def]

/-- The algebra norm agrees with the explicit quadratic norm on the
prime-over-`19` scalar. -/
theorem diamondPrime_algebraNorm :
    Algebra.norm ℚ diamondPrime = 19 := by
  rw [Algebra.norm_apply]
  change LinearMap.det
      (DistribSMul.toLinearMap ℚ DiamondField diamondPrime) = 19
  rw [QuadraticAlgebra.det_toLinearMap_eq_norm,
    diamondPrime_quadraticNorm]

/-- Restricting scalar multiplication by `3+2ω` to `ℚ` has determinant
`19^[V:DiamondField]`. -/
theorem det_restrictScalars_diamondPrime
    (V : Type*) [AddCommGroup V] [Module DiamondField V] [Module ℚ V]
    [IsScalarTower ℚ DiamondField V] [Module.Finite DiamondField V] :
    LinearMap.det
        ((Algebra.lsmul DiamondField DiamondField V diamondPrime).restrictScalars ℚ) =
      (19 : ℚ) ^ Module.finrank DiamondField V := by
  rw [LinearMap.det_restrictScalars, Algebra.lsmul_eq_smul_one,
    LinearMap.det_smul]
  simp only [map_one, mul_one, map_pow, diamondPrime_algebraNorm]

/-! ## A quadratic scalar action from the diamond endomorphism -/

variable {V : Type*} [AddCommGroup V] [Module ℚ V]

/-- Linear-map form of the relation `γ²-γ+1=0`. -/
def SatisfiesDiamondRelation (γ : Module.End ℚ V) : Prop :=
  γ * γ = γ - 1

/-- The quadratic algebra acts through any rational endomorphism satisfying
the diamond relation. -/
def diamondAlgebraHom (γ : Module.End ℚ V)
    (hγ : SatisfiesDiamondRelation γ) :
    DiamondField →ₐ[ℚ] Module.End ℚ V :=
  QuadraticAlgebra.lift ⟨γ, by
    dsimp only [SatisfiesDiamondRelation] at hγ
    simpa [sub_eq_add_neg, add_comm] using hγ⟩

@[simp]
theorem diamondAlgebraHom_omega (γ : Module.End ℚ V)
    (hγ : SatisfiesDiamondRelation γ) :
    diamondAlgebraHom γ hγ QuadraticAlgebra.omega = γ := by
  simp [diamondAlgebraHom]

/-- Rational-linear form of the prime-over-`19` endomorphism. -/
def rationalPrimeEndomorphism (γ : Module.End ℚ V) : Module.End ℚ V :=
  3 • (1 : Module.End ℚ V) + 2 • γ

/-- The determinant formula for the rational prime endomorphism.  The
integer `k` is the dimension after adjoining the diamond scalar. -/
theorem exists_det_prime_formula
    [Module.Finite ℚ V] (γ : Module.End ℚ V)
    (hγ : SatisfiesDiamondRelation γ) :
    ∃ k : ℕ,
      Module.finrank ℚ V = 2 * k ∧
      LinearMap.det (rationalPrimeEndomorphism γ) =
        (19 : ℚ) ^ k := by
  let ρ : DiamondField →ₐ[ℚ] Module.End ℚ V :=
    diamondAlgebraHom γ hγ
  letI : Module DiamondField V := Module.compHom V ρ.toRingHom
  letI : IsScalarTower ℚ DiamondField V :=
    IsScalarTower.of_algebraMap_smul (by
      intro r x
      change ρ (algebraMap ℚ DiamondField r) x = r • x
      rw [ρ.commutes]
      rfl)
  letI : Module.Finite DiamondField V :=
    Module.Finite.of_restrictScalars_finite ℚ DiamondField V
  refine ⟨Module.finrank DiamondField V, ?_, ?_⟩
  · rw [← Module.finrank_mul_finrank ℚ DiamondField V,
      QuadraticAlgebra.finrank_eq_two]
  · have hscalar :
        (Algebra.lsmul DiamondField DiamondField V diamondPrime).restrictScalars ℚ =
          rationalPrimeEndomorphism γ := by
      ext x
      change diamondPrime • x =
        (rationalPrimeEndomorphism γ) x
      change ρ diamondPrime x =
        (rationalPrimeEndomorphism γ) x
      change (3 : ℚ) • x + (2 : ℚ) • γ x =
        3 • x + 2 • γ x
      congr 1
      · exact ofNat_smul_eq_nsmul (R := ℚ) (n := 3) x
      · exact ofNat_smul_eq_nsmul (R := ℚ) (n := 2) (γ x)
    rw [← hscalar]
    exact det_restrictScalars_diamondPrime V

/-- A rational diamond representation has dimension zero if the determinant
of `3+2γ` is an integral unit. -/
theorem finrank_eq_zero_of_det_prime_eq_one_or_neg_one
    [Module.Finite ℚ V] (γ : Module.End ℚ V)
    (hγ : SatisfiesDiamondRelation γ)
    (hdet :
      LinearMap.det (rationalPrimeEndomorphism γ) = 1 ∨
      LinearMap.det (rationalPrimeEndomorphism γ) = -1) :
    Module.finrank ℚ V = 0 := by
  obtain ⟨k, hrank, hformula⟩ := exists_det_prime_formula γ hγ
  rw [hformula] at hdet
  have hk : k = 0 := by
    by_contra hk0
    have hlarge : (1 : ℚ) < 19 ^ k :=
      one_lt_pow₀ (by norm_num) hk0
    rcases hdet with hone | hneg
    · linarith
    · have hpos : (0 : ℚ) < 19 ^ k := pow_pos (by norm_num) k
      linarith
  simpa [hk] using hrank

/-! ## Integral lattices -/

variable {B : Type*} [AddCommGroup B] [Module ℤ B]

/-- Integral-linear form of the prime-over-`19` endomorphism. -/
def integralPrimeEndomorphism (γ : Module.End ℤ B) : Module.End ℤ B :=
  3 • (1 : Module.End ℤ B) + 2 • γ

/-- On a finite free integral lattice with the quadratic diamond action,
surjectivity of the single prime-over-`19` endomorphism forces rank zero. -/
theorem finrank_eq_zero_of_integralPrime_surjective
    [Module.Finite ℤ B] [Module.Free ℤ B]
    (γ : Module.End ℤ B) (hγ : γ * γ = γ - 1)
    (hprime : Function.Surjective (integralPrimeEndomorphism γ)) :
    Module.finrank ℤ B = 0 := by
  let p : Module.End ℤ B := integralPrimeEndomorphism γ
  have hpBijective : Function.Bijective p :=
    ⟨Module.End.injective_of_surjective ℤ B hprime, hprime⟩
  have hpUnit : IsUnit p := (Module.End.isUnit_iff p).mpr hpBijective
  have hdetUnit : IsUnit (LinearMap.det p) :=
    LinearMap.isUnit_det p hpUnit
  have hdetCases : LinearMap.det p = 1 ∨ LinearMap.det p = -1 :=
    Int.isUnit_iff.mp hdetUnit
  let V₀ := ℚ ⊗[ℤ] B
  let γ₀ : Module.End ℚ V₀ := γ.baseChange ℚ
  have hγ₀ : SatisfiesDiamondRelation γ₀ := by
    dsimp only [SatisfiesDiamondRelation, γ₀, V₀]
    calc
      γ.baseChange ℚ * γ.baseChange ℚ =
          (γ * γ).baseChange ℚ :=
        (LinearMap.baseChange_mul γ γ).symm
      _ = (γ - 1).baseChange ℚ := congrArg (fun f ↦ f.baseChange ℚ) hγ
      _ = γ.baseChange ℚ - 1 := by
        rw [LinearMap.baseChange_sub, LinearMap.baseChange_one]
  have hpBase : p.baseChange ℚ = rationalPrimeEndomorphism γ₀ := by
    dsimp only [p, integralPrimeEndomorphism, rationalPrimeEndomorphism, γ₀]
    change (LinearMap.baseChangeHom ℤ ℚ B B)
        (3 • (1 : Module.End ℤ B) + 2 • γ) =
      3 • (1 : Module.End ℚ (ℚ ⊗[ℤ] B)) + 2 • γ.baseChange ℚ
    rw [map_add, map_nsmul, map_nsmul,
      LinearMap.baseChangeHom_apply, LinearMap.baseChangeHom_apply,
      LinearMap.baseChange_one]
  have hdetBase :
      LinearMap.det (rationalPrimeEndomorphism γ₀) =
        algebraMap ℤ ℚ (LinearMap.det p) := by
    rw [← hpBase, LinearMap.det_baseChange]
  have hdetRational :
      LinearMap.det (rationalPrimeEndomorphism γ₀) = 1 ∨
      LinearMap.det (rationalPrimeEndomorphism γ₀) = -1 := by
    rcases hdetCases with hone | hneg
    · left
      rw [hdetBase, hone, map_one]
    · right
      rw [hdetBase, hneg, map_neg, map_one]
  have hV₀ : Module.finrank ℚ V₀ = 0 :=
    finrank_eq_zero_of_det_prime_eq_one_or_neg_one γ₀ hγ₀ hdetRational
  rw [Module.finrank_baseChange] at hV₀
  exact hV₀

/-! ## Finitely generated abelian groups -/

variable {A : Type*} [AddCommGroup A]

/-- Correct one-prime Mazur--Tate endpoint.  On a finitely generated abelian
group carrying the diamond relation, surjectivity of `3+2γ` alone forces the
free rank to vanish. -/
theorem finrank_eq_zero_of_primeEndomorphism_surjective
    [AddGroup.FG A] (γ : A →+ A)
    (hγ : SatisfiesQuadraticRelation γ)
    (hprime : Function.Surjective (primeEndomorphism γ)) :
    Module.finrank ℤ A = 0 := by
  letI : Module.Finite ℤ A :=
    Module.Finite.iff_addGroup_fg.mpr (inferInstance : AddGroup.FG A)
  let T : Submodule ℤ A := Submodule.torsion ℤ A
  let B₀ := A ⧸ T
  letI : Module.Finite ℤ B₀ := Module.Finite.quotient ℤ T
  have preservesTorsion (f : Module.End ℤ A) : T ≤ T.comap f := by
    intro x hx
    apply (Submodule.mem_torsion_iff (R := ℤ) (f x)).mpr
    obtain ⟨r, hr⟩ := (Submodule.mem_torsion_iff (R := ℤ) x).mp hx
    refine ⟨r, ?_⟩
    change (r : ℤ) • f x = 0
    calc
      (r : ℤ) • f x = f ((r : ℤ) • x) := (f.map_smul (r : ℤ) x).symm
      _ = f 0 := congrArg f hr
      _ = 0 := f.map_zero
  let γℤ : Module.End ℤ A := γ.toIntLinearMap
  have hγT : T ≤ T.comap γℤ := preservesTorsion γℤ
  let γ₀ : Module.End ℤ B₀ := T.mapQ T γℤ hγT
  letI : Module.IsTorsionFree ℤ B₀ := by
    dsimp only [B₀, T]
    exact Submodule.QuotientTorsion.instIsTorsionFree
  letI : Module.Free ℤ B₀ :=
    Module.free_of_finite_type_torsion_free'
  have hγ₀_mk (x : A) :
      γ₀ (Submodule.Quotient.mk x) = Submodule.Quotient.mk (γ x) := by
    change (T.mapQ T γℤ hγT) (Submodule.Quotient.mk x) =
      Submodule.Quotient.mk (γ x)
    rw [Submodule.mapQ_apply]
    rfl
  have hγ₀ : γ₀ * γ₀ = γ₀ - 1 := by
    apply LinearMap.ext
    intro q
    refine Submodule.Quotient.induction_on T q ?_
    intro x
    change γ₀ (γ₀ (Submodule.Quotient.mk x)) =
      γ₀ (Submodule.Quotient.mk x) - Submodule.Quotient.mk x
    rw [hγ₀_mk, hγ₀_mk, hγ x]
    rfl
  have hprime₀ : Function.Surjective (integralPrimeEndomorphism γ₀) := by
    intro q
    refine Submodule.Quotient.induction_on T q ?_
    intro x
    obtain ⟨y, hy⟩ := hprime x
    refine ⟨Submodule.Quotient.mk y, ?_⟩
    change Submodule.Quotient.mk (3 • y + 2 • γ y) =
      Submodule.Quotient.mk x
    rw [← primeEndomorphism_apply, hy]
  have hquotient : Module.finrank ℤ B₀ = 0 :=
    finrank_eq_zero_of_integralPrime_surjective γ₀ hγ₀ hprime₀
  have hrank : Module.finrank ℤ B₀ = Module.finrank ℤ A := by
    exact finrank_quotient_eq_of_le_torsion (le_refl T)
  exact hrank.symm.trans hquotient

/-- The resulting finitely generated abelian group is finite. -/
theorem finite_of_primeEndomorphism_surjective_single
    [AddGroup.FG A] (γ : A →+ A)
    (hγ : SatisfiesQuadraticRelation γ)
    (hprime : Function.Surjective (primeEndomorphism γ)) :
    Finite A := by
  letI : Module.Finite ℤ A :=
    Module.Finite.iff_addGroup_fg.mpr (inferInstance : AddGroup.FG A)
  have hrank : Module.finrank ℤ A = 0 :=
    finrank_eq_zero_of_primeEndomorphism_surjective γ hγ hprime
  have hmoduleTorsion : Module.IsTorsion ℤ A :=
    (Module.finrank_eq_zero_iff_isTorsion (R := ℤ)).mp hrank
  exact AddCommGroup.finite_of_fg_torsion A
    (AddMonoid.isTorsion_iff_isTorsion_int.mpr hmoduleTorsion)

end

end MazurTorsion.XOneThirteenPrimeSurjectiveRank
