/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenPadicSquareclass
import MazurTorsion.NumberTheory.XOneThirteenTwoDescentLocalKummerQuotient

/-!
# Scalar generators inside the dyadic sextic algebra

The dyadic scalar squareclasses are generated by `-1`, `2`, and `5`.  This
leaf checks the two identities that simplify their images in the explicit
sextic algebra:

* `-1 = i²`;
* `2 = lambda * pi²`.

It also packages `lambda` and `pi` as genuine algebra units using explicit
inverses obtained from the second identity.  These are the exact algebraic
inputs needed to turn an arbitrary scalar in a fake-Kummer equality into the
two finite factors `lambda` and `5` used by the mod-two/mod-four verifier.
-/

namespace MazurTorsion.XOneThirteenTwoDescentLocalScalarGenerators

open XOneThirteenTwoDescentMagmaBridge
open XOneThirteenTwoDescentLocalElements
open XOneThirteenTwoDescentLocalKummerPoints
open XOneThirteenTwoDescentLocalKummerQuotient

noncomputable section

private instance : Fact (Nat.Prime 2) := ⟨by decide⟩

/-- The checked identity `lambda * pi² = 2`, after dyadic base change. -/
theorem padicLambda_mul_padicPi_sq :
    magmaOrderToPadic localLambda *
        (magmaOrderToPadic localPi) ^ 2 = 2 := by
  rw [← map_pow, ← map_mul, localLambda_mul_localPi_sq, map_ofNat]

private theorem padicTwo_mul_half :
    (2 : MagmaPadicAlgebra) *
      algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) = 1 := by
  rw [← map_ofNat (algebraMap ℚ_[2] MagmaPadicAlgebra) 2,
    ← map_mul]
  norm_num

/-- An explicit inverse for `lambda`. -/
def padicLambdaInverse : MagmaPadicAlgebra :=
  (magmaOrderToPadic localPi) ^ 2 *
    algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹)

/-- An explicit inverse for `pi`. -/
def padicPiInverse : MagmaPadicAlgebra :=
  magmaOrderToPadic localLambda * magmaOrderToPadic localPi *
    algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹)

theorem padicLambda_mul_inverse :
    magmaOrderToPadic localLambda * padicLambdaInverse = 1 := by
  calc
    magmaOrderToPadic localLambda * padicLambdaInverse =
        (magmaOrderToPadic localLambda *
          (magmaOrderToPadic localPi) ^ 2) *
          algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) := by
      simp only [padicLambdaInverse]
      ring
    _ = (2 : MagmaPadicAlgebra) *
          algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) := by
      rw [padicLambda_mul_padicPi_sq]
    _ = 1 := padicTwo_mul_half

theorem padicPi_mul_inverse :
    magmaOrderToPadic localPi * padicPiInverse = 1 := by
  calc
    magmaOrderToPadic localPi * padicPiInverse =
        (magmaOrderToPadic localLambda *
          (magmaOrderToPadic localPi) ^ 2) *
          algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) := by
      simp only [padicPiInverse]
      ring
    _ = (2 : MagmaPadicAlgebra) *
          algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) := by
      rw [padicLambda_mul_padicPi_sq]
    _ = 1 := padicTwo_mul_half

/-- The algebra unit represented by `lambda`. -/
def padicLambdaUnit : MagmaPadicAlgebraˣ :=
  Units.mkOfMulEqOne (magmaOrderToPadic localLambda)
    padicLambdaInverse padicLambda_mul_inverse

/-- The algebra unit represented by `pi`. -/
def padicPiUnit : MagmaPadicAlgebraˣ :=
  Units.mkOfMulEqOne (magmaOrderToPadic localPi)
    padicPiInverse padicPi_mul_inverse

/-- The checked fourth root of unity after dyadic base change. -/
def padicIUnit : MagmaPadicAlgebraˣ :=
  Units.map magmaOrderToPadic.toMonoidHom integralIUnit

/-- The scalar unit `-1` in `ℚ₂`. -/
def padicMinusOneUnit : ℚ_[2]ˣ :=
  Units.mk0 (-1) (by norm_num)

/-- The scalar unit `5` in `ℚ₂`. -/
def padicFiveUnit : ℚ_[2]ˣ :=
  Units.mk0 5 (by norm_num)

/-- Inside the sextic algebra, scalar `-1` is the square of `i`. -/
theorem scalarMinusOne_eq_padicI_sq :
    scalarUnitMap padicMinusOneUnit = padicIUnit ^ 2 := by
  apply Units.ext
  simp only [scalarUnitMap, padicMinusOneUnit, padicIUnit, Units.coe_map,
    Units.val_mk0, Units.val_pow_eq_pow_val, integralIUnit_coe]
  have hmap := congrArg magmaOrderToPadic integralI_sq
  calc
    algebraMap ℚ_[2] MagmaPadicAlgebra (-1) =
        (-1 : MagmaPadicAlgebra) := by rw [map_neg, map_one]
    _ = magmaOrderToPadic integralI ^ 2 := by
      simpa only [map_pow, map_neg, map_one] using hmap.symm

/-- Inside the sextic algebra, scalar `2` is `lambda` times the square of
`pi`. -/
theorem scalarTwo_eq_padicLambda_mul_padicPi_sq :
    scalarUnitMap padicTwoUnit = padicLambdaUnit * padicPiUnit ^ 2 := by
  apply Units.ext
  simp only [scalarUnitMap, padicTwoUnit, padicLambdaUnit, padicPiUnit,
    Units.coe_map, Units.val_mk0, Units.val_mul,
    Units.val_pow_eq_pow_val]
  exact padicLambda_mul_padicPi_sq.symm

/-- The three dyadic scalar generators, after mapping to the sextic algebra:
the first is a square, the second is `lambda` times a square, and the third
is retained as scalar `5`. -/
theorem dyadic_scalar_generator_identities :
    scalarUnitMap padicMinusOneUnit = padicIUnit ^ 2 ∧
      scalarUnitMap padicTwoUnit = padicLambdaUnit * padicPiUnit ^ 2 ∧
      scalarUnitMap padicFiveUnit = scalarUnitMap padicFiveUnit :=
  ⟨scalarMinusOne_eq_padicI_sq,
    scalarTwo_eq_padicLambda_mul_padicPi_sq, rfl⟩

end

end MazurTorsion.XOneThirteenTwoDescentLocalScalarGenerators
