/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI
-/

import MazurTorsion.NumberTheory.XOneEighteenQuotientTwoDescentModel
import MazurTorsion.NumberTheory.XOneEighteenTwoDivisionClassNumber

/-!
# Identifying the `X₁(18)` descent algebra with the explicit compositum

The generic `x - T` descent is phrased in the cubic algebra obtained from
the completed two-division polynomial.  The arithmetic certificates use the
explicit relative cubic compositum generated by `s`, with `s³ = 3s + 10`.
This file gives an actual algebra equivalence between those presentations.

The inverse is completely explicit.  If `z` denotes the root of the
completed two-division polynomial, then

`s = (4z² - 11z + 70) / 27`.

Thus no irreducibility or dimension-count oracle is hidden in the bridge.
-/

open Polynomial WeierstrassCurve
open scoped WeierstrassCurve.Affine

namespace MazurTorsion.XOneEighteenDescentAlgebraEquiv

noncomputable section

open MazurTorsion.XOneEighteenQuotientTwoDescentModel
open MazurTorsion.XOneEighteenTwoDivisionArithmetic
open MazurTorsion.XOneEighteenTwoDivisionClassNumber

abbrev K := MazurTorsion.XOneEighteenRealCubicQuotient.K

/-- The completed two-division root generates the explicit relative cubic
field: the original generator is recovered by this quadratic expression. -/
theorem recover_s_in_compositum :
    (4 * descentRootInM ^ 2 - 11 * descentRootInM + 70) / 27 = s := by
  have hquarter : algebraMap K M (1 / 4 : K) = (1 / 4 : M) := by
    simp only [div_eq_mul_inv, one_mul, map_inv₀, map_ofNat]
  simp only [descentRootInM, relativeTwoDivisionZ]
  rw [hquarter]
  field_simp
  linear_combination 9 * (s - 4) * s_cubic

private theorem descentRootInM_adjoin_eq_top :
    IntermediateField.adjoin K {descentRootInM} = ⊤ := by
  let L : IntermediateField K M :=
    IntermediateField.adjoin K {descentRootInM}
  have hz : descentRootInM ∈ L :=
    IntermediateField.mem_adjoin_simple_self K descentRootInM
  have hs : s ∈ L := by
    rw [← recover_s_in_compositum]
    exact L.div_mem
      (L.add_mem
        (L.sub_mem
          (L.mul_mem (L.natCast_mem 4) (L.pow_mem hz 2))
          (L.mul_mem (L.natCast_mem 11) hz))
        (L.natCast_mem 70))
      (L.natCast_mem 27)
  apply top_unique
  intro x _hx
  have hadjoin :
      Algebra.adjoin K ({s} : Set M) ≤
        L.toSubalgebra :=
    Algebra.adjoin_le (Set.singleton_subset_iff.mpr hs)
  have hsTop : Algebra.adjoin K ({s} : Set M) = ⊤ := by
    change Algebra.adjoin K
      ({AdjoinRoot.root relativePolynomial} : Set M) = ⊤
    exact AdjoinRoot.adjoinRoot_eq_top
  rw [hsTop] at hadjoin
  change x ∈ L
  exact hadjoin (show x ∈ (⊤ : Subalgebra K M) from trivial)

/-- The completed two-division cubic is irreducible over the real cubic
coefficient field. -/
theorem descentPolynomial_irreducible :
    Irreducible descentCurve.toAffine.f := by
  have hroot : Polynomial.aeval descentRootInM descentCurve.toAffine.f = 0 := by
    rw [← Polynomial.eval_map_algebraMap]
    exact descentRootInM_isRoot
  have hdegree : (minpoly K descentRootInM).natDegree = 3 := by
    have h :=
      (Field.primitive_element_iff_minpoly_natDegree_eq
        K descentRootInM).mp descentRootInM_adjoin_eq_top
    simpa only [finrank_M_over_K] using h
  have hint : IsIntegral K descentRootInM := IsIntegral.of_finite K descentRootInM
  have hdvd : minpoly K descentRootInM ∣ descentCurve.toAffine.f :=
    minpoly.dvd K descentRootInM hroot
  have heq : descentCurve.toAffine.f = minpoly K descentRootInM :=
    Polynomial.eq_of_monic_of_dvd_of_natDegree_le
      (minpoly.monic hint) descentCurve.toAffine.monic_f hdvd (by
        rw [hdegree, descentCurve.toAffine.natDegree_f])
  rw [heq]
  exact minpoly.irreducible hint

private instance descentPolynomial_irreducibleFact :
    Fact (Irreducible descentCurve.toAffine.f) :=
  ⟨descentPolynomial_irreducible⟩

private theorem descentPolynomial_cleared :
    C (4 : K) * descentCurve.toAffine.f =
      C (4 : K) * X ^ 3 - C (3 : K) * X ^ 2 +
        C (102 : K) * X + C (5 : K) := by
  rw [descentCurve_f, mul_add, mul_add, mul_sub]
  simp only [← mul_assoc, ← C_mul]
  norm_num

/-- The distinguished root in the generic completed two-division algebra. -/
def genericRoot : descentCurve.toAffine.A :=
  AdjoinRoot.root descentCurve.toAffine.f

/-- The generic root satisfies the cleared completed two-division cubic. -/
theorem genericRoot_cubic :
    4 * genericRoot ^ 3 - 3 * genericRoot ^ 2 +
        102 * genericRoot + 5 = 0 := by
  have hroot : Polynomial.aeval genericRoot descentCurve.toAffine.f = 0 := by
    rw [aeval_def]
    exact AdjoinRoot.eval₂_root descentCurve.toAffine.f
  have h := congrArg (Polynomial.aeval genericRoot)
    descentPolynomial_cleared
  simp only [map_mul, map_sub, map_add, map_pow, aeval_X,
    map_ofNat, hroot, mul_zero] at h
  simpa only [mul_comm, mul_left_comm, mul_assoc] using h.symm

/-- Recover the relative generator from the completed two-division root. -/
def recoveredS : descentCurve.toAffine.A :=
  (4 * genericRoot ^ 2 - 11 * genericRoot + 70) / 27

/-- The recovered element satisfies `S³ - 3S - 10`. -/
theorem recoveredS_cubic : recoveredS ^ 3 = 3 * recoveredS + 10 := by
  have h := genericRoot_cubic
  let N : descentCurve.toAffine.A :=
    4 * genericRoot ^ 2 - 11 * genericRoot + 70
  have hN : N ^ 3 - 3 * 27 ^ 2 * N - 10 * 27 ^ 3 = 0 := by
    dsimp only [N]
    linear_combination
      (16 * genericRoot ^ 3 - 120 * genericRoot ^ 2 +
        705 * genericRoot - 1384) * h
  have h27 : (27 : descentCurve.toAffine.A) ≠ 0 := by
    simpa only [map_ofNat] using
      (_root_.map_ne_zero (algebraMap K descentCurve.toAffine.A)).mpr
        (by norm_num : (27 : K) ≠ 0)
  change (N / 27) ^ 3 = 3 * (N / 27) + 10
  field_simp [h27]
  linear_combination hN

private theorem recoveredS_isRoot :
    Polynomial.aeval recoveredS relativePolynomial = 0 := by
  simp only [relativePolynomial, map_sub, map_pow, aeval_X,
    map_mul, map_ofNat]
  linear_combination recoveredS_cubic

/-- Map the generic descent algebra to the explicit relative cubic field. -/
def toCompositumHom : descentCurve.toAffine.A →ₐ[K] M :=
  AdjoinRoot.liftAlgHom descentCurve.toAffine.f (Algebra.ofId K M)
    descentRootInM (by
      rw [Algebra.toRingHom_ofId, ← aeval_def]
      rw [← Polynomial.eval_map_algebraMap]
      exact descentRootInM_isRoot)

@[simp]
theorem toCompositumHom_genericRoot :
    toCompositumHom genericRoot = descentRootInM := by
  exact AdjoinRoot.liftAlgHom_root descentCurve.toAffine.f _ _ _

/-- Map the explicit relative cubic presentation back to the generic
descent algebra. -/
def fromCompositumHom : M →ₐ[K] descentCurve.toAffine.A :=
  AdjoinRoot.liftAlgHom relativePolynomial
    (Algebra.ofId K descentCurve.toAffine.A) recoveredS (by
      rw [Algebra.toRingHom_ofId, ← aeval_def]
      exact recoveredS_isRoot)

@[simp]
theorem fromCompositumHom_s : fromCompositumHom s = recoveredS := by
  exact AdjoinRoot.liftAlgHom_root relativePolynomial _ _ _

private theorem recover_genericRoot :
    algebraMap K descentCurve.toAffine.A (1 / 4 : K) *
        (3 * recoveredS ^ 2 - 6 * recoveredS - 5) = genericRoot := by
  have hquarter :
      algebraMap K descentCurve.toAffine.A (1 / 4 : K) =
        (1 / 4 : descentCurve.toAffine.A) := by
    simp only [div_eq_mul_inv, one_mul, map_inv₀, map_ofNat]
  rw [hquarter]
  have h := genericRoot_cubic
  let N : descentCurve.toAffine.A :=
    4 * genericRoot ^ 2 - 11 * genericRoot + 70
  have hN :
      3 * N ^ 2 - 6 * 27 * N - 5 * 27 ^ 2 -
          4 * 27 ^ 2 * genericRoot = 0 := by
    dsimp only [N]
    linear_combination 3 * (4 * genericRoot - 19) * h
  have h4 : (4 : descentCurve.toAffine.A) ≠ 0 := by
    simpa only [map_ofNat] using
      (_root_.map_ne_zero (algebraMap K descentCurve.toAffine.A)).mpr
        (by norm_num : (4 : K) ≠ 0)
  have h27 : (27 : descentCurve.toAffine.A) ≠ 0 := by
    simpa only [map_ofNat] using
      (_root_.map_ne_zero (algebraMap K descentCurve.toAffine.A)).mpr
        (by norm_num : (27 : K) ≠ 0)
  change (1 / 4 : descentCurve.toAffine.A) *
      (3 * (N / 27) ^ 2 - 6 * (N / 27) - 5) = genericRoot
  field_simp [h4, h27]
  linear_combination hN

private theorem to_from :
    toCompositumHom.comp fromCompositumHom = AlgHom.id K M := by
  apply AdjoinRoot.algHom_ext
  change toCompositumHom (fromCompositumHom s) = s
  rw [fromCompositumHom_s]
  simpa only [recoveredS, map_div₀, _root_.map_add,
    _root_.map_sub, _root_.map_mul, _root_.map_pow,
    _root_.map_ofNat, toCompositumHom_genericRoot] using
      recover_s_in_compositum

private theorem from_to :
    fromCompositumHom.comp toCompositumHom =
      AlgHom.id K descentCurve.toAffine.A := by
  apply AdjoinRoot.algHom_ext
  change fromCompositumHom (toCompositumHom genericRoot) = genericRoot
  rw [toCompositumHom_genericRoot]
  simpa only [descentRootInM, relativeTwoDivisionZ, map_div₀,
    _root_.map_add, _root_.map_sub, _root_.map_mul, _root_.map_pow,
    _root_.map_inv₀, _root_.map_ofNat, fromCompositumHom_s,
    AlgHom.commutes] using recover_genericRoot

/-- The generic `x - T` algebra is the explicit degree-nine compositum,
as an algebra over the real cubic coefficient field. -/
def descentAlgebraEquiv : descentCurve.toAffine.A ≃ₐ[K] M :=
  AlgEquiv.ofAlgHom toCompositumHom fromCompositumHom to_from from_to

@[simp]
theorem descentAlgebraEquiv_genericRoot :
    descentAlgebraEquiv genericRoot = descentRootInM := by
  exact toCompositumHom_genericRoot

/-- The induced equivalence on square classes. -/
def descentSquareclassEquiv :
    descentCurve.toAffine.M ≃* Units.modPow M 2 :=
  Units.modPow.congr descentAlgebraEquiv.toMulEquiv 2

end

end MazurTorsion.XOneEighteenDescentAlgebraEquiv
