/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI
-/

import EllipticCurves.X18SelmerCardinality
import MazurTorsion.NumberTheory.XOneEighteenCoefficientFieldArithmetic

/-!
# The dyadic supported squareclasses of the `X₁(18)` coefficient field

The rational prime `2` is inert in the real cubic coefficient field.  Thus
there is one dyadic place, the class of `2` supplies its nonzero valuation
parity, and the supported squareclass group has cardinality
`8 * 2 = 16`.
-/

open IsDedekindDomain NumberField Ideal RingOfIntegers
  UniqueFactorizationMonoid

namespace MazurTorsion.XOneEighteenCoefficientDyadicSelmer

noncomputable section

open EllipticCurves.X18SelmerCardinality
open MazurTorsion.XOneEighteenCoefficientFieldArithmetic
open MazurTorsion.XOneEighteenTwoDivisionPrincipalSmallPrimes

abbrev K := MazurTorsion.XOneEighteenRealCubicQuotient.K

/-- The even places of the real cubic coefficient field. -/
def coefficientDyadicSupport : Set (HeightOneSpectrum (𝓞 K)) :=
  {v | v.valuation K 2 ≠ 1}

/-- Squareclasses in the coefficient field supported at its even places. -/
abbrev DyadicSelmerK :=
  selmerGroup (R := 𝓞 K) (K := K)
    (S := coefficientDyadicSupport) (n := 2)

private instance : Fact (Nat.Prime 2) := ⟨by norm_num⟩

private noncomputable def chosenPrimeTwo :
    Ideal.primesOver (Ideal.span {(2 : ℤ)}) (𝓞 K) :=
  letI : (Ideal.span {(2 : ℤ)}).IsMaximal :=
    Int.ideal_span_isMaximal_of_prime 2
  Classical.choice inferInstance

/-- A selected height-one prime above `2`.  It is proved below that this
is the unique such prime. -/
def coefficientPrimeTwo : HeightOneSpectrum (𝓞 K) :=
  .ofPrime (Ideal.prime_of_mem_primesOver (by norm_num)
    chosenPrimeTwo.property)

@[simp] theorem coefficientPrimeTwo_asIdeal :
    coefficientPrimeTwo.asIdeal = chosenPrimeTwo := rfl

theorem coefficientPrimeTwo_mem_primesOver :
    coefficientPrimeTwo.asIdeal ∈
      Ideal.primesOver (Ideal.span {(2 : ℤ)}) (𝓞 K) := by
  simpa only [coefficientPrimeTwo_asIdeal] using chosenPrimeTwo.property

private theorem absNorm_prime_over_two
    (P : Ideal (𝓞 K))
    (hP : P ∈ Ideal.primesOver (Ideal.span {(2 : ℤ)}) (𝓞 K)) :
    P.absNorm = 8 := by
  letI : P.IsPrime := hP.1
  letI : P.LiesOver (Ideal.span {(2 : ℤ)}) := hP.2
  rw [← Ideal.pow_inertiaDeg 2 P,
    coefficient_inertiaDeg_eq_three_at_two P hP]
  norm_num

private theorem absNorm_span_two :
    Ideal.absNorm (Ideal.span {(2 : 𝓞 K)}) = 8 := by
  calc
    Ideal.absNorm (Ideal.span {(2 : 𝓞 K)}) =
        2 ^ Module.finrank ℤ (𝓞 K) := by
      simpa using (Ideal.absNorm_span_natCast (S := 𝓞 K) 2)
    _ = 8 := by
      rw [RingOfIntegers.rank, finrank_K_over_rat]
      norm_num

private theorem prime_over_two_dvd_span
    (P : Ideal (𝓞 K))
    (hP : P ∈ Ideal.primesOver (Ideal.span {(2 : ℤ)}) (𝓞 K)) :
    P ∣ Ideal.span {(2 : 𝓞 K)} := by
  letI : (Ideal.span {(2 : ℤ)}).IsMaximal :=
    Int.ideal_span_isMaximal_of_prime 2
  have hmap := (Ideal.liesOver_iff_dvd_map hP.1.ne_top).mp hP.2
  simpa only [Ideal.map_span, Set.image_singleton, map_ofNat] using hmap

private theorem eq_span_two_of_mem_primesOver
    (P : Ideal (𝓞 K))
    (hP : P ∈ Ideal.primesOver (Ideal.span {(2 : ℤ)}) (𝓞 K)) :
    P = Ideal.span {(2 : 𝓞 K)} := by
  obtain ⟨J, hJ⟩ := prime_over_two_dvd_span P hP
  have hnorm := congrArg Ideal.absNorm hJ
  rw [map_mul, absNorm_prime_over_two P hP, absNorm_span_two] at hnorm
  have hJnorm : J.absNorm = 1 := by omega
  have hJtop : J = ⊤ := Ideal.absNorm_eq_one_iff.mp hJnorm
  rw [hJtop, mul_top] at hJ
  exact hJ.symm

/-- The selected dyadic prime is the principal ideal generated by `2`. -/
theorem coefficientPrimeTwo_span :
    coefficientPrimeTwo.asIdeal = Ideal.span {(2 : 𝓞 K)} :=
  eq_span_two_of_mem_primesOver _ coefficientPrimeTwo_mem_primesOver

private theorem mem_coefficientDyadicSupport_iff
    (v : HeightOneSpectrum (𝓞 K)) :
    v ∈ coefficientDyadicSupport ↔ (2 : 𝓞 K) ∈ v.asIdeal := by
  rw [coefficientDyadicSupport, Set.mem_setOf_eq]
  constructor
  · intro hv
    by_contra hmem
    exact hv (v.valuation_eq_one_iff_notMem.mpr hmem)
  · intro hmem heq
    exact (v.valuation_eq_one_iff_notMem.mp heq) hmem

/-- The coefficient dyadic support consists of exactly one place. -/
theorem coefficientDyadicSupport_eq_singleton :
    coefficientDyadicSupport = {coefficientPrimeTwo} := by
  ext v
  rw [mem_coefficientDyadicSupport_iff, Set.mem_singleton_iff]
  constructor
  · intro htwo
    apply HeightOneSpectrum.ext
    have hspanLe : Ideal.span {(2 : 𝓞 K)} ≤ v.asIdeal := by
      rw [Ideal.span_singleton_le_iff_mem]
      exact htwo
    have hprimeLe : coefficientPrimeTwo.asIdeal ≤ v.asIdeal := by
      simpa only [coefficientPrimeTwo_span] using hspanLe
    exact
      (coefficientPrimeTwo.isMaximal.eq_of_le v.isPrime.ne_top hprimeLe).symm
  · intro hv
    subst v
    rw [coefficientPrimeTwo_span]
    exact Ideal.subset_span (Set.mem_singleton 2)

/-- The unique dyadic place as a one-element indexing equivalence. -/
def coefficientDyadicPlaceEquiv : Fin 1 ≃ coefficientDyadicSupport where
  toFun _ := ⟨coefficientPrimeTwo, by
    rw [coefficientDyadicSupport_eq_singleton]
    exact Set.mem_singleton _⟩
  invFun _ := 0
  left_inv i := Fin.ext (by omega)
  right_inv v := by
    apply Subtype.ext
    have hvMem : (v : HeightOneSpectrum (𝓞 K)) ∈
        ({coefficientPrimeTwo} : Set (HeightOneSpectrum (𝓞 K))) := by
      rw [← coefficientDyadicSupport_eq_singleton]
      exact v.property
    have hv : (v : HeightOneSpectrum (𝓞 K)) = coefficientPrimeTwo :=
      Set.mem_singleton_iff.mp hvMem
    exact hv.symm

theorem natCard_coefficientDyadicSupport :
    Nat.card coefficientDyadicSupport = 1 := by
  calc
    Nat.card coefficientDyadicSupport = Nat.card (Fin 1) :=
      (Nat.card_congr coefficientDyadicPlaceEquiv).symm
    _ = 1 := Nat.card_fin 1

private theorem two_ne_zero : (2 : K) ≠ 0 := by norm_num

/-- The coefficient-field squareclass of the dyadic uniformizer. -/
def twoSquareclass : Units.modPow K 2 :=
  QuotientGroup.mk (Units.mk0 (2 : K) two_ne_zero)

/-- The uniformizer squareclass is supported only at the dyadic place. -/
theorem twoSquareclass_mem : twoSquareclass ∈ DyadicSelmerK := by
  intro v hv
  change v.valuationOfNeZeroMod 2
      (QuotientGroup.mk (Units.mk0 (2 : K) two_ne_zero)) = 1
  rw [HeightOneSpectrum.valuationOfNeZeroMod_mk_eq_one_iff]
  have hval : v.valuation K (2 : K) = 1 := by
    by_contra hne
    exact hv hne
  have hvalUnit :
      v.valuationOfNeZero (Units.mk0 (2 : K) two_ne_zero) = 1 := by
    rw [v.valuationOfNeZero_eq_iff]
    simpa only [Units.val_mk0, WithZero.coe_one] using hval
  rw [hvalUnit]
  simp

/-- The supported uniformizer class. -/
def dyadicTwo : DyadicSelmerK := ⟨twoSquareclass, twoSquareclass_mem⟩

private theorem coefficientPrimeTwo_valuation_two :
    coefficientPrimeTwo.valuation K (2 : K) =
      WithZero.exp (-1 : ℤ) := by
  calc
    coefficientPrimeTwo.valuation K (2 : K) =
        coefficientPrimeTwo.intValuation (2 : 𝓞 K) := by
      simpa only [map_ofNat] using
        coefficientPrimeTwo.valuation_of_algebraMap (K := K) (2 : 𝓞 K)
    _ = WithZero.exp (-1 : ℤ) := by
      rw [coefficientPrimeTwo.intValuation_eq_exp_neg_multiplicity
          (by norm_num), coefficientPrimeTwo_span]
      simp

private theorem coefficientPrimeTwo_valuationOfNeZero_two :
    coefficientPrimeTwo.valuationOfNeZero
        (Units.mk0 (2 : K) two_ne_zero) =
      Multiplicative.ofAdd (-1 : ℤ) := by
  rw [coefficientPrimeTwo.valuationOfNeZero_eq_iff]
  change coefficientPrimeTwo.valuation K (2 : K) =
    WithZero.exp (-1 : ℤ)
  exact coefficientPrimeTwo_valuation_two

private theorem eq_one_or_parityOne (z : Multiplicative (ZMod 2)) :
    z = 1 ∨ z = parityOne := by
  cases z with
  | ofAdd z =>
      fin_cases z
      · left
        apply Multiplicative.toAdd.injective
        rfl
      · right
        rfl

private theorem dyadicTwo_valuation_ne_one :
    supportValuation (R := 𝓞 K) (K := K)
      coefficientDyadicSupport 2 dyadicTwo
        ⟨coefficientPrimeTwo, by
          rw [coefficientDyadicSupport_eq_singleton]
          exact Set.mem_singleton _⟩ ≠ 1 := by
  intro hone
  have hdvd : (2 : ℤ) ∣ Multiplicative.toAdd
      (coefficientPrimeTwo.valuationOfNeZero
        (Units.mk0 (2 : K) two_ne_zero)) := by
    apply (HeightOneSpectrum.valuationOfNeZeroMod_mk_eq_one_iff
      coefficientPrimeTwo 2 (Units.mk0 (2 : K) two_ne_zero)).mp
    exact hone
  rw [coefficientPrimeTwo_valuationOfNeZero_two] at hdvd
  norm_num at hdvd

private theorem dyadicTwo_valuation_eq_parityOne :
    supportValuation (R := 𝓞 K) (K := K)
      coefficientDyadicSupport 2 dyadicTwo
        ⟨coefficientPrimeTwo, by
          rw [coefficientDyadicSupport_eq_singleton]
          exact Set.mem_singleton _⟩ = parityOne := by
  rcases eq_one_or_parityOne
      (supportValuation (R := 𝓞 K) (K := K)
        coefficientDyadicSupport 2 dyadicTwo
          ⟨coefficientPrimeTwo, by
            rw [coefficientDyadicSupport_eq_singleton]
            exact Set.mem_singleton _⟩) with h | h
  · exact False.elim (dyadicTwo_valuation_ne_one h)
  · exact h

/-- Every parity at the unique dyadic place is realized. -/
theorem coefficientSupportValuation_surjective :
    Function.Surjective
      (supportValuation (R := 𝓞 K) (K := K)
        coefficientDyadicSupport 2) := by
  intro y
  let vTwo : coefficientDyadicSupport :=
    ⟨coefficientPrimeTwo, by
      rw [coefficientDyadicSupport_eq_singleton]
      exact Set.mem_singleton _⟩
  rcases eq_one_or_parityOne (y vTwo) with hy | hy
  · refine ⟨1, ?_⟩
    funext v
    have hv : v = vTwo := by
      apply Subtype.ext
      have hvMem : (v : HeightOneSpectrum (𝓞 K)) ∈
          ({coefficientPrimeTwo} : Set (HeightOneSpectrum (𝓞 K))) := by
        rw [← coefficientDyadicSupport_eq_singleton]
        exact v.property
      have hv' : (v : HeightOneSpectrum (𝓞 K)) = coefficientPrimeTwo :=
        Set.mem_singleton_iff.mp hvMem
      simpa only [vTwo] using hv'
    subst v
    simpa only [map_one, Pi.one_apply] using hy.symm
  · refine ⟨dyadicTwo, ?_⟩
    funext v
    have hv : v = vTwo := by
      apply Subtype.ext
      have hvMem : (v : HeightOneSpectrum (𝓞 K)) ∈
          ({coefficientPrimeTwo} : Set (HeightOneSpectrum (𝓞 K))) := by
        rw [← coefficientDyadicSupport_eq_singleton]
        exact v.property
      have hv' : (v : HeightOneSpectrum (𝓞 K)) = coefficientPrimeTwo :=
        Set.mem_singleton_iff.mp hvMem
      simpa only [vTwo] using hv'
    subst v
    exact dyadicTwo_valuation_eq_parityOne.trans hy.symm

/-- The dyadically supported coefficient-field squareclass group has
exactly sixteen elements. -/
theorem natCard_dyadicSelmerK : Nat.card DyadicSelmerK = 16 := by
  letI : IsPrincipalIdealRing (𝓞 K) :=
    coefficientRingOfIntegers_isPrincipal
  letI : Subsingleton (ClassGroup (𝓞 K)) := inferInstance
  letI : Fact (0 < (2 : ℕ)) := ⟨by norm_num⟩
  letI : NeZero (2 : ℕ) := ⟨by norm_num⟩
  letI : Finite coefficientDyadicSupport :=
    Nat.finite_of_card_ne_zero
      (natCard_coefficientDyadicSupport.trans_ne (by norm_num))
  letI : Finite (Units.modPow (𝓞 K) 2) :=
    Nat.finite_of_card_ne_zero
      (natCard_coefficientUnitsModSq.trans_ne (by norm_num))
  have hempty :
      Nat.card
          (selmerGroup (R := 𝓞 K) (K := K)
            (S := (∅ : Set (HeightOneSpectrum (𝓞 K)))) (n := 2)) = 8 :=
    (natCard_emptySelmer_eq_unitsModPow
      (R := 𝓞 K) (K := K) 2).trans natCard_coefficientUnitsModSq
  letI : Finite
      (selmerGroup (R := 𝓞 K) (K := K)
        (S := (∅ : Set (HeightOneSpectrum (𝓞 K)))) (n := 2)) :=
    Nat.finite_of_card_ne_zero (hempty.trans_ne (by norm_num))
  rw [natCard_supportedSelmer_eq_of_valuation_surjective
    (R := 𝓞 K) (K := K) coefficientDyadicSupport 2
      coefficientSupportValuation_surjective,
    hempty, natCard_coefficientDyadicSupport]
  norm_num

end

end MazurTorsion.XOneEighteenCoefficientDyadicSelmer
