/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenPicardCoordinateRing
import MazurTorsion.NumberTheory.XOneThirteenTwoDescentSextic
import Mathlib.RingTheory.ClassGroup.Basic
import Mathlib.RingTheory.Polynomial.Eisenstein.Basic

/-!
# Explicit affine Picard classes for `X₁(13)`

The coordinate ring of the fixed affine genus-two curve is a domain.  This
file proves that fact by an Eisenstein certificate in the outer variable
`Y`, at the prime generated by the irreducible sextic in `ℚ[X]`.  It then
packages the point ideals from `XOneThirteenPicardCoordinateRing` as
invertible fractional ideals, hence as honest elements of the ideal class
group.

This is the Picard group of the affine coordinate ring.  Relating it to the
degree-zero Picard group of the smooth projective curve, including the two
points at infinity, is a separate geometric step.
-/

namespace MazurTorsion.XOneThirteenPicard

open Ideal IsFractionRing Polynomial
open scoped nonZeroDivisors

open XOneThirteenMumford
open XOneThirteenTwoDescentSextic

noncomputable section

theorem sexticPolynomial_eq_rationalSextic :
    sexticPolynomial = rationalSextic := by
  simp [sexticPolynomial, rationalSextic]

theorem sexticPolynomial_irreducible : Irreducible sexticPolynomial := by
  rw [sexticPolynomial_eq_rationalSextic]
  exact rationalSextic_irreducible

theorem sexticPolynomial_natDegree : sexticPolynomial.natDegree = 6 := by
  simp only [sexticPolynomial]
  compute_degree!

private theorem relationPolynomial_isEisenstein :
    relationPolynomial.IsEisensteinAt (Ideal.span {sexticPolynomial}) := by
  apply relationPolynomial_monic.isEisensteinAt_of_mem_of_notMem
  · exact (Ideal.isPrime_span_singleton_of_prime
      sexticPolynomial_irreducible.prime).ne_top
  · intro n hn
    rw [relationPolynomial_natDegree] at hn
    interval_cases n <;>
      simp [relationPolynomial]
  · simp only [relationPolynomial, coeff_sub, coeff_X_pow, coeff_C,
      if_neg (by norm_num : (0 : ℕ) ≠ 2), zero_sub]
    simp only [if_true]
    rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    rintro ⟨a, ha⟩
    have hdiv : sexticPolynomial ^ 2 ∣ sexticPolynomial := by
      refine ⟨-a, ?_⟩
      linear_combination -ha
    have hdegree := natDegree_le_of_dvd hdiv
      sexticPolynomial_irreducible.ne_zero
    rw [natDegree_pow, sexticPolynomial_natDegree] at hdegree
    omega

theorem relationPolynomial_irreducible : Irreducible relationPolynomial :=
  relationPolynomial_isEisenstein.irreducible
    (Ideal.isPrime_span_singleton_of_prime
      sexticPolynomial_irreducible.prime)
    relationPolynomial_monic.isPrimitive
    (by rw [relationPolynomial_natDegree]; omega)

/-- The fixed affine coordinate ring is an integral domain. -/
noncomputable instance CoordinateRing.instIsDomain : IsDomain CoordinateRing :=
  AdjoinRoot.isDomain_of_prime relationPolynomial_irreducible.prime

namespace CoordinateRing

/-- The fraction field used for explicit affine Picard classes. -/
abbrev FractionField := FractionRing CoordinateRing

private theorem algebraMap_coordinateRing_injective :
    Function.Injective (algebraMap ℚ[X] CoordinateRing) := by
  exact AdjoinRoot.of.injective_of_degree_ne_zero (by
    rw [degree_eq_natDegree relationPolynomial_monic.ne_zero,
      relationPolynomial_natDegree]
    norm_num)

theorem xClass_ne_zero (x : ℚ) : xClass x ≠ 0 := by
  intro hx
  have hpoly : X - C x = (0 : ℚ[X]) := by
    apply algebraMap_coordinateRing_injective
    simpa only [map_zero, xClass] using hx
  have hcoeff := congrArg (fun p : ℚ[X] ↦ p.coeff 1) hpoly
  norm_num at hcoeff

theorem xClass_fraction_ne_zero (x : ℚ) :
    algebraMap CoordinateRing FractionField (xClass x) ≠ 0 :=
  by
    simpa only [map_zero] using
      (IsFractionRing.injective CoordinateRing FractionField).ne (xClass_ne_zero x)

/-- An integral point ideal, embedded into the fractional-ideal monoid. -/
noncomputable def pointFractionalIdeal (x y : ℚ) :
    FractionalIdeal CoordinateRing⁰ FractionField :=
  (pointIdeal x y : Ideal CoordinateRing)

/-- The checked product of conjugate point ideals, now in the fractional
ideal monoid. -/
theorem pointFractionalIdeal_neg_mul_pointFractionalIdeal
    {x y : ℚ} (hcurve : IsAffinePoint x y) (hy : y ≠ 0) :
    pointFractionalIdeal x (-y) * pointFractionalIdeal x y =
      FractionalIdeal.spanSingleton CoordinateRing⁰
        (algebraMap CoordinateRing FractionField (xClass x)) := by
  simp only [pointFractionalIdeal]
  rw [← FractionalIdeal.coeIdeal_mul,
    pointIdeal_neg_mul_pointIdeal hcurve hy,
    xIdeal,
    FractionalIdeal.coeIdeal_span_singleton]

/-- A displayed fractional ideal inverse for a non-Weierstrass affine
point ideal. -/
noncomputable def pointFractionalIdealInverse (x y : ℚ) :
    FractionalIdeal CoordinateRing⁰ FractionField :=
  FractionalIdeal.spanSingleton CoordinateRing⁰
      (algebraMap CoordinateRing FractionField (xClass x))⁻¹ *
    pointFractionalIdeal x (-y)

private theorem pointFractionalIdeal_mul_inverse
    {x y : ℚ} (hcurve : IsAffinePoint x y) (hy : y ≠ 0) :
    pointFractionalIdeal x y * pointFractionalIdealInverse x y = 1 := by
  rw [pointFractionalIdealInverse]
  calc
    pointFractionalIdeal x y *
        (FractionalIdeal.spanSingleton CoordinateRing⁰
            (algebraMap CoordinateRing FractionField (xClass x))⁻¹ *
          pointFractionalIdeal x (-y)) =
        FractionalIdeal.spanSingleton CoordinateRing⁰
            (algebraMap CoordinateRing FractionField (xClass x))⁻¹ *
          (pointFractionalIdeal x (-y) * pointFractionalIdeal x y) := by
            ac_rfl
    _ = FractionalIdeal.spanSingleton CoordinateRing⁰
          (algebraMap CoordinateRing FractionField (xClass x))⁻¹ *
        FractionalIdeal.spanSingleton CoordinateRing⁰
          (algebraMap CoordinateRing FractionField (xClass x)) := by
      rw [pointFractionalIdeal_neg_mul_pointFractionalIdeal hcurve hy]
    _ = 1 := by
      rw [FractionalIdeal.spanSingleton_mul_spanSingleton,
        inv_mul_cancel₀ (xClass_fraction_ne_zero x),
        FractionalIdeal.spanSingleton_one]

/-- The invertible fractional ideal attached to a non-Weierstrass affine
point. -/
noncomputable def pointFractionalIdealUnit
    (x y : ℚ) (hcurve : IsAffinePoint x y) (hy : y ≠ 0) :
    (FractionalIdeal CoordinateRing⁰ FractionField)ˣ :=
  Units.mkOfMulEqOne (pointFractionalIdeal x y)
    (pointFractionalIdealInverse x y)
    (pointFractionalIdeal_mul_inverse hcurve hy)

/-- The honest affine ideal class attached to a non-Weierstrass rational
point. -/
noncomputable def pointClass
    (x y : ℚ) (hcurve : IsAffinePoint x y) (hy : y ≠ 0) :
    ClassGroup CoordinateRing :=
  ClassGroup.mk FractionField (pointFractionalIdealUnit x y hcurve hy)

theorem isAffinePoint_neg {x y : ℚ} (hcurve : IsAffinePoint x y) :
    IsAffinePoint x (-y) := by
  simpa only [IsAffinePoint, neg_sq] using hcurve

private theorem pointFractionalIdealUnit_neg_mul
    {x y : ℚ} (hcurve : IsAffinePoint x y) (hy : y ≠ 0) :
    pointFractionalIdealUnit x (-y) (isAffinePoint_neg hcurve)
        (neg_ne_zero.mpr hy) *
      pointFractionalIdealUnit x y hcurve hy =
        toPrincipalIdeal CoordinateRing FractionField
          (Units.mk0 (algebraMap CoordinateRing FractionField (xClass x))
            (xClass_fraction_ne_zero x)) := by
  apply Units.ext
  rw [Units.val_mul, coe_toPrincipalIdeal, Units.val_mk0]
  exact pointFractionalIdeal_neg_mul_pointFractionalIdeal hcurve hy

/-- Hyperelliptic conjugate points give inverse affine Picard classes. -/
theorem pointClass_neg_mul
    {x y : ℚ} (hcurve : IsAffinePoint x y) (hy : y ≠ 0) :
    pointClass x (-y) (isAffinePoint_neg hcurve) (neg_ne_zero.mpr hy) *
      pointClass x y hcurve hy = 1 := by
  rw [pointClass, pointClass, ← map_mul,
    pointFractionalIdealUnit_neg_mul hcurve hy]
  apply (ClassGroup.mk_eq_one_iff).2
  rw [coe_toPrincipalIdeal, FractionalIdeal.coe_spanSingleton]
  exact ⟨⟨_, rfl⟩⟩

private theorem cuspZero_isAffinePoint : IsAffinePoint 0 1 := by
  norm_num [IsAffinePoint, sexticPolynomial]

/-- The affine Picard class of the cusp `(0,1)`. -/
noncomputable def cuspZeroClass : ClassGroup CoordinateRing :=
  pointClass 0 1 cuspZero_isAffinePoint one_ne_zero

/-- The affine Picard class of its hyperelliptic conjugate `(0,-1)`. -/
noncomputable def cuspZeroConjugateClass : ClassGroup CoordinateRing :=
  pointClass 0 (-1) (isAffinePoint_neg cuspZero_isAffinePoint) (by norm_num)

/-- Concrete cusp consumer of the conjugate-inverse law. -/
theorem cuspZeroConjugateClass_mul_cuspZeroClass :
    cuspZeroConjugateClass * cuspZeroClass = 1 := by
  exact pointClass_neg_mul cuspZero_isAffinePoint one_ne_zero

end CoordinateRing

end

end MazurTorsion.XOneThirteenPicard
