/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneEighteenRealCubicQuotient
import Mathlib.Algebra.CubicDiscriminant
import Mathlib.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Degree
import Mathlib.FieldTheory.Normal.Basic

/-!
# Excluding three-torsion on the `X₁(18)` elliptic quotient

The third division polynomial of the real-cubic quotient has a linear
factor and a cubic factor.  The linear factor would make `-3` a square in
the coefficient field.  After an exact translation, the cubic factor is
the rational cubic `Z³ + 6Z - 2`.  The coefficient field is the normal
cubic field generated by a root of `T³ - 3T - 1`; normality would make the
second cubic split there.  Its discriminant is `-972`, so this would again
put a square root of `-3` in a cubic field, contradicting the tower-degree
formula.

All arguments are internal algebraic certificates.  In particular, no
injectivity assertion for reduction of torsion is used.
-/

open Polynomial WeierstrassCurve
open scoped WeierstrassCurve.Affine

namespace MazurTorsion.XOneEighteenQuotientThreeTorsion

noncomputable section

open MazurTorsion.XOneEighteenRealCubicQuotient

private theorem tau_pow_four : tau ^ 4 = 3 * tau ^ 2 + tau := by
  calc
    tau ^ 4 = tau * tau ^ 3 := by ring
    _ = 3 * tau ^ 2 + tau := by rw [tau_cubic]; ring

private theorem tau_pow_five : tau ^ 5 = tau ^ 2 + 9 * tau + 3 := by
  calc
    tau ^ 5 = tau * tau ^ 4 := by ring
    _ = tau * (3 * tau ^ 2 + tau) := by rw [tau_pow_four]
    _ = 3 * tau ^ 3 + tau ^ 2 := by ring
    _ = tau ^ 2 + 9 * tau + 3 := by rw [tau_cubic]; ring

private theorem tau_pow_six : tau ^ 6 = 9 * tau ^ 2 + 6 * tau + 1 := by
  calc
    tau ^ 6 = tau * tau ^ 5 := by ring
    _ = tau * (tau ^ 2 + 9 * tau + 3) := by rw [tau_pow_five]
    _ = tau ^ 3 + 9 * tau ^ 2 + 3 * tau := by ring
    _ = 9 * tau ^ 2 + 6 * tau + 1 := by rw [tau_cubic]; ring

private theorem tau_pow_seven : tau ^ 7 = 6 * tau ^ 2 + 28 * tau + 9 := by
  calc
    tau ^ 7 = tau * tau ^ 6 := by ring
    _ = tau * (9 * tau ^ 2 + 6 * tau + 1) := by rw [tau_pow_six]
    _ = 9 * tau ^ 3 + 6 * tau ^ 2 + tau := by ring
    _ = 6 * tau ^ 2 + 28 * tau + 9 := by rw [tau_cubic]; ring

private theorem tau_pow_eight : tau ^ 8 = 28 * tau ^ 2 + 27 * tau + 6 := by
  calc
    tau ^ 8 = tau * tau ^ 7 := by ring
    _ = tau * (6 * tau ^ 2 + 28 * tau + 9) := by rw [tau_pow_seven]
    _ = 6 * tau ^ 3 + 28 * tau ^ 2 + 9 * tau := by ring
    _ = 28 * tau ^ 2 + 27 * tau + 6 := by rw [tau_cubic]; ring

/-! ## The normal coefficient cubic -/

private theorem coefficientPolynomial_map_factorization :
    cubicPolynomial.map (algebraMap ℚ K) =
      (X - C tau) * (X - C (tau ^ 2 - tau - 2)) *
        (X - C (-tau ^ 2 + 2)) := by
  change ((X ^ 3 - 3 * X - 1 : Polynomial ℚ).map
    (algebraMap ℚ K)) = _
  simp only [Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_mul,
    Polynomial.map_ofNat, Polynomial.map_one, map_X]
  have hsum :
      tau + (tau ^ 2 - tau - 2) + (-tau ^ 2 + 2) = 0 := by
    ring
  have hpairs :
      tau * (tau ^ 2 - tau - 2) + tau * (-tau ^ 2 + 2) +
        (tau ^ 2 - tau - 2) * (-tau ^ 2 + 2) = -3 := by
    ring_nf
    simp only [tau_pow_four, tau_cubic]
    ring
  have hprod :
      tau * (tau ^ 2 - tau - 2) * (-tau ^ 2 + 2) = 1 := by
    ring_nf
    simp only [tau_pow_five, tau_pow_four, tau_cubic]
    ring
  calc
    (X ^ 3 - 3 * X - 1 : Polynomial K) =
        X ^ 3 - C (tau + (tau ^ 2 - tau - 2) + (-tau ^ 2 + 2)) * X ^ 2 +
          C (tau * (tau ^ 2 - tau - 2) + tau * (-tau ^ 2 + 2) +
            (tau ^ 2 - tau - 2) * (-tau ^ 2 + 2)) * X -
          C (tau * (tau ^ 2 - tau - 2) * (-tau ^ 2 + 2)) := by
      rw [hsum, hpairs, hprod]
      norm_num
      rw [C_ofNat]
      ring
    _ = (X - C tau) * (X - C (tau ^ 2 - tau - 2)) *
        (X - C (-tau ^ 2 + 2)) := by
      simp only [C_add, C_sub, C_neg, C_mul]
      ring

private theorem coefficientPolynomial_splits :
    (cubicPolynomial.map (algebraMap ℚ K)).Splits := by
  rw [coefficientPolynomial_map_factorization]
  exact ((Splits.X_sub_C tau).mul
    (Splits.X_sub_C (tau ^ 2 - tau - 2))).mul
      (Splits.X_sub_C (-tau ^ 2 + 2))

private theorem tau_mem_coefficientPolynomial_rootSet :
    tau ∈ cubicPolynomial.rootSet K := by
  rw [mem_rootSet_of_ne cubicPolynomial_irreducible.ne_zero]
  simp only [Polynomial.aeval_def, cubicPolynomial, eval₂_sub, eval₂_X_pow,
    eval₂_mul, eval₂_X, eval₂_ofNat, eval₂_one]
  linear_combination tau_cubic

private instance coefficientField_isSplittingField :
    Polynomial.IsSplittingField ℚ K cubicPolynomial where
  splits' := coefficientPolynomial_splits
  adjoin_rootSet' := by
    apply top_unique
    calc
      ⊤ = Algebra.adjoin ℚ ({tau} : Set K) :=
        (AdjoinRoot.adjoinRoot_eq_top (f := cubicPolynomial)).symm
      _ ≤ Algebra.adjoin ℚ (cubicPolynomial.rootSet K) := by
        apply Algebra.adjoin_mono
        intro z hz
        rw [Set.mem_singleton_iff] at hz
        simpa only [hz] using tau_mem_coefficientPolynomial_rootSet

private instance coefficientField_normal : Normal ℚ K :=
  Normal.of_isSplittingField cubicPolynomial

private theorem finrank_coefficientField : Module.finrank ℚ K = 3 := by
  calc
    Module.finrank ℚ K = cubicPolynomial.natDegree :=
      (AdjoinRoot.powerBasis cubicPolynomial_irreducible.ne_zero).finrank
    _ = 3 := by
      simp only [cubicPolynomial]
      compute_degree!

/-! ## A cubic field has no quadratic subfield -/

private def negThreePolynomial : Polynomial ℚ :=
  X ^ 2 + 3

private theorem negThreePolynomial_monic : negThreePolynomial.Monic := by
  simp only [negThreePolynomial]
  monicity
  norm_num

private theorem negThreePolynomial_natDegree :
    negThreePolynomial.natDegree = 2 := by
  simp only [negThreePolynomial]
  compute_degree!

private theorem negThreePolynomial_irreducible :
    Irreducible negThreePolynomial := by
  refine Polynomial.irreducible_of_degree_le_three_of_not_isRoot
    (p := negThreePolynomial) ?_ ?_
  · rw [negThreePolynomial_natDegree]
    norm_num
  · intro z
    unfold Polynomial.IsRoot
    simp only [negThreePolynomial, eval_add, eval_pow, eval_X,
      eval_ofNat]
    nlinarith [sq_nonneg z]

private theorem no_square_root_neg_three (z : K) : z ^ 2 ≠ -3 := by
  intro hz
  have hsplits :
      (negThreePolynomial.map (algebraMap ℚ K)).Splits := by
    apply Splits.of_natDegree_eq_two (x := z)
    · rw [negThreePolynomial_monic.natDegree_map]
      exact negThreePolynomial_natDegree
    · rw [eval_map_algebraMap]
      simp only [negThreePolynomial, Polynomial.aeval_def, eval₂_add,
        eval₂_X_pow, eval₂_ofNat]
      linear_combination hz
  have hdvd :=
    negThreePolynomial_irreducible.natDegree_dvd_finrank hsplits
  rw [negThreePolynomial_natDegree, finrank_coefficientField] at hdvd
  norm_num at hdvd

/-! ## The translated cubic factor -/

private def depressedPolynomialInt : Polynomial ℤ :=
  X ^ 3 + 6 * X - 2

private theorem depressedPolynomialInt_monic :
    depressedPolynomialInt.Monic := by
  simp only [depressedPolynomialInt]
  monicity <;> norm_num

private theorem depressedPolynomialInt_mod_seven :
    depressedPolynomialInt.map (Int.castRingHom (ZMod 7)) =
      (X ^ 3 + 6 * X - 2 : Polynomial (ZMod 7)) := by
  norm_num [depressedPolynomialInt]

private theorem depressedPolynomial_mod_seven_irreducible :
    Irreducible (X ^ 3 + 6 * X - 2 : Polynomial (ZMod 7)) := by
  letI : Fact (Nat.Prime 7) := ⟨by decide⟩
  have hdegree :
      (X ^ 3 + 6 * X - 2 : Polynomial (ZMod 7)).natDegree = 3 := by
    compute_degree <;> norm_num
  refine Polynomial.irreducible_of_degree_le_three_of_not_isRoot
    (p := (X ^ 3 + 6 * X - 2 : Polynomial (ZMod 7))) ?_ ?_
  · rw [hdegree]
    norm_num
  · intro z
    unfold Polynomial.IsRoot
    simp only [eval_sub, eval_add, eval_mul, eval_pow, eval_X, eval_ofNat]
    fin_cases z
    · change ¬ ((0 : ZMod 7) ^ 3 + 6 * 0 - 2 = 0)
      decide
    · change ¬ ((1 : ZMod 7) ^ 3 + 6 * 1 - 2 = 0)
      decide
    · change ¬ ((2 : ZMod 7) ^ 3 + 6 * 2 - 2 = 0)
      decide
    · change ¬ ((3 : ZMod 7) ^ 3 + 6 * 3 - 2 = 0)
      decide
    · change ¬ ((4 : ZMod 7) ^ 3 + 6 * 4 - 2 = 0)
      decide
    · change ¬ ((5 : ZMod 7) ^ 3 + 6 * 5 - 2 = 0)
      decide
    · change ¬ ((6 : ZMod 7) ^ 3 + 6 * 6 - 2 = 0)
      decide

private theorem depressedPolynomialInt_irreducible :
    Irreducible depressedPolynomialInt := by
  letI : Fact (Nat.Prime 7) := ⟨by decide⟩
  apply depressedPolynomialInt_monic.irreducible_of_irreducible_map
    (Int.castRingHom (ZMod 7))
  simpa only [depressedPolynomialInt_mod_seven] using
    depressedPolynomial_mod_seven_irreducible

private def depressedPolynomial : Polynomial ℚ :=
  X ^ 3 + 6 * X - 2

private theorem depressedPolynomial_eq_map_int :
    depressedPolynomialInt.map (algebraMap ℤ ℚ) =
      depressedPolynomial := by
  norm_num [depressedPolynomialInt, depressedPolynomial]

private theorem depressedPolynomial_monic : depressedPolynomial.Monic := by
  simp only [depressedPolynomial]
  monicity <;> norm_num

private theorem depressedPolynomial_natDegree :
    depressedPolynomial.natDegree = 3 := by
  simp only [depressedPolynomial]
  compute_degree!

private theorem depressedPolynomial_irreducible :
    Irreducible depressedPolynomial := by
  rw [← depressedPolynomial_eq_map_int]
  exact
    (depressedPolynomialInt_monic.irreducible_iff_irreducible_map_fraction_map
      (K := ℚ)).mp depressedPolynomialInt_irreducible

private def depressedCubic : Cubic ℚ :=
  ⟨1, 0, 6, -2⟩

private theorem depressedCubic_toPoly :
    depressedCubic.toPoly = depressedPolynomial := by
  simp [depressedCubic, depressedPolynomial, Cubic.toPoly,
    ← Polynomial.C_ofNat, sub_eq_add_neg]

private theorem depressedCubic_discriminant :
    depressedCubic.discr = -972 := by
  norm_num [depressedCubic, Cubic.discr]

private theorem depressedPolynomial_no_root (z : K) :
    Polynomial.eval z (depressedPolynomial.map (algebraMap ℚ K)) ≠ 0 := by
  intro hz
  have hmin : depressedPolynomial = minpoly ℚ z := by
    apply minpoly.eq_of_irreducible_of_monic depressedPolynomial_irreducible
    · change Polynomial.eval₂ (algebraMap ℚ K) z depressedPolynomial = 0
      rw [← eval_map]
      exact hz
    · exact depressedPolynomial_monic
  have hsplits :
      (depressedPolynomial.map (algebraMap ℚ K)).Splits := by
    rw [hmin]
    exact Normal.splits coefficientField_normal z
  have hsplitsCubic :
      (depressedCubic.toPoly.map (algebraMap ℚ K)).Splits := by
    rwa [depressedCubic_toPoly]
  have ha : depressedCubic.a ≠ 0 := by
    norm_num [depressedCubic]
  obtain ⟨a, b, c, hroots⟩ :=
    (Cubic.splits_iff_roots_eq_three
      (P := depressedCubic) (φ := algebraMap ℚ K) ha).mp
        hsplitsCubic
  have hdisc := Cubic.discr_eq_prod_three_roots
    (P := depressedCubic) (φ := algebraMap ℚ K)
    (x := a) (y := b) (z := c) ha hroots
  rw [depressedCubic_discriminant] at hdisc
  let w : K :=
    algebraMap ℚ K depressedCubic.a *
      algebraMap ℚ K depressedCubic.a *
        (a - b) * (a - c) * (b - c)
  have hw : w ^ 2 = (-972 : K) := by
    dsimp only [w]
    simpa using hdisc.symm
  apply no_square_root_neg_three (w / 18)
  calc
    (w / 18) ^ 2 = w ^ 2 / 324 := by ring
    _ = (-972 : K) / 324 := by rw [hw]
    _ = -3 := by norm_num

/-! ## The third division polynomial -/

private theorem tangent_forces_three_division
    {a₁ a₂ a₃ a₄ a₆ x y slope : K}
    (hcurve :
      y ^ 2 + a₁ * x * y + a₃ * y =
        x ^ 3 + a₂ * x ^ 2 + a₄ * x + a₆)
    (hslope :
      slope * (2 * y + a₁ * x + a₃) =
        3 * x ^ 2 + 2 * a₂ * x + a₄ - a₁ * y)
    (hx : slope ^ 2 + a₁ * slope - a₂ - 3 * x = 0) :
    3 * x ^ 4 + (a₁ ^ 2 + 4 * a₂) * x ^ 3 +
      3 * (a₁ * a₃ + 2 * a₄) * x ^ 2 +
      3 * (a₃ ^ 2 + 4 * a₆) * x +
      (a₁ ^ 2 * a₆ + 4 * a₂ * a₆ - a₁ * a₃ * a₄ +
        a₂ * a₃ ^ 2 - a₄ ^ 2) = 0 := by
  linear_combination
    -(2 * y + a₁ * x + a₃) ^ 2 * hx +
    ((3 * x ^ 2 + 2 * a₂ * x + a₄ - a₁ * y) +
      slope * (2 * y + a₁ * x + a₃) +
      a₁ * (2 * y + a₁ * x + a₃)) * hslope -
    (a₁ ^ 2 + 4 * a₂ + 12 * x) * hcurve

private theorem eval_psi_three_eq_zero_of_three_nsmul
    {x y : K} (hP : quotientCurve.toAffine.Nonsingular x y)
    (hthree : (3 : ℕ) •
      WeierstrassCurve.Affine.Point.some x y hP = 0) :
    Polynomial.eval x quotientCurve.toAffine.Ψ₃ = 0 := by
  let P := WeierstrassCurve.Affine.Point.some x y hP
  have hthree' : (2 : ℕ) • P + P = 0 := by
    simpa [P, three_nsmul, two_nsmul, add_assoc] using hthree
  have hdouble : (2 : ℕ) • P = -P := by
    rw [← add_eq_zero_iff_eq_neg]
    exact hthree'
  have hy : y ≠ quotientCurve.toAffine.negY x y := by
    intro hy
    have htwo : (2 : ℕ) • P = 0 := by
      change (2 : ℕ) • WeierstrassCurve.Affine.Point.some x y hP = 0
      rw [two_nsmul,
        WeierstrassCurve.Affine.Point.add_self_of_Y_eq hy]
    have hzero : P = 0 := by
      rw [htwo, zero_add] at hthree'
      exact hthree'
    exact WeierstrassCurve.Affine.Point.some_ne_zero hP hzero
  let slope := quotientCurve.toAffine.slope x x y y
  have hadd :=
    WeierstrassCurve.Affine.Point.add_self_of_Y_ne (h₁ := hP) hy
  have hxcoord : quotientCurve.toAffine.addX x x slope = x := by
    have hsum : P + P = -P := by
      simpa [two_nsmul] using hdouble
    have hsome := hadd.symm.trans hsum
    exact (WeierstrassCurve.Affine.Point.some.inj hsome).1
  have hslope :
      slope * (2 * y + quotientCurve.toAffine.a₁ * x +
        quotientCurve.toAffine.a₃) =
      3 * x ^ 2 + 2 * quotientCurve.toAffine.a₂ * x +
        quotientCurve.toAffine.a₄ - quotientCurve.toAffine.a₁ * y := by
    have hden : y - quotientCurve.toAffine.negY x y =
        2 * y + quotientCurve.toAffine.a₁ * x +
          quotientCurve.toAffine.a₃ := by
      simp only [WeierstrassCurve.Affine.negY]
      ring
    dsimp [slope]
    rw [← hden, WeierstrassCurve.Affine.slope_of_Y_ne rfl hy,
      div_mul_cancel₀ _ (sub_ne_zero.mpr hy)]
  have hx : slope ^ 2 + quotientCurve.toAffine.a₁ * slope -
      quotientCurve.toAffine.a₂ - 3 * x = 0 := by
    simp only [WeierstrassCurve.Affine.addX] at hxcoord
    linear_combination hxcoord
  have hcurve := hP.1
  rw [WeierstrassCurve.Affine.equation_iff] at hcurve
  have hpsi := tangent_forces_three_division hcurve hslope hx
  simp only [WeierstrassCurve.Ψ₃, Polynomial.eval_add,
    Polynomial.eval_mul, Polynomial.eval_pow, Polynomial.eval_C,
    Polynomial.eval_X, Polynomial.eval_ofNat, WeierstrassCurve.b₂,
    WeierstrassCurve.b₄, WeierstrassCurve.b₆, WeierstrassCurve.b₈]
  ring_nf at hpsi ⊢
  exact hpsi

private theorem quotientCurve_psi_three_factorization (x : K) :
    Polynomial.eval x quotientCurve.toAffine.Ψ₃ =
      (3 * x + tau ^ 2 + tau - 2) *
        ((x + (tau ^ 2 + tau - 3) / 3) ^ 3 +
          (2 / 3) * (x + (tau ^ 2 + tau - 3) / 3) - 2 / 27) := by
  simp only [WeierstrassCurve.Ψ₃, Polynomial.eval_add,
    Polynomial.eval_mul, Polynomial.eval_pow, Polynomial.eval_C,
    Polynomial.eval_X, Polynomial.eval_ofNat, WeierstrassCurve.b₂,
    WeierstrassCurve.b₄, WeierstrassCurve.b₆, WeierstrassCurve.b₈,
    quotientCurve, WeierstrassCurve.toAffine]
  ring_nf
  simp only [tau_pow_eight, tau_pow_seven, tau_pow_six, tau_pow_five,
    tau_pow_four, tau_cubic]
  ring

private theorem linear_factor_impossible
    {x y : K} (hP : quotientCurve.toAffine.Nonsingular x y)
    (hlinear : 3 * x + tau ^ 2 + tau - 2 = 0) : False := by
  have hx : x = (2 - tau ^ 2 - tau) / 3 := by
    linear_combination (1 / 3 : K) * hlinear
  have hcurve := hP.1
  rw [WeierstrassCurve.Affine.equation_iff] at hcurve
  have hdisc :
      (x + (tau ^ 2 + tau - 1)) ^ 2 +
        4 * (x ^ 3 + (tau ^ 2 + tau - 3) * x ^ 2 +
          (-tau ^ 2 + 4) * x - tau - 2) = (-1 / 3 : K) := by
    rw [hx]
    ring_nf
    simp only [tau_pow_six, tau_pow_five, tau_pow_four, tau_cubic]
    ring
  have hsquare :
      (2 * y + x + (tau ^ 2 + tau - 1)) ^ 2 = (-1 / 3 : K) := by
    calc
      (2 * y + x + (tau ^ 2 + tau - 1)) ^ 2 =
          4 * (y ^ 2 + x * y + (tau ^ 2 + tau - 1) * y) +
            (x + (tau ^ 2 + tau - 1)) ^ 2 := by ring
      _ = 4 * (x ^ 3 + (tau ^ 2 + tau - 3) * x ^ 2 +
            (-tau ^ 2 + 4) * x - tau - 2) +
            (x + (tau ^ 2 + tau - 1)) ^ 2 := by
          rw [show y ^ 2 + x * y + (tau ^ 2 + tau - 1) * y =
            x ^ 3 + (tau ^ 2 + tau - 3) * x ^ 2 +
              (-tau ^ 2 + 4) * x - tau - 2 by
            simpa [quotientCurve, sub_eq_add_neg, add_assoc] using hcurve]
      _ = -1 / 3 := by linear_combination hdisc
  apply no_square_root_neg_three
    (3 * (2 * y + x + (tau ^ 2 + tau - 1)))
  calc
    (3 * (2 * y + x + (tau ^ 2 + tau - 1))) ^ 2 =
        9 * (-1 / 3 : K) := by rw [mul_pow, hsquare]; ring
    _ = -3 := by norm_num

private theorem cubic_factor_impossible (x : K)
    (hcubic :
      (x + (tau ^ 2 + tau - 3) / 3) ^ 3 +
        (2 / 3) * (x + (tau ^ 2 + tau - 3) / 3) - 2 / 27 = 0) : False := by
  let z : K := 3 * (x + (tau ^ 2 + tau - 3) / 3)
  apply depressedPolynomial_no_root z
  rw [show depressedPolynomial.map (algebraMap ℚ K) =
    X ^ 3 + 6 * X - 2 by norm_num [depressedPolynomial]]
  simp only [eval_sub, eval_add, eval_mul, eval_pow, eval_X, eval_ofNat]
  dsimp only [z]
  linear_combination 27 * hcubic

/-- The real-cubic quotient has no nonidentity point killed by three. -/
theorem eq_zero_of_three_nsmul_eq_zero
    (P : quotientCurve.toAffine.Point) (hP : (3 : ℕ) • P = 0) :
    P = 0 := by
  cases P with
  | zero => rfl
  | some x y hxy =>
      exfalso
      have hpsi := eval_psi_three_eq_zero_of_three_nsmul hxy hP
      rw [quotientCurve_psi_three_factorization] at hpsi
      rcases mul_eq_zero.mp hpsi with hlinear | hcubic
      · exact linear_factor_impossible hxy hlinear
      · exact cubic_factor_impossible x hcubic

end

end MazurTorsion.XOneEighteenQuotientThreeTorsion
