/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenCyclotomicMinkowski
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import Mathlib.Tactic.NormNum.Prime

/-!
# Exceptional rational primes for the thirteenth cyclotomic field

The residue degree of an unramified rational prime in `ℚ(ζ₁₃)` is the
multiplicative order of that prime modulo `13`.  Combined with the checked
Minkowski cutoff, the following finite certificate leaves exactly the six
norms `27, 13, 53, 79, 131, 157` to be generated by principal ideals.
-/

namespace MazurTorsion.XOneThirteenCyclotomic

open Nat
open NumberField Ideal

local instance : Fact (Nat.Prime 13) := ⟨by decide⟩

/-- The six rational primes whose least possible prime-ideal norm is at most
the Minkowski cutoff. -/
def exceptionalPrimes : Finset ℕ := {3, 13, 53, 79, 131, 157}

private theorem orderOf_two_mod_thirteen :
    orderOf (2 : ZMod 13) = 12 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_three_mod_thirteen :
    orderOf (3 : ZMod 13) = 3 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_four_mod_thirteen :
    orderOf (4 : ZMod 13) = 6 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_five_mod_thirteen :
    orderOf (5 : ZMod 13) = 4 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_six_mod_thirteen :
    orderOf (6 : ZMod 13) = 12 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_seven_mod_thirteen :
    orderOf (7 : ZMod 13) = 12 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_eight_mod_thirteen :
    orderOf (8 : ZMod 13) = 4 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_nine_mod_thirteen :
    orderOf (9 : ZMod 13) = 3 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_ten_mod_thirteen :
    orderOf (10 : ZMod 13) = 6 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_eleven_mod_thirteen :
    orderOf (11 : ZMod 13) = 12 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m <;> decide

private theorem orderOf_twelve_mod_thirteen :
    orderOf (12 : ZMod 13) = 2 := by
  rw [orderOf_eq_iff (by norm_num)]
  constructor
  · decide
  · intro m hm hm0
    interval_cases m ; decide

/-- Exact multiplicative-order certificate for all rational primes at most
`306`: outside the six exceptional primes, `p ^ ord₁₃(p)` exceeds `306`. -/
theorem pow_orderOf_mod_thirteen_gt_cutoff
    (p : ℕ) (hp : p.Prime) (hp_le : p ≤ 306)
    (hp_not_exceptional : p ∉ exceptionalPrimes) :
    306 < p ^ orderOf (p : ZMod 13) := by
  interval_cases p
  all_goals try norm_num at hp
  all_goals try simp [exceptionalPrimes] at hp_not_exceptional
  all_goals rw [← ZMod.natCast_mod]
  all_goals norm_num [orderOf_two_mod_thirteen,
    orderOf_three_mod_thirteen, orderOf_four_mod_thirteen,
    orderOf_five_mod_thirteen, orderOf_six_mod_thirteen,
    orderOf_seven_mod_thirteen, orderOf_eight_mod_thirteen,
    orderOf_nine_mod_thirteen, orderOf_ten_mod_thirteen,
    orderOf_eleven_mod_thirteen, orderOf_twelve_mod_thirteen]

/-- Equivalently, any prime at most `306` with residue-degree norm at most
`306` is one of the six exceptional primes. -/
theorem mem_exceptionalPrimes_of_pow_orderOf_le
    (p : ℕ) (hp : p.Prime) (hp_le : p ≤ 306)
    (hpow : p ^ orderOf (p : ZMod 13) ≤ 306) :
    p ∈ exceptionalPrimes := by
  by_contra h
  exact (not_lt_of_ge hpow)
    (pow_orderOf_mod_thirteen_gt_cutoff p hp hp_le h)

variable {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {13} ℚ K]

/-- Actual input to the Galois Minkowski criterion: for a nonexceptional
rational prime below the checked cutoff, every prime ideal above it already
has residue-degree norm beyond that cutoff. -/
theorem floor_minkowskiClassBound_lt_pow_inertiaDeg
    (p : ℕ) (hp : p.Prime)
    (hp_le : p ≤ ⌊minkowskiClassBound K⌋₊)
    (hp_not_exceptional : p ∉ exceptionalPrimes)
    (P : Ideal (𝓞 K))
    (hP : P ∈ primesOver (span {(p : ℤ)}) (𝓞 K)) :
    ⌊minkowskiClassBound K⌋₊ < p ^ P.inertiaDeg ℤ := by
  letI : Fact p.Prime := ⟨hp⟩
  letI : P.IsPrime := hP.1
  letI : P.LiesOver (span {(p : ℤ)}) := hP.2
  have hp_ne_thirteen : p ≠ 13 := by
    intro h
    apply hp_not_exceptional
    simp [exceptionalPrimes, h]
  have hp_not_dvd_thirteen : ¬p ∣ 13 := by
    intro hdiv
    rcases (Nat.dvd_prime (by decide : Nat.Prime 13)).mp hdiv with hp_one | hp_thirteen
    · exact hp.ne_one hp_one
    · exact hp_ne_thirteen hp_thirteen
  rw [IsCyclotomicExtension.Rat.inertiaDeg_eq_of_not_dvd
    p K P hp_not_dvd_thirteen]
  exact lt_of_le_of_lt (floor_minkowskiClassBound_le K)
    (pow_orderOf_mod_thirteen_gt_cutoff p hp
      (hp_le.trans (floor_minkowskiClassBound_le K)) hp_not_exceptional)

end MazurTorsion.XOneThirteenCyclotomic
