/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenTwoDescentSextic
import Mathlib.NumberTheory.NumberField.Discriminant.Basic
import Mathlib.LinearAlgebra.Matrix.Block
import Mathlib.LinearAlgebra.Matrix.ToLinearEquiv
import Mathlib.Tactic.FinCases

/-!
# An integral order in the `X₁(13)` sextic field

This file gives exact arithmetic certificates for the degree-six field used
by the two-descent on `X₁(13)`.  In particular, it records an integral
six-element basis candidate, its index-eight change of basis from the power
basis, and its discriminant `-10816`.

The retained data are exact polynomial and matrix identities checked by
Lean.  No computer-algebra output is trusted as an assumption.
-/

namespace MazurTorsion.XOneThirteenSexticOrder

open Algebra Matrix Module Polynomial
open scoped Matrix

noncomputable section

open XOneThirteenTwoDescentSextic

theorem rationalSextic_monic : rationalSextic.Monic := by
  simp only [rationalSextic]
  monicity!

theorem rationalSextic_natDegree : rationalSextic.natDegree = 6 := by
  have h := rationalSextic_monic
  simp only [rationalSextic] at h ⊢
  compute_degree!

/-- The canonical power basis generated by `theta`. -/
def sexticPowerBasis : PowerBasis ℚ SexticField :=
  AdjoinRoot.powerBasis rationalSextic_irreducible.ne_zero

@[simp]
theorem sexticPowerBasis_dim : sexticPowerBasis.dim = 6 := by
  rw [sexticPowerBasis, AdjoinRoot.powerBasis_dim,
    rationalSextic_natDegree]

@[simp]
theorem sexticPowerBasis_gen : sexticPowerBasis.gen = theta := by
  rfl

/-- The power basis reindexed by the concrete type `Fin 6`. -/
def powerBasisSix : Basis (Fin 6) ℚ SexticField :=
  sexticPowerBasis.basis.reindex (finCongr sexticPowerBasis_dim)

/-- The companion matrix of the defining sextic in increasing-power order. -/
def companionMatrix : Matrix (Fin 6) (Fin 6) ℚ :=
  ![![0, 0, 0, 0, 0, -1],
    ![1, 0, 0, 0, 0, -4],
    ![0, 1, 0, 0, 0, -6],
    ![0, 0, 1, 0, 0, -2],
    ![0, 0, 0, 1, 0, -1],
    ![0, 0, 0, 0, 1, -2]]

private theorem sexticPowerBasis_minpolyGen :
    sexticPowerBasis.minpolyGen = rationalSextic := by
  rw [PowerBasis.minpolyGen_eq, sexticPowerBasis,
    AdjoinRoot.minpoly_powerBasis_gen_of_monic rationalSextic_monic]

theorem leftMulMatrix_theta :
    Algebra.leftMulMatrix powerBasisSix theta = companionMatrix := by
  ext i j
  rw [Algebra.leftMulMatrix_eq_repr_mul]
  simp only [powerBasisSix, Basis.reindex_apply, Basis.repr_reindex_apply]
  rw [← Algebra.leftMulMatrix_eq_repr_mul]
  rw [← sexticPowerBasis_gen, PowerBasis.leftMulMatrix]
  simp only [sexticPowerBasis_dim, sexticPowerBasis_minpolyGen]
  fin_cases i <;> fin_cases j <;>
    simp [companionMatrix, rationalSextic, finCongr_symm, coeff_one, coeff_X]

/-- Traces of the powers `thetaⁿ` needed by the discriminant matrix. -/
def powerTraceValues : Fin 11 → ℚ :=
  ![6, -2, 2, -8, -6, 8, -4, 54, -54, 46, -148]

/-- An exact table of the first eleven powers of the companion matrix. -/
def companionPowerValues : Fin 11 → Matrix (Fin 6) (Fin 6) ℚ
  | 0 => ![![1, 0, 0, 0, 0, 0],
    ![0, 1, 0, 0, 0, 0],
    ![0, 0, 1, 0, 0, 0],
    ![0, 0, 0, 1, 0, 0],
    ![0, 0, 0, 0, 1, 0],
    ![0, 0, 0, 0, 0, 1]]
  | 1 => ![![0, 0, 0, 0, 0, -1],
    ![1, 0, 0, 0, 0, -4],
    ![0, 1, 0, 0, 0, -6],
    ![0, 0, 1, 0, 0, -2],
    ![0, 0, 0, 1, 0, -1],
    ![0, 0, 0, 0, 1, -2]]
  | 2 => ![![0, 0, 0, 0, -1, 2],
    ![0, 0, 0, 0, -4, 7],
    ![1, 0, 0, 0, -6, 8],
    ![0, 1, 0, 0, -2, -2],
    ![0, 0, 1, 0, -1, 0],
    ![0, 0, 0, 1, -2, 3]]
  | 3 => ![![0, 0, 0, -1, 2, -3],
    ![0, 0, 0, -4, 7, -10],
    ![0, 0, 0, -6, 8, -11],
    ![1, 0, 0, -2, -2, 2],
    ![0, 1, 0, -1, 0, -5],
    ![0, 0, 1, -2, 3, -6]]
  | 4 => ![![0, 0, -1, 2, -3, 6],
    ![0, 0, -4, 7, -10, 21],
    ![0, 0, -6, 8, -11, 26],
    ![0, 0, -2, -2, 2, 1],
    ![1, 0, -1, 0, -5, 8],
    ![0, 1, -2, 3, -6, 7]]
  | 5 => ![![0, -1, 2, -3, 6, -7],
    ![0, -4, 7, -10, 21, -22],
    ![0, -6, 8, -11, 26, -21],
    ![0, -2, -2, 2, 1, 12],
    ![0, -1, 0, -5, 8, -6],
    ![1, -2, 3, -6, 7, -6]]
  | 6 => ![![-1, 2, -3, 6, -7, 6],
    ![-4, 7, -10, 21, -22, 17],
    ![-6, 8, -11, 26, -21, 14],
    ![-2, -2, 2, 1, 12, -9],
    ![-1, 0, -5, 8, -6, 18],
    ![-2, 3, -6, 7, -6, 6]]
  | 7 => ![![2, -3, 6, -7, 6, -6],
    ![7, -10, 21, -22, 17, -18],
    ![8, -11, 26, -21, 14, -19],
    ![-2, 2, 1, 12, -9, 2],
    ![0, -5, 8, -6, 18, -15],
    ![3, -6, 7, -6, 6, 6]]
  | 8 => ![![-3, 6, -7, 6, -6, -6],
    ![-10, 21, -22, 17, -18, -30],
    ![-11, 26, -21, 14, -19, -54],
    ![2, 1, 12, -9, 2, -31],
    ![-5, 8, -6, 18, -15, -4],
    ![-6, 7, -6, 6, 6, -27]]
  | 9 => ![![6, -7, 6, -6, -6, 27],
    ![21, -22, 17, -18, -30, 102],
    ![26, -21, 14, -19, -54, 132],
    ![1, 12, -9, 2, -31, 0],
    ![8, -6, 18, -15, -4, -4],
    ![7, -6, 6, 6, -27, 50]]
  | 10 => ![![-7, 6, -6, -6, 27, -50],
    ![-22, 17, -18, -30, 102, -173],
    ![-21, 14, -19, -54, 132, -198],
    ![12, -9, 2, -31, 0, 32],
    ![-6, 18, -15, -4, -4, -50],
    ![-6, 6, 6, -27, 50, -104]]

private theorem companionPower_step_zero :
    companionPowerValues 1 = companionPowerValues 0 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_one :
    companionPowerValues 2 = companionPowerValues 1 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_two :
    companionPowerValues 3 = companionPowerValues 2 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_three :
    companionPowerValues 4 = companionPowerValues 3 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_four :
    companionPowerValues 5 = companionPowerValues 4 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_five :
    companionPowerValues 6 = companionPowerValues 5 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_six :
    companionPowerValues 7 = companionPowerValues 6 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_seven :
    companionPowerValues 8 = companionPowerValues 7 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_eight :
    companionPowerValues 9 = companionPowerValues 8 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPower_step_nine :
    companionPowerValues 10 = companionPowerValues 9 * companionMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [companionPowerValues, companionMatrix, Fin.sum_univ_succ,
      Matrix.cons_val_zero, Matrix.cons_val_one]

private theorem companionPowerValues_succ (n : Fin 10) :
    companionPowerValues n.succ =
      companionPowerValues n.castSucc * companionMatrix := by
  fin_cases n
  · exact companionPower_step_zero
  · exact companionPower_step_one
  · exact companionPower_step_two
  · exact companionPower_step_three
  · exact companionPower_step_four
  · exact companionPower_step_five
  · exact companionPower_step_six
  · exact companionPower_step_seven
  · exact companionPower_step_eight
  · exact companionPower_step_nine

private theorem companionMatrix_pow_aux (n : ℕ) (hn : n < 11) :
    companionMatrix ^ n = companionPowerValues ⟨n, hn⟩ := by
  induction n with
  | zero =>
      ext i j
      rw [pow_zero, Matrix.one_apply]
      fin_cases i <;> fin_cases j <;> simp [companionPowerValues]
  | succ n ih =>
      have hn' : n < 10 := by omega
      rw [pow_succ, ih (by omega)]
      simpa using (companionPowerValues_succ ⟨n, hn'⟩).symm

private theorem companionMatrix_pow (n : Fin 11) :
    companionMatrix ^ (n : ℕ) = companionPowerValues n := by
  exact companionMatrix_pow_aux n n.isLt

theorem trace_theta_pow (n : Fin 11) :
    Algebra.trace ℚ SexticField (theta ^ (n : ℕ)) = powerTraceValues n := by
  rw [Algebra.trace_eq_matrix_trace powerBasisSix]
  rw [map_pow, leftMulMatrix_theta, companionMatrix_pow]
  fin_cases n <;>
    simp only [Matrix.trace, Fin.sum_univ_succ] <;>
    simp only [Matrix.diag_apply] <;>
    norm_num [companionPowerValues, powerTraceValues,
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two]

@[simp]
theorem powerBasisSix_apply (i : Fin 6) :
    powerBasisSix i = theta ^ (i : ℕ) := by
  simp [powerBasisSix, sexticPowerBasis, finCongr, theta]

/-- The trace Gram matrix of the power basis. -/
def powerTraceMatrix : Matrix (Fin 6) (Fin 6) ℚ :=
  ![![6, -2, 2, -8, -6, 8],
    ![-2, 2, -8, -6, 8, -4],
    ![2, -8, -6, 8, -4, 54],
    ![-8, -6, 8, -4, 54, -54],
    ![-6, 8, -4, 54, -54, 46],
    ![8, -4, 54, -54, 46, -148]]

theorem traceMatrix_powerBasisSix :
    Algebra.traceMatrix ℚ powerBasisSix = powerTraceMatrix := by
  ext i j
  rw [Algebra.traceMatrix_apply, Algebra.traceForm_apply]
  rw [powerBasisSix_apply, powerBasisSix_apply, ← pow_add]
  rw [trace_theta_pow ⟨(i : ℕ) + (j : ℕ), by omega⟩]
  fin_cases i <;> fin_cases j <;>
    norm_num [powerTraceMatrix, powerTraceValues,
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two]

/-- The index-eight rational change matrix.  Its columns are the order
basis written in the power basis. -/
def orderChangeMatrix : Matrix (Fin 6) (Fin 6) ℚ :=
  ![![1, 0, 0, 1 / 2, 1 / 2, 1 / 2],
    ![0, 1, 0, 0, 1 / 2, 1 / 2],
    ![0, 0, 1, 1 / 2, 1 / 2, 0],
    ![0, 0, 0, 1 / 2, 0, 0],
    ![0, 0, 0, 0, 1 / 2, 0],
    ![0, 0, 0, 0, 0, 1 / 2]]

/-- The first half-integral generator of the order. -/
def halfCubicElement : SexticField :=
  (1 / 2 : ℚ) • (1 + theta ^ 2 + theta ^ 3)

/-- The second half-integral generator of the order. -/
def halfQuarticElement : SexticField :=
  (1 / 2 : ℚ) • (1 + theta + theta ^ 2 + theta ^ 4)

/-- The third half-integral generator of the order. -/
def halfQuinticElement : SexticField :=
  (1 / 2 : ℚ) • (1 + theta + theta ^ 5)

/-- Six explicit elements of the order of discriminant `-10816`. -/
def sexticOrderFamily : Fin 6 → SexticField :=
  ![1,
    theta,
    theta ^ 2,
    halfCubicElement,
    halfQuarticElement,
    halfQuinticElement]

theorem sexticOrderFamily_eq_vecMul :
    sexticOrderFamily =
      powerBasisSix ᵥ* orderChangeMatrix.map (algebraMap ℚ SexticField) := by
  funext j
  fin_cases j <;>
    simp [sexticOrderFamily, orderChangeMatrix, Matrix.vecMul,
      halfCubicElement, halfQuarticElement, halfQuinticElement,
      Matrix.dotProduct, Fin.sum_univ_succ, Algebra.smul_def,
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two] <;>
    ring

/-- The exact trace Gram matrix of the order family. -/
def sexticOrderTraceMatrix : Matrix (Fin 6) (Fin 6) ℚ :=
  ![![6, -2, 2, 0, 0, 6],
    ![-2, 2, -8, -8, 0, -2],
    ![2, -8, -6, 2, -8, 24],
    ![0, -8, 2, 0, 8, -2],
    ![0, 0, -8, 8, -18, 26],
    ![6, -2, 24, -2, 26, -34]]

theorem traceMatrix_sexticOrderFamily :
    Algebra.traceMatrix ℚ sexticOrderFamily = sexticOrderTraceMatrix := by
  rw [sexticOrderFamily_eq_vecMul,
    Algebra.traceMatrix_of_matrix_vecMul, traceMatrix_powerBasisSix]
  ext i j
  rw [Matrix.mul_apply]
  simp_rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [orderChangeMatrix, powerTraceMatrix, sexticOrderTraceMatrix,
      Matrix.transpose_apply, Fin.sum_univ_succ, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.cons_val_two]

private theorem orderChangeMatrix_upperTriangular :
    orderChangeMatrix.BlockTriangular id := by
  intro i j hij
  fin_cases i <;> fin_cases j <;>
    simp_all [orderChangeMatrix]

/-- The rational order family has determinant `1/8` relative to the power
basis, so the corresponding integral power order has index eight in it. -/
theorem orderChangeMatrix_det : orderChangeMatrix.det = 1 / 8 := by
  rw [Matrix.det_of_upperTriangular orderChangeMatrix_upperTriangular]
  norm_num [orderChangeMatrix, Fin.prod_univ_succ,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two]

/-- The lower-triangular factor in an exact `L U` certificate for the order
trace matrix. -/
private def traceLowerMatrix : Matrix (Fin 6) (Fin 6) ℚ :=
  ![![1, 0, 0, 0, 0, 0],
    ![-1 / 3, 1, 0, 0, 0, 0],
    ![1 / 3, -11 / 2, 1, 0, 0, 0],
    ![0, -6, 42 / 47, 1, 0, 0],
    ![0, 0, 8 / 47, -178 / 123, 1, 0],
    ![1, 0, -22 / 47, 509 / 246, -43 / 25, 1]]

/-- The upper-triangular factor in an exact `L U` certificate for the order
trace matrix. -/
private def traceUpperMatrix : Matrix (Fin 6) (Fin 6) ℚ :=
  ![![6, -2, 2, 0, 0, 6],
    ![0, 4 / 3, -22 / 3, -8, 0, 0],
    ![0, 0, -47, -42, -8, 22],
    ![0, 0, 0, -492 / 47, 712 / 47, -1018 / 47],
    ![0, 0, 0, 0, 650 / 123, -1118 / 123],
    ![0, 0, 0, 0, 0, -13 / 25]]

private theorem sexticOrderTraceMatrix_eq_lower_mul_upper :
    sexticOrderTraceMatrix = traceLowerMatrix * traceUpperMatrix := by
  ext i j
  rw [Matrix.mul_apply]
  fin_cases i <;> fin_cases j <;>
    norm_num [sexticOrderTraceMatrix, traceLowerMatrix, traceUpperMatrix,
      Fin.sum_univ_succ, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_two]

private theorem traceLowerMatrix_lowerTriangular :
    traceLowerMatrix.BlockTriangular OrderDual.toDual := by
  intro i j hij
  fin_cases i <;> fin_cases j <;>
    simp_all [traceLowerMatrix]

private theorem traceUpperMatrix_upperTriangular :
    traceUpperMatrix.BlockTriangular id := by
  intro i j hij
  fin_cases i <;> fin_cases j <;>
    simp_all [traceUpperMatrix]

private theorem traceLowerMatrix_det : traceLowerMatrix.det = 1 := by
  rw [Matrix.det_of_lowerTriangular traceLowerMatrix
    traceLowerMatrix_lowerTriangular]
  norm_num [traceLowerMatrix, Fin.prod_univ_succ,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two]

private theorem traceUpperMatrix_det : traceUpperMatrix.det = -10816 := by
  rw [Matrix.det_of_upperTriangular traceUpperMatrix_upperTriangular]
  norm_num [traceUpperMatrix, Fin.prod_univ_succ,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two]

theorem sexticOrderTraceMatrix_det :
    sexticOrderTraceMatrix.det = -10816 := by
  rw [sexticOrderTraceMatrix_eq_lower_mul_upper, Matrix.det_mul,
    traceLowerMatrix_det, traceUpperMatrix_det, one_mul]

/-- Exact discriminant certificate for the explicit order family. -/
theorem sexticOrderFamily_discr :
    Algebra.discr ℚ sexticOrderFamily = -10816 := by
  rw [Algebra.discr_def, traceMatrix_sexticOrderFamily,
    sexticOrderTraceMatrix_det]

theorem sexticOrderFamily_linearIndependent :
    LinearIndependent ℚ sexticOrderFamily := by
  by_contra h
  have hz := Algebra.discr_zero_of_not_linearIndependent h
  rw [sexticOrderFamily_discr] at hz
  norm_num at hz

/-- The explicit order family, promoted to a rational basis of the sextic
field. -/
noncomputable def sexticOrderBasis : Basis (Fin 6) ℚ SexticField :=
  basisOfLinearIndependentOfCardEqFinrank
    sexticOrderFamily_linearIndependent
    (by
      simpa [sexticPowerBasis_dim] using
        (PowerBasis.finrank sexticPowerBasis).symm)

@[simp]
theorem sexticOrderBasis_apply (i : Fin 6) :
    sexticOrderBasis i = sexticOrderFamily i := by
  simp [sexticOrderBasis]

theorem sexticOrderBasis_discr :
    Algebra.discr ℚ sexticOrderBasis = -10816 := by
  simpa only [sexticOrderBasis_apply] using sexticOrderFamily_discr

end

end MazurTorsion.XOneThirteenSexticOrder
