/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenTwoDescentLocalPointInputs
import Mathlib.Algebra.Ring.Int.Parity
import Mathlib.NumberTheory.Padics.RingHoms

/-!
# Squareclass normal forms over `Q_2`

This file proves the concrete normal form for nonzero dyadic squareclasses
needed by `XOneThirteenTwoDescentLocalIntersection`.  The proof extracts the
valuation parity and reduces a normalized unit modulo eight.  A checked
Hensel step supplies the square root of the remaining `1 mod 8` unit.
-/

namespace MazurTorsion.XOneThirteenPadicSquareclass

open Polynomial

noncomputable section

private instance : Fact (Nat.Prime 2) := ⟨by decide⟩

/-- Exponentiation by a Boolean bit. -/
def bitPow {M : Type*} [Monoid M] (x : M) (b : Bool) : M :=
  x ^ b.toNat

@[simp]
theorem bitPow_false {M : Type*} [Monoid M] (x : M) :
    bitPow x false = 1 := by
  simp [bitPow]

@[simp]
theorem bitPow_true {M : Type*} [Monoid M] (x : M) :
    bitPow x true = x := by
  simp [bitPow]

/-- The four units modulo eight are generated by `-1` and `5`. -/
private theorem zmodEight_unit_normalForm
    (r : ZMod 8) (hr : IsUnit r) :
    ∃ e g : Bool,
      r = bitPow (-1 : ZMod 8) e *
        bitPow ((5 : ℕ) : ZMod 8) g := by
  have hr' : IsUnit (r.val : ZMod 8) := by
    simpa only [ZMod.natCast_zmod_val] using hr
  have hcoprime : r.val.Coprime 8 :=
    (ZMod.isUnit_iff_coprime r.val 8).mp hr'
  have hcases :
      r.val = 1 ∨ r.val = 3 ∨ r.val = 5 ∨ r.val = 7 := by
    have hlt := r.val_lt
    have hcoprimeTwo : r.val.Coprime 2 :=
      hcoprime.coprime_dvd_right (by norm_num)
    obtain ⟨k, hk⟩ := (Nat.coprime_two_right.mp hcoprimeTwo)
    omega
  rw [← ZMod.natCast_zmod_val r]
  rcases hcases with h | h | h | h
  · rw [h]
    exact ⟨false, false, by norm_num⟩
  · rw [h]
    refine ⟨true, true, ?_⟩
    simp only [bitPow_true]
    change ((3 : ℤ) : ZMod 8) = ((-5 : ℤ) : ZMod 8)
    rw [ZMod.intCast_eq_intCast_iff_dvd_sub]
    norm_num
  · rw [h]
    exact ⟨false, true, by norm_num⟩
  · rw [h]
    refine ⟨true, false, ?_⟩
    simp only [bitPow_true, bitPow_false, mul_one]
    change ((7 : ℤ) : ZMod 8) = ((-1 : ℤ) : ZMod 8)
    rw [ZMod.intCast_eq_intCast_iff_dvd_sub]
    norm_num

private theorem zmodEight_bitGenerators_sq (e g : Bool) :
    (bitPow (-1 : ZMod 8) e *
      bitPow ((5 : ℕ) : ZMod 8) g) ^ 2 = 1 := by
  cases e <;> cases g
  · simp
  · simp only [bitPow_false, bitPow_true, one_mul]
    change ((25 : ℤ) : ZMod 8) = ((1 : ℤ) : ZMod 8)
    rw [ZMod.intCast_eq_intCast_iff_dvd_sub]
    norm_num
  · simp
  · simp only [bitPow_true]
    change ((25 : ℤ) : ZMod 8) = ((1 : ℤ) : ZMod 8)
    rw [ZMod.intCast_eq_intCast_iff_dvd_sub]
    norm_num

/-- The square of every dyadic integral unit is `1` modulo `8`. -/
theorem padicIntUnit_square_mod_eight (U : ℤ_[2]ˣ) :
    PadicInt.toZModPow 3 ((U : ℤ_[2]) ^ 2) = 1 := by
  let r : ZMod 8 := PadicInt.toZModPow 3 (U : ℤ_[2])
  have hrUnit : IsUnit r := U.isUnit.map (PadicInt.toZModPow 3)
  obtain ⟨e, g, hr⟩ := zmodEight_unit_normalForm r hrUnit
  calc
    PadicInt.toZModPow 3 ((U : ℤ_[2]) ^ 2) = r ^ 2 := by
      exact map_pow (PadicInt.toZModPow 3) (U : ℤ_[2]) 2
    _ = (bitPow (-1 : ZMod 8) e *
        bitPow ((5 : ℕ) : ZMod 8) g) ^ 2 := by rw [hr]
    _ = 1 := zmodEight_bitGenerators_sq e g

/-- A dyadic integer congruent to one modulo eight has a square root. -/
private theorem exists_padicInt_sq_eq_of_mod_eight_eq_one
    (u : ℤ_[2])
    (hu : PadicInt.toZModPow 3 u = 1) :
    ∃ z : ℤ_[2], z ^ 2 = u := by
  let F : ℤ_[2][X] := X ^ 2 - C u
  let a : ℤ_[2] := 1
  have hEval : F.aeval a = 1 - u := by
    simp [F, a]
  have hDerivative : F.derivative.aeval a = (2 : ℤ_[2]) := by
    norm_num [F, a, aeval_def]
  have hMem :
      1 - u ∈
        (Ideal.span {((2 : ℕ) : ℤ_[2]) ^ 3} : Ideal ℤ_[2]) := by
    rw [← PadicInt.ker_toZModPow (p := 2) 3, RingHom.mem_ker]
    simp [hu]
  have hNormBound :
      ‖1 - u‖ ≤ (2 : ℝ) ^ (-3 : ℤ) :=
    (PadicInt.norm_le_pow_iff_mem_span_pow (p := 2) (1 - u) 3).2 hMem
  have hHensel : ‖F.aeval a‖ < ‖F.derivative.aeval a‖ ^ 2 := by
    rw [hEval, hDerivative]
    calc
      ‖1 - u‖ ≤ (2 : ℝ) ^ (-3 : ℤ) := hNormBound
      _ < ((2 : ℝ)⁻¹) ^ 2 := by norm_num
      _ = ‖(2 : ℤ_[2])‖ ^ 2 := by
        exact congrArg (fun x : ℝ ↦ x ^ 2)
          (PadicInt.norm_p (p := 2)).symm
  obtain ⟨z, hz, -⟩ := hensels_lemma hHensel
  refine ⟨z, ?_⟩
  have hz' : z ^ 2 - u = 0 := by
    simpa [F] using hz
  exact sub_eq_zero.mp hz'

/-- A norm-one dyadic unit is, modulo a square, generated by `-1` and `5`. -/
theorem unit_squareclass_normalForm
    (u : ℚ_[2]) (hu : ‖u‖ = 1) :
    ∃ (s : ℚ_[2]) (e g : Bool),
      u = s ^ 2 * bitPow (-1 : ℚ_[2]) e *
        bitPow ((5 : ℕ) : ℚ_[2]) g := by
  let U : ℤ_[2]ˣ := PadicInt.mkUnits hu
  let r : ZMod 8 := PadicInt.toZModPow 3 (U : ℤ_[2])
  have hrUnit : IsUnit r := by
    exact U.isUnit.map (PadicInt.toZModPow 3)
  obtain ⟨e, g, hr⟩ := zmodEight_unit_normalForm r hrUnit
  let c : ℤ_[2] :=
    bitPow (-1) e * bitPow ((5 : ℕ) : ℤ_[2]) g
  have hFiveMap :
      PadicInt.toZModPow 3 ((5 : ℕ) : ℤ_[2]) =
        ((5 : ℕ) : ZMod 8) :=
    map_natCast (PadicInt.toZModPow 3) 5
  have hcMap : PadicInt.toZModPow 3 c = r := by
    rw [hr]
    simp only [c, bitPow, map_mul, map_pow, map_neg, map_one,
      hFiveMap]
  let w : ℤ_[2] := (U : ℤ_[2]) * c
  have hwMod : PadicInt.toZModPow 3 w = 1 := by
    calc
      PadicInt.toZModPow 3 w =
          PadicInt.toZModPow 3 (U : ℤ_[2]) *
            PadicInt.toZModPow 3 c := by
        exact map_mul (PadicInt.toZModPow 3) (U : ℤ_[2]) c
      _ = r * r := by rw [hcMap]
      _ = (bitPow (-1 : ZMod 8) e *
          bitPow ((5 : ℕ) : ZMod 8) g) ^ 2 := by
        rw [hr, pow_two]
      _ = 1 := zmodEight_bitGenerators_sq e g
  obtain ⟨z, hz⟩ :=
    exists_padicInt_sq_eq_of_mod_eight_eq_one w hwMod
  let cQ : ℚ_[2] :=
    bitPow (-1) e * bitPow ((5 : ℕ) : ℚ_[2]) g
  have hcQ : cQ ≠ 0 := by
    simp [cQ, bitPow]
  have hUCoe : ((U : ℤ_[2]) : ℚ_[2]) = u := by
    simpa only [U] using PadicInt.mkUnits_eq hu
  have hcCoe : (c : ℚ_[2]) = cQ := by
    simp only [c, cQ, bitPow, PadicInt.coe_mul, PadicInt.coe_pow,
      PadicInt.coe_neg, PadicInt.coe_one, PadicInt.coe_natCast]
  have hzQ : (z : ℚ_[2]) ^ 2 = u * cQ := by
    calc
      (z : ℚ_[2]) ^ 2 = (w : ℚ_[2]) := by
        simpa only [PadicInt.coe_pow] using
          congrArg (fun t : ℤ_[2] ↦ (t : ℚ_[2])) hz
      _ = u * cQ := by
        change ((((U : ℤ_[2]) * c : ℤ_[2]) : ℚ_[2])) = u * cQ
        rw [PadicInt.coe_mul, hUCoe, hcCoe]
  refine ⟨(z : ℚ_[2]) / cQ, e, g, ?_⟩
  have hmain : u = ((z : ℚ_[2]) / cQ) ^ 2 * cQ := by
    rw [div_pow, hzQ]
    field_simp [hcQ]
  simpa only [cQ, mul_assoc] using hmain

/-- Every nonzero dyadic number has squareclass represented by a product of
the three standard generators `-1`, `2`, and `5`. -/
theorem nonzero_squareclass_normalForm
    (q : ℚ_[2]) (hq : q ≠ 0) :
    ∃ (s : ℚ_[2]) (e f g : Bool),
      q = s ^ 2 * bitPow (-1 : ℚ_[2]) e *
        bitPow ((2 : ℕ) : ℚ_[2]) f *
        bitPow ((5 : ℕ) : ℚ_[2]) g := by
  let u : ℚ_[2] :=
    q * ((2 : ℕ) : ℚ_[2]) ^ (-q.valuation : ℤ)
  have hTwo : ((2 : ℕ) : ℚ_[2]) ≠ 0 := by norm_num
  have hu : ‖u‖ = 1 := by
    dsimp only [u]
    simp [hq, Padic.norm_eq_zpow_neg_valuation,
      zpow_ne_zero]
  obtain ⟨t, e, g, huForm⟩ := unit_squareclass_normalForm u hu
  have hqFrom :
      q = u * ((2 : ℕ) : ℚ_[2]) ^ (q.valuation : ℤ) := by
    dsimp only [u]
    rw [mul_assoc, ← zpow_add₀ hTwo]
    simp
  obtain ⟨k, hv | hv⟩ := Int.even_or_odd' q.valuation
  · refine ⟨t * ((2 : ℕ) : ℚ_[2]) ^ k, e, false, g, ?_⟩
    calc
      q = u * ((2 : ℕ) : ℚ_[2]) ^ (q.valuation : ℤ) := hqFrom
      _ = (t ^ 2 * bitPow (-1 : ℚ_[2]) e *
          bitPow ((5 : ℕ) : ℚ_[2]) g) *
          ((2 : ℕ) : ℚ_[2]) ^ (2 * k) := by
        rw [huForm, hv]
      _ = (t * ((2 : ℕ) : ℚ_[2]) ^ k) ^ 2 *
          bitPow (-1 : ℚ_[2]) e *
          bitPow ((2 : ℕ) : ℚ_[2]) false *
          bitPow ((5 : ℕ) : ℚ_[2]) g := by
        rw [zpow_mul']
        simp only [bitPow_false, mul_one, zpow_ofNat]
        ring
  · refine ⟨t * ((2 : ℕ) : ℚ_[2]) ^ k, e, true, g, ?_⟩
    calc
      q = u * ((2 : ℕ) : ℚ_[2]) ^ (q.valuation : ℤ) := hqFrom
      _ = (t ^ 2 * bitPow (-1 : ℚ_[2]) e *
          bitPow ((5 : ℕ) : ℚ_[2]) g) *
          ((2 : ℕ) : ℚ_[2]) ^ (2 * k + 1) := by
        rw [huForm, hv]
      _ = (t * ((2 : ℕ) : ℚ_[2]) ^ k) ^ 2 *
          bitPow (-1 : ℚ_[2]) e *
          bitPow ((2 : ℕ) : ℚ_[2]) true *
          bitPow ((5 : ℕ) : ℚ_[2]) g := by
        rw [zpow_add₀ hTwo, zpow_mul']
        simp only [bitPow_true, zpow_ofNat]
        ring

end

end MazurTorsion.XOneThirteenPadicSquareclass
