/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenPicardPointCRT
import Mathlib.Algebra.BigOperators.Finsupp.Basic

/-!
# Rational affine divisors and their affine ideal classes on `X₁(13)`

The checked irreducibility of the fixed sextic rules out rational affine
points with ordinate zero.  Thus every bundled rational affine point defines
the invertible point ideal constructed in `XOneThirteenPicardClass` and hence
an honest affine ideal class.

This file extends that point-class assignment additively from basis points to
the free abelian group of rational affine divisors.  It concerns the class
group of the affine coordinate ring; it makes no identification with the
degree-zero Picard group of the smooth projective curve.
-/

namespace MazurTorsion.XOneThirteenPicard

open Polynomial

open XOneThirteenMumford

noncomputable section

namespace CoordinateRing

/-- The irreducible sextic has no rational affine point with ordinate zero. -/
theorem y_ne_zero_of_isAffinePoint
    {x y : ℚ} (hcurve : IsAffinePoint x y) : y ≠ 0 := by
  intro hy
  have hroot : sexticPolynomial.IsRoot x := by
    change sexticPolynomial.eval x = 0
    rw [← hcurve, hy]
    norm_num
  exact sexticPolynomial_irreducible.not_isRoot_of_natDegree_ne_one
    (by rw [sexticPolynomial_natDegree]; norm_num) hroot

/-- Every bundled rational affine point has nonzero ordinate. -/
theorem rationalAffinePoint_y_ne_zero (P : RationalAffinePoint) :
    P.1.2 ≠ 0 :=
  y_ne_zero_of_isAffinePoint P.2

/-- The honest affine ideal class attached to a bundled rational affine
point. -/
def rationalAffinePointClass (P : RationalAffinePoint) :
    ClassGroup CoordinateRing :=
  pointClass P.1.1 P.1.2 P.2 (rationalAffinePoint_y_ne_zero P)

/-- The free abelian group on rational affine points of the fixed model. -/
abbrev RationalAffineDivisor := RationalAffinePoint →₀ ℤ

/-- Send a rational affine divisor to the sum of its point classes in the
additive form of the affine ideal class group. -/
def rationalAffineDivisorClass :
    RationalAffineDivisor →+ Additive (ClassGroup CoordinateRing) :=
  Finsupp.liftAddHom fun P =>
    zmultiplesHom (Additive (ClassGroup CoordinateRing))
      (Additive.ofMul (rationalAffinePointClass P))

/-- Formula on a point with arbitrary integral multiplicity. -/
@[simp] theorem rationalAffineDivisorClass_single
    (P : RationalAffinePoint) (n : ℤ) :
    rationalAffineDivisorClass (Finsupp.single P n) =
      n • Additive.ofMul (rationalAffinePointClass P) := by
  simp [rationalAffineDivisorClass]

/-- A basis point maps to its honest affine point class. -/
@[simp] theorem rationalAffineDivisorClass_basis
    (P : RationalAffinePoint) :
    rationalAffineDivisorClass (Finsupp.single P 1) =
      Additive.ofMul (rationalAffinePointClass P) := by
  simp

/-- The divisor-class assignment is additive. -/
theorem rationalAffineDivisorClass_add
    (D E : RationalAffineDivisor) :
    rationalAffineDivisorClass (D + E) =
      rationalAffineDivisorClass D + rationalAffineDivisorClass E :=
  map_add rationalAffineDivisorClass D E

/-- Negating a divisor negates its affine ideal class. -/
theorem rationalAffineDivisorClass_neg
    (D : RationalAffineDivisor) :
    rationalAffineDivisorClass (-D) = -rationalAffineDivisorClass D :=
  map_neg rationalAffineDivisorClass D

/-- Subtraction of divisors becomes subtraction of affine ideal classes. -/
theorem rationalAffineDivisorClass_sub
    (D E : RationalAffineDivisor) :
    rationalAffineDivisorClass (D - E) =
      rationalAffineDivisorClass D - rationalAffineDivisorClass E :=
  map_sub rationalAffineDivisorClass D E

/-- The finite-sum formula for the affine class of a rational divisor. -/
theorem rationalAffineDivisorClass_apply (D : RationalAffineDivisor) :
    rationalAffineDivisorClass D =
      D.sum fun P n => n • Additive.ofMul (rationalAffinePointClass P) := by
  rfl

/-! ## A concrete conjugate-cusp divisor -/

/-- The affine cusp `(0,1)` as a bundled rational point. -/
def cuspZeroPositivePoint : RationalAffinePoint :=
  ⟨(0, 1), cuspZeroPositive_isAffinePoint⟩

/-- The affine cusp `(0,-1)` as a bundled rational point. -/
def cuspZeroNegativePoint : RationalAffinePoint :=
  ⟨(0, -1), cuspZeroNegative_isAffinePoint⟩

/-- The effective degree-two divisor formed by the two conjugate affine
cusps. -/
def cuspZeroConjugateSumDivisor : RationalAffineDivisor :=
  Finsupp.single cuspZeroNegativePoint 1 +
    Finsupp.single cuspZeroPositivePoint 1

/-- The conjugate cusp sum has trivial affine ideal class, reflecting the
checked principal-ideal product generated by `X`. -/
theorem rationalAffineDivisorClass_cuspZeroConjugateSum :
    rationalAffineDivisorClass cuspZeroConjugateSumDivisor = 0 := by
  have hmul := pointClass_neg_mul cuspZeroPositive_isAffinePoint one_ne_zero
  have hadd := congrArg Additive.ofMul hmul
  simpa [cuspZeroConjugateSumDivisor, rationalAffinePointClass,
    cuspZeroPositivePoint, cuspZeroNegativePoint] using hadd

end CoordinateRing

end

end MazurTorsion.XOneThirteenPicard
