/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneEighteenRealCubicQuotient

/-!
# The finite fibers of the `X₁(18)` real-cubic quotient

The seven points in the cyclic subgroup generated by `(1,0)` on the
real-cubic quotient have only three affine abscissas:

`1`, `3 - τ²`, and `1 - τ`.

This file proves directly that the quotient of a rational sextic abscissa
cannot have the first value, and can have the other two only at the cusp
abscissas `0` and `1`.  The proof clears the genuine quotient denominator
and uses the degree-three minimal polynomial of `τ`; no point enumeration
or Mordell--Weil assertion is made here.
-/

open Polynomial

namespace MazurTorsion.XOneEighteenFinalQuotientFibers

noncomputable section

open MazurTorsion.XOneEighteenRealCubicQuotient

private theorem cubicPolynomial_monic : cubicPolynomial.Monic := by
  simp only [cubicPolynomial]
  monicity <;> norm_num

private theorem of_rat_eq_cast (q : ℚ) :
    AdjoinRoot.of cubicPolynomial q = (q : K) := by
  rw [← AdjoinRoot.algebraMap_eq]
  exact map_ratCast (algebraMap ℚ K) q

/-- A nonzero rational polynomial of degree at most two cannot vanish at
the cubic generator `τ`. -/
private theorem quadratic_tau_ne_zero
    (a b c : ℚ)
    (hp : C a * X ^ 2 + C b * X + C c ≠ (0 : Polynomial ℚ)) :
    (a : K) * tau ^ 2 + (b : K) * tau + (c : K) ≠ 0 := by
  intro h
  have hdeg :
      (C a * X ^ 2 + C b * X + C c : Polynomial ℚ).natDegree <
        cubicPolynomial.natDegree := by
    have hp_le :
        (C a * X ^ 2 + C b * X + C c : Polynomial ℚ).natDegree ≤ 2 := by
      compute_degree
    have hcubic : cubicPolynomial.natDegree = 3 := by
      simp only [cubicPolynomial]
      compute_degree!
    omega
  apply
    AdjoinRoot.mk_ne_zero_of_natDegree_lt cubicPolynomial_monic hp hdeg
  change
    AdjoinRoot.mk cubicPolynomial
      (C a * X ^ 2 + C b * X + C c) = 0
  simpa only [map_add, map_mul, map_pow, AdjoinRoot.mk_C,
    AdjoinRoot.mk_X, of_rat_eq_cast, tau] using h

private theorem first_relation_polynomial_ne_zero (x : ℚ) :
    C (x + 1) * X ^ 2 + C (3 * x + 1) * X + C x ≠
      (0 : Polynomial ℚ) := by
  intro h
  have htwo := congrArg (fun p : Polynomial ℚ ↦ p.coeff 2) h
  have hone := congrArg (fun p : Polynomial ℚ ↦ p.coeff 1) h
  simp only [C_mul_X_pow_eq_monomial, C_mul_X_eq_monomial,
    coeff_add, coeff_monomial, coeff_C, coeff_zero] at htwo hone
  norm_num at htwo hone
  linarith

private theorem second_relation_polynomial_ne_zero (x : ℚ) :
    C (x - 1) * X ^ 2 + C (-1) * X + C (-2 * x + 1) ≠
      (0 : Polynomial ℚ) := by
  intro h
  have hone := congrArg (fun p : Polynomial ℚ ↦ p.coeff 1) h
  rw [C_mul_X_pow_eq_monomial, C_mul_X_eq_monomial] at hone
  norm_num [coeff_add, coeff_monomial, coeff_C, coeff_one,
    coeff_zero] at hone

private theorem third_relation_polynomial_ne_zero (x : ℚ) :
    C 1 * X ^ 2 + C (x - 2) * X + C (-1) ≠
      (0 : Polynomial ℚ) := by
  intro h
  have htwo := congrArg (fun p : Polynomial ℚ ↦ p.coeff 2) h
  rw [C_mul_X_pow_eq_monomial, C_mul_X_eq_monomial] at htwo
  norm_num [coeff_add, coeff_monomial, coeff_C, coeff_one,
    coeff_zero] at htwo

private theorem tau_pow_four : tau ^ 4 = 3 * tau ^ 2 + tau := by
  calc
    tau ^ 4 = tau * tau ^ 3 := by ring
    _ = 3 * tau ^ 2 + tau := by rw [tau_cubic]; ring

private theorem tau_pow_five : tau ^ 5 = tau ^ 2 + 9 * tau + 3 := by
  calc
    tau ^ 5 = tau * tau ^ 4 := by ring
    _ = tau * (3 * tau ^ 2 + tau) := by rw [tau_pow_four]
    _ = 3 * tau ^ 3 + tau ^ 2 := by ring
    _ = tau ^ 2 + 9 * tau + 3 := by rw [tau_cubic]; ring

private theorem tau_pow_six : tau ^ 6 = 9 * tau ^ 2 + 6 * tau + 1 := by
  calc
    tau ^ 6 = tau * tau ^ 5 := by ring
    _ = tau * (tau ^ 2 + 9 * tau + 3) := by rw [tau_pow_five]
    _ = tau ^ 3 + 9 * tau ^ 2 + 3 * tau := by ring
    _ = 9 * tau ^ 2 + 6 * tau + 1 := by rw [tau_cubic]; ring

/-! ## Cleared quotient identities -/

private theorem quotientX_sub_one_cleared (x : ℚ) :
    12 * ((x : K) + tau) ^ 2 * (quotientX x - 1) =
      -12 *
        (((x + 1 : ℚ) : K) * tau ^ 2 +
          ((3 * x + 1 : ℚ) : K) * tau + (x : K)) := by
  simp only [quotientX, quotientD]
  field_simp [rational_add_tau_ne_zero]
  ring_nf
  simp only [tau_pow_six, tau_pow_four, tau_cubic]
  push_cast
  ring

private theorem quotientX_sub_three_sub_tau_sq_cleared (x : ℚ) :
    12 * ((x : K) + tau) ^ 2 *
        (quotientX x - (3 - tau ^ 2)) =
      12 * (x : K) *
        ((((x - 1 : ℚ) : K) * tau ^ 2) - tau +
          ((-2 * x + 1 : ℚ) : K)) := by
  simp only [quotientX, quotientD]
  field_simp [rational_add_tau_ne_zero]
  ring_nf
  simp only [tau_pow_six, tau_pow_four, tau_cubic]
  push_cast
  ring

private theorem quotientX_sub_one_sub_tau_cleared (x : ℚ) :
    12 * ((x : K) + tau) ^ 2 *
        (quotientX x - (1 - tau)) =
      12 * (((x - 1 : ℚ) : K)) *
        (tau ^ 2 + ((x - 2 : ℚ) : K) * tau - 1) := by
  simp only [quotientX, quotientD]
  field_simp [rational_add_tau_ne_zero]
  ring_nf
  simp only [tau_pow_six, tau_pow_four, tau_cubic]
  push_cast
  ring

/-! ## The three finite fibers -/

/-- No rational abscissa maps to the torsion abscissa `1`. -/
theorem quotientX_ne_one (x : ℚ) : quotientX x ≠ 1 := by
  intro hx
  have hrel := quotientX_sub_one_cleared x
  rw [hx, sub_self, mul_zero] at hrel
  have hzero :
      (((x + 1 : ℚ) : K) * tau ^ 2 +
        ((3 * x + 1 : ℚ) : K) * tau + (x : K)) = 0 := by
    have hprod :
        (-12 : K) *
          (((x + 1 : ℚ) : K) * tau ^ 2 +
            ((3 * x + 1 : ℚ) : K) * tau + (x : K)) = 0 := hrel.symm
    exact (mul_eq_zero.mp hprod).resolve_left (by norm_num)
  exact
    quadratic_tau_ne_zero (x + 1) (3 * x + 1) x
      (first_relation_polynomial_ne_zero x) hzero

/-- The torsion abscissa `3-τ²` can occur only above the cusp `x=0`. -/
theorem quotientX_eq_three_sub_tau_sq_imp_eq_zero
    (x : ℚ) (hx : quotientX x = 3 - tau ^ 2) : x = 0 := by
  by_contra hx0
  have hrel := quotientX_sub_three_sub_tau_sq_cleared x
  rw [hx, sub_self, mul_zero] at hrel
  have hxK : (x : K) ≠ 0 := by exact_mod_cast hx0
  have hzero :
      (((x - 1 : ℚ) : K) * tau ^ 2 - tau +
        ((-2 * x + 1 : ℚ) : K)) = 0 := by
    have hprod :
        (12 : K) * (x : K) *
          ((((x - 1 : ℚ) : K) * tau ^ 2 - tau +
            ((-2 * x + 1 : ℚ) : K))) = 0 := hrel.symm
    exact
      (mul_eq_zero.mp hprod).resolve_left
        (mul_ne_zero (by norm_num) hxK)
  exact
    quadratic_tau_ne_zero (x - 1) (-1) (-2 * x + 1)
      (second_relation_polynomial_ne_zero x) (by
        simpa only [Rat.cast_neg, Rat.cast_one, neg_one_mul,
          sub_eq_add_neg] using hzero)

/-- The torsion abscissa `1-τ` can occur only above the cusp `x=1`. -/
theorem quotientX_eq_one_sub_tau_imp_eq_one
    (x : ℚ) (hx : quotientX x = 1 - tau) : x = 1 := by
  by_contra hx1
  have hrel := quotientX_sub_one_sub_tau_cleared x
  rw [hx, sub_self, mul_zero] at hrel
  have hxK : (((x - 1 : ℚ) : K)) ≠ 0 := by
    exact_mod_cast sub_ne_zero.mpr hx1
  have hzero : tau ^ 2 + ((x - 2 : ℚ) : K) * tau - 1 = 0 := by
    have hprod :
        (12 : K) * (((x - 1 : ℚ) : K)) *
          (tau ^ 2 + ((x - 2 : ℚ) : K) * tau - 1) = 0 := hrel.symm
    exact
      (mul_eq_zero.mp hprod).resolve_left
        (mul_ne_zero (by norm_num) hxK)
  exact
    quadratic_tau_ne_zero 1 (x - 2) (-1)
      (third_relation_polynomial_ne_zero x) (by
        simpa only [Rat.cast_one, Rat.cast_neg, one_mul, neg_one_mul,
          sub_eq_add_neg] using hzero)

/-- A rational noncuspidal sextic abscissa cannot map to any of the three
affine abscissas occurring in the seven-point torsion subgroup. -/
theorem quotientX_not_mem_torsion_abscissas
    (x : ℚ) (hx0 : x ≠ 0) (hx1 : x ≠ 1) :
    quotientX x ≠ 1 ∧
      quotientX x ≠ 3 - tau ^ 2 ∧
      quotientX x ≠ 1 - tau := by
  refine ⟨quotientX_ne_one x, ?_, ?_⟩
  · exact fun h ↦ hx0 (quotientX_eq_three_sub_tau_sq_imp_eq_zero x h)
  · exact fun h ↦ hx1 (quotientX_eq_one_sub_tau_imp_eq_one x h)

end

end MazurTorsion.XOneEighteenFinalQuotientFibers
