/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.NumberTheory.XOneThirteenTwoDescentLocalKummerUnits
import Mathlib.Algebra.Group.Subgroup.Even

/-!
# The dyadic fake Kummer quotient for `X₁(13)`

This file constructs the actual multiplicative target used by the local fake
two-descent: units of the explicit dyadic sextic algebra, modulo squares and
units coming from `ℚ₂`.  The two Hensel points constructed previously are
then represented by the honest unit classes of `qB` and `qC`.

No Jacobian group law or local-image spanning claim is made here.  The point
is to replace the earlier informal phrase "up to squares and scalars" by a
checked quotient group and exact class equalities.
-/

namespace MazurTorsion.XOneThirteenTwoDescentLocalKummerQuotient

open XOneThirteenTwoDescentLocalElements
open XOneThirteenTwoDescentLocalKummerPoints
open XOneThirteenTwoDescentLocalKummerUnits

noncomputable section

private instance : Fact (Nat.Prime 2) := ⟨by decide⟩

/-- Scalar units from `ℚ₂` inside the dyadic sextic algebra. -/
def scalarUnitMap : ℚ_[2]ˣ →* MagmaPadicAlgebraˣ :=
  Units.map (algebraMap ℚ_[2] MagmaPadicAlgebra).toMonoidHom

/-- The subgroup generated by squares and scalar units. -/
def localKummerRelations : Subgroup MagmaPadicAlgebraˣ :=
  Subgroup.square MagmaPadicAlgebraˣ ⊔ scalarUnitMap.range

/-- The genuine dyadic fake Kummer target. -/
abbrev LocalFakeKummer :=
  MagmaPadicAlgebraˣ ⧸ localKummerRelations

/-- Projection of an algebra unit to its fake Kummer class. -/
def localKummerClass : MagmaPadicAlgebraˣ →* LocalFakeKummer :=
  QuotientGroup.mk' localKummerRelations

@[simp]
theorem localKummerClass_square (u : MagmaPadicAlgebraˣ) :
    localKummerClass (u ^ 2) = 1 := by
  change ((u ^ 2 : MagmaPadicAlgebraˣ) : LocalFakeKummer) = 1
  apply (QuotientGroup.eq_one_iff _).mpr
  apply (show Subgroup.square MagmaPadicAlgebraˣ ≤
    localKummerRelations from le_sup_left)
  exact (show IsSquare (u ^ 2) from ⟨u, by simp [pow_two]⟩)

@[simp]
theorem localKummerClass_scalar (q : ℚ_[2]ˣ) :
    localKummerClass (scalarUnitMap q) = 1 := by
  change ((scalarUnitMap q : MagmaPadicAlgebraˣ) : LocalFakeKummer) = 1
  apply (QuotientGroup.eq_one_iff _).mpr
  apply (show scalarUnitMap.range ≤ localKummerRelations from le_sup_right)
  exact ⟨q, rfl⟩

/-- The nonzero dyadic scalar `2`, as a unit. -/
def padicTwoUnit : ℚ_[2]ˣ :=
  Units.mk0 2 (by norm_num)

/-- Unit representative of the point at `x = 1/2`.  Its scalar factor is
discarded in `LocalFakeKummer`. -/
def pointOneHalfUnit : MagmaPadicAlgebraˣ :=
  (scalarUnitMap padicTwoUnit)⁻¹ * padicQBUnit

/-- Unit representative of the point at `x = 2`. -/
def pointTwoUnit : MagmaPadicAlgebraˣ :=
  padicQCUnit

/-- The chosen unit above `x = 1/2` has exactly the expected underlying
`x - a²` value. -/
theorem pointOneHalfUnit_coe :
    (pointOneHalfUnit : MagmaPadicAlgebra) =
      pointKummerRepresentative (1 / 2) := by
  have hscalar :
      (algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) *
          (2 : MagmaPadicAlgebra)) = 1 := by
    rw [← map_ofNat (algebraMap ℚ_[2] MagmaPadicAlgebra) 2,
      ← map_mul]
    norm_num
  change
    algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) *
        magmaOrderToPadic localQB =
      pointKummerRepresentative (1 / 2)
  rw [← two_mul_pointKummerRepresentative_oneHalf]
  calc
    algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) *
        (2 * pointKummerRepresentative (1 / 2)) =
        (algebraMap ℚ_[2] MagmaPadicAlgebra ((2 : ℚ_[2])⁻¹) *
          2) * pointKummerRepresentative (1 / 2) := by ring
    _ = pointKummerRepresentative (1 / 2) := by rw [hscalar, one_mul]

/-- The chosen unit above `x = 2` has exactly the expected underlying
`x - a²` value. -/
@[simp]
theorem pointTwoUnit_coe :
    (pointTwoUnit : MagmaPadicAlgebra) =
      pointKummerRepresentative 2 := by
  rw [pointTwoUnit, padicQCUnit_coe, pointKummerRepresentative_two]

/-- In the fake quotient, the point at `x = 1/2` is represented by `qB`. -/
theorem pointOneHalf_class_eq_qB :
    localKummerClass pointOneHalfUnit =
      localKummerClass padicQBUnit := by
  simp [pointOneHalfUnit, map_mul]

/-- In the fake quotient, the point at `x = 2` is represented by `qC`. -/
theorem pointTwo_class_eq_qC :
    localKummerClass pointTwoUnit =
      localKummerClass padicQCUnit := by
  rfl

/-- Both actual local point classes, bundled for the later local-image
calculation. -/
theorem two_local_point_classes :
    localKummerClass pointOneHalfUnit =
        localKummerClass padicQBUnit ∧
      localKummerClass pointTwoUnit =
        localKummerClass padicQCUnit :=
  ⟨pointOneHalf_class_eq_qB, pointTwo_class_eq_qC⟩

end

end MazurTorsion.XOneThirteenTwoDescentLocalKummerQuotient
