/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI Codex
-/

import MazurTorsion.ModularCurve.XZeroEllipticQuotientRepresentability
import MazurTorsion.ModularCurve.XZeroWeierstrassProjectivePointAddition
import MazurTorsion.NumberTheory.XZeroFortyNineTransfer

/-!
# The constructed elliptic quotient at level 49

The exact-order-49 source in `XZeroFortyNineTransfer` already supplies the
split finite-flat cyclic subgroup generated by the rational torsion point.
The representability theorem imported here constructs its ambient elliptic
quotient.  This file is the arithmetic downstream consumer: unlike the older
geometric seam, none of its declarations accepts a quotient presentation as
input.  Its group object and projective-point comparison are the canonical
constructions on the concrete reduced Weierstrass cubic.  The point comparison
is derived from the checked compatibility of that group law with coordinate
addition; neither an abstract group object nor an arbitrary equivalence of
rational-point groups is accepted.

The resulting quotient is smooth of relative dimension one.  Its projection is fppf, its
displayed scheme-theoretic kernel is the actual order-49 subgroup, and its point quotient
injects into quotient-scheme
rational points with the expected fppf-boundary exactness, and the kernel
identification survives arbitrary base change (with the field-extension
specialization used by the order-49 API recorded separately).
-/

noncomputable section

open CategoryTheory CategoryTheory.MonoidalCategory CategoryTheory.MonObj
open AlgebraicGeometry
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli.WeierstrassGroupSchemeInterface
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli.WeierstrassProjectiveCubic
open EllipticQuotientRepresentability

attribute [local instance] CategoryTheory.Over.cartesianMonoidalCategory
  CategoryTheory.Over.braidedCategory

namespace MazurTorsion.XZeroFortyNine

noncomputable local instance concreteGeometricallyIntegral
    (E : WeierstrassCurve ℚ) : GeometricallyIntegral (toOver E).hom := by
  change GeometricallyIntegral (structureMap E)
  exact structureMap_geometricallyIntegral E

noncomputable local instance datumOfTorsionGrpObj
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    GrpObj
      (toOver
        (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP).curve) := by
  change GrpObj (toOver E)
  infer_instance

noncomputable local instance datumOfTorsionGeometricallyIntegral
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    GeometricallyIntegral
      (toOver
        (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP).curve).hom := by
  change GeometricallyIntegral (structureMap E)
  exact structureMap_geometricallyIntegral E

/-- The canonical equivalence from coordinate points to represented geometric points, derived
from compatibility of the concrete cubic's group-object law.  This prevents the order-49
consumer from transporting `P` through an unrelated abstract group equivalence. -/
noncomputable def orderFortyNineCanonicalPointEquiv
    (E : WeierstrassCurve ℚ) [E.IsElliptic] :
    Multiplicative E.toProjective.Point ≃*
      AbelianVarietyRationalPoint (toAbelianVariety E) :=
  canonicalProjectivePointEquivOfGroupLaw E
    (canonicalPointGroupLawCompatibility E).map_zero
    (canonicalPointGroupLawCompatibility E).map_add

/-- The order-49 point comparison is definitionally the canonical coordinate-to-scheme map. -/
@[simp]
theorem orderFortyNineCanonicalPointEquiv_apply
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (Q : Multiplicative E.toProjective.Point) :
    orderFortyNineCanonicalPointEquiv E Q =
      projectivePointToAbelianVarietyRationalPoint E Q.toAdd :=
  canonicalProjectivePointEquivOfGroupLaw_apply E
    (canonicalPointGroupLawCompatibility E).map_zero
    (canonicalPointGroupLawCompatibility E).map_add Q

/-- The concrete cubic group-scheme interface used by the constructed order-49 quotient.  This
is deliberately obtained from the cubic itself, rather than accepted as an arbitrary interface
having only the same group of rational points. -/
noncomputable def orderFortyNineConcreteGroupSchemeInterface
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    WeierstrassGroupSchemeInterface E :=
  EllipticQuotientRepresentability.concreteGroupSchemeInterface
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E)

/-- The actual abelian variety obtained by quotienting the concrete Weierstrass cubic by the
subgroup generated by the order-49 point. -/
noncomputable def orderFortyNineEllipticQuotient
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    TauCeti.AlgebraicGeometry.AbelianVariety ℚ :=
  EllipticQuotientRepresentability.quotientAbelianVariety
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E)

/-- The genuine finite étale projection from the concrete cubic to its represented
order-49 quotient abelian variety. -/
noncomputable def orderFortyNineEllipticQuotientProjection
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    (orderFortyNineConcreteGroupSchemeInterface E P hP).groupScheme ⟶
      CommGrp.mk (orderFortyNineEllipticQuotient E P hP).toOver :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVariety
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E)

/-- The actual elliptic-quotient presentation attached to a rational point
of exact order 49.  There is deliberately no supplied quotient argument. -/
noncomputable def orderFortyNineEllipticQuotientPresentation
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    CommGroupScheme.FppfQuotientPresentation
      (splitFiniteFlatSourceOfOrderFortyNineTorsion E
        (orderFortyNineConcreteGroupSchemeInterface E P hP) P hP).subgroup.inclusion :=
  EllipticQuotientRepresentability.geometricQuotientPresentation
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E)

@[simp]
theorem orderFortyNineEllipticQuotient_toOver
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    (orderFortyNineEllipticQuotient E P hP).toOver =
      (orderFortyNineEllipticQuotientPresentation E P hP).quotient.X :=
  rfl

/-- The represented order-49 quotient is genuinely one-dimensional, not only an abelian
group scheme with a finite étale presentation. -/
theorem orderFortyNineEllipticQuotient_structureMap_smoothOfRelativeDimension_one
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    SmoothOfRelativeDimension 1
      (orderFortyNineEllipticQuotient E P hP).toOver.hom := by
  change SmoothOfRelativeDimension 1
    (EllipticQuotientRepresentability.quotient
      (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
      (orderFortyNineCanonicalPointEquiv E)).X.hom
  exact EllipticQuotientRepresentability.quotient_structureMap_smoothOfRelativeDimension_one
      (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
      (orderFortyNineCanonicalPointEquiv E)

/-- The projection exposed by the abelian quotient is the projection in the exact-kernel
presentation. -/
theorem orderFortyNineEllipticQuotientProjection_eq_presentation
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    orderFortyNineEllipticQuotientProjection E P hP =
      (orderFortyNineEllipticQuotientPresentation E P hP).project :=
  rfl

/-- The constructed order-49 projection is an fppf cover of its quotient. -/
theorem orderFortyNineEllipticQuotientProjection_is_fppf
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    Flat (AlgebraicGeometry.CommGroupScheme.underlyingHom
      (orderFortyNineEllipticQuotientProjection E P hP)) ∧
      Surjective (AlgebraicGeometry.CommGroupScheme.underlyingHom
        (orderFortyNineEllipticQuotientProjection E P hP)) ∧
      LocallyOfFinitePresentation (AlgebraicGeometry.CommGroupScheme.underlyingHom
        (orderFortyNineEllipticQuotientProjection E P hP)) :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVariety_is_fppf
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E)

/-- The actual order-49 projection to the represented abelian quotient is finite. -/
theorem orderFortyNineEllipticQuotientProjection_isFinite
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    IsFinite (AlgebraicGeometry.CommGroupScheme.underlyingHom
      (orderFortyNineEllipticQuotientProjection E P hP)) :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVariety_isFinite
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E)

/-- The actual order-49 projection to the represented abelian quotient is étale. -/
theorem orderFortyNineEllipticQuotientProjection_etale
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    Etale (AlgebraicGeometry.CommGroupScheme.underlyingHom
      (orderFortyNineEllipticQuotientProjection E P hP)) :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVariety_etale
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E)

/-- The geometric kernel of the constructed projection is exactly the
finite-flat subgroup generated by the order-49 point. -/
theorem orderFortyNineEllipticQuotient_kernel_exact
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    (orderFortyNineEllipticQuotientPresentation E P hP).kernelIso.hom ≫
        CommGroupScheme.kernelInclusion
          (orderFortyNineEllipticQuotientPresentation E P hP).project =
      (splitFiniteFlatSourceOfOrderFortyNineTorsion E
        (orderFortyNineConcreteGroupSchemeInterface E P hP) P hP).subgroup.inclusion :=
  (orderFortyNineEllipticQuotientPresentation E P hP).kernelIso_hom_kernelInclusion

/-- Exact geometric kernel of the named projection to the represented order-49 abelian
quotient. -/
theorem orderFortyNineEllipticQuotientProjection_kernel_exact
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    (EllipticQuotientRepresentability.projectionToQuotientAbelianVarietyKernelIso
          (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
          (orderFortyNineCanonicalPointEquiv E)).hom ≫
        CommGroupScheme.kernelInclusion
          (orderFortyNineEllipticQuotientProjection E P hP) =
      (splitFiniteFlatSourceOfOrderFortyNineTorsion E
        (orderFortyNineConcreteGroupSchemeInterface E P hP) P hP).subgroup.inclusion :=
  EllipticQuotientRepresentability.projectionToQuotientAbelianVarietyKernelIso_hom_kernelInclusion
      (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
      (orderFortyNineCanonicalPointEquiv E)

/-- The quotient of represented rational points by the actual order-49
subgroup injects into the rational points of the constructed quotient. -/
theorem orderFortyNineEllipticQuotientPointQuotientMap_injective
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    Function.Injective
      ((orderFortyNineEllipticQuotientPresentation E P hP).pointQuotientMap
        (AffineCommGroupScheme.testObject (R := ℚ) ℚ)) :=
  orderFortyNineGeometricPointQuotientMap_injective E
    (orderFortyNineConcreteGroupSchemeInterface E P hP) P hP
    (orderFortyNineEllipticQuotientPresentation E P hP)

/-- The image of the constructed order-49 point quotient is exactly the zero
fibre of its genuine fppf connecting map. -/
theorem orderFortyNineEllipticQuotient_boundary_exact
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    Function.MulExact
      ((orderFortyNineEllipticQuotientPresentation E P hP).pointQuotientMap
        (AffineCommGroupScheme.testObject (R := ℚ) ℚ))
      (WeierstrassGroupSchemeInterface.rationalDatumGeometricPointBoundaryHom
        (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
        (orderFortyNineConcreteGroupSchemeInterface E P hP)
        (orderFortyNineEllipticQuotientPresentation E P hP)) :=
  orderFortyNineGeometricPointQuotient_boundary_exact E
    (orderFortyNineConcreteGroupSchemeInterface E P hP) P hP
    (orderFortyNineEllipticQuotientPresentation E P hP)

/-- The exact-kernel presentation of the constructed order-49 quotient is
compatible with pullback along an arbitrary morphism of base schemes. -/
theorem orderFortyNineEllipticQuotient_baseChange_kernel_inclusion
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange
      t).kernelPresentation.inclusion =
      (Over.pullback t).mapCommGrp.map
        (splitFiniteFlatSourceOfOrderFortyNineTorsion E
          (orderFortyNineConcreteGroupSchemeInterface E P hP) P hP).subgroup.inclusion :=
  EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange_kernel_inclusion
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E) t

/-- The quotient object in the arbitrary-base-change presentation is literally the pullback of
the constructed order-49 quotient. -/
theorem orderFortyNineEllipticQuotient_baseChange_quotient
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).quotient =
      (Over.pullback t).mapCommGrp.obj
        (orderFortyNineEllipticQuotientPresentation E P hP).quotient :=
  EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange_quotient
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E) t

/-- The projection in the arbitrary-base-change presentation is literally the pullback of the
constructed order-49 projection. -/
theorem orderFortyNineEllipticQuotient_baseChange_project
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).project =
      (Over.pullback t).mapCommGrp.map
        (orderFortyNineEllipticQuotientPresentation E P hP).project :=
  EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange_project
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E) t

/-- Every base change of the constructed order-49 projection remains finite. -/
theorem orderFortyNineEllipticQuotient_baseChange_project_isFinite
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    IsFinite (AlgebraicGeometry.CommGroupScheme.underlyingHom
      ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).project) :=
  EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange_project_isFinite
      (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
      (orderFortyNineCanonicalPointEquiv E) t

/-- Every base change of the constructed order-49 projection remains étale. -/
theorem orderFortyNineEllipticQuotient_baseChange_project_etale
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    Etale (AlgebraicGeometry.CommGroupScheme.underlyingHom
      ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).project) :=
  EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange_project_etale
      (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
      (orderFortyNineCanonicalPointEquiv E) t

/-- Every base change of the constructed order-49 quotient remains smooth of relative dimension
one. -/
theorem
    orderFortyNineEllipticQuotient_baseChange_quotient_structureMap_smoothOfRelativeDimension_one
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    SmoothOfRelativeDimension 1
      ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange
        t).quotient.X.hom := by
  change SmoothOfRelativeDimension 1
    (EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange
      (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
      (orderFortyNineCanonicalPointEquiv E) t).quotient.X.hom
  exact
    geometricQuotientPresentationBaseChange_quotient_structureMap_smoothOfRelativeDimension_one
      (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
      (orderFortyNineCanonicalPointEquiv E) t

/-- The pulled-back order-49 subgroup remains exactly the geometric kernel after every base
change, not merely after field extension. -/
theorem orderFortyNineEllipticQuotient_baseChange_kernel_exact
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).kernelIso.hom ≫
        CommGroupScheme.kernelInclusion
          ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).project =
      (Over.pullback t).mapCommGrp.map
        (splitFiniteFlatSourceOfOrderFortyNineTorsion E
          (orderFortyNineConcreteGroupSchemeInterface E P hP) P hP).subgroup.inclusion :=
  EllipticQuotientRepresentability.geometricQuotientPresentationBaseChange_kernel_exact
    (ModularCurve.XZeroModuli.RationalDatum.datumOfTorsion E P hP)
    (orderFortyNineCanonicalPointEquiv E) t

/-- For every field extension of `ℚ`, the base-changed kernel inclusion is
the finite-flat base change of the subgroup generated by the order-49 point. -/
theorem orderFortyNineEllipticQuotient_fieldBaseChange_kernel_inclusion
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (L : Type) [Field L] [Algebra ℚ L] :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange
      (Spec.map (CommRingCat.ofHom (algebraMap ℚ L)))).kernelPresentation.inclusion =
      ((splitFiniteFlatSourceOfOrderFortyNineTorsion E
        (orderFortyNineConcreteGroupSchemeInterface E P hP)
        P hP).subgroup.baseChange).inclusion :=
  orderFortyNineGeometricQuotient_baseChange_kernel_inclusion E
    (orderFortyNineConcreteGroupSchemeInterface E P hP) P hP
    (orderFortyNineEllipticQuotientPresentation E P hP) L

end MazurTorsion.XZeroFortyNine
