/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI Codex
-/

import MazurTorsion.ModularCurve.XZeroWeierstrassCanonicalCyclicQuotient
import MazurTorsion.NumberTheory.XZeroFortyNineTransfer

/-!
# The constructed elliptic quotient at level 49

The exact-order-49 source in `XZeroFortyNineTransfer` already supplies the
split finite-flat cyclic subgroup generated by the rational torsion point.
The canonical quotient construction imported here constructs its ambient
elliptic quotient.  This file is the arithmetic downstream consumer: unlike
the older geometric seam, none of its declarations accepts a quotient
presentation as input or rebuilds one from a raw rational datum and point
equivalence.  Its group object, finite-flat subgroup, and quotient are the
canonical constructions on the concrete reduced Weierstrass cubic.

The resulting quotient is smooth of relative dimension one.  Its projection
is fppf, its displayed scheme-theoretic kernel is the actual order-49
subgroup, and its point quotient injects into quotient-scheme rational points
with the expected fppf-boundary exactness.  The kernel identification survives
arbitrary base change, with the field-extension specialization recorded
separately.
-/

noncomputable section

open CategoryTheory CategoryTheory.MonoidalCategory CategoryTheory.MonObj
open AlgebraicGeometry
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli.WeierstrassGroupSchemeInterface
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli.WeierstrassProjectiveCubic

attribute [local instance] CategoryTheory.Over.cartesianMonoidalCategory
  CategoryTheory.Over.braidedCategory

namespace MazurTorsion.XZeroFortyNine

/-- The canonical equivalence from coordinate points to represented geometric points, derived
from compatibility of the concrete cubic's group-object law.  This prevents the order-49
consumer from transporting `P` through an unrelated abstract group equivalence. -/
noncomputable def orderFortyNineCanonicalPointEquiv
    (E : WeierstrassCurve ℚ) [E.IsElliptic] :
    Multiplicative E.toProjective.Point ≃*
      AbelianVarietyRationalPoint (toAbelianVariety E) :=
  canonicalProjectivePointMulEquiv E

/-- The order-49 point comparison is definitionally the canonical coordinate-to-scheme map. -/
@[simp]
theorem orderFortyNineCanonicalPointEquiv_apply
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (Q : Multiplicative E.toProjective.Point) :
    orderFortyNineCanonicalPointEquiv E Q =
      projectivePointToAbelianVarietyRationalPoint E Q.toAdd :=
  canonicalProjectivePointMulEquiv_apply E Q

/-- The concrete cubic group-scheme interface used by the constructed order-49 quotient.  This
is deliberately obtained from the cubic itself, rather than accepted as an arbitrary interface
having only the same group of rational points. -/
noncomputable def orderFortyNineConcreteGroupSchemeInterface
    (E : WeierstrassCurve ℚ) [E.IsElliptic] :
    WeierstrassGroupSchemeInterface E :=
  canonicalWeierstrassGroupSchemeInterface E

/-- The actual abelian variety obtained by quotienting the concrete Weierstrass cubic by the
subgroup generated by the order-49 point. -/
noncomputable def orderFortyNineEllipticQuotient
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    TauCeti.AlgebraicGeometry.AbelianVariety ℚ :=
  canonicalCyclicQuotientAbelianVariety E P hP

/-- The genuine finite étale projection from the concrete cubic to its represented
order-49 quotient abelian variety. -/
noncomputable def orderFortyNineEllipticQuotientProjection
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    (orderFortyNineConcreteGroupSchemeInterface E).groupScheme ⟶
      CommGrp.mk (orderFortyNineEllipticQuotient E P hP).toOver :=
  canonicalCyclicQuotientProjection E P hP

/-- The actual elliptic-quotient presentation attached to a rational point
of exact order 49.  There is deliberately no supplied quotient argument. -/
noncomputable def orderFortyNineEllipticQuotientPresentation
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    CommGroupScheme.FppfQuotientPresentation
      (splitFiniteFlatSourceOfOrderFortyNineTorsion E P hP).subgroup.inclusion :=
  canonicalCyclicQuotientPresentation E P hP

@[simp]
theorem orderFortyNineEllipticQuotient_toOver
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    (orderFortyNineEllipticQuotient E P hP).toOver =
      (orderFortyNineEllipticQuotientPresentation E P hP).quotient.X :=
  canonicalCyclicQuotientAbelianVariety_toOver E P hP

/-- The represented order-49 quotient is genuinely one-dimensional, not only an abelian
group scheme with a finite étale presentation. -/
theorem orderFortyNineEllipticQuotient_structureMap_smoothOfRelativeDimension_one
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    SmoothOfRelativeDimension 1
      (orderFortyNineEllipticQuotient E P hP).toOver.hom :=
  canonicalCyclicQuotient_structureMap_smoothOfRelativeDimension_one E P hP

/-- The projection exposed by the abelian quotient is the projection in the exact-kernel
presentation. -/
theorem orderFortyNineEllipticQuotientProjection_eq_presentation
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    orderFortyNineEllipticQuotientProjection E P hP =
      (orderFortyNineEllipticQuotientPresentation E P hP).project :=
  canonicalCyclicQuotientProjection_eq_presentation E P hP

/-- The constructed order-49 projection is an fppf cover of its quotient. -/
theorem orderFortyNineEllipticQuotientProjection_is_fppf
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    Flat (AlgebraicGeometry.CommGroupScheme.underlyingHom
      (orderFortyNineEllipticQuotientProjection E P hP)) ∧
      Surjective (AlgebraicGeometry.CommGroupScheme.underlyingHom
        (orderFortyNineEllipticQuotientProjection E P hP)) ∧
      LocallyOfFinitePresentation (AlgebraicGeometry.CommGroupScheme.underlyingHom
        (orderFortyNineEllipticQuotientProjection E P hP)) :=
  canonicalCyclicQuotientProjection_is_fppf E P hP

/-- The actual order-49 projection to the represented abelian quotient is finite. -/
theorem orderFortyNineEllipticQuotientProjection_isFinite
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    IsFinite (AlgebraicGeometry.CommGroupScheme.underlyingHom
      (orderFortyNineEllipticQuotientProjection E P hP)) :=
  canonicalCyclicQuotientProjection_isFinite E P hP

/-- The actual order-49 projection to the represented abelian quotient is étale. -/
theorem orderFortyNineEllipticQuotientProjection_etale
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    Etale (AlgebraicGeometry.CommGroupScheme.underlyingHom
      (orderFortyNineEllipticQuotientProjection E P hP)) :=
  canonicalCyclicQuotientProjection_etale E P hP

/-- The geometric kernel of the constructed projection is exactly the
finite-flat subgroup generated by the order-49 point. -/
theorem orderFortyNineEllipticQuotient_kernel_exact
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    (orderFortyNineEllipticQuotientPresentation E P hP).kernelIso.hom ≫
        CommGroupScheme.kernelInclusion
          (orderFortyNineEllipticQuotientPresentation E P hP).project =
      (splitFiniteFlatSourceOfOrderFortyNineTorsion E P hP).subgroup.inclusion :=
  canonicalCyclicQuotientPresentation_kernel_exact E P hP

/-- Exact geometric kernel of the named projection to the represented order-49 abelian
quotient. -/
theorem orderFortyNineEllipticQuotientProjection_kernel_exact
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    (canonicalCyclicQuotientProjectionKernelIso E P hP).hom ≫
        CommGroupScheme.kernelInclusion
          (orderFortyNineEllipticQuotientProjection E P hP) =
      (splitFiniteFlatSourceOfOrderFortyNineTorsion E P hP).subgroup.inclusion :=
  canonicalCyclicQuotientProjectionKernelIso_hom_kernelInclusion E P hP

/-- The quotient of represented rational points by the actual order-49
subgroup injects into the rational points of the constructed quotient. -/
theorem orderFortyNineEllipticQuotientPointQuotientMap_injective
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    Function.Injective
      ((orderFortyNineEllipticQuotientPresentation E P hP).pointQuotientMap
        (AffineCommGroupScheme.testObject (R := ℚ) ℚ)) :=
  canonicalCyclicQuotientPointQuotientMap_injective E P hP

/-- The image of the constructed order-49 point quotient is exactly the zero
fibre of its genuine fppf connecting map. -/
theorem orderFortyNineEllipticQuotient_boundary_exact
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49) :
    Function.MulExact
      ((orderFortyNineEllipticQuotientPresentation E P hP).pointQuotientMap
        (AffineCommGroupScheme.testObject (R := ℚ) ℚ))
      (canonicalCyclicQuotientBoundaryHom E P hP) :=
  canonicalCyclicQuotientPointQuotient_boundary_exact E P hP

/-- The exact-kernel presentation of the constructed order-49 quotient is
compatible with pullback along an arbitrary morphism of base schemes. -/
theorem orderFortyNineEllipticQuotient_baseChange_kernel_inclusion
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange
      t).kernelPresentation.inclusion =
      (Over.pullback t).mapCommGrp.map
        (splitFiniteFlatSourceOfOrderFortyNineTorsion E P hP).subgroup.inclusion :=
  canonicalCyclicQuotientPresentationBaseChange_kernel_inclusion E P hP t

/-- The quotient object in the arbitrary-base-change presentation is literally the pullback of
the constructed order-49 quotient. -/
theorem orderFortyNineEllipticQuotient_baseChange_quotient
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).quotient =
      (Over.pullback t).mapCommGrp.obj
        (orderFortyNineEllipticQuotientPresentation E P hP).quotient :=
  canonicalCyclicQuotientPresentationBaseChange_quotient E P hP t

/-- The projection in the arbitrary-base-change presentation is literally the pullback of the
constructed order-49 projection. -/
theorem orderFortyNineEllipticQuotient_baseChange_project
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).project =
      (Over.pullback t).mapCommGrp.map
        (orderFortyNineEllipticQuotientPresentation E P hP).project :=
  canonicalCyclicQuotientPresentationBaseChange_project E P hP t

/-- Every base change of the constructed order-49 projection remains finite. -/
theorem orderFortyNineEllipticQuotient_baseChange_project_isFinite
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    IsFinite (AlgebraicGeometry.CommGroupScheme.underlyingHom
      ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).project) :=
  canonicalCyclicQuotientPresentationBaseChange_project_isFinite E P hP t

/-- Every base change of the constructed order-49 projection remains étale. -/
theorem orderFortyNineEllipticQuotient_baseChange_project_etale
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    Etale (AlgebraicGeometry.CommGroupScheme.underlyingHom
      ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).project) :=
  canonicalCyclicQuotientPresentationBaseChange_project_etale E P hP t

/-- Every base change of the constructed order-49 quotient remains smooth of relative dimension
one. -/
theorem
    orderFortyNineEllipticQuotient_baseChange_quotient_structureMap_smoothOfRelativeDimension_one
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    SmoothOfRelativeDimension 1
      ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange
        t).quotient.X.hom :=
  canonicalCyclicQuotientBaseChange_smoothOfRelativeDimension_one E P hP t

/-- The pulled-back order-49 subgroup remains exactly the geometric kernel after every base
change, not merely after field extension. -/
theorem orderFortyNineEllipticQuotient_baseChange_kernel_exact
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (T : Scheme) (t : T ⟶ Spec (CommRingCat.of ℚ)) :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).kernelIso.hom ≫
        CommGroupScheme.kernelInclusion
          ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange t).project =
      (Over.pullback t).mapCommGrp.map
        (splitFiniteFlatSourceOfOrderFortyNineTorsion E P hP).subgroup.inclusion :=
  canonicalCyclicQuotientPresentationBaseChange_kernel_exact E P hP t

/-- For every field extension of `ℚ`, the base-changed kernel inclusion is
the finite-flat base change of the subgroup generated by the order-49 point. -/
theorem orderFortyNineEllipticQuotient_fieldBaseChange_kernel_inclusion
    (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (P : E.toAffine.Point) (hP : addOrderOf P = 49)
    (L : Type) [Field L] [Algebra ℚ L] :
    ((orderFortyNineEllipticQuotientPresentation E P hP).baseChange
      (Spec.map (CommRingCat.ofHom (algebraMap ℚ L)))).kernelPresentation.inclusion =
      ((splitFiniteFlatSourceOfOrderFortyNineTorsion E P hP).subgroup.baseChange).inclusion :=
  canonicalCyclicQuotient_fieldBaseChange_kernel_inclusion E P hP L

end MazurTorsion.XZeroFortyNine
