/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, OpenAI Codex
-/

import MazurTorsion.ModularCurve.XZeroEllipticQuotientRepresentability
import MazurTorsion.ModularCurve.XZeroWeierstrassGeometricIntegrality

/-!
# The residual order-seven point on the level-49 quotient

A rational cyclic subgroup of order 49 contains its intrinsic subgroup of
order seven.  Quotienting by that subgroup leaves the class of the original
generator with exact order seven.  This file checks that statement first in
the coordinate point group and then on any geometric quotient whose kernel is
the actual finite-flat level-seven subgroup.

The final declarations instantiate the reviewed finite-translation quotient
constructor.  They do not choose a Weierstrass model for `X₀(49)`, construct a
classifying map, or assert that the resulting point is noncuspidal.
-/

noncomputable section

open CategoryTheory CategoryTheory.MonoidalCategory CategoryTheory.MonObj
open AlgebraicGeometry
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli.WeierstrassGroupSchemeInterface
open MazurTorsion.ModularCurve.XZeroFiniteFlatModuli.WeierstrassProjectiveCubic
open EllipticQuotientRepresentability

attribute [local instance] CategoryTheory.Over.cartesianMonoidalCategory
  CategoryTheory.Over.braidedCategory

namespace MazurTorsion.XZeroFortyNine

private abbrev baseTestObject :=
  AffineCommGroupScheme.testObject (R := ℚ) ℚ

private theorem seven_dvd_fortyNine : 7 ∣ 49 := by norm_num

/-- In the coordinate point quotient by the intrinsic order-seven subgroup,
the original order-49 generator has exact order seven. -/
theorem levelSevenPointQuotient_generator_addOrderOf
    (x : ModularCurve.XZeroModuli.RationalDatum ℚ 49) :
    addOrderOf
        ((x.forgetToDivisor 7 seven_dvd_fortyNine).pointQuotientMap
          x.generator) = 7 := by
  change addOrderOf
    ((x.subgroup.divisorSubgroup 7 seven_dvd_fortyNine).quotientMap
      (x.subgroup.generator : x.curve.toAffine.Point)) = 7
  exact x.subgroup.addOrderOf_divisorSubgroup_quotientMap_generator
    7 seven_dvd_fortyNine

/-- The image of the order-49 generator on a supplied geometric quotient by
the actual finite-flat order-seven subgroup. -/
noncomputable def levelSevenGeometricResidualPoint
    (x : ModularCurve.XZeroModuli.RationalDatum ℚ 49)
    (M : WeierstrassGroupSchemeInterface
      (x.forgetToDivisor 7 seven_dvd_fortyNine).curve)
    (Q : RationalDatumGeometricQuotientPresentation
      (x.forgetToDivisor 7 seven_dvd_fortyNine) M) :
    Q.quotient.Point baseTestObject :=
  AlgebraicGeometry.CommGroupScheme.mapPoint Q.project baseTestObject
    (M.rationalPointEquiv (Multiplicative.ofAdd x.generator))

/-- The residual point has exact order seven because the displayed geometric
kernel is exactly the finite-flat subgroup generated by `7 • x.generator`.
-/
theorem levelSevenGeometricResidualPoint_orderOf
    (x : ModularCurve.XZeroModuli.RationalDatum ℚ 49)
    (M : WeierstrassGroupSchemeInterface
      (x.forgetToDivisor 7 seven_dvd_fortyNine).curve)
    (Q : RationalDatumGeometricQuotientPresentation
      (x.forgetToDivisor 7 seven_dvd_fortyNine) M) :
    orderOf (levelSevenGeometricResidualPoint x M Q) = 7 := by
  let x7 := x.forgetToDivisor 7 seven_dvd_fortyNine
  let R := M.rationalPointEquiv (Multiplicative.ofAdd x.generator)
  letI : Fact (Nat.Prime 7) := ⟨Nat.prime_seven⟩
  apply orderOf_eq_prime
  · change (AlgebraicGeometry.CommGroupScheme.mapPoint
      Q.project baseTestObject R) ^ 7 = 1
    rw [← map_pow]
    apply (Q.project_point_eq_one_iff baseTestObject (R ^ 7)).2
    change Additive.ofMul (R ^ 7) ∈
      (Q.pointKernelRange baseTestObject).toAddSubgroup
    rw [rationalDatumGeometricPointKernelRange_toAddSubgroup x7 M Q,
      finiteFlatSubgroupPointRange_eq_map]
    refine ⟨(7 : ℕ) • x.generator, ?_, ?_⟩
    · change (7 : ℕ) • x.generator ∈
        (x.subgroup.divisorSubgroup 7 seven_dvd_fortyNine).carrier
      rw [x.subgroup.divisorSubgroup_generator_carrier]
      exact AddSubgroup.mem_zmultiples_iff.mpr ⟨1, by
        norm_num [ModularCurve.XZeroModuli.RationalDatum.generator]⟩
    · change rationalPointAddEquiv M (7 • x.generator) =
        7 • rationalPointAddEquiv M x.generator
      exact map_nsmul (rationalPointAddEquiv M) 7 x.generator
  · intro hpoint
    have hkernel : R ∈ Q.pointKernelRange baseTestObject := by
      apply (Q.project_point_eq_one_iff baseTestObject R).1
      simpa [levelSevenGeometricResidualPoint, R] using hpoint
    have hrange : Additive.ofMul R ∈ finiteFlatSubgroupPointRange x7 M := by
      rw [← rationalDatumGeometricPointKernelRange_toAddSubgroup x7 M Q]
      exact hkernel
    rw [finiteFlatSubgroupPointRange_eq_map] at hrange
    rcases hrange with ⟨P, hP, hPeq⟩
    have hgenerator : (P : x7.curve.toAffine.Point) = x.generator := by
      apply (rationalPointAddEquiv M).injective
      change rationalPointAddEquiv M P =
        rationalPointAddEquiv M x.generator at hPeq
      exact hPeq
    have hgeneratorMem : x.generator ∈ x7.subgroup.carrier := by
      rw [hgenerator] at hP
      change x.generator ∈ x7.subgroup.carrier at hP
      exact hP
    have hsevenZero : (7 : ℕ) • x.generator = 0 :=
      (ModularCurve.XZeroModuli.RationalDatum.forgetToDivisor_subgroup_mem
        x 7 seven_dvd_fortyNine x.generator).mp hgeneratorMem |>.2
    have hdivides : (49 : ℕ) ∣ 7 := by
      rw [← x.addOrderOf_generator]
      exact addOrderOf_dvd_of_nsmul_eq_zero hsevenZero
    norm_num at hdivides

noncomputable local instance rationalDatumGeometricallyIntegral
    (x : ModularCurve.XZeroModuli.RationalDatum ℚ 49) :
    GeometricallyIntegral (toOver x.curve).hom := by
  change GeometricallyIntegral (structureMap x.curve)
  exact structureMap_geometricallyIntegral x.curve

noncomputable local instance levelSevenDatumGrpObj
    (x : ModularCurve.XZeroModuli.RationalDatum ℚ 49)
    [GrpObj (toOver x.curve)] :
    GrpObj (toOver (x.forgetToDivisor 7 seven_dvd_fortyNine).curve) := by
  change GrpObj (toOver x.curve)
  infer_instance

/-- The residual point on the quotient constructed from the concrete cubic
and its canonical coordinate-to-scheme point comparison. -/
noncomputable def levelSevenActualResidualPoint
    (x : ModularCurve.XZeroModuli.RationalDatum ℚ 49)
    [GrpObj (toOver x.curve)]
    (hgroup : CanonicalPointGroupLawCompatibility x.curve) :
    (geometricQuotientPresentation
      (x.forgetToDivisor 7 seven_dvd_fortyNine)
      (canonicalProjectivePointEquivOfGroupLaw x.curve
        hgroup.map_zero hgroup.map_add)).quotient.Point baseTestObject :=
  levelSevenGeometricResidualPoint x
    (concreteGroupSchemeInterface
      (x.forgetToDivisor 7 seven_dvd_fortyNine)
      (canonicalProjectivePointEquivOfGroupLaw x.curve
        hgroup.map_zero hgroup.map_add))
    (geometricQuotientPresentation
      (x.forgetToDivisor 7 seven_dvd_fortyNine)
      (canonicalProjectivePointEquivOfGroupLaw x.curve
        hgroup.map_zero hgroup.map_add))

/-- The reviewed finite-translation quotient constructor carries the same
honest residual order-seven point. -/
theorem levelSevenActualResidualPoint_orderOf
    (x : ModularCurve.XZeroModuli.RationalDatum ℚ 49)
    [GrpObj (toOver x.curve)]
    (hgroup : CanonicalPointGroupLawCompatibility x.curve) :
    orderOf (levelSevenActualResidualPoint x hgroup) = 7 := by
  exact levelSevenGeometricResidualPoint_orderOf x
    (concreteGroupSchemeInterface
      (x.forgetToDivisor 7 seven_dvd_fortyNine)
      (canonicalProjectivePointEquivOfGroupLaw x.curve
        hgroup.map_zero hgroup.map_add))
    (geometricQuotientPresentation
      (x.forgetToDivisor 7 seven_dvd_fortyNine)
      (canonicalProjectivePointEquivOfGroupLaw x.curve
        hgroup.map_zero hgroup.map_add))

end MazurTorsion.XZeroFortyNine
