/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.AlgebraicGeometry.FormalImmersion
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The Nakayama step in the cotangent criterion

This file proves the local-algebra consequence of cotangent surjectivity needed by the formal
immersion route.  For a local homomorphism `A → B`, if the maximal ideal of `B` is finite as a
`B`-module, then a surjection

`m_A / m_A² → m_B / m_B²`

forces the extension of `m_A` to equal `m_B`.  The finiteness assumption is exactly the input to
Nakayama's lemma; Noetherianity of all of `B` is not required.

This is deliberately only the first-order algebra step.  Surjectivity of `A → B` itself requires
additional residue-field lifting and completeness/separatedness hypotheses.  The scheme theorem
below applies the checked local result to stalk maps, and the modular degree-one certificate is a
separate downstream consumer.
-/

namespace IsLocalRing

/-- The cotangent map of a local ring homomorphism, viewed over the common scalar ring `ℤ`. -/
noncomputable def cotangentMap
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f] :
    CotangentSpace A →ₗ[ℤ] CotangentSpace B :=
  Ideal.mapCotangent
    (maximalIdeal A) (maximalIdeal B) f.toIntAlgHom
    (by
      change maximalIdeal A ≤ (maximalIdeal B).comap f
      rw [maximalIdeal_comap])

/-- The local cotangent map sends the class of `a` to the class of `f a`. -/
@[simp]
theorem cotangentMap_toCotangent
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f] (a : maximalIdeal A) :
    cotangentMap f ((maximalIdeal A).toCotangent a) =
      (maximalIdeal B).toCotangent
        ⟨f a, map_nonunit f a a.property⟩ :=
  rfl

/-- The map on second infinitesimal neighbourhoods induced by a local ring homomorphism. -/
def maximalIdealSquareQuotientMap
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f] :
    A ⧸ (maximalIdeal A) ^ 2 →+* B ⧸ (maximalIdeal B) ^ 2 :=
  Ideal.quotientMap (I := (maximalIdeal A) ^ 2) ((maximalIdeal B) ^ 2) f
    (by
      rw [← maximalIdeal_comap f]
      exact Ideal.le_comap_pow f 2)

/-- Nakayama detects whether a submodule of a local ring's maximal ideal is all of it from its
image in the cotangent space.

Mathlib's `IsLocalRing.CotangentSpace.map_eq_top_iff` assumes the whole ring is Noetherian.  This
version records the precise weaker hypothesis used by the proof: the maximal ideal itself is a
finite module. -/
theorem CotangentSpace.map_eq_top_iff_of_finite_maximalIdeal
    {R : Type*} [CommRing R] [IsLocalRing R]
    [Module.Finite R (maximalIdeal R)]
    {M : Submodule R (maximalIdeal R)} :
    M.map (maximalIdeal R).toCotangent = ⊤ ↔ M = ⊤ := by
  refine ⟨fun H ↦ eq_top_iff.mpr ?_, by rintro rfl; simp [Ideal.toCotangent_range]⟩
  refine (Submodule.map_le_map_iff_of_injective (Submodule.injective_subtype _) _ _).mp ?_
  rw [Submodule.map_top, Submodule.range_subtype]
  apply Submodule.le_of_le_smul_of_le_jacobson_bot
    ((Submodule.fg_top (maximalIdeal R)).mp Module.Finite.fg_top)
    (IsLocalRing.jacobson_eq_maximalIdeal _ bot_ne_top).ge
  rw [smul_eq_mul, ← pow_two, ← Ideal.map_toCotangent_ker, ← Submodule.map_sup,
    ← Submodule.comap_map_eq, H, Submodule.comap_top, Submodule.map_top,
    Submodule.range_subtype]

/-- For a local homomorphism, cotangent surjectivity forces the target maximal ideal to be
generated by the image of the source maximal ideal.

Only finite generation of the target maximal ideal is used.  In particular, this conclusion does
not need adic completeness or separatedness. -/
theorem map_maximalIdeal_eq_of_surjective_mapCotangent
    {A B : Type*} [CommRing A] [CommRing B]
    [IsLocalRing A] [IsLocalRing B] [Module.Finite B (maximalIdeal B)]
    (f : A →+* B) [IsLocalHom f]
    (h : Function.Surjective (cotangentMap f)) :
    (maximalIdeal A).map f = maximalIdeal B := by
  let I : Ideal B := (maximalIdeal A).map f
  have hI : I ≤ maximalIdeal B := by
    dsimp [I]
    rw [Ideal.map_le_iff_le_comap, maximalIdeal_comap]
  let M : Submodule B (maximalIdeal B) :=
    Submodule.comap (maximalIdeal B).subtype I
  have hMmap : M.map (maximalIdeal B).toCotangent = ⊤ := by
    rw [eq_top_iff]
    intro z _
    obtain ⟨y, rfl⟩ := h z
    obtain ⟨a, rfl⟩ := (maximalIdeal A).toCotangent_surjective y
    let b : maximalIdeal B :=
      ⟨f a, hI (Ideal.mem_map_of_mem f a.property)⟩
    have hbM : b ∈ M := by
      change (b : B) ∈ I
      exact Ideal.mem_map_of_mem f a.property
    exact ⟨b, hbM, rfl⟩
  have hM : M = ⊤ :=
    CotangentSpace.map_eq_top_iff_of_finite_maximalIdeal.mp hMmap
  apply le_antisymm hI
  intro b hb
  have hbM : (⟨b, hb⟩ : maximalIdeal B) ∈ M := by
    rw [hM]
    exact Submodule.mem_top
  exact hbM

/-- Surjectivity on residue fields gives a lift modulo the target maximal ideal. -/
theorem exists_sub_map_mem_maximalIdeal_of_surjective_residueFieldMap
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f]
    (hresidue : Function.Surjective (ResidueField.map f)) (b : B) :
    ∃ a : A, b - f a ∈ maximalIdeal B := by
  obtain ⟨r, hr⟩ := hresidue (residue B b)
  obtain ⟨a, ha⟩ := residue_surjective r
  refine ⟨a, (residue_eq_zero_iff _).mp ?_⟩
  rw [map_sub, ← ResidueField.map_residue f, ha, hr, sub_self]

/-- Surjectivity on residue fields and cotangent spaces makes the induced map on the square of
the maximal ideal quotient surjective.

This is the first nontrivial infinitesimal quotient in the completion argument.  Unlike the
Nakayama conclusion above, it does not require finite generation. -/
theorem maximalIdealSquareQuotientMap_surjective
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f]
    (hresidue : Function.Surjective (ResidueField.map f))
    (hcotangent : Function.Surjective (cotangentMap f)) :
    Function.Surjective (maximalIdealSquareQuotientMap f) := by
  intro z
  obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective z
  obtain ⟨a₀, ha₀⟩ :=
    exists_sub_map_mem_maximalIdeal_of_surjective_residueFieldMap f hresidue b
  let r : maximalIdeal B := ⟨b - f a₀, ha₀⟩
  obtain ⟨y, hy⟩ := hcotangent ((maximalIdeal B).toCotangent r)
  obtain ⟨a₁, rfl⟩ := (maximalIdeal A).toCotangent_surjective y
  refine ⟨Ideal.Quotient.mk ((maximalIdeal A) ^ 2) (a₀ + a₁), ?_⟩
  rw [maximalIdealSquareQuotientMap, Ideal.quotientMap_mk, Ideal.Quotient.eq]
  have hcot :
      (maximalIdeal B).toCotangent
          ⟨f a₁, map_nonunit f a₁ a₁.property⟩ =
        (maximalIdeal B).toCotangent r := by
    simpa only [cotangentMap_toCotangent] using hy
  have hsquare : f a₁ - (b - f a₀) ∈ (maximalIdeal B) ^ 2 :=
    (maximalIdeal B).toCotangent_eq.mp hcot
  rw [map_add]
  have heq : f a₀ + f a₁ - b = f a₁ - (b - f a₀) := by abel
  rw [heq]
  exact hsquare

end IsLocalRing

namespace AlgebraicGeometry

universe u

open CategoryTheory

namespace Scheme.Hom

variable {X Y : Scheme.{u}} (f : X ⟶ Y) (x : X)

/-- A cotangent-surjective scheme morphism generates the source-stalk maximal ideal from the
target-stalk maximal ideal.

This is the stalk-level consumer of
`IsLocalRing.map_maximalIdeal_eq_of_surjective_mapCotangent`. -/
theorem map_maximalIdeal_stalkMap_eq_of_isCotangentSurjectiveAt
    [Module.Finite (X.presheaf.stalk x)
      (IsLocalRing.maximalIdeal (X.presheaf.stalk x))]
    (h : IsCotangentSurjectiveAt f x) :
    (IsLocalRing.maximalIdeal (Y.presheaf.stalk (f x))).map (f.stalkMap x).hom =
      IsLocalRing.maximalIdeal (X.presheaf.stalk x) :=
  IsLocalRing.map_maximalIdeal_eq_of_surjective_mapCotangent
    (f.stalkMap x).hom h

/-- The checked residue-field and cotangent criterion is surjective on the square of the maximal
ideal quotient of the two stalks. -/
theorem maximalIdealSquareQuotientMap_stalkMap_surjective_of_isCotangentCriterionAt
    (h : IsCotangentCriterionAt f x) :
    Function.Surjective
      (IsLocalRing.maximalIdealSquareQuotientMap (f.stalkMap x).hom) := by
  letI := h.1
  have hresidue : Function.Surjective
      (IsLocalRing.ResidueField.map (f.stalkMap x).hom) :=
    (ConcreteCategory.bijective_of_isIso (f.residueFieldMap x)).2
  exact IsLocalRing.maximalIdealSquareQuotientMap_surjective
    (f.stalkMap x).hom hresidue h.2

end Scheme.Hom

end AlgebraicGeometry
