/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.AlgebraicGeometry.FormalImmersionNakayama

/-!
# Lifting a special-fibre cotangent calculation

This file packages the local-algebra bridge from a cotangent calculation after
quotienting by compatible ideals to a formal immersion on the total local
rings.  It is designed for the degree-one calculation on the characteristic-
five fibre of Mazur's modular map.

The target quotient ideal is required to lie in the ideal generated by the
source maximal ideal.  Cotangent surjectivity on the quotient, together with
finite generation of the quotient target maximal ideal, therefore identifies
the two quotient maximal ideals by Nakayama.  Surjectivity of the quotient map
lifts that equality to the total target maximal ideal.  A residue-field lift
then recovers total cotangent surjectivity, and the existing completion theorem
gives the formal-immersion consumer.
-/

namespace IsLocalRing

noncomputable section

variable {A B : Type*} [CommRing A] [CommRing B]
  [IsLocalRing A] [IsLocalRing B]

/-- If the source maximal ideal generates the target maximal ideal and the
residue-field map is onto, then the local cotangent map is onto. -/
theorem cotangentMap_surjective_of_residue_and_map_maximalIdeal_eq
    (f : A →+* B) [IsLocalHom f]
    (hresidue : Function.Surjective (ResidueField.map f))
    (hmax : (maximalIdeal A).map f = maximalIdeal B) :
    Function.Surjective (cotangentMap f) := by
  letI : Algebra A B := f.toAlgebra
  let d : CotangentSpace A →ₗ[A] CotangentSpace B :=
    Ideal.mapCotangent
      (maximalIdeal A) (maximalIdeal B) (Algebra.ofId A B)
        (by
          change maximalIdeal A ≤ (maximalIdeal B).comap f
          rw [maximalIdeal_comap])
  have hd (x : CotangentSpace A) : d x = cotangentMap f x := by
    obtain ⟨a, rfl⟩ := (maximalIdeal A).toCotangent_surjective x
    rfl
  intro z
  obtain ⟨b, rfl⟩ := (maximalIdeal B).toCotangent_surjective z
  have hb : (b : B) ∈ (maximalIdeal A).map f := by
    rw [hmax]
    exact b.property
  change (b : B) ∈ Ideal.span (f '' maximalIdeal A) at hb
  have hspan : ∀ (x : B) (hx : x ∈ Ideal.span (f '' maximalIdeal A)),
      ∃ y : CotangentSpace A, ∃ hxB : x ∈ maximalIdeal B,
        d y = (maximalIdeal B).toCotangent ⟨x, hxB⟩ := by
    intro x hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
        obtain ⟨a, ha, rfl⟩ := hx
        exact ⟨(maximalIdeal A).toCotangent ⟨a, ha⟩,
          map_nonunit f a ha, rfl⟩
    | zero =>
        refine ⟨0, zero_mem _, ?_⟩
        change d 0 = (maximalIdeal B).toCotangent (0 : maximalIdeal B)
        simp
    | add x y hx hy ihx ihy =>
        obtain ⟨a, hxB, ha⟩ := ihx
        obtain ⟨c, hyB, hc⟩ := ihy
        refine ⟨a + c, add_mem hxB hyB, ?_⟩
        rw [map_add, ha, hc]
        exact ((maximalIdeal B).toCotangent.map_add
          ⟨x, hxB⟩ ⟨y, hyB⟩).symm
    | smul r x hx ih =>
        obtain ⟨a, hxB, ha⟩ := ih
        obtain ⟨c, hc⟩ :=
          exists_sub_map_mem_maximalIdeal_of_surjective_residueFieldMap
            f hresidue r
        refine ⟨c • a, (maximalIdeal B).mul_mem_left r hxB, ?_⟩
        rw [map_smul, ha]
        change (maximalIdeal B).toCotangent ⟨f c * x, _⟩ =
          (maximalIdeal B).toCotangent ⟨r * x, _⟩
        apply (maximalIdeal B).toCotangent_eq.mpr
        change f c * x - r * x ∈ (maximalIdeal B) ^ 2
        rw [← sub_mul, pow_two]
        exact Ideal.mul_mem_mul (by simpa using neg_mem hc) hxB
  obtain ⟨y, hbB, hy⟩ := hspan b hb
  refine ⟨y, (hd y).symm.trans ?_⟩
  simpa only using hy

private theorem quotientMap_isLocalHom
    (f : A →+* B) [IsLocalHom f] (I : Ideal A) (J : Ideal B)
    [IsLocalRing (A ⧸ I)]
    [IsLocalHom (Ideal.Quotient.mk I)]
    [IsLocalRing (B ⧸ J)]
    [IsLocalHom (Ideal.Quotient.mk J)]
    (hIJ : I.map f ≤ J) :
    IsLocalHom (Ideal.quotientMap J f (Ideal.map_le_iff_le_comap.mp hIJ)) := by
  let fbar : A ⧸ I →+* B ⧸ J :=
    Ideal.quotientMap J f (Ideal.map_le_iff_le_comap.mp hIJ)
  refine ((local_hom_TFAE fbar).out 1 0).mp ?_
  rintro _ ⟨x, hx, rfl⟩
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective x
  have ha : a ∈ maximalIdeal A := by
    rw [← maximalIdeal_comap (Ideal.Quotient.mk I)]
    exact hx
  change Ideal.Quotient.mk J (f a) ∈ maximalIdeal (B ⧸ J)
  exact map_nonunit (Ideal.Quotient.mk J) (f a) (map_nonunit f a ha)

/-- Surjectivity of the cotangent map induced on two compatible local-ring
quotients. This predicate hides the canonical local structures on proper
quotients, so a special-fibre calculation does not expose instance plumbing. -/
def IsQuotientCotangentSurjective
    (f : A →+* B) [IsLocalHom f]
    (I : Ideal A) (J : Ideal B)
    (hI : I ≤ maximalIdeal A) (hJ : J ≤ maximalIdeal B)
    (hIJ : I.map f ≤ J) : Prop :=
  letI : Nontrivial (A ⧸ I) := Ideal.Quotient.nontrivial_iff.mpr
    (hI.trans_lt (maximalIdeal.isMaximal A).lt_top).ne
  letI : IsLocalRing (A ⧸ I) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  letI : IsLocalHom (Ideal.Quotient.mk I) :=
    IsLocalHom.of_surjective (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  letI : Nontrivial (B ⧸ J) := Ideal.Quotient.nontrivial_iff.mpr
    (hJ.trans_lt (maximalIdeal.isMaximal B).lt_top).ne
  letI : IsLocalRing (B ⧸ J) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk J) Ideal.Quotient.mk_surjective
  letI : IsLocalHom (Ideal.Quotient.mk J) :=
    IsLocalHom.of_surjective (Ideal.Quotient.mk J) Ideal.Quotient.mk_surjective
  let fbar : A ⧸ I →+* B ⧸ J :=
    Ideal.quotientMap J f (Ideal.map_le_iff_le_comap.mp hIJ)
  letI : IsLocalHom fbar := quotientMap_isLocalHom f I J hIJ
  Function.Surjective (cotangentMap fbar)

/-- The common special-fibre case in which the target quotient ideal is the
extension of the source quotient ideal. -/
def IsMappedIdealCotangentSurjective
    (f : A →+* B) [IsLocalHom f]
    (I : Ideal A) (hI : I ≤ maximalIdeal A) : Prop :=
  IsQuotientCotangentSurjective f I (I.map f) hI
    ((Ideal.map_mono hI).trans (map_maximalIdeal_le f)) le_rfl

/-- The exact special-fibre data needed to lift cotangent surjectivity to a
local homomorphism. Finiteness is imposed only on the target quotient's
maximal ideal, and the target quotient ideal must already come from the source
maximal ideal. -/
structure QuotientCotangentCertificate
    (f : A →+* B) [IsLocalHom f] where
  sourceIdeal : Ideal A
  targetIdeal : Ideal B
  sourceIdeal_le : sourceIdeal ≤ maximalIdeal A
  targetIdeal_le : targetIdeal ≤ maximalIdeal B
  map_sourceIdeal_le : sourceIdeal.map f ≤ targetIdeal
  targetIdeal_le_map_maximalIdeal : targetIdeal ≤ (maximalIdeal A).map f
  finite_target_maximalIdeal : Module.Finite (B ⧸ targetIdeal)
    ((maximalIdeal B).map (Ideal.Quotient.mk targetIdeal))
  quotient_cotangent_surjective :
    IsQuotientCotangentSurjective f sourceIdeal targetIdeal
      sourceIdeal_le targetIdeal_le map_sourceIdeal_le

namespace QuotientCotangentCertificate

/-- Build the lift certificate when the target special-fibre ideal is exactly
the extension of the source ideal. -/
def ofMappedIdeal
    (f : A →+* B) [IsLocalHom f]
    (I : Ideal A) (hI : I ≤ maximalIdeal A)
    (hfinite : Module.Finite (B ⧸ I.map f)
      ((maximalIdeal B).map (Ideal.Quotient.mk (I.map f))))
    (hquotient : IsMappedIdealCotangentSurjective f I hI) :
    QuotientCotangentCertificate f where
  sourceIdeal := I
  targetIdeal := I.map f
  sourceIdeal_le := hI
  targetIdeal_le := (Ideal.map_mono hI).trans (map_maximalIdeal_le f)
  map_sourceIdeal_le := le_rfl
  targetIdeal_le_map_maximalIdeal := Ideal.map_mono hI
  finite_target_maximalIdeal := hfinite
  quotient_cotangent_surjective := hquotient

end QuotientCotangentCertificate

/-- A cotangent calculation after quotienting by compatible ideals lifts to
the total local map. -/
theorem cotangentMap_surjective_of_quotientCotangentCertificate
    (f : A →+* B) [IsLocalHom f]
    (data : QuotientCotangentCertificate f)
    (hresidue : Function.Surjective (ResidueField.map f)) :
    Function.Surjective (cotangentMap f) := by
  rcases data with ⟨I, J, hI, hJ, hIJ, hJsource, hfinite, hquotient⟩
  have hIne : I ≠ ⊤ :=
    (hI.trans_lt (maximalIdeal.isMaximal A).lt_top).ne
  have hJne : J ≠ ⊤ :=
    (hJ.trans_lt (maximalIdeal.isMaximal B).lt_top).ne
  letI : Nontrivial (A ⧸ I) := Ideal.Quotient.nontrivial_iff.mpr hIne
  letI : IsLocalRing (A ⧸ I) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  letI : IsLocalHom (Ideal.Quotient.mk I) :=
    IsLocalHom.of_surjective (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  letI : Nontrivial (B ⧸ J) := Ideal.Quotient.nontrivial_iff.mpr hJne
  letI : IsLocalRing (B ⧸ J) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk J) Ideal.Quotient.mk_surjective
  letI : IsLocalHom (Ideal.Quotient.mk J) :=
    IsLocalHom.of_surjective (Ideal.Quotient.mk J) Ideal.Quotient.mk_surjective
  let fbar : A ⧸ I →+* B ⧸ J :=
    Ideal.quotientMap J f (Ideal.map_le_iff_le_comap.mp hIJ)
  letI : IsLocalHom fbar := quotientMap_isLocalHom f I J hIJ
  have hsourceQuotient : (maximalIdeal A).map (Ideal.Quotient.mk I) =
      maximalIdeal (A ⧸ I) :=
    map_maximalIdeal_of_surjective (Ideal.Quotient.mk I)
      Ideal.Quotient.mk_surjective
  have htargetQuotient : (maximalIdeal B).map (Ideal.Quotient.mk J) =
      maximalIdeal (B ⧸ J) :=
    map_maximalIdeal_of_surjective (Ideal.Quotient.mk J)
      Ideal.Quotient.mk_surjective
  letI : Module.Finite (B ⧸ J) (maximalIdeal (B ⧸ J)) := by
    rw [← htargetQuotient]
    exact hfinite
  change Function.Surjective (cotangentMap fbar) at hquotient
  have hbarmax : (maximalIdeal (A ⧸ I)).map fbar =
      maximalIdeal (B ⧸ J) :=
    map_maximalIdeal_eq_of_surjective_mapCotangent fbar hquotient
  have hcomp : (Ideal.Quotient.mk J).comp f =
      fbar.comp (Ideal.Quotient.mk I) := by
    ext a
    rfl
  have hmapQuotient :
      ((maximalIdeal A).map f).map (Ideal.Quotient.mk J) =
        (maximalIdeal B).map (Ideal.Quotient.mk J) := by
    rw [Ideal.map_map, hcomp, ← Ideal.map_map, hsourceQuotient,
      hbarmax, htargetQuotient]
  have hsup :=
    (Ideal.map_eq_iff_sup_ker_eq_of_surjective (Ideal.Quotient.mk J)
      Ideal.Quotient.mk_surjective).mp hmapQuotient
  rw [Ideal.mk_ker, sup_eq_left.mpr hJsource, sup_eq_left.mpr hJ] at hsup
  exact cotangentMap_surjective_of_residue_and_map_maximalIdeal_eq
    f hresidue hsup

end

end IsLocalRing

namespace AlgebraicGeometry.LocalCompletion

variable {A B : Type*} [CommRing A] [CommRing B]
  [IsLocalRing A] [IsLocalRing B]

/-- A checked quotient/special-fibre cotangent certificate is sufficient for
surjectivity on completed local rings. This is the completion consumer of
`IsLocalRing.QuotientCotangentCertificate`. -/
theorem map_surjective_of_quotientCotangentCertificate_of_finite_maximalIdeals
    [Module.Finite A (IsLocalRing.maximalIdeal A)]
    [Module.Finite B (IsLocalRing.maximalIdeal B)]
    (f : A →+* B) [IsLocalHom f]
    (data : IsLocalRing.QuotientCotangentCertificate f)
    (hresidue : Function.Surjective (IsLocalRing.ResidueField.map f)) :
    Function.Surjective (map f) :=
  map_surjective_of_residue_and_cotangent_of_finite_maximalIdeals
    f hresidue
      (IsLocalRing.cotangentMap_surjective_of_quotientCotangentCertificate
        f data hresidue)

end AlgebraicGeometry.LocalCompletion

namespace AlgebraicGeometry.Scheme.Hom

universe u

open CategoryTheory

variable {X Y : Scheme.{u}} (f : X ⟶ Y) (x : X)

/-- A quotient/special-fibre cotangent certificate on the stalk map proves
formal immersion once the residue fields agree. -/
theorem isFormalImmersionAt_of_quotientCotangentCertificate
    [Module.Finite (Y.presheaf.stalk (f x))
      (IsLocalRing.maximalIdeal (Y.presheaf.stalk (f x)))]
    [Module.Finite (X.presheaf.stalk x)
      (IsLocalRing.maximalIdeal (X.presheaf.stalk x))]
    (hresidue : IsIso (f.residueFieldMap x))
    (data : IsLocalRing.QuotientCotangentCertificate (f.stalkMap x).hom) :
    IsFormalImmersionAt f x := by
  rw [IsFormalImmersionAt]
  change Function.Surjective (LocalCompletion.map (f.stalkMap x).hom)
  letI := hresidue
  have hsurjective : Function.Surjective
      (IsLocalRing.ResidueField.map (f.stalkMap x).hom) :=
    (ConcreteCategory.bijective_of_isIso (f.residueFieldMap x)).2
  exact
    LocalCompletion.map_surjective_of_quotientCotangentCertificate_of_finite_maximalIdeals
      (f.stalkMap x).hom data hsurjective

/-- In the standard special-fibre situation, quotienting the target-scheme
stalk by `I` and the source-scheme stalk by its extended ideal is enough to
prove formal immersion. -/
theorem isFormalImmersionAt_of_mappedIdealCotangentSurjective
    [Module.Finite (Y.presheaf.stalk (f x))
      (IsLocalRing.maximalIdeal (Y.presheaf.stalk (f x)))]
    [Module.Finite (X.presheaf.stalk x)
      (IsLocalRing.maximalIdeal (X.presheaf.stalk x))]
    (hresidue : IsIso (f.residueFieldMap x))
    (I : Ideal (Y.presheaf.stalk (f x)))
    (hI : I ≤ IsLocalRing.maximalIdeal (Y.presheaf.stalk (f x)))
    (hfinite : Module.Finite
      (X.presheaf.stalk x ⧸ I.map (f.stalkMap x).hom)
      ((IsLocalRing.maximalIdeal (X.presheaf.stalk x)).map
        (Ideal.Quotient.mk (I.map (f.stalkMap x).hom))))
    (hquotient : IsLocalRing.IsMappedIdealCotangentSurjective
      (f.stalkMap x).hom I hI) :
    IsFormalImmersionAt f x :=
  isFormalImmersionAt_of_quotientCotangentCertificate f x hresidue
    (IsLocalRing.QuotientCotangentCertificate.ofMappedIdeal
      (f.stalkMap x).hom I hI hfinite hquotient)

/-- On locally Noetherian schemes, the quotient-cotangent certificate proves
formal immersion without exposing finite-generation instances for the two
stalk maximal ideals. -/
theorem
    isFormalImmersionAt_of_quotientCotangentCertificate_of_isLocallyNoetherian
    [IsLocallyNoetherian X] [IsLocallyNoetherian Y]
    (hresidue : IsIso (f.residueFieldMap x))
    (data : IsLocalRing.QuotientCotangentCertificate (f.stalkMap x).hom) :
    IsFormalImmersionAt f x :=
  isFormalImmersionAt_of_quotientCotangentCertificate f x hresidue data

/-- Locally Noetherian source and target schemes discharge the two total-stalk
finiteness conditions in the mapped-special-fibre criterion. -/
theorem
    isFormalImmersionAt_of_mappedIdealCotangentSurjective_of_isLocallyNoetherian
    [IsLocallyNoetherian X] [IsLocallyNoetherian Y]
    (hresidue : IsIso (f.residueFieldMap x))
    (I : Ideal (Y.presheaf.stalk (f x)))
    (hI : I ≤ IsLocalRing.maximalIdeal (Y.presheaf.stalk (f x)))
    (hquotient : IsLocalRing.IsMappedIdealCotangentSurjective
      (f.stalkMap x).hom I hI) :
    IsFormalImmersionAt f x :=
  isFormalImmersionAt_of_mappedIdealCotangentSurjective
    f x hresidue I hI (by infer_instance) hquotient

end AlgebraicGeometry.Scheme.Hom
