/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.AlgebraicGeometry.FormalImmersion
import Mathlib.AlgebraicGeometry.Noetherian
import Mathlib.RingTheory.AdicCompletion.Functoriality
import Mathlib.RingTheory.AdicCompletion.LocalRing
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The Nakayama step in the cotangent criterion

This file proves the local-algebra consequence of cotangent surjectivity needed by the formal
immersion route.  For a local homomorphism `A → B`, if the maximal ideal of `B` is finite as a
`B`-module, then a surjection

`m_A / m_A² → m_B / m_B²`

forces the extension of `m_A` to equal `m_B`.  The finiteness assumption is exactly the input to
Nakayama's lemma; Noetherianity of all of `B` is not required.

The completion theorem then combines this first-order algebra with residue-field lifting and
Mathlib's precomplete/Hausdorff surjectivity criterion.  It separates the logically minimal
precompleteness hypothesis on the source completion from a convenient corollary assuming both
maximal ideals are finite.  The scheme theorem applies that corollary to stalk maps, and the
modular degree-one certificate is a separate downstream consumer.
-/

namespace IsLocalRing

/-- The cotangent map of a local ring homomorphism, viewed over the common scalar ring `ℤ`. -/
noncomputable def cotangentMap
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f] :
    CotangentSpace A →ₗ[ℤ] CotangentSpace B :=
  Ideal.mapCotangent
    (maximalIdeal A) (maximalIdeal B) f.toIntAlgHom
    (by
      change maximalIdeal A ≤ (maximalIdeal B).comap f
      rw [maximalIdeal_comap])

/-- The local cotangent map sends the class of `a` to the class of `f a`. -/
@[simp]
theorem cotangentMap_toCotangent
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f] (a : maximalIdeal A) :
    cotangentMap f ((maximalIdeal A).toCotangent a) =
      (maximalIdeal B).toCotangent
        ⟨f a, map_nonunit f a a.property⟩ :=
  rfl

/-- The map on second infinitesimal neighbourhoods induced by a local ring homomorphism. -/
def maximalIdealSquareQuotientMap
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f] :
    A ⧸ (maximalIdeal A) ^ 2 →+* B ⧸ (maximalIdeal B) ^ 2 :=
  Ideal.quotientMap (I := (maximalIdeal A) ^ 2) ((maximalIdeal B) ^ 2) f
    (by
      rw [← maximalIdeal_comap f]
      exact Ideal.le_comap_pow f 2)

/-- Nakayama detects whether a submodule of a local ring's maximal ideal is all of it from its
image in the cotangent space.

Mathlib's `IsLocalRing.CotangentSpace.map_eq_top_iff` assumes the whole ring is Noetherian.  This
version records the precise weaker hypothesis used by the proof: the maximal ideal itself is a
finite module. -/
theorem CotangentSpace.map_eq_top_iff_of_finite_maximalIdeal
    {R : Type*} [CommRing R] [IsLocalRing R]
    [Module.Finite R (maximalIdeal R)]
    {M : Submodule R (maximalIdeal R)} :
    M.map (maximalIdeal R).toCotangent = ⊤ ↔ M = ⊤ := by
  refine ⟨fun H ↦ eq_top_iff.mpr ?_, by rintro rfl; simp [Ideal.toCotangent_range]⟩
  refine (Submodule.map_le_map_iff_of_injective (Submodule.injective_subtype _) _ _).mp ?_
  rw [Submodule.map_top, Submodule.range_subtype]
  apply Submodule.le_of_le_smul_of_le_jacobson_bot
    ((Submodule.fg_top (maximalIdeal R)).mp Module.Finite.fg_top)
    (IsLocalRing.jacobson_eq_maximalIdeal _ bot_ne_top).ge
  rw [smul_eq_mul, ← pow_two, ← Ideal.map_toCotangent_ker, ← Submodule.map_sup,
    ← Submodule.comap_map_eq, H, Submodule.comap_top, Submodule.map_top,
    Submodule.range_subtype]

/-- For a local homomorphism, cotangent surjectivity forces the target maximal ideal to be
generated by the image of the source maximal ideal.

Only finite generation of the target maximal ideal is used.  In particular, this conclusion does
not need adic completeness or separatedness. -/
theorem map_maximalIdeal_eq_of_surjective_mapCotangent
    {A B : Type*} [CommRing A] [CommRing B]
    [IsLocalRing A] [IsLocalRing B] [Module.Finite B (maximalIdeal B)]
    (f : A →+* B) [IsLocalHom f]
    (h : Function.Surjective (cotangentMap f)) :
    (maximalIdeal A).map f = maximalIdeal B := by
  let I : Ideal B := (maximalIdeal A).map f
  have hI : I ≤ maximalIdeal B := by
    dsimp [I]
    rw [Ideal.map_le_iff_le_comap, maximalIdeal_comap]
  let M : Submodule B (maximalIdeal B) :=
    Submodule.comap (maximalIdeal B).subtype I
  have hMmap : M.map (maximalIdeal B).toCotangent = ⊤ := by
    rw [eq_top_iff]
    intro z _
    obtain ⟨y, rfl⟩ := h z
    obtain ⟨a, rfl⟩ := (maximalIdeal A).toCotangent_surjective y
    let b : maximalIdeal B :=
      ⟨f a, hI (Ideal.mem_map_of_mem f a.property)⟩
    have hbM : b ∈ M := by
      change (b : B) ∈ I
      exact Ideal.mem_map_of_mem f a.property
    exact ⟨b, hbM, rfl⟩
  have hM : M = ⊤ :=
    CotangentSpace.map_eq_top_iff_of_finite_maximalIdeal.mp hMmap
  apply le_antisymm hI
  intro b hb
  have hbM : (⟨b, hb⟩ : maximalIdeal B) ∈ M := by
    rw [hM]
    exact Submodule.mem_top
  exact hbM

/-- Surjectivity on residue fields gives a lift modulo the target maximal ideal. -/
theorem exists_sub_map_mem_maximalIdeal_of_surjective_residueFieldMap
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f]
    (hresidue : Function.Surjective (ResidueField.map f)) (b : B) :
    ∃ a : A, b - f a ∈ maximalIdeal B := by
  obtain ⟨r, hr⟩ := hresidue (residue B b)
  obtain ⟨a, ha⟩ := residue_surjective r
  refine ⟨a, (residue_eq_zero_iff _).mp ?_⟩
  rw [map_sub, ← ResidueField.map_residue f, ha, hr, sub_self]

/-- Surjectivity on residue fields and cotangent spaces makes the induced map on the square of
the maximal ideal quotient surjective.

This is the first nontrivial infinitesimal quotient in the completion argument.  Unlike the
Nakayama conclusion above, it does not require finite generation. -/
theorem maximalIdealSquareQuotientMap_surjective
    {A B : Type*} [CommRing A] [CommRing B] [IsLocalRing A] [IsLocalRing B]
    (f : A →+* B) [IsLocalHom f]
    (hresidue : Function.Surjective (ResidueField.map f))
    (hcotangent : Function.Surjective (cotangentMap f)) :
    Function.Surjective (maximalIdealSquareQuotientMap f) := by
  intro z
  obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective z
  obtain ⟨a₀, ha₀⟩ :=
    exists_sub_map_mem_maximalIdeal_of_surjective_residueFieldMap f hresidue b
  let r : maximalIdeal B := ⟨b - f a₀, ha₀⟩
  obtain ⟨y, hy⟩ := hcotangent ((maximalIdeal B).toCotangent r)
  obtain ⟨a₁, rfl⟩ := (maximalIdeal A).toCotangent_surjective y
  refine ⟨Ideal.Quotient.mk ((maximalIdeal A) ^ 2) (a₀ + a₁), ?_⟩
  rw [maximalIdealSquareQuotientMap, Ideal.quotientMap_mk, Ideal.Quotient.eq]
  have hcot :
      (maximalIdeal B).toCotangent
          ⟨f a₁, map_nonunit f a₁ a₁.property⟩ =
        (maximalIdeal B).toCotangent r := by
    simpa only [cotangentMap_toCotangent] using hy
  have hsquare : f a₁ - (b - f a₀) ∈ (maximalIdeal B) ^ 2 :=
    (maximalIdeal B).toCotangent_eq.mp hcot
  rw [map_add]
  have heq : f a₀ + f a₁ - b = f a₁ - (b - f a₀) := by abel
  rw [heq]
  exact hsquare

end IsLocalRing

namespace AlgebraicGeometry

universe u

open CategoryTheory

namespace LocalCompletion

variable {A B : Type*} [CommRing A] [CommRing B]
  [IsLocalRing A] [IsLocalRing B]

/-- The residue-field and cotangent criterion makes the induced map on local completions
surjective.

The target maximal ideal is finite so that Nakayama identifies it with the extension of the
source maximal ideal and so that the target completion is Hausdorff for that ideal.  On the source
side, the proof only needs precompleteness of its completion for the extended maximal ideal; this
is stated directly instead of imposing a stronger Noetherian hypothesis. -/
theorem map_surjective_of_residue_and_cotangent
    [Module.Finite B (IsLocalRing.maximalIdeal B)]
    [IsPrecomplete
      ((IsLocalRing.maximalIdeal A).map (algebraMap A (Ring A))) (Ring A)]
    (f : A →+* B) [IsLocalHom f]
    (hresidue : Function.Surjective (IsLocalRing.ResidueField.map f))
    (hcotangent : Function.Surjective (IsLocalRing.cotangentMap f)) :
    Function.Surjective (map f) := by
  have hfgB : (IsLocalRing.maximalIdeal B).FG :=
    (Submodule.fg_top (IsLocalRing.maximalIdeal B)).mp Module.Finite.fg_top
  have hmax : (IsLocalRing.maximalIdeal A).map f =
      IsLocalRing.maximalIdeal B :=
    IsLocalRing.map_maximalIdeal_eq_of_surjective_mapCotangent f hcotangent
  let I : Ideal (Ring A) :=
    (IsLocalRing.maximalIdeal A).map (algebraMap A (Ring A))
  let J : Ideal (Ring B) :=
    (IsLocalRing.maximalIdeal B).map (algebraMap B (Ring B))
  let F : Ring A →+* Ring B := map f
  have hcomp : F.comp (algebraMap A (Ring A)) =
      (algebraMap B (Ring B)).comp f := by
    apply RingHom.ext
    intro a
    change map f (AdicCompletion.of (IsLocalRing.maximalIdeal A) A a) =
      AdicCompletion.of (IsLocalRing.maximalIdeal B) B (f a)
    exact map_of f a
  have hIJ : I.map F = J := by
    dsimp only [I, J]
    rw [Ideal.map_map, hcomp, ← Ideal.map_map, hmax]
  letI : IsAdicComplete J (Ring B) := by
    dsimp only [J, Ring]
    exact AdicCompletion.isAdicComplete_self _ hfgB
  letI : IsHausdorff (I.map F) (Ring B) := by
    rw [hIJ]
    infer_instance
  apply surjective_of_mk_map_comp_surjective (I := I) F
  intro z
  obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective z
  obtain ⟨r, hr⟩ := hresidue
    (AdicCompletion.evalOneₐ (IsLocalRing.maximalIdeal B) b)
  obtain ⟨a, ha⟩ := IsLocalRing.residue_surjective r
  refine ⟨AdicCompletion.of (IsLocalRing.maximalIdeal A) A a, ?_⟩
  rw [RingHom.comp_apply]
  apply (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).2
  rw [hIJ]
  change F (AdicCompletion.of (IsLocalRing.maximalIdeal A) A a) - b ∈
    (IsLocalRing.maximalIdeal B).map (algebraMap B (Ring B))
  rw [← AdicCompletion.ker_evalOneₐ_eq_map _ hfgB]
  change AdicCompletion.evalOneₐ (IsLocalRing.maximalIdeal B)
      (F (AdicCompletion.of (IsLocalRing.maximalIdeal A) A a) - b) = 0
  rw [map_sub]
  dsimp only [F]
  rw [map_of, AdicCompletion.evalOneₐ_of, sub_eq_zero]
  change IsLocalRing.residue B (f a) =
    AdicCompletion.evalOneₐ (IsLocalRing.maximalIdeal B) b
  rw [← IsLocalRing.ResidueField.map_residue f, ha, hr]

/-- Finite maximal ideals provide the precompleteness hypothesis in
`map_surjective_of_residue_and_cotangent` automatically. -/
theorem map_surjective_of_residue_and_cotangent_of_finite_maximalIdeals
    [Module.Finite A (IsLocalRing.maximalIdeal A)]
    [Module.Finite B (IsLocalRing.maximalIdeal B)]
    (f : A →+* B) [IsLocalHom f]
    (hresidue : Function.Surjective (IsLocalRing.ResidueField.map f))
    (hcotangent : Function.Surjective (IsLocalRing.cotangentMap f)) :
    Function.Surjective (map f) := by
  have hfgA : (IsLocalRing.maximalIdeal A).FG :=
    (Submodule.fg_top (IsLocalRing.maximalIdeal A)).mp Module.Finite.fg_top
  letI : IsAdicComplete
      ((IsLocalRing.maximalIdeal A).map (algebraMap A (Ring A))) (Ring A) :=
    AdicCompletion.isAdicComplete_self _ hfgA
  exact map_surjective_of_residue_and_cotangent f hresidue hcotangent

end LocalCompletion

namespace Scheme.Hom

variable {X Y : Scheme.{u}} (f : X ⟶ Y) (x : X)

/-- A cotangent-surjective scheme morphism generates the source-stalk maximal ideal from the
target-stalk maximal ideal.

This is the stalk-level consumer of
`IsLocalRing.map_maximalIdeal_eq_of_surjective_mapCotangent`. -/
theorem map_maximalIdeal_stalkMap_eq_of_isCotangentSurjectiveAt
    [Module.Finite (X.presheaf.stalk x)
      (IsLocalRing.maximalIdeal (X.presheaf.stalk x))]
    (h : IsCotangentSurjectiveAt f x) :
    (IsLocalRing.maximalIdeal (Y.presheaf.stalk (f x))).map (f.stalkMap x).hom =
      IsLocalRing.maximalIdeal (X.presheaf.stalk x) :=
  IsLocalRing.map_maximalIdeal_eq_of_surjective_mapCotangent
    (f.stalkMap x).hom h

/-- The checked residue-field and cotangent criterion is surjective on the square of the maximal
ideal quotient of the two stalks. -/
theorem maximalIdealSquareQuotientMap_stalkMap_surjective_of_isCotangentCriterionAt
    (h : IsCotangentCriterionAt f x) :
    Function.Surjective
      (IsLocalRing.maximalIdealSquareQuotientMap (f.stalkMap x).hom) := by
  letI := h.1
  have hresidue : Function.Surjective
      (IsLocalRing.ResidueField.map (f.stalkMap x).hom) :=
    (ConcreteCategory.bijective_of_isIso (f.residueFieldMap x)).2
  exact IsLocalRing.maximalIdealSquareQuotientMap_surjective
    (f.stalkMap x).hom hresidue h.2

/-- For stalks with finite maximal ideals, the residue-field and cotangent criterion is a formal
immersion: the induced map on completed local rings is surjective. -/
theorem isFormalImmersionAt_of_isCotangentCriterionAt
    [Module.Finite (Y.presheaf.stalk (f x))
      (IsLocalRing.maximalIdeal (Y.presheaf.stalk (f x)))]
    [Module.Finite (X.presheaf.stalk x)
      (IsLocalRing.maximalIdeal (X.presheaf.stalk x))]
    (h : IsCotangentCriterionAt f x) :
    IsFormalImmersionAt f x := by
  rw [IsFormalImmersionAt]
  change Function.Surjective (LocalCompletion.map (f.stalkMap x).hom)
  letI := h.1
  have hresidue : Function.Surjective
      (IsLocalRing.ResidueField.map (f.stalkMap x).hom) :=
    (ConcreteCategory.bijective_of_isIso (f.residueFieldMap x)).2
  exact LocalCompletion.map_surjective_of_residue_and_cotangent_of_finite_maximalIdeals
    (f.stalkMap x).hom hresidue h.2

/-- On locally Noetherian schemes, Mathlib's Noetherian stalk theorem supplies the finite
maximal ideals required by the completed-local-ring criterion. -/
theorem isFormalImmersionAt_of_isCotangentCriterionAt_of_isLocallyNoetherian
    [IsLocallyNoetherian X] [IsLocallyNoetherian Y]
    (h : IsCotangentCriterionAt f x) :
    IsFormalImmersionAt f x :=
  isFormalImmersionAt_of_isCotangentCriterionAt f x h

end Scheme.Hom

end AlgebraicGeometry
