name = "mazur-tauceti-challenges"
defaultTargets = ["MazurTauCetiChallenge"]

[[require]]
name = "TauCeti"
git = "https://github.com/Vilin97/TauCeti"
rev = "10cb4c41fc7a663ea55f54f30c9db489e906b357"

[[lean_lib]]
name = "MazurTauCetiChallenge"
globs = ["MazurTauCetiChallenge", "MazurTauCetiChallenge.+"]
leanOptions = { weak.linter.mathlibStandardSet = true }

[[lean_exe]]
name = "contractAxioms"
root = "scripts.ContractAxioms"
