name = "mazur-tauceti-challenges"
defaultTargets = ["MazurTauCetiChallenge"]

[[require]]
name = "TauCeti"
git = "https://github.com/Vilin97/TauCeti"
rev = "a74dfee78f800df63f085a19006f7d502eee365e"

[[lean_lib]]
name = "MazurTauCetiChallenge"
globs = ["MazurTauCetiChallenge", "MazurTauCetiChallenge.+"]
leanOptions = { weak.linter.mathlibStandardSet = true }

[[lean_exe]]
name = "contractAxioms"
root = "scripts.ContractAxioms"
