/-
Copyright (c) 2026 Vasil V. and contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasil V., OpenAI Codex
-/
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Basic
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# The standard affine cover of projective space

This file defines projective space as the projective spectrum of the
standard-graded polynomial ring.  Its coordinate basic opens form a finite
cover, and every nonempty finite intersection of those opens is affine.

The indexed-intersection API retains repeated coordinates, as needed by a
Čech nerve.
-/

open CategoryTheory AlgebraicGeometry TopologicalSpace

noncomputable section

universe u v

namespace MazurTorsion.AlgebraicGeometry.CoherentCohomology.ProjectiveSpace

open MvPolynomial

/-- The standard grading on the homogeneous coordinate ring of projective
`d`-space over `k`. -/
abbrev homogeneousGrading (k : Type u) [CommRing k] (d : ℕ) :=
  MvPolynomial.homogeneousSubmodule (Fin (d + 1)) k

/-- The standard grading is a graded-ring structure. -/
instance homogeneousGradingGradedRing
    (k : Type u) [CommRing k] (d : ℕ) :
    GradedRing (homogeneousGrading k d) :=
  MvPolynomial.gradedAlgebra

/-- Projective `d`-space over `k`, defined as `Proj k[X₀, …, X_d]`. -/
abbrev scheme (k : Type u) [CommRing k] (d : ℕ) : Scheme.{u} :=
  Proj (homogeneousGrading k d)

/-- The homogeneous coordinate `Xᵢ`. -/
abbrev coordinate (k : Type u) [CommRing k] {d : ℕ}
    (i : Fin (d + 1)) :
    MvPolynomial (Fin (d + 1)) k :=
  X i

/-- The standard coordinate chart `D₊(Xᵢ)`. -/
def standardChart (k : Type u) [CommRing k] {d : ℕ}
    (i : Fin (d + 1)) :
    (scheme k d).Opens :=
  Proj.basicOpen (homogeneousGrading k d) (coordinate k i)

/-- A coordinate has homogeneous degree one. -/
lemma coordinate_mem_degreeOne (k : Type u) [CommRing k] {d : ℕ}
    (i : Fin (d + 1)) :
    coordinate k i ∈ homogeneousGrading k d 1 :=
  MvPolynomial.isHomogeneous_X k i

/-- The irrelevant ideal is contained in the ideal generated by the
homogeneous coordinates. -/
lemma irrelevant_le_coordinateIdeal (k : Type u) [CommRing k] (d : ℕ) :
    (HomogeneousIdeal.irrelevant
      (homogeneousGrading k d)).toIdeal ≤
      Ideal.span (Set.range (coordinate k : Fin (d + 1) →
        MvPolynomial (Fin (d + 1)) k)) := by
  rw [HomogeneousIdeal.toIdeal_irrelevant_le]
  intro n hn p hp
  change p ∈ MvPolynomial.idealOfVars (Fin (d + 1)) k
  rw [← pow_one (MvPolynomial.idealOfVars (Fin (d + 1)) k),
    MvPolynomial.mem_pow_idealOfVars_iff]
  intro a ha
  have hdegree : a.degree = n := by
    rw [Finsupp.degree_eq_weight_one]
    exact hp (MvPolynomial.mem_support_iff.mp ha)
  omega

/-- The standard coordinate charts cover projective space. -/
lemma iSup_standardChart (k : Type u) [CommRing k] (d : ℕ) :
    ⨆ i : Fin (d + 1), standardChart k i = ⊤ :=
  Proj.iSup_basicOpen_eq_top
    (homogeneousGrading k d) (coordinate k)
    (irrelevant_le_coordinateIdeal k d)

/-- The standard coordinate charts as a finite affine open cover in
Mathlib's scheme-cover API. -/
noncomputable def standardAffineOpenCover
    (k : Type u) [CommRing k] (d : ℕ) :
    (scheme k d).AffineOpenCover :=
  Proj.affineOpenCoverOfIrrelevantLESpan
    (homogeneousGrading k d) (coordinate k)
    (m := fun _ => 1)
    (coordinate_mem_degreeOne k)
    (fun _ => Nat.zero_lt_one)
    (irrelevant_le_coordinateIdeal k d)

/-- The index type of the standard affine cover is the finite set of
homogeneous coordinates. -/
@[simp]
lemma standardAffineOpenCover_I₀
    (k : Type u) [CommRing k] (d : ℕ) :
    (standardAffineOpenCover k d).I₀ = Fin (d + 1) :=
  rfl

/-- The chart object in the standard cover is the spectrum of the
degree-zero homogeneous localization at the corresponding coordinate. -/
@[simp]
lemma standardAffineOpenCover_X
    (k : Type u) [CommRing k] (d : ℕ) (i : Fin (d + 1)) :
    (standardAffineOpenCover k d).X i =
      .of (HomogeneousLocalization.Away
        (homogeneousGrading k d) (coordinate k i)) :=
  rfl

instance standardAffineOpenCover_isOpenImmersion
    (k : Type u) [CommRing k] (d : ℕ) (i : Fin (d + 1)) :
    IsOpenImmersion ((standardAffineOpenCover k d).f i) :=
  (standardAffineOpenCover k d).map_prop i

/-- The range of a component of the standard affine cover is its coordinate
basic open. -/
@[simp]
lemma standardAffineOpenCover_opensRange
    (k : Type u) [CommRing k] (d : ℕ) (i : Fin (d + 1)) :
    ((standardAffineOpenCover k d).f i).opensRange =
      standardChart k i := by
  exact Proj.opensRange_awayι
    (homogeneousGrading k d) (coordinate k i)
    (coordinate_mem_degreeOne k i) Nat.zero_lt_one

/-- Each standard coordinate chart is affine. -/
lemma isAffineOpen_standardChart (k : Type u) [CommRing k] {d : ℕ}
    (i : Fin (d + 1)) :
    IsAffineOpen (standardChart k i) :=
  Proj.isAffineOpen_basicOpen
    (homogeneousGrading k d) (coordinate k i)
    (coordinate_mem_degreeOne k i) Nat.zero_lt_one

/-- The product of the coordinates appearing in a finite indexed family. -/
def coordinateProduct (k : Type u) [CommRing k] {d : ℕ}
    {ι : Type v} [Fintype ι] (a : ι → Fin (d + 1)) :
    MvPolynomial (Fin (d + 1)) k :=
  ∏ j, coordinate k (a j)

/-- The intersection of an indexed family of standard charts, represented
as one projective basic open. -/
def standardIntersection (k : Type u) [CommRing k] {d : ℕ}
    {ι : Type v} [Fintype ι] (a : ι → Fin (d + 1)) :
    (scheme k d).Opens :=
  Proj.basicOpen (homogeneousGrading k d) (coordinateProduct k a)

/-- The coordinate product is homogeneous of degree the cardinality of its
indexing type. -/
lemma coordinateProduct_mem_degreeCard (k : Type u) [CommRing k]
    {d : ℕ} {ι : Type v} [Fintype ι] (a : ι → Fin (d + 1)) :
    coordinateProduct k a ∈
      homogeneousGrading k d (Fintype.card ι) := by
  classical
  simpa [coordinateProduct] using
    MvPolynomial.IsHomogeneous.prod Finset.univ
      (fun j : ι => coordinate k (a j)) (fun _ => 1)
      (fun j _ => coordinate_mem_degreeOne k (a j))

private lemma basicOpen_coordinateProduct_finset
    (k : Type u) [CommRing k] {d : ℕ} {ι : Type v}
    (a : ι → Fin (d + 1)) (s : Finset ι) :
    Proj.basicOpen (homogeneousGrading k d)
        (∏ j ∈ s, coordinate k (a j)) =
      ⨅ j ∈ s, standardChart k (a j) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert j s hj ih =>
      rw [Finset.prod_insert hj, Proj.basicOpen_mul, ih,
        Finset.iInf_insert]
      rfl

/-- The product basic open is the intersection of the corresponding
coordinate charts. -/
lemma standardIntersection_eq_iInf (k : Type u) [CommRing k]
    {d : ℕ} {ι : Type v} [Fintype ι] (a : ι → Fin (d + 1)) :
    standardIntersection k a = ⨅ j, standardChart k (a j) := by
  classical
  simpa [standardIntersection, coordinateProduct] using
    basicOpen_coordinateProduct_finset k a Finset.univ

/-- A nonempty finite intersection of standard coordinate charts is
affine. -/
lemma isAffineOpen_standardIntersection (k : Type u) [CommRing k]
    {d : ℕ} {ι : Type v} [Fintype ι] [Nonempty ι]
    (a : ι → Fin (d + 1)) :
    IsAffineOpen (standardIntersection k a) :=
  Proj.isAffineOpen_basicOpen
    (homogeneousGrading k d) (coordinateProduct k a)
    (coordinateProduct_mem_degreeCard k a)
    (Fintype.card_pos)

/-- Typeclass form of affineness for finite nonempty intersections. -/
instance isAffine_standardIntersection (k : Type u) [CommRing k]
    {d : ℕ} {ι : Type v} [Fintype ι] [Nonempty ι]
    (a : ι → Fin (d + 1)) :
    IsAffine (standardIntersection k a) :=
  isAffineOpen_standardIntersection k a

/-- The explicit affine-spectrum presentation of a nonempty finite
intersection. -/
noncomputable def standardIntersectionIsoSpec
    (k : Type u) [CommRing k] {d : ℕ}
    {ι : Type v} [Fintype ι] [Nonempty ι]
    (a : ι → Fin (d + 1)) :
    (standardIntersection k a).toScheme ≅
      Spec (.of <| HomogeneousLocalization.Away
        (homogeneousGrading k d) (coordinateProduct k a)) :=
  Proj.basicOpenIsoSpec
    (homogeneousGrading k d) (coordinateProduct k a)
    (coordinateProduct_mem_degreeCard k a)
    (Fintype.card_pos)

/-- The standard `(p + 1)`-fold intersection associated to a Čech
`p`-simplex. -/
abbrev cechIntersection (k : Type u) [CommRing k] {d p : ℕ}
    (a : Fin (p + 1) → Fin (d + 1)) :
    (scheme k d).Opens :=
  standardIntersection k a

/-- Every standard Čech intersection is affine. -/
lemma isAffineOpen_cechIntersection
    (k : Type u) [CommRing k] {d p : ℕ}
    (a : Fin (p + 1) → Fin (d + 1)) :
    IsAffineOpen (cechIntersection k a) :=
  isAffineOpen_standardIntersection k a

end MazurTorsion.AlgebraicGeometry.CoherentCohomology.ProjectiveSpace
