/-
Copyright (c) 2026 Vasil V. and contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasil V., OpenAI Codex
-/
import MazurTorsion.Upstream.CoherentCohomologyFinite.SheafCohomologyExactSequence
import Mathlib.CategoryTheory.Abelian.GrothendieckAxioms.Sheaf
import Mathlib.CategoryTheory.Abelian.GrothendieckCategory.HasExt
import Mathlib.CategoryTheory.Limits.Constructions.EpiMono
import Mathlib.Topology.Sheaves.Flasque

/-!
# Flasque sheaves and higher cohomology

This file proves that injective sheaves of abelian groups are flasque and
that flasque sheaves have vanishing higher cohomology.
-/

open CategoryTheory Limits Opposite TopCat TopologicalSpace

universe u

variable {X : TopCat.{u}}

namespace TopCat.Sheaf.IsFlasque

noncomputable section

/-- The sheafification of the presheaf which is freely generated by an open. -/
abbrev freeAbSheaf (U : Opens X) :
    CategoryTheory.Sheaf (Opens.grothendieckTopology X)
      AddCommGrpCat.{u} :=
  (presheafToSheaf _ _).obj
    (yoneda.obj U ⋙ AddCommGrpCat.free)

/-- Inclusion of opens induces a map between their free abelian sheaves. -/
abbrev freeAbSheafMap {U V : Opens X} (i : U ⟶ V) :
    freeAbSheaf U ⟶ freeAbSheaf V :=
  (presheafToSheaf _ _).map
    (Functor.whiskerRight (yoneda.map i) AddCommGrpCat.free)

/-- Maps from the free abelian sheaf on `U` correspond to sections over `U`. -/
def freeAbSheafHomEquiv (U : Opens X)
    (I : CategoryTheory.Sheaf (Opens.grothendieckTopology X)
      AddCommGrpCat.{u}) :
    (freeAbSheaf U ⟶ I) ≃ I.obj.obj (op U) :=
  ((sheafificationAdjunction _ _).homEquiv
      (yoneda.obj U ⋙ AddCommGrpCat.free) I).trans <|
    ((AddCommGrpCat.adj.whiskerRight _).homEquiv
      (yoneda.obj U)
      ((sheafToPresheaf _ _).obj I)).trans yonedaEquiv

lemma freeAbSheafHomEquiv_naturality {U V : Opens X}
    (i : U ⟶ V)
    (I : CategoryTheory.Sheaf (Opens.grothendieckTopology X)
      AddCommGrpCat.{u})
    (f : freeAbSheaf V ⟶ I) :
    freeAbSheafHomEquiv U I (freeAbSheafMap i ≫ f) =
      I.obj.map i.op (freeAbSheafHomEquiv V I f) := by
  simp only [freeAbSheafHomEquiv, freeAbSheafMap]
  change
    yonedaEquiv
      (((AddCommGrpCat.adj.whiskerRight _).homEquiv _ _)
        (((sheafificationAdjunction _ _).homEquiv _ _)
          ((presheafToSheaf _ _).map
              (Functor.whiskerRight (yoneda.map i)
                AddCommGrpCat.free) ≫ f))) = _
  erw [Adjunction.homEquiv_naturality_left,
    ← Functor.whiskeringRight_obj_map]
  erw [Adjunction.homEquiv_naturality_left]
  exact (yonedaEquiv_naturality _ i).symm

instance freeAbSheafMap_mono {U V : Opens X} (i : U ⟶ V) :
    Mono (freeAbSheafMap i) :=
  haveI : PreservesFiniteLimits
      (presheafToSheaf
        (Opens.grothendieckTopology X) AddCommGrpCat.{u}) :=
    HasSheafify.isLeftExact
  Functor.map_mono _ _

/-- Injective sheaves of abelian groups are flasque. -/
instance of_injective
    (I : CategoryTheory.Sheaf (Opens.grothendieckTopology X)
      AddCommGrpCat.{u})
    [Injective I] : IsFlasque I where
  epi := by
    refine fun i =>
      AddCommGrpCat.epi_iff_surjective _ |>.mpr (fun s => ?_)
    obtain ⟨h, hh⟩ :=
      Injective.factors
        ((freeAbSheafHomEquiv _ I).symm s)
        (freeAbSheafMap i.unop)
    use freeAbSheafHomEquiv _ I h
    rw [← Quiver.Hom.op_unop i,
      ← freeAbSheafHomEquiv_naturality, hh]
    simp

/-- A flasque sheaf has zero cohomology in every positive degree. -/
theorem H_isZero
    (F : CategoryTheory.Sheaf (Opens.grothendieckTopology X)
      AddCommGrpCat)
    [IsFlasque F] (n : ℕ) :
    IsZero (AddCommGrpCat.of (CategoryTheory.Sheaf.H F (n + 1))) := by
  induction n generalizing F with
  | zero =>
      obtain ⟨I, _, f, _⟩ := EnoughInjectives.presentation F
      let S := ShortComplex.mk f (cokernel.π f) (by cat_disch)
      have hS : S.ShortExact :=
        ShortComplex.ShortExact.mk
          (ShortComplex.exact_cokernel f)
      have hLS :=
        CategoryTheory.Sheaf.H.longSequence_exact hS 0 1 rfl
      refine ShortComplex.Exact.isZero_of_both_zeros
        (hLS.exact 2) ?_
        (zero_of_target_iso_zero _
          (IsZero.isoZero
            (AddCommGrpCat.isZero_of_subsingleton
              (AddCommGrpCat.of
                (CategoryTheory.Sheaf.H I 1)))))
      rw [← ShortComplex.Exact.epi_f_iff (hLS.exact 1),
        AddCommGrpCat.epi_iff_surjective]
      change Function.Surjective (CategoryTheory.Sheaf.H.map S.g 0)
      rw [← Equiv.surjective_comp
        (CategoryTheory.Sheaf.H.equiv₀ I
          Limits.isTerminalTop).symm.toEquiv]
      change Function.Surjective
        ((CategoryTheory.Sheaf.H.map S.g 0) ∘
          (CategoryTheory.Sheaf.H.equiv₀ I
            Limits.isTerminalTop).symm.toEquiv)
      conv =>
        right
        equals
          (CategoryTheory.Sheaf.H.equiv₀ S.X₃
            Limits.isTerminalTop).symm.toEquiv ∘
            S.g.hom.app (op ⊤) =>
          ext x
          exact
            CategoryTheory.Sheaf.H.equiv₀_symm_naturality
              Limits.isTerminalTop S.g x
      rw [Equiv.comp_surjective,
        ← AddCommGrpCat.epi_iff_surjective]
      exact epi_of_shortExact hS
  | succ n hn =>
      obtain ⟨I, _, f, _⟩ := EnoughInjectives.presentation F
      have hS : (ShortComplex.mk f (cokernel.π f)
          (by cat_disch)).ShortExact :=
        ShortComplex.ShortExact.mk
          (ShortComplex.exact_cokernel f)
      haveI := of_shortExact_of_isFlasque₁₂ hS
      exact ShortComplex.Exact.isZero_of_both_isZero
        ((CategoryTheory.Sheaf.H.longSequence_exact
          hS (n + 1) (n + 2) rfl).exact 2)
        (hn _)
        (AddCommGrpCat.isZero_of_subsingleton
          (AddCommGrpCat.of
            (CategoryTheory.Sheaf.H I (n + 2))))

/-- Higher cohomology of a flasque sheaf is subsingleton. -/
instance subsingleton_H
    {F : CategoryTheory.Sheaf (Opens.grothendieckTopology X)
      AddCommGrpCat}
    [IsFlasque F] (n : ℕ) :
    Subsingleton
      (CategoryTheory.Sheaf.H F (n + 1)) :=
  AddCommGrpCat.subsingleton_of_isZero (H_isZero F n)

end

end TopCat.Sheaf.IsFlasque
