/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin, Codex
-/

import MazurTorsion.AlgebraicGeometry.Jacobian.SymmetricPower
import MazurTorsion.AlgebraicGeometry.Jacobian.UniversalEffectiveDivisor
import MazurTorsion.AlgebraicGeometry.Jacobian.FiniteGroupQuotientFlatBaseChange
import MazurTorsion.AlgebraicGeometry.Jacobian.AffineLineSymmetricPower
import MazurTorsion.AlgebraicGeometry.Jacobian.UniversalRootFactorization

/-!
# Finite quotients of the ordered universal incidence family

This file constructs the finite-group quotient of the ordered incidence
family on a challenge curve.  The key geometric input is an affine orbit
neighbourhood theorem for both the ordered ambient product and its invariant
closed subscheme.  It is obtained by mapping the curve finitely to `P¹`,
taking the product of that map with its componentwise power, and pulling back
affine orbit neighbourhoods from a projective target.

The quotient of the incidence family maps canonically to the quotient of the
ambient product.  The next representability step identifies that ambient
quotient with `C × Sym^d(C)` and proves that the descended closed family is a
relative effective Cartier divisor.
-/

noncomputable section

universe u

open CategoryTheory Limits
open _root_.AlgebraicGeometry

namespace MazurTorsion.AlgebraicGeometry.Jacobian.UniversalEffectiveDivisor

open FiniteGroupQuotient
open PermutationPower
open ProjectiveFiniteOrbit

/-- The symmetric power of the affine line is the affine coefficient space:
its coordinate ring is freely generated by the elementary symmetric
functions.  This identifies the quotient target used by the incidence
construction with the base of the universal monic polynomial. -/
noncomputable def affineLineSymmetricPowerIsoCoefficientSpace
    (R : Type u) [CommRing R] (n : ℕ) :
    AffineLineSymmetricPower.invariantRootScheme R n ≅
      Spec (CommRingCat.of (MvPolynomial (Fin n) R)) :=
  AffineLineSymmetricPower.invariantRootSchemeIsoCoefficientSpace R n

/-- The affine-line local model of the universal effective divisor is finite
flat of constant rank `n + 1`.  This is the local algebraic input to the
curve-level descent construction below. -/
theorem affineLineUniversalEffectiveDivisor_finite_flat_rank
    (R : Type u) [CommRing R] [Nontrivial R] (n : ℕ) :
    IsFinite (UniversalRootFactorization.universalRootProjection R n) ∧
      Flat (UniversalRootFactorization.universalRootProjection R n) ∧
        (UniversalRootFactorization.universalRootProjection R n).finrank =
          fun _ ↦ n + 1 := by
  exact ⟨inferInstance, inferInstance,
    UniversalRootFactorization.universalRootProjection_finrank R n⟩

/-- In the affine-line model the universal family is the closed subscheme cut
out by one regular equation, namely the universal monic polynomial. -/
theorem affineLineUniversalEffectiveDivisor_isPrincipalCartier
    (R : Type u) [CommRing R] [Nontrivial R] (n : ℕ) :
    IsClosedImmersion (UniversalRootFactorization.universalRootLocusι R n) ∧
      RingHom.ker (UniversalRootFactorization.ambientToFactors R n) =
        Ideal.span {UniversalRootFactorization.universalPolynomial R n} ∧
      IsRegular (UniversalRootFactorization.universalPolynomial R n) := by
  exact ⟨inferInstance,
    UniversalRootFactorization.ambientToFactors_ker R n,
    UniversalRootFactorization.universalPolynomial_isRegular R n⟩

variable (S : Scheme.{u}) (d : ℕ) {X Y : Over S}

/-- A morphism `X ⟶ Y` induces a morphism on the ordered ambient products,
acting on the distinguished point and componentwise on the ordered power. -/
noncomputable def orderedAmbientMap (f : X ⟶ Y) :
    orderedAmbient S d X ⟶ orderedAmbient S d Y :=
  Limits.prod.map f (PermutationPower.map S (Fin d) f)

/-- The induced map on ordered ambient products is finite when the original
morphism is finite. -/
theorem orderedAmbientMap_isFinite (f : X ⟶ Y) [IsFinite f.left] :
    IsFinite (orderedAmbientMap S d f).left := by
  letI : IsFinite (PermutationPower.map S (Fin d) f).left :=
    PermutationPower.map_isFinite S (Fin d) f
  exact PermutationPower.binaryMap_isFinite S f
    (PermutationPower.map S (Fin d) f)

/-- The induced map on ordered ambient products commutes with coordinate
permutations. -/
theorem orderedAmbientMap_equivariant (f : X ⟶ Y)
    (g : Equiv.Perm (Fin d)) :
    (orderedAmbientAction S d X).hom g ≫ (orderedAmbientMap S d f).left =
      (orderedAmbientMap S d f).left ≫
        (orderedAmbientAction S d Y).hom g := by
  change
    (orderedAmbientPermutationHom S d X g ≫ orderedAmbientMap S d f).left =
      (orderedAmbientMap S d f ≫
        orderedAmbientPermutationHom S d Y g).left
  congr 1
  apply Limits.prod.hom_ext
  · simp [orderedAmbientMap, orderedAmbientPermutationHom]
  · simp only [orderedAmbientMap, orderedAmbientPermutationHom,
      Limits.prod.map_snd, Category.assoc]
    have h : PermutationPower.permutationHom S (Fin d) X g ≫
        PermutationPower.map S (Fin d) f =
      PermutationPower.map S (Fin d) f ≫
        PermutationPower.permutationHom S (Fin d) Y g := by
      apply Limits.Pi.hom_ext
      intro i
      simp only [Category.assoc, PermutationPower.map_comp_π,
        PermutationPower.permutationHom_comp_π]
      rw [← Category.assoc, PermutationPower.permutationHom_comp_π]
    simp only [← Category.assoc, Limits.prod.map_snd]
    rw [Category.assoc, h]
    simp

section Curve

variable (K : Type u) [Field K]

/-- The projective line as an object over `Spec K`. -/
noncomputable abbrev projectiveLine : Over (Spec (.of K)) :=
  Over.mk (TauCeti.AlgebraicGeometry.ProjectiveLine.structureMap K)

/-- The ordered ambient product for a positive power of `P¹` is projective. -/
theorem projectiveLineOrderedAmbient_isProjectiveFactorization (n : ℕ) :
    CoherentCohomology.ProjectiveSpace.IsProjectiveFactorization
      (orderedAmbient (Spec (.of K)) (n + 1) (projectiveLine K)).hom := by
  exact binaryProduct_isProjectiveFactorization K (projectiveLine K)
    (PermutationPower.power (Spec (.of K)) (Fin (n + 1))
      (projectiveLine K))
    (by
      change CoherentCohomology.ProjectiveSpace.IsProjectiveFactorization
        (TauCeti.AlgebraicGeometry.ProjectiveLine.structureMap K)
      rw [projectiveLine_structureMap_eq_toSpec K]
      exact CoherentCohomology.ProjectiveSpace.isProjectiveFactorization_toSpec K 1)
    (projectiveLinePower_isProjectiveFactorization K n)

/-- Every orbit of the action fixing the distinguished `P¹` coordinate and
permuting the remaining positive number of coordinates has an affine
neighbourhood. -/
theorem projectiveLineOrderedAmbient_hasAffineOrbit (n : ℕ) :
    HasAffineOrbit
      (orderedAmbientAction (Spec (.of K)) (n + 1) (projectiveLine K)) :=
  hasAffineOrbit_of_isProjectiveFactorization K _
    (projectiveLineOrderedAmbient_isProjectiveFactorization K n)

variable (C : Over (Spec (.of K)))
variable [GeometricallyIrreducible C.hom] [IsProper C.hom]
variable [SmoothOfRelativeDimension 1 C.hom]

/-- Every orbit in `C × C^(n+1)` for the action fixing the first coordinate
and permuting the remaining coordinates has an affine neighbourhood. -/
theorem curveOrderedAmbient_hasAffineOrbit_succ (n : ℕ) :
    HasAffineOrbit (orderedAmbientAction (Spec (.of K)) (n + 1) C) := by
  let f := FiniteMapToProjectiveLine.overHom K C
  letI : IsFinite f.left := FiniteMapToProjectiveLine.hom_isFinite K C
  letI : IsFinite (orderedAmbientMap (Spec (.of K)) (n + 1) f).left :=
    orderedAmbientMap_isFinite (Spec (.of K)) (n + 1) f
  exact hasAffineOrbit_of_equivariant_affine
    (orderedAmbientAction (Spec (.of K)) (n + 1) C)
    (orderedAmbientAction (Spec (.of K)) (n + 1) (projectiveLine K))
    (orderedAmbientMap (Spec (.of K)) (n + 1) f).left
    (projectiveLineOrderedAmbient_hasAffineOrbit K n)
    (orderedAmbientMap_equivariant (Spec (.of K)) (n + 1) f)

/-- The underlying ordered ambient product is separated as an absolute
scheme.  This supplies the affine-diagonal hypothesis of the quotient
construction. -/
instance curveOrderedAmbient_isSeparated (n : ℕ) :
    (orderedAmbient (Spec (.of K)) (n + 1) C).left.IsSeparated := by
  letI : IsAffineHom (terminal.from (Spec (.of K))) := by infer_instance
  letI : IsProper (orderedAmbient (Spec (.of K)) (n + 1) C).hom :=
    SymmetricPower.binaryProduct_isProper K C
      (PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C)
      inferInstance inferInstance
  constructor
  rw [← terminal.comp_from
    (orderedAmbient (Spec (.of K)) (n + 1) C).hom]
  infer_instance

/-- Affine orbit neighbourhoods restrict from the ordered ambient product to
the invariant ordered incidence closed subscheme. -/
theorem curveOrderedIncidence_hasAffineOrbit_succ (n : ℕ) :
    HasAffineOrbit
      (orderedIncidenceAction (Spec (.of K)) (n + 1) C) := by
  exact hasAffineOrbit_of_equivariant_affine
    (orderedIncidenceAction (Spec (.of K)) (n + 1) C)
    (orderedAmbientAction (Spec (.of K)) (n + 1) C)
    (orderedIncidenceι (Spec (.of K)) (n + 1) C)
    (curveOrderedAmbient_hasAffineOrbit_succ K C n)
    (orderedIncidenceAction_comp_ι (Spec (.of K)) (n + 1) C)

/-- The ordered incidence closed subscheme is separated as an absolute
scheme. -/
instance curveOrderedIncidence_isSeparated (n : ℕ) :
    (orderedIncidence (Spec (.of K)) (n + 1) C).IsSeparated := by
  constructor
  rw [← terminal.comp_from
    (orderedIncidenceι (Spec (.of K)) (n + 1) C)]
  infer_instance

/-- The finite-group quotient of the ordered ambient product. -/
noncomputable def curveOrderedAmbientQuotientSucc (n : ℕ) : Scheme.{u} :=
  quotient (orderedAmbientAction (Spec (.of K)) (n + 1) C)
    (curveOrderedAmbient_hasAffineOrbit_succ K C n)

/-- The quotient projection from the ordered ambient product. -/
noncomputable def curveOrderedAmbientQuotientProjectionSucc (n : ℕ) :
    (orderedAmbient (Spec (.of K)) (n + 1) C).left ⟶
      curveOrderedAmbientQuotientSucc K C n :=
  quotientπ (orderedAmbientAction (Spec (.of K)) (n + 1) C)
    (curveOrderedAmbient_hasAffineOrbit_succ K C n)

instance curveOrderedAmbientQuotientProjectionSucc_isAffineHom (n : ℕ) :
    IsAffineHom (curveOrderedAmbientQuotientProjectionSucc K C n) := by
  exact quotientπ_isAffineHom
    (orderedAmbientAction (Spec (.of K)) (n + 1) C)
    (curveOrderedAmbient_hasAffineOrbit_succ K C n)

instance curveOrderedAmbientQuotientProjectionSucc_surjective (n : ℕ) :
    Surjective (curveOrderedAmbientQuotientProjectionSucc K C n) := by
  exact quotientπ_surjectiveProperty
    (orderedAmbientAction (Spec (.of K)) (n + 1) C)
    (curveOrderedAmbient_hasAffineOrbit_succ K C n)

/-- The finite-group quotient of the ordered incidence family. -/
noncomputable def curveOrderedIncidenceQuotientSucc (n : ℕ) : Scheme.{u} :=
  quotient (orderedIncidenceAction (Spec (.of K)) (n + 1) C)
    (curveOrderedIncidence_hasAffineOrbit_succ K C n)

/-- The quotient projection from the ordered incidence family. -/
noncomputable def curveOrderedIncidenceQuotientProjectionSucc (n : ℕ) :
    orderedIncidence (Spec (.of K)) (n + 1) C ⟶
      curveOrderedIncidenceQuotientSucc K C n :=
  quotientπ (orderedIncidenceAction (Spec (.of K)) (n + 1) C)
    (curveOrderedIncidence_hasAffineOrbit_succ K C n)

instance curveOrderedIncidenceQuotientProjectionSucc_isAffineHom (n : ℕ) :
    IsAffineHom (curveOrderedIncidenceQuotientProjectionSucc K C n) := by
  exact quotientπ_isAffineHom
    (orderedIncidenceAction (Spec (.of K)) (n + 1) C)
    (curveOrderedIncidence_hasAffineOrbit_succ K C n)

instance curveOrderedIncidenceQuotientProjectionSucc_surjective (n : ℕ) :
    Surjective (curveOrderedIncidenceQuotientProjectionSucc K C n) := by
  exact quotientπ_surjectiveProperty
    (orderedIncidenceAction (Spec (.of K)) (n + 1) C)
    (curveOrderedIncidence_hasAffineOrbit_succ K C n)

/-- The ordered incidence inclusion followed by the ambient quotient
projection is invariant under coordinate permutations. -/
theorem orderedIncidenceι_comp_ambientQuotientProjection_invariant
    (n : ℕ) (g : Equiv.Perm (Fin (n + 1))) :
    (orderedIncidenceAction (Spec (.of K)) (n + 1) C).hom g ≫
        orderedIncidenceι (Spec (.of K)) (n + 1) C ≫
          curveOrderedAmbientQuotientProjectionSucc K C n =
      orderedIncidenceι (Spec (.of K)) (n + 1) C ≫
        curveOrderedAmbientQuotientProjectionSucc K C n := by
  rw [← Category.assoc, orderedIncidenceAction_comp_ι,
    Category.assoc]
  exact congrArg
    (fun q ↦ orderedIncidenceι (Spec (.of K)) (n + 1) C ≫ q)
    (FiniteGroupQuotient.hom_quotientπ
      (orderedAmbientAction (Spec (.of K)) (n + 1) C)
      (curveOrderedAmbient_hasAffineOrbit_succ K C n) g)

/-- The quotient of the ordered incidence family maps canonically into the
quotient of the ordered ambient product. -/
noncomputable def curveIncidenceQuotientToAmbientQuotientSucc (n : ℕ) :
    curveOrderedIncidenceQuotientSucc K C n ⟶
      curveOrderedAmbientQuotientSucc K C n :=
  Classical.choose <| FiniteGroupQuotient.existsUnique_quotientπ_lift
    (orderedIncidenceAction (Spec (.of K)) (n + 1) C)
    (curveOrderedIncidence_hasAffineOrbit_succ K C n)
    (orderedIncidenceι (Spec (.of K)) (n + 1) C ≫
      curveOrderedAmbientQuotientProjectionSucc K C n)
    (orderedIncidenceι_comp_ambientQuotientProjection_invariant K C n)

/-- Pulling the descended incidence morphism back along the quotient
projection recovers the ordered incidence inclusion followed by the ambient
quotient projection. -/
@[reassoc]
theorem curveOrderedIncidenceQuotientProjection_comp_descendedι (n : ℕ) :
    curveOrderedIncidenceQuotientProjectionSucc K C n ≫
        curveIncidenceQuotientToAmbientQuotientSucc K C n =
      orderedIncidenceι (Spec (.of K)) (n + 1) C ≫
        curveOrderedAmbientQuotientProjectionSucc K C n :=
  (Classical.choose_spec <| FiniteGroupQuotient.existsUnique_quotientπ_lift
    (orderedIncidenceAction (Spec (.of K)) (n + 1) C)
    (curveOrderedIncidence_hasAffineOrbit_succ K C n)
    (orderedIncidenceι (Spec (.of K)) (n + 1) C ≫
      curveOrderedAmbientQuotientProjectionSucc K C n)
    (orderedIncidenceι_comp_ambientQuotientProjection_invariant K C n)).1

/-- Before quotienting the ambient product, take the symmetric quotient in
the ordered-power coordinate and leave the distinguished curve coordinate
unchanged. -/
noncomputable def curveOrderedAmbientToSymmetricProductSucc (n : ℕ) :
    (orderedAmbient (Spec (.of K)) (n + 1) C).left ⟶
      (C ⨯ SymmetricPower.curveSchemeSucc K C n).left :=
  (Limits.prod.map (𝟙 C) (SymmetricPower.curveProjectionSucc K C n)).left

/-- The map from the ordered ambient product to
`C × Sym^(n+1)(C)` is invariant under coordinate permutations. -/
theorem curveOrderedAmbientToSymmetricProductSucc_invariant
    (n : ℕ) (g : Equiv.Perm (Fin (n + 1))) :
    (orderedAmbientAction (Spec (.of K)) (n + 1) C).hom g ≫
        curveOrderedAmbientToSymmetricProductSucc K C n =
      curveOrderedAmbientToSymmetricProductSucc K C n := by
  change
    (orderedAmbientPermutationHom (Spec (.of K)) (n + 1) C g ≫
      Limits.prod.map (𝟙 C)
        (SymmetricPower.curveProjectionSucc K C n)).left =
    (Limits.prod.map (𝟙 C)
      (SymmetricPower.curveProjectionSucc K C n)).left
  congr 1
  apply Limits.prod.hom_ext
  · simp [orderedAmbientPermutationHom]
  · simp only [orderedAmbientPermutationHom, Category.assoc,
      Limits.prod.map_snd]
    rw [← Category.assoc, Limits.prod.map_snd, Category.assoc]
    have hq :
        PermutationPower.permutationHom (Spec (.of K)) (Fin (n + 1)) C g ≫
            SymmetricPower.curveProjectionSucc K C n =
          SymmetricPower.curveProjectionSucc K C n := by
      apply Over.OverMorphism.ext
      exact SymmetricPower.action_comp_projection
        (Spec (.of K)) (n + 1) C
        (SymmetricPower.curve_hasAffineOrbits_succ K C n) g
    rw [hq]

/-- The map which quotients only the ordered-power coordinate is the base
change of the symmetric-power projection along the second projection from
`C × Sym^(n+1)(C)`. -/
theorem curveOrderedAmbientToSymmetricProductSucc_isPullback (n : ℕ) :
    IsPullback
      (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
        PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left
      (curveOrderedAmbientToSymmetricProductSucc K C n)
      (SymmetricPower.curveProjectionSucc K C n).left
      (Limits.prod.snd : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
        SymmetricPower.curveSchemeSucc K C n).left := by
  have hAmbient : IsPullback
      (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
        PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left
      (Limits.prod.fst : orderedAmbient (Spec (.of K)) (n + 1) C ⟶ C).left
      (PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).hom C.hom := by
    apply IsPullback.flip
    refine IsPullback.of_iso_pullback ⟨?_⟩
      (Over.prodLeftIsoPullback C
        (PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C))
      (Over.prodLeftIsoPullback_hom_fst C
        (PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C))
      (Over.prodLeftIsoPullback_hom_snd C
        (PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C))
    exact (Limits.prod.fst : orderedAmbient (Spec (.of K)) (n + 1) C ⟶ C).w.trans
      (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
        PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).w.symm
  have hProduct : IsPullback
      (Limits.prod.snd : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
        SymmetricPower.curveSchemeSucc K C n).left
      (Limits.prod.fst : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶ C).left
      (SymmetricPower.curveSchemeSucc K C n).hom C.hom := by
    apply IsPullback.flip
    refine IsPullback.of_iso_pullback ⟨?_⟩
      (Over.prodLeftIsoPullback C (SymmetricPower.curveSchemeSucc K C n))
      (Over.prodLeftIsoPullback_hom_fst C (SymmetricPower.curveSchemeSucc K C n))
      (Over.prodLeftIsoPullback_hom_snd C (SymmetricPower.curveSchemeSucc K C n))
    exact (Limits.prod.fst : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶ C).w.trans
      (Limits.prod.snd : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
        SymmetricPower.curveSchemeSucc K C n).w.symm
  have hComposite : IsPullback
      (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
        PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left
      (curveOrderedAmbientToSymmetricProductSucc K C n ≫
        (Limits.prod.fst : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶ C).left)
      ((SymmetricPower.curveProjectionSucc K C n).left ≫
        (SymmetricPower.curveSchemeSucc K C n).hom)
      C.hom := by
    simpa only [← Over.comp_left, curveOrderedAmbientToSymmetricProductSucc,
      Limits.prod.map_fst, Category.comp_id,
      SymmetricPower.curveProjectionSucc_comp_structureMap] using hAmbient
  exact hComposite.of_bot
    (congrArg Over.Hom.left
      (Limits.prod.map_snd (𝟙 C) (SymmetricPower.curveProjectionSucc K C n))).symm
    hProduct

/-- The projection `C × Sym^(n+1)(C) ⟶ Sym^(n+1)(C)` is flat: it is
the base change of the smooth curve `C ⟶ Spec K`. -/
instance curveProductSymmetricPowerSnd_flat (n : ℕ) :
    Flat (Limits.prod.snd : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
      SymmetricPower.curveSchemeSucc K C n).left := by
  have hProduct : IsPullback
      (Limits.prod.snd : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
        SymmetricPower.curveSchemeSucc K C n).left
      (Limits.prod.fst : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶ C).left
      (SymmetricPower.curveSchemeSucc K C n).hom C.hom := by
    apply IsPullback.flip
    refine IsPullback.of_iso_pullback ⟨?_⟩
      (Over.prodLeftIsoPullback C (SymmetricPower.curveSchemeSucc K C n))
      (Over.prodLeftIsoPullback_hom_fst C (SymmetricPower.curveSchemeSucc K C n))
      (Over.prodLeftIsoPullback_hom_snd C (SymmetricPower.curveSchemeSucc K C n))
    exact (Limits.prod.fst : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶ C).w.trans
      (Limits.prod.snd : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
        SymmetricPower.curveSchemeSucc K C n).w.symm
  exact MorphismProperty.of_isPullback hProduct.flip
    (inferInstance : Flat C.hom)

/-- The ordered ambient product identified with the pullback of the
symmetric quotient along `C × Sym^(n+1)(C) ⟶ Sym^(n+1)(C)`. -/
noncomputable def curveOrderedAmbientBaseChangeIso (n : ℕ) :
    (orderedAmbient (Spec (.of K)) (n + 1) C).left ≅
      pullback (SymmetricPower.curveProjectionSucc K C n).left
        (Limits.prod.snd : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
          SymmetricPower.curveSchemeSucc K C n).left :=
  (curveOrderedAmbientToSymmetricProductSucc_isPullback K C n).isoPullback

/-- The second projection from `C × Sym^(n+1)(C)`, with its codomain
written as the underlying finite-group quotient rather than through the
symmetric-power wrapper. -/
noncomputable def curveProductToPermutationQuotientSucc (n : ℕ) :
    (C ⨯ SymmetricPower.curveSchemeSucc K C n).left ⟶
      FiniteGroupQuotient.quotient
        (SymmetricPower.Action (Spec (.of K)) (n + 1) C)
        (SymmetricPower.curve_hasAffineOrbits_succ K C n) :=
  (Limits.prod.snd : (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
    SymmetricPower.curveSchemeSucc K C n).left

instance curveProductToPermutationQuotientSucc_flat (n : ℕ) :
    Flat (curveProductToPermutationQuotientSucc K C n) := by
  change Flat (Limits.prod.snd :
    (C ⨯ SymmetricPower.curveSchemeSucc K C n) ⟶
      SymmetricPower.curveSchemeSucc K C n).left
  infer_instance

/-- Exact quotient-typed form of the ambient pullback square. -/
theorem curveOrderedAmbientToPermutationQuotientSucc_isPullback (n : ℕ) :
    IsPullback
      (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
        PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left
      (curveOrderedAmbientToSymmetricProductSucc K C n)
      (FiniteGroupQuotient.quotientπ
        (SymmetricPower.Action (Spec (.of K)) (n + 1) C)
        (SymmetricPower.curve_hasAffineOrbits_succ K C n))
      (curveProductToPermutationQuotientSucc K C n) := by
  exact curveOrderedAmbientToSymmetricProductSucc_isPullback K C n

/-- Exact quotient-typed comparison isomorphism for the ordered ambient
product. -/
noncomputable def curveOrderedAmbientPermutationQuotientBaseChangeIso (n : ℕ) :
    (orderedAmbient (Spec (.of K)) (n + 1) C).left ≅
      pullback
        (FiniteGroupQuotient.quotientπ
          (SymmetricPower.Action (Spec (.of K)) (n + 1) C)
          (SymmetricPower.curve_hasAffineOrbits_succ K C n))
        (curveProductToPermutationQuotientSucc K C n) :=
  (curveOrderedAmbientToPermutationQuotientSucc_isPullback K C n).isoPullback

/-- The pullback action on the base-changed symmetric quotient corresponds,
under the comparison isomorphism, to permuting the ordered coordinates of
the ambient product. -/
theorem pullbackQuotientSMul_comp_curveOrderedAmbientBaseChangeIso_inv
    (n : ℕ) (g : Equiv.Perm (Fin (n + 1))) :
    FiniteGroupQuotient.pullbackQuotientSMul
        (SymmetricPower.Action (Spec (.of K)) (n + 1) C)
        (SymmetricPower.curve_hasAffineOrbits_succ K C n)
        (curveProductToPermutationQuotientSucc K C n) g ≫
        (curveOrderedAmbientPermutationQuotientBaseChangeIso K C n).inv =
      (curveOrderedAmbientPermutationQuotientBaseChangeIso K C n).inv ≫
        (orderedAmbientAction (Spec (.of K)) (n + 1) C).hom g := by
  let σ := SymmetricPower.Action (Spec (.of K)) (n + 1) C
  let hσ := SymmetricPower.curve_hasAffineOrbits_succ K C n
  let w := curveProductToPermutationQuotientSucc K C n
  let π := FiniteGroupQuotient.quotientπ σ hσ
  let E := curveOrderedAmbientPermutationQuotientBaseChangeIso K C n
  let hpb := curveOrderedAmbientToPermutationQuotientSucc_isPullback K C n
  have hEinvfst : E.inv ≫
      (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
        PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left =
      pullback.fst π w := by
    exact hpb.isoPullback_inv_fst
  have hEhomfst : E.hom ≫ pullback.fst π w =
      (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
        PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left := by
    exact hpb.isoPullback_hom_fst
  have hEinvsnd : E.inv ≫ curveOrderedAmbientToSymmetricProductSucc K C n =
      pullback.snd π w := by
    exact hpb.isoPullback_inv_snd
  have hEhomsnd : E.hom ≫ pullback.snd π w =
      curveOrderedAmbientToSymmetricProductSucc K C n := by
    exact hpb.isoPullback_hom_snd
  have hAmbientSnd :
      (orderedAmbientAction (Spec (.of K)) (n + 1) C).hom g ≫
          (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
            PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left =
        (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
            PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left ≫
          σ.hom g := by
    exact congrArg Over.Hom.left
      (Limits.prod.map_snd (𝟙 C)
        (PermutationPower.permutationHom (Spec (.of K)) (Fin (n + 1)) C g))
  change FiniteGroupQuotient.pullbackQuotientSMul σ hσ w g ≫ E.inv =
    E.inv ≫ (orderedAmbientAction (Spec (.of K)) (n + 1) C).hom g
  apply (cancel_mono E.hom).mp
  rw [Category.assoc, Iso.inv_hom_id, Category.comp_id]
  apply pullback.hom_ext
  · calc
      FiniteGroupQuotient.pullbackQuotientSMul σ hσ w g ≫
          pullback.fst π w =
        pullback.fst π w ≫ σ.hom g := by
        rw [FiniteGroupQuotient.pullbackQuotientSMul_fst]
      _ = E.inv ≫
          (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
            PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left ≫
          σ.hom g := by
        simpa only [Category.assoc] using
          congrArg (fun t ↦ t ≫ σ.hom g) hEinvfst.symm
      _ = E.inv ≫
          (orderedAmbientAction (Spec (.of K)) (n + 1) C).hom g ≫
          (Limits.prod.snd : orderedAmbient (Spec (.of K)) (n + 1) C ⟶
            PermutationPower.power (Spec (.of K)) (Fin (n + 1)) C).left := by
        rw [← Category.assoc, hAmbientSnd, Category.assoc]
      _ = (E.inv ≫ (orderedAmbientAction (Spec (.of K)) (n + 1) C).hom g) ≫
          E.hom ≫ pullback.fst π w := by
        rw [hEhomfst]
        exact (Category.assoc _ _ _).symm
  · calc
      FiniteGroupQuotient.pullbackQuotientSMul σ hσ w g ≫
          pullback.snd π w = pullback.snd π w := by
        rw [FiniteGroupQuotient.pullbackQuotientSMul_snd]
      _ = E.inv ≫
          curveOrderedAmbientToSymmetricProductSucc K C n := by
        exact hEinvsnd.symm
      _ = E.inv ≫
          (orderedAmbientAction (Spec (.of K)) (n + 1) C).hom g ≫
          curveOrderedAmbientToSymmetricProductSucc K C n := by
        rw [curveOrderedAmbientToSymmetricProductSucc_invariant]
      _ = (E.inv ≫ (orderedAmbientAction (Spec (.of K)) (n + 1) C).hom g) ≫
          E.hom ≫ pullback.snd π w := by
        rw [hEhomsnd]
        exact (Category.assoc _ _ _).symm

/-- The inverse candidate from `C × Sym^(n+1)(C)` to the quotient of the
ordered ambient product, obtained from flat base change of the permutation
quotient. -/
noncomputable def curveSymmetricProductToAmbientQuotientSucc (n : ℕ) :
    (C ⨯ SymmetricPower.curveSchemeSucc K C n).left ⟶
      curveOrderedAmbientQuotientSucc K C n :=
  Classical.choose <| FiniteGroupQuotient.existsUnique_quotientπ_lift_baseChange_of_flat
    (SymmetricPower.Action (Spec (.of K)) (n + 1) C)
    (SymmetricPower.curve_hasAffineOrbits_succ K C n)
    (curveProductToPermutationQuotientSucc K C n)
    ((curveOrderedAmbientPermutationQuotientBaseChangeIso K C n).inv ≫
      curveOrderedAmbientQuotientProjectionSucc K C n)
    (fun g ↦ by
      rw [← Category.assoc,
        pullbackQuotientSMul_comp_curveOrderedAmbientBaseChangeIso_inv,
        Category.assoc]
      exact congrArg
        (fun t ↦ (curveOrderedAmbientPermutationQuotientBaseChangeIso K C n).inv ≫ t)
        (FiniteGroupQuotient.hom_quotientπ
          (orderedAmbientAction (Spec (.of K)) (n + 1) C)
          (curveOrderedAmbient_hasAffineOrbit_succ K C n) g))

/-- Defining factorization of the inverse candidate on the canonical
base-changed quotient. -/
@[reassoc]
theorem pullbackSnd_comp_curveSymmetricProductToAmbientQuotientSucc (n : ℕ) :
    pullback.snd
        (FiniteGroupQuotient.quotientπ
          (SymmetricPower.Action (Spec (.of K)) (n + 1) C)
          (SymmetricPower.curve_hasAffineOrbits_succ K C n))
        (curveProductToPermutationQuotientSucc K C n) ≫
        curveSymmetricProductToAmbientQuotientSucc K C n =
      (curveOrderedAmbientPermutationQuotientBaseChangeIso K C n).inv ≫
        curveOrderedAmbientQuotientProjectionSucc K C n :=
  (Classical.choose_spec <|
    FiniteGroupQuotient.existsUnique_quotientπ_lift_baseChange_of_flat
      (SymmetricPower.Action (Spec (.of K)) (n + 1) C)
      (SymmetricPower.curve_hasAffineOrbits_succ K C n)
      (curveProductToPermutationQuotientSucc K C n)
      ((curveOrderedAmbientPermutationQuotientBaseChangeIso K C n).inv ≫
        curveOrderedAmbientQuotientProjectionSucc K C n)
      (fun g ↦ by
        rw [← Category.assoc,
          pullbackQuotientSMul_comp_curveOrderedAmbientBaseChangeIso_inv,
          Category.assoc]
        exact congrArg
          (fun t ↦ (curveOrderedAmbientPermutationQuotientBaseChangeIso K C n).inv ≫ t)
          (FiniteGroupQuotient.hom_quotientπ
            (orderedAmbientAction (Spec (.of K)) (n + 1) C)
            (curveOrderedAmbient_hasAffineOrbit_succ K C n) g))).1

/-- Pulling the inverse candidate back to the ordered ambient product gives
the ambient quotient projection. -/
@[reassoc]
theorem curveOrderedAmbientToSymmetricProductSucc_comp_inverse (n : ℕ) :
    curveOrderedAmbientToSymmetricProductSucc K C n ≫
        curveSymmetricProductToAmbientQuotientSucc K C n =
      curveOrderedAmbientQuotientProjectionSucc K C n := by
  let E := curveOrderedAmbientPermutationQuotientBaseChangeIso K C n
  let hpb := curveOrderedAmbientToPermutationQuotientSucc_isPullback K C n
  let π := FiniteGroupQuotient.quotientπ
    (SymmetricPower.Action (Spec (.of K)) (n + 1) C)
    (SymmetricPower.curve_hasAffineOrbits_succ K C n)
  let w := curveProductToPermutationQuotientSucc K C n
  have hEhom : E.hom ≫ pullback.snd π w =
      curveOrderedAmbientToSymmetricProductSucc K C n := by
    exact hpb.isoPullback_hom_snd
  rw [← hEhom, Category.assoc,
    pullbackSnd_comp_curveSymmetricProductToAmbientQuotientSucc,
    ← Category.assoc, Iso.hom_inv_id, Category.id_comp]

/-- The invariant ambient map descends to the finite-group quotient. -/
noncomputable def curveAmbientQuotientToSymmetricProductSucc (n : ℕ) :
    curveOrderedAmbientQuotientSucc K C n ⟶
      (C ⨯ SymmetricPower.curveSchemeSucc K C n).left :=
  Classical.choose <| FiniteGroupQuotient.existsUnique_quotientπ_lift
    (orderedAmbientAction (Spec (.of K)) (n + 1) C)
    (curveOrderedAmbient_hasAffineOrbit_succ K C n)
    (curveOrderedAmbientToSymmetricProductSucc K C n)
    (curveOrderedAmbientToSymmetricProductSucc_invariant K C n)

@[reassoc]
theorem curveOrderedAmbientQuotientProjection_comp_toSymmetricProduct
    (n : ℕ) :
    curveOrderedAmbientQuotientProjectionSucc K C n ≫
        curveAmbientQuotientToSymmetricProductSucc K C n =
      curveOrderedAmbientToSymmetricProductSucc K C n :=
  (Classical.choose_spec <| FiniteGroupQuotient.existsUnique_quotientπ_lift
    (orderedAmbientAction (Spec (.of K)) (n + 1) C)
    (curveOrderedAmbient_hasAffineOrbit_succ K C n)
    (curveOrderedAmbientToSymmetricProductSucc K C n)
    (curveOrderedAmbientToSymmetricProductSucc_invariant K C n)).1

/-- The quotient of `C × C^(n+1)` by permutations of the ordered-power
coordinates is canonically `C × Sym^(n+1)(C)`. -/
noncomputable def curveAmbientQuotientSymmetricProductIso (n : ℕ) :
    curveOrderedAmbientQuotientSucc K C n ≅
      (C ⨯ SymmetricPower.curveSchemeSucc K C n).left where
  hom := curveAmbientQuotientToSymmetricProductSucc K C n
  inv := curveSymmetricProductToAmbientQuotientSucc K C n
  hom_inv_id := by
    let p := curveOrderedAmbientQuotientProjectionSucc K C n
    haveI : Epi p := FiniteGroupQuotient.epi_quotientπ
      (orderedAmbientAction (Spec (.of K)) (n + 1) C)
      (curveOrderedAmbient_hasAffineOrbit_succ K C n)
    apply (cancel_epi p).mp
    rw [← Category.assoc,
      curveOrderedAmbientQuotientProjection_comp_toSymmetricProduct,
      curveOrderedAmbientToSymmetricProductSucc_comp_inverse,
      Category.comp_id]
  inv_hom_id := by
    let σ := SymmetricPower.Action (Spec (.of K)) (n + 1) C
    let hσ := SymmetricPower.curve_hasAffineOrbits_succ K C n
    let w := curveProductToPermutationQuotientSucc K C n
    let π := FiniteGroupQuotient.quotientπ σ hσ
    let E := curveOrderedAmbientPermutationQuotientBaseChangeIso K C n
    let hpb := curveOrderedAmbientToPermutationQuotientSucc_isPullback K C n
    have hEinvsnd : E.inv ≫ curveOrderedAmbientToSymmetricProductSucc K C n =
        pullback.snd π w := by
      exact hpb.isoPullback_inv_snd
    haveI : Epi (pullback.snd π w) :=
      FiniteGroupQuotient.epi_pullback_snd_quotientπ_of_flat σ hσ w
    apply (cancel_epi (pullback.snd π w)).mp
    rw [← Category.assoc,
      pullbackSnd_comp_curveSymmetricProductToAmbientQuotientSucc,
      Category.assoc,
      curveOrderedAmbientQuotientProjection_comp_toSymmetricProduct,
      hEinvsnd, Category.comp_id]

instance curveAmbientQuotientToSymmetricProductSucc_isIso (n : ℕ) :
    IsIso (curveAmbientQuotientToSymmetricProductSucc K C n) := by
  change IsIso (curveAmbientQuotientSymmetricProductIso K C n).hom
  infer_instance

/-- The descended incidence family as a morphism into
`C × Sym^(n+1)(C)`. -/
noncomputable def curveDescendedIncidenceιSucc (n : ℕ) :
    curveOrderedIncidenceQuotientSucc K C n ⟶
      (C ⨯ SymmetricPower.curveSchemeSucc K C n).left :=
  curveIncidenceQuotientToAmbientQuotientSucc K C n ≫
    curveAmbientQuotientToSymmetricProductSucc K C n

/-- Pullback of the descended incidence morphism to the ordered incidence
family is the original inclusion followed by quotienting the divisor
coordinate. -/
@[reassoc]
theorem curveOrderedIncidenceQuotientProjection_comp_descendedIncidenceι
    (n : ℕ) :
    curveOrderedIncidenceQuotientProjectionSucc K C n ≫
        curveDescendedIncidenceιSucc K C n =
      orderedIncidenceι (Spec (.of K)) (n + 1) C ≫
        curveOrderedAmbientToSymmetricProductSucc K C n := by
  rw [curveDescendedIncidenceιSucc, ← Category.assoc,
    curveOrderedIncidenceQuotientProjection_comp_descendedι,
    Category.assoc,
    curveOrderedAmbientQuotientProjection_comp_toSymmetricProduct]

end Curve

end MazurTorsion.AlgebraicGeometry.Jacobian.UniversalEffectiveDivisor
