/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import MazurTorsion.GroupTheory.ForbiddenEmbeddings
import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Tactic.NormNum

/-!
# Embeddings from independent cyclic generators

This file packages a small group-theoretic construction used after an
explicit two-isogeny.  A point `P` of exact order two and a point `Q` of
exact order `n` generate an embedded `ZMod 2 × ZMod n` as soon as `P`
does not lie in the cyclic subgroup generated by `Q`.
-/

namespace MazurTorsion.IndependentCyclicGenerators

variable {G : Type*} [AddCommGroup G]

/-- The homomorphism from `ZMod n` which sends `1` to `P`. -/
def zmodHom (n : ℕ) (P : G) (hP : n • P = 0) :
    ZMod n →+ G :=
  ZMod.lift n
    ⟨
      { toFun := fun z : ℤ => z • P
        map_zero' := zero_zsmul P
        map_add' := fun a b => add_zsmul P a b },
      by simpa using hP⟩

@[simp] theorem zmodHom_intCast
    (n : ℕ) (P : G) (hP : n • P = 0) (z : ℤ) :
    zmodHom n P hP (z : ZMod n) = z • P := by
  simp [zmodHom]

@[simp] theorem zmodHom_one
    (n : ℕ) (P : G) (hP : n • P = 0) :
    zmodHom n P hP 1 = P := by
  simpa using zmodHom_intCast n P hP 1

/-- Exact order makes the cyclic-generator homomorphism injective. -/
theorem zmodHom_injective
    (n : ℕ) (P : G) (hP : n • P = 0)
    (horder : addOrderOf P = n) :
    Function.Injective (zmodHom n P hP) := by
  change Function.Injective (ZMod.lift n _)
  rw [ZMod.lift_injective]
  intro z hz
  change z • P = 0 at hz
  apply (CharP.intCast_eq_zero_iff (ZMod n) n z).2
  rw [← horder]
  exact (addOrderOf_dvd_iff_zsmul_eq_zero).2 hz

/-- The sum of the two cyclic-generator maps. -/
def productHom
    (P Q : G) (hP : (2 : ℕ) • P = 0)
    (n : ℕ) (hQ : n • Q = 0) :
    ZMod 2 × ZMod n →+ G :=
  (zmodHom 2 P hP).coprod (zmodHom n Q hQ)

@[simp] theorem productHom_apply
    (P Q : G) (hP : (2 : ℕ) • P = 0)
    (n : ℕ) (hQ : n • Q = 0)
    (z : ZMod 2 × ZMod n) :
    productHom P Q hP n hQ z =
      zmodHom 2 P hP z.1 + zmodHom n Q hQ z.2 :=
  rfl

private theorem zmodHom_mem_zmultiples
    (n : ℕ) (Q : G) (hQ : n • Q = 0)
    (z : ZMod n) :
    zmodHom n Q hQ z ∈ AddSubgroup.zmultiples Q := by
  obtain ⟨k, rfl⟩ := ZMod.intCast_surjective z
  rw [zmodHom_intCast]
  exact AddSubgroup.zsmul_mem_zmultiples Q k

/-- The product map is injective when the order-two generator is not in
the cyclic subgroup generated by the other generator. -/
theorem productHom_injective
    (P Q : G)
    (hPorder : addOrderOf P = 2)
    (n : ℕ) (hQorder : addOrderOf Q = n)
    (hindependent : P ∉ AddSubgroup.zmultiples Q) :
    Function.Injective
      (productHom P Q
        (addOrderOf_dvd_iff_nsmul_eq_zero.mp
          (hPorder ▸ dvd_rfl))
        n
        (addOrderOf_dvd_iff_nsmul_eq_zero.mp
          (hQorder ▸ dvd_rfl))) := by
  let hP : (2 : ℕ) • P = 0 :=
    addOrderOf_dvd_iff_nsmul_eq_zero.mp
      (hPorder ▸ dvd_rfl)
  let hQ : n • Q = 0 :=
    addOrderOf_dvd_iff_nsmul_eq_zero.mp
      (hQorder ▸ dvd_rfl)
  let fP : ZMod 2 →+ G := zmodHom 2 P hP
  let fQ : ZMod n →+ G := zmodHom n Q hQ
  let f : ZMod 2 × ZMod n →+ G := fP.coprod fQ
  have hfker : f.ker = ⊥ := by
    apply (AddSubgroup.eq_bot_iff_forall f.ker).mpr
    rintro ⟨i, j⟩ hij
    have hsum : fP i + fQ j = 0 := by
      simpa only [AddMonoidHom.mem_ker, f,
        AddMonoidHom.coprod_apply] using hij
    have hfi_mem :
        fP i ∈ AddSubgroup.zmultiples Q := by
      have hfj_mem :
          fQ j ∈ AddSubgroup.zmultiples Q := by
        exact zmodHom_mem_zmultiples n Q hQ j
      have hneg_mem :
          -fQ j ∈ AddSubgroup.zmultiples Q :=
        (AddSubgroup.zmultiples Q).neg_mem hfj_mem
      rw [eq_neg_of_add_eq_zero_left hsum]
      exact hneg_mem
    have hi : i = 0 := by
      by_contra hi
      have hi_one : i = 1 :=
        Fin.eq_one_of_ne_zero i hi
      apply hindependent
      simpa only [fP, hi_one, zmodHom_one] using hfi_mem
    have hj : j = 0 := by
      apply (zmodHom_injective n Q hQ hQorder)
      rw [map_zero]
      simpa only [hi, map_zero, zero_add] using hsum
    exact Prod.ext hi hj
  exact (AddMonoidHom.ker_eq_bot_iff f).mp hfker

/-- Existence form suited to a `ForbidsEmbedding` contradiction. -/
theorem exists_embedding
    (P Q : G)
    (hPorder : addOrderOf P = 2)
    (n : ℕ) (hQorder : addOrderOf Q = n)
    (hindependent : P ∉ AddSubgroup.zmultiples Q) :
    ∃ f : ZMod 2 × ZMod n →+ G, Function.Injective f := by
  let hP : (2 : ℕ) • P = 0 :=
    addOrderOf_dvd_iff_nsmul_eq_zero.mp
      (hPorder ▸ dvd_rfl)
  let hQ : n • Q = 0 :=
    addOrderOf_dvd_iff_nsmul_eq_zero.mp
      (hQorder ▸ dvd_rfl)
  exact
    ⟨productHom P Q hP n hQ,
      productHom_injective P Q hPorder n hQorder
        hindependent⟩

/-- In a cyclic group of exact order `2n`, the sole nonzero point killed
by two is the `n`-multiple of a generator.  Consequently, any other point
of exact order two is outside that cyclic subgroup. -/
theorem orderTwo_not_mem_zmultiples
    (P Q : G) (n : ℕ)
    (hPorder : addOrderOf P = 2)
    (hQorder : addOrderOf Q = 2 * n)
    (hhalf : P ≠ n • Q) :
    P ∉ AddSubgroup.zmultiples Q := by
  have hP0 : P ≠ 0 := by
    intro hP
    rw [hP, addOrderOf_zero] at hPorder
    norm_num at hPorder
  have hPtwo : (2 : ℕ) • P = 0 :=
    addOrderOf_dvd_iff_nsmul_eq_zero.mp
      (hPorder ▸ dvd_rfl)
  have hQtwoN : (2 * n : ℕ) • Q = 0 :=
    addOrderOf_dvd_iff_nsmul_eq_zero.mp
      (hQorder ▸ dvd_rfl)
  have hStwo : (2 : ℤ) • (n • Q) = 0 := by
    rw [show (2 : ℤ) = (2 : ℕ) by norm_num,
      natCast_zsmul]
    simpa only [Nat.mul_comm, mul_nsmul] using hQtwoN
  intro hmem
  obtain ⟨k, hk⟩ :=
    AddSubgroup.mem_zmultiples_iff.mp hmem
  have htwice : (2 * k : ℤ) • Q = 0 := by
    calc
      (2 * k : ℤ) • Q = (2 : ℤ) • (k • Q) := by
        rw [mul_zsmul]
      _ = (2 : ℤ) • P := by rw [hk]
      _ = (2 : ℕ) • P := by
        norm_num only [ofNat_zsmul]
      _ = 0 := hPtwo
  have hdiv : ((2 * n : ℕ) : ℤ) ∣ 2 * k := by
    rw [← hQorder]
    exact
      (addOrderOf_dvd_iff_zsmul_eq_zero).2 htwice
  have hnDiv : (n : ℤ) ∣ k := by
    apply
      (mul_dvd_mul_iff_left
        (show (2 : ℤ) ≠ 0 by norm_num)).mp
    exact_mod_cast hdiv
  obtain ⟨l, hl⟩ := hnDiv
  have hP_eq : P = l • (n • Q) := by
    calc
      P = k • Q := hk.symm
      _ = ((n : ℤ) * l) • Q := by rw [hl]
      _ = l • (n • Q) := by
        rw [mul_comm, mul_zsmul]
        norm_num
  obtain ⟨r, hr | hr⟩ := Int.even_or_odd' l
  · apply hP0
    calc
      P = l • (n • Q) := hP_eq
      _ = (2 * r : ℤ) • (n • Q) := by rw [hr]
      _ = (r * 2 : ℤ) • (n • Q) := by
        rw [Int.mul_comm 2 r]
      _ = r • ((2 : ℤ) • (n • Q)) :=
        mul_zsmul (n • Q) r 2
      _ = 0 := by rw [hStwo, smul_zero]
  · apply hhalf
    calc
      P = l • (n • Q) := hP_eq
      _ = (2 * r + 1 : ℤ) • (n • Q) := by rw [hr]
      _ = (2 * r : ℤ) • (n • Q) + n • Q := by
        rw [add_zsmul, one_zsmul]
      _ = (r * 2 : ℤ) • (n • Q) + n • Q := by
        rw [Int.mul_comm 2 r]
      _ = r • ((2 : ℤ) • (n • Q)) + n • Q := by
        rw [mul_zsmul]
      _ = n • Q := by rw [hStwo, smul_zero, zero_add]

end MazurTorsion.IndependentCyclicGenerators
