/-
Copyright (c) 2026 Vasily Ilin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vasily Ilin
-/

import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.LinearCombination

/-!
# The explicit two-isogeny with kernel generated by `(0, 0)`

For the rational Weierstrass curve

`E(a,b) : y² = x(x² + ax + b)`

this file defines the denominator-safe point map to

`E'(a,b) : Y² = X(X² - 2aX + a² - 4b)`.

Away from the kernel its coordinates are

`X = y²/x² = x + a + b/x`,

`Y = y(b - x²)/x²`.

The second coordinate is the negative of the other common convention
`y(1 - b/x²)`.

The exact-pin library has no general isogeny or elliptic-curve-morphism
API.  Accordingly, `pointMapFun` and `dualPointMapFun` are underlying point
functions rather than bundled homomorphisms.  This file proves their
denominator safety, exact kernels, kernel-translation identity, and the
global composition `dualPointMapFun (pointMapFun P) = 2 • P`.  Bundling
`pointMapFun` remains the separate task of proving preservation of the raw
affine chord-and-tangent addition formula in all secant, tangent, and
exceptional-fiber cases.
-/

open WeierstrassCurve

namespace MazurTorsion.TwoIsogeny

open WeierstrassCurve.Affine

section AbstractOrder

variable {A B : Type*} [AddGroup A] [AddGroup B]

/-- If `Q` has order `2m`, its `m`-multiple lies in the kernel of `f`,
and the kernel of `f` is killed by two, then `f Q` has exact order `m`. -/
theorem addOrderOf_image_eq_half
    (f : A →+ B) (Q : A) (m : ℕ)
    (hQ : addOrderOf Q = 2 * m)
    (hmid : f (m • Q) = 0)
    (hker : ∀ R : A, f R = 0 → (2 : ℕ) • R = 0) :
    addOrderOf (f Q) = m := by
  have hm_image : (m : ℕ) • f Q = 0 := by
    rw [← map_nsmul]
    exact hmid
  have himage_dvd : addOrderOf (f Q) ∣ m :=
    addOrderOf_dvd_of_nsmul_eq_zero hm_image
  have horder_kernel :
      f (addOrderOf (f Q) • Q) = 0 := by
    rw [map_nsmul, addOrderOf_nsmul_eq_zero]
  have htwice :
      (2 : ℕ) • (addOrderOf (f Q) • Q) = 0 :=
    hker _ horder_kernel
  have htwice' :
      (2 * addOrderOf (f Q)) • Q = 0 := by
    simpa only [← mul_nsmul, Nat.mul_comm] using htwice
  have hdouble_dvd :
      2 * m ∣ 2 * addOrderOf (f Q) := by
    rw [← hQ]
    exact addOrderOf_dvd_of_nsmul_eq_zero htwice'
  have hm_dvd : m ∣ addOrderOf (f Q) :=
    (Nat.mul_dvd_mul_iff_left (by norm_num : 0 < 2)).mp
      hdouble_dvd
  exact Nat.dvd_antisymm himage_dvd hm_dvd

end AbstractOrder

/-- A rational Weierstrass model with the two-torsion point `(0,0)`. -/
def sourceCurve (a b : ℚ) : WeierstrassCurve ℚ :=
  ⟨0, a, 0, b, 0⟩

/-- The standard quotient model by the subgroup generated by `(0,0)`. -/
def targetCurve (a b : ℚ) : WeierstrassCurve ℚ :=
  ⟨0, -2 * a, 0, a ^ 2 - 4 * b, 0⟩

lemma sourceCurve_discriminant (a b : ℚ) :
    (sourceCurve a b).Δ = 16 * b ^ 2 * (a ^ 2 - 4 * b) := by
  simp [sourceCurve, WeierstrassCurve.Δ,
    WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈]
  ring

lemma targetCurve_discriminant (a b : ℚ) :
    (targetCurve a b).Δ =
      256 * b * (a ^ 2 - 4 * b) ^ 2 := by
  simp [targetCurve, WeierstrassCurve.Δ,
    WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈]
  ring

lemma source_b_ne_zero (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    b ≠ 0 := by
  have hs : 16 * b ^ 2 * (a ^ 2 - 4 * b) ≠ 0 := by
    simpa only [sourceCurve_discriminant] using
      (sourceCurve a b).isUnit_Δ.ne_zero
  exact fun hb ↦ hs (by simp [hb])

lemma source_discriminant_factor_ne_zero (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    a ^ 2 - 4 * b ≠ 0 := by
  have hs : 16 * b ^ 2 * (a ^ 2 - 4 * b) ≠ 0 := by
    simpa only [sourceCurve_discriminant] using
      (sourceCurve a b).isUnit_Δ.ne_zero
  exact fun hd ↦ hs (by simp [hd])

/-- Nonsingularity of the source implies nonsingularity of its standard
two-isogenous model. -/
noncomputable instance targetCurve_isElliptic
    (a b : ℚ) [(sourceCurve a b).IsElliptic] :
    (targetCurve a b).IsElliptic := by
  rw [WeierstrassCurve.isElliptic_iff, isUnit_iff_ne_zero,
    targetCurve_discriminant]
  have hs : 16 * b ^ 2 * (a ^ 2 - 4 * b) ≠ 0 := by
    simpa only [sourceCurve_discriminant] using
      (sourceCurve a b).isUnit_Δ.ne_zero
  have hb : b ≠ 0 := source_b_ne_zero a b
  have hd : a ^ 2 - 4 * b ≠ 0 :=
    source_discriminant_factor_ne_zero a b
  exact mul_ne_zero (mul_ne_zero (by norm_num) hb) (pow_ne_zero 2 hd)

lemma source_equation {a b x y : ℚ}
    (h : (sourceCurve a b).toAffine.Nonsingular x y) :
    y ^ 2 = x * (x ^ 2 + a * x + b) := by
  have heq := h.1
  rw [WeierstrassCurve.Affine.equation_iff] at heq
  simp only [sourceCurve] at heq
  convert heq using 1 <;> ring

lemma target_equation {a b X Y : ℚ}
    (h : (targetCurve a b).toAffine.Nonsingular X Y) :
    Y ^ 2 = X * (X ^ 2 - 2 * a * X + a ^ 2 - 4 * b) := by
  have heq := h.1
  rw [WeierstrassCurve.Affine.equation_iff] at heq
  simp only [targetCurve] at heq
  convert heq using 1 <;> ring

private lemma source_origin_nonsingular
    (a b : ℚ) [(sourceCurve a b).IsElliptic] :
    (sourceCurve a b).toAffine.Nonsingular 0 0 := by
  apply (sourceCurve a b).toAffine.equation_iff_nonsingular.mp
  norm_num [WeierstrassCurve.Affine.equation_iff, sourceCurve]

/-- The nonzero rational two-torsion point on the source curve. -/
def sourceOrigin (a b : ℚ) [(sourceCurve a b).IsElliptic] :
    (sourceCurve a b).toAffine.Point :=
  .some 0 0 (source_origin_nonsingular a b)

private lemma target_origin_nonsingular
    (a b : ℚ) [(sourceCurve a b).IsElliptic] :
    (targetCurve a b).toAffine.Nonsingular 0 0 := by
  apply (targetCurve a b).toAffine.equation_iff_nonsingular.mp
  norm_num [WeierstrassCurve.Affine.equation_iff, targetCurve]

/-- The visible two-torsion point `(0,0)` on the target curve. -/
def targetOrigin (a b : ℚ) [(sourceCurve a b).IsElliptic] :
    (targetCurve a b).toAffine.Point :=
  .some 0 0 (target_origin_nonsingular a b)

/-- The `X`-coordinate of the explicit isogeny away from its kernel. -/
def mapX (x y : ℚ) : ℚ :=
  y ^ 2 / x ^ 2

/-- The `Y`-coordinate of the explicit isogeny away from its kernel. -/
def mapY (b x y : ℚ) : ℚ :=
  y * (b - x ^ 2) / x ^ 2

lemma mapX_eq {a b x y : ℚ} (hx : x ≠ 0)
    (hcurve : y ^ 2 = x * (x ^ 2 + a * x + b)) :
    mapX x y = x + a + b / x := by
  simp only [mapX]
  field_simp [hx]
  linear_combination hcurve

lemma mapY_eq_common_convention (b x y : ℚ) (hx : x ≠ 0) :
    mapY b x y = -y * (1 - b / x ^ 2) := by
  simp only [mapY]
  field_simp [hx]
  ring

/-- Direct substitution verifies that the explicit rational functions land
on the target curve. -/
lemma map_equation {a b x y : ℚ} (hx : x ≠ 0)
    (hcurve : y ^ 2 = x * (x ^ 2 + a * x + b)) :
    mapY b x y ^ 2 =
      mapX x y *
        (mapX x y ^ 2 - 2 * a * mapX x y +
          a ^ 2 - 4 * b) := by
  rw [mapX_eq hx hcurve]
  simp only [mapY]
  field_simp [hx]
  rw [hcurve]
  ring

private lemma map_nonsingular {a b x y : ℚ}
    [(sourceCurve a b).IsElliptic]
    (h : (sourceCurve a b).toAffine.Nonsingular x y)
    (hx : x ≠ 0) :
    (targetCurve a b).toAffine.Nonsingular
      (mapX x y) (mapY b x y) := by
  apply (targetCurve a b).toAffine.equation_iff_nonsingular.mp
  rw [WeierstrassCurve.Affine.equation_iff]
  have hm := map_equation hx (source_equation h)
  simp only [targetCurve]
  convert hm using 1 <;> ring

/-- The denominator-safe underlying point map.  Both the point at infinity
and the affine kernel point `(0,0)` are sent to infinity. -/
noncomputable def pointMapFun (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    (sourceCurve a b).toAffine.Point →
      (targetCurve a b).toAffine.Point
  | .zero => .zero
  | .some x y h =>
      if hx : x = 0 then .zero
      else .some (mapX x y) (mapY b x y)
        (map_nonsingular h hx)

@[simp] lemma pointMapFun_zero (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    pointMapFun a b 0 = 0 :=
  rfl

@[simp] lemma pointMapFun_sourceOrigin (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    pointMapFun a b (sourceOrigin a b) = 0 := by
  simp only [sourceOrigin, pointMapFun]
  change Point.zero = Point.zero
  rfl

lemma pointMapFun_some_of_ne {a b x y : ℚ}
    [(sourceCurve a b).IsElliptic]
    (h : (sourceCurve a b).toAffine.Nonsingular x y)
    (hx : x ≠ 0) :
    pointMapFun a b (.some x y h) =
      .some (mapX x y) (mapY b x y)
        (map_nonsingular h hx) := by
  simp [pointMapFun, hx]

lemma source_y_eq_zero_of_x_eq_zero {a b x y : ℚ}
    (h : (sourceCurve a b).toAffine.Nonsingular x y)
    (hx : x = 0) :
    y = 0 := by
  have hcurve := source_equation h
  rw [hx] at hcurve
  norm_num at hcurve
  exact hcurve

lemma pointMapFun_eq_zero_iff {a b : ℚ}
    [(sourceCurve a b).IsElliptic]
    (P : (sourceCurve a b).toAffine.Point) :
    pointMapFun a b P = 0 ↔
      P = 0 ∨ P = sourceOrigin a b := by
  cases P with
  | zero =>
      change Point.zero = Point.zero ↔
        Point.zero = Point.zero ∨
          Point.zero = sourceOrigin a b
      simp
  | some x y h =>
      by_cases hx : x = 0
      · have hy := source_y_eq_zero_of_x_eq_zero h hx
        subst x
        subst y
        have hP :
            (Point.some 0 0 h :
              (sourceCurve a b).toAffine.Point) =
                sourceOrigin a b := by
          rfl
        rw [hP, pointMapFun_sourceOrigin]
        simp
      · rw [pointMapFun_some_of_ne h hx]
        have hmapne :
            (Point.some (mapX x y) (mapY b x y)
              (map_nonsingular h hx) :
                (targetCurve a b).toAffine.Point) ≠ 0 :=
          Point.some_ne_zero _
        have hPzero :
            (Point.some x y h :
              (sourceCurve a b).toAffine.Point) ≠ 0 :=
          Point.some_ne_zero _
        have hPorigin :
            (Point.some x y h :
              (sourceCurve a b).toAffine.Point) ≠
                sourceOrigin a b := by
          intro horigin
          have hxzero : x = 0 := by
            exact (show x = 0 ∧ y = 0 by
              simpa only [sourceOrigin, Point.some.injEq] using
                horigin).1
          exact hx hxzero
        simp only [hmapne, hPzero, hPorigin, false_or]

lemma pointMapFun_neg {a b : ℚ}
    [(sourceCurve a b).IsElliptic]
    (P : (sourceCurve a b).toAffine.Point) :
    pointMapFun a b (-P) = -pointMapFun a b P := by
  cases P with
  | zero => rfl
  | some x y h =>
      by_cases hx : x = 0
      · have hy := source_y_eq_zero_of_x_eq_zero h hx
        subst x
        subst y
        rw [Point.neg_some]
        simp [pointMapFun]
        rfl
      · rw [Point.neg_some, pointMapFun_some_of_ne]
        · rw [pointMapFun_some_of_ne h hx, Point.neg_some]
          simp only [Point.some.injEq]
          constructor
          · simp [mapX, sourceCurve, negY]
          · simp [mapY, sourceCurve, targetCurve, negY]
            ring
        · exact hx

@[simp] lemma sourceOrigin_add_self (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    sourceOrigin a b + sourceOrigin a b = 0 := by
  simp only [sourceOrigin]
  apply Point.add_self_of_Y_eq
  norm_num [sourceCurve, negY]

lemma pointMapFun_kernel_killed_by_two {a b : ℚ}
    [(sourceCurve a b).IsElliptic]
    {P : (sourceCurve a b).toAffine.Point}
    (hP : pointMapFun a b P = 0) :
    (2 : ℕ) • P = 0 := by
  rcases (pointMapFun_eq_zero_iff P).mp hP with rfl | rfl
  · simp
  · simpa only [two_nsmul] using sourceOrigin_add_self a b

private lemma translated_nonsingular {a b x y : ℚ}
    [(sourceCurve a b).IsElliptic]
    (h : (sourceCurve a b).toAffine.Nonsingular x y)
    (hx : x ≠ 0) :
    (sourceCurve a b).toAffine.Nonsingular
      (b / x) (-b * y / x ^ 2) := by
  apply (sourceCurve a b).toAffine.equation_iff_nonsingular.mp
  rw [WeierstrassCurve.Affine.equation_iff]
  simp only [sourceCurve]
  have hcurve := source_equation h
  field_simp [hx]
  linear_combination b ^ 2 * hcurve

/-- Translation by the kernel point `(0,0)` in affine coordinates. -/
lemma add_sourceOrigin {a b x y : ℚ}
    [(sourceCurve a b).IsElliptic]
    (h : (sourceCurve a b).toAffine.Nonsingular x y)
    (hx : x ≠ 0) :
    (Point.some x y h :
        (sourceCurve a b).toAffine.Point) +
        sourceOrigin a b =
      Point.some (b / x) (-b * y / x ^ 2)
        (translated_nonsingular h hx) := by
  rw [sourceOrigin, Point.add_of_X_ne hx]
  simp only [Point.some.injEq]
  have hcurve := source_equation h
  constructor
  · rw [(sourceCurve a b).toAffine.slope_of_X_ne hx]
    simp only [addX, sourceCurve]
    field_simp [hx]
    linear_combination x * hcurve
  · rw [(sourceCurve a b).toAffine.slope_of_X_ne hx]
    simp only [addY, negAddY, addX, negY, sourceCurve]
    field_simp [hx]
    linear_combination -x ^ 2 * y * hcurve

/-- The isogeny is constant on the two-element cosets generated by its
kernel point. -/
lemma pointMapFun_add_sourceOrigin {a b : ℚ}
    [(sourceCurve a b).IsElliptic]
    (P : (sourceCurve a b).toAffine.Point) :
    pointMapFun a b (P + sourceOrigin a b) =
      pointMapFun a b P := by
  cases P with
  | zero =>
      change pointMapFun a b (sourceOrigin a b) =
        pointMapFun a b Point.zero
      rw [pointMapFun_sourceOrigin]
      rfl
  | some x y h =>
      by_cases hx : x = 0
      · have hy := source_y_eq_zero_of_x_eq_zero h hx
        subst x
        subst y
        have hP :
            (Point.some 0 0 h :
              (sourceCurve a b).toAffine.Point) =
                sourceOrigin a b := by
          rfl
        rw [hP, sourceOrigin_add_self]
        simp
      · rw [add_sourceOrigin h hx]
        have hb : b ≠ 0 := source_b_ne_zero a b
        have hbx : b / x ≠ 0 := div_ne_zero hb hx
        rw [pointMapFun_some_of_ne _ hbx,
          pointMapFun_some_of_ne h hx]
        simp only [Point.some.injEq]
        constructor
        · simp only [mapX]
          field_simp [hb, hx]
        · simp only [mapY]
          field_simp [hb, hx]
          ring

/-- The `x`-coordinate of the dual two-isogeny. -/
def dualMapX (X Y : ℚ) : ℚ :=
  Y ^ 2 / (4 * X ^ 2)

/-- The `y`-coordinate of the dual two-isogeny. -/
def dualMapY (a b X Y : ℚ) : ℚ :=
  Y * (a ^ 2 - 4 * b - X ^ 2) / (8 * X ^ 2)

/-- Direct substitution verifies the dual rational functions. -/
lemma dual_map_equation {a b X Y : ℚ} (hX : X ≠ 0)
    (hcurve :
      Y ^ 2 =
        X * (X ^ 2 - 2 * a * X + a ^ 2 - 4 * b)) :
    dualMapY a b X Y ^ 2 =
      dualMapX X Y *
        (dualMapX X Y ^ 2 + a * dualMapX X Y + b) := by
  simp only [dualMapX, dualMapY]
  field_simp [hX]
  rw [hcurve]
  ring

private lemma dual_map_nonsingular {a b X Y : ℚ}
    [(sourceCurve a b).IsElliptic]
    (h : (targetCurve a b).toAffine.Nonsingular X Y)
    (hX : X ≠ 0) :
    (sourceCurve a b).toAffine.Nonsingular
      (dualMapX X Y) (dualMapY a b X Y) := by
  apply (sourceCurve a b).toAffine.equation_iff_nonsingular.mp
  rw [WeierstrassCurve.Affine.equation_iff]
  have hm := dual_map_equation hX (target_equation h)
  simp only [sourceCurve]
  convert hm using 1 <;> ring

/-- The denominator-safe underlying point map for the dual isogeny. -/
noncomputable def dualPointMapFun (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    (targetCurve a b).toAffine.Point →
      (sourceCurve a b).toAffine.Point
  | .zero => .zero
  | .some X Y h =>
      if hX : X = 0 then .zero
      else .some (dualMapX X Y) (dualMapY a b X Y)
        (dual_map_nonsingular h hX)

@[simp] lemma dualPointMapFun_zero (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    dualPointMapFun a b 0 = 0 :=
  rfl

@[simp] lemma dualPointMapFun_targetOrigin (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    dualPointMapFun a b (targetOrigin a b) = 0 := by
  simp only [targetOrigin, dualPointMapFun]
  change Point.zero = Point.zero
  rfl

lemma dualPointMapFun_some_of_ne {a b X Y : ℚ}
    [(sourceCurve a b).IsElliptic]
    (h : (targetCurve a b).toAffine.Nonsingular X Y)
    (hX : X ≠ 0) :
    dualPointMapFun a b (.some X Y h) =
      .some (dualMapX X Y) (dualMapY a b X Y)
        (dual_map_nonsingular h hX) := by
  simp [dualPointMapFun, hX]

lemma target_y_eq_zero_of_x_eq_zero {a b X Y : ℚ}
    (h : (targetCurve a b).toAffine.Nonsingular X Y)
    (hX : X = 0) :
    Y = 0 := by
  have hcurve := target_equation h
  rw [hX] at hcurve
  norm_num at hcurve
  exact hcurve

lemma dualPointMapFun_eq_zero_iff {a b : ℚ}
    [(sourceCurve a b).IsElliptic]
    (P : (targetCurve a b).toAffine.Point) :
    dualPointMapFun a b P = 0 ↔
      P = 0 ∨ P = targetOrigin a b := by
  cases P with
  | zero =>
      change Point.zero = Point.zero ↔
        Point.zero = Point.zero ∨
          Point.zero = targetOrigin a b
      simp
  | some X Y h =>
      by_cases hX : X = 0
      · have hY := target_y_eq_zero_of_x_eq_zero h hX
        subst X
        subst Y
        have hP :
            (Point.some 0 0 h :
              (targetCurve a b).toAffine.Point) =
                targetOrigin a b := by
          rfl
        rw [hP, dualPointMapFun_targetOrigin]
        simp
      · rw [dualPointMapFun_some_of_ne h hX]
        have hmapne :
            (Point.some (dualMapX X Y) (dualMapY a b X Y)
              (dual_map_nonsingular h hX) :
                (sourceCurve a b).toAffine.Point) ≠ 0 :=
          Point.some_ne_zero _
        have hPzero :
            (Point.some X Y h :
              (targetCurve a b).toAffine.Point) ≠ 0 :=
          Point.some_ne_zero _
        have hPorigin :
            (Point.some X Y h :
              (targetCurve a b).toAffine.Point) ≠
                targetOrigin a b := by
          intro horigin
          have hXzero : X = 0 := by
            exact (show X = 0 ∧ Y = 0 by
              simpa only [targetOrigin, Point.some.injEq] using
                horigin).1
          exact hX hXzero
        simp only [hmapne, hPzero, hPorigin, false_or]

@[simp] lemma targetOrigin_add_self (a b : ℚ)
    [(sourceCurve a b).IsElliptic] :
    targetOrigin a b + targetOrigin a b = 0 := by
  simp only [targetOrigin]
  apply Point.add_self_of_Y_eq
  norm_num [targetCurve, negY]

lemma dualPointMapFun_kernel_killed_by_two {a b : ℚ}
    [(sourceCurve a b).IsElliptic]
    {P : (targetCurve a b).toAffine.Point}
    (hP : dualPointMapFun a b P = 0) :
    (2 : ℕ) • P = 0 := by
  rcases (dualPointMapFun_eq_zero_iff P).mp hP with rfl | rfl
  · simp
  · simpa only [two_nsmul] using targetOrigin_add_self a b

lemma dualMapX_map {b x y : ℚ} (hx : x ≠ 0) (hy : y ≠ 0) :
    dualMapX (mapX x y) (mapY b x y) =
      (x ^ 2 - b) ^ 2 / (4 * y ^ 2) := by
  simp only [dualMapX, mapX, mapY]
  field_simp [hx, hy]
  ring

lemma dualMapY_map {a b x y : ℚ} (hx : x ≠ 0) (hy : y ≠ 0) :
    dualMapY a b (mapX x y) (mapY b x y) =
      y * (b - x ^ 2) *
        ((a ^ 2 - 4 * b) * x ^ 4 - y ^ 4) /
          (8 * x ^ 2 * y ^ 4) := by
  simp only [dualMapY, mapX, mapY]
  field_simp [hx, hy]

private lemma source_y_ne_negY {a b x y : ℚ} (hy : y ≠ 0) :
    y ≠ (sourceCurve a b).toAffine.negY x y := by
  intro h
  simp only [sourceCurve, negY] at h
  apply hy
  linarith

private lemma source_duplication_identity_algebra
    {a b x y x₂ : ℚ} (hy : y ≠ 0)
    (hcurve : y ^ 2 = x * (x ^ 2 + a * x + b))
    (hx₂ :
      x₂ =
        ((3 * x ^ 2 + 2 * a * x + b) / (2 * y)) ^ 2 -
          a - 2 * x) :
    x₂ * (2 * y) ^ 2 = (x ^ 2 - b) ^ 2 := by
  rw [hx₂]
  field_simp [hy]
  linear_combination -4 * (a + 2 * x) * hcurve

lemma source_doubleX {a b x y : ℚ}
    (h : (sourceCurve a b).toAffine.Nonsingular x y)
    (hy : y ≠ 0) :
    (sourceCurve a b).toAffine.addX x x
        ((sourceCurve a b).toAffine.slope x x y y) =
      (x ^ 2 - b) ^ 2 / (4 * y ^ 2) := by
  have hcurve := source_equation h
  have hx₂ :
      (sourceCurve a b).toAffine.addX x x
          ((sourceCurve a b).toAffine.slope x x y y) =
        ((3 * x ^ 2 + 2 * a * x + b) / (2 * y)) ^ 2 -
          a - 2 * x := by
    rw [(sourceCurve a b).toAffine.slope_of_Y_ne rfl
      (source_y_ne_negY hy)]
    simp [sourceCurve, negY, addX]
    ring
  have hid :=
    source_duplication_identity_algebra hy hcurve hx₂
  rw [eq_div_iff (mul_ne_zero (by norm_num) (pow_ne_zero 2 hy))]
  convert hid using 1
  all_goals ring

lemma source_doubleY {a b x y : ℚ}
    (h : (sourceCurve a b).toAffine.Nonsingular x y)
    (hy : y ≠ 0) :
    (sourceCurve a b).toAffine.addY x x y
        ((sourceCurve a b).toAffine.slope x x y y) =
      dualMapY a b (mapX x y) (mapY b x y) := by
  have hcurve := source_equation h
  have hx : x ≠ 0 := by
    intro hx
    rw [hx] at hcurve
    norm_num at hcurve
    exact hy hcurve
  rw [(sourceCurve a b).toAffine.slope_of_Y_ne rfl
    (source_y_ne_negY hy)]
  simp only [sourceCurve, negY, addY, negAddY, addX,
    dualMapY, mapX, mapY]
  field_simp [hx, hy]
  linear_combination
    8 * y ^ 3 *
      (8 * a ^ 2 * x ^ 3 + 5 * a * b * x ^ 2 +
        27 * a * x ^ 4 + b ^ 2 * x + 4 * b * x ^ 3 +
        b * y ^ 2 + 27 * x ^ 5 - 9 * x ^ 2 * y ^ 2) *
        hcurve

/-- The explicit dual composed with the explicit two-isogeny is
multiplication by two on rational points. -/
theorem dualPointMapFun_comp_pointMapFun {a b : ℚ}
    [(sourceCurve a b).IsElliptic]
    (P : (sourceCurve a b).toAffine.Point) :
    dualPointMapFun a b (pointMapFun a b P) =
      (2 : ℕ) • P := by
  cases P with
  | zero =>
      change Point.zero = (2 : ℕ) •
        (Point.zero : (sourceCurve a b).toAffine.Point)
      rfl
  | some x y h =>
      by_cases hx : x = 0
      · have hy := source_y_eq_zero_of_x_eq_zero h hx
        subst x
        subst y
        have hP :
            (Point.some 0 0 h :
              (sourceCurve a b).toAffine.Point) =
                sourceOrigin a b := by
          rfl
        rw [hP, pointMapFun_sourceOrigin,
          dualPointMapFun_zero, two_nsmul,
          sourceOrigin_add_self]
      · by_cases hy : y = 0
        · have himage :
              pointMapFun a b
                  (Point.some x y h :
                    (sourceCurve a b).toAffine.Point) =
                targetOrigin a b := by
            rw [pointMapFun_some_of_ne h hx]
            rw [targetOrigin]
            simp only [Point.some.injEq]
            subst y
            simp [mapX, mapY]
          rw [himage, dualPointMapFun_targetOrigin, two_nsmul]
          symm
          apply Point.add_self_of_Y_eq
          simp [sourceCurve, negY, hy]
        · have hmapX : mapX x y ≠ 0 := by
            exact div_ne_zero (pow_ne_zero 2 hy) (pow_ne_zero 2 hx)
          rw [pointMapFun_some_of_ne h hx,
            dualPointMapFun_some_of_ne _ hmapX,
            two_nsmul,
            Point.add_self_of_Y_ne (source_y_ne_negY hy)]
          simp only [Point.some.injEq]
          constructor
          · exact (dualMapX_map hx hy).trans
              (source_doubleX h hy).symm
          · exact (source_doubleY h hy).symm

end MazurTorsion.TwoIsogeny
