name: Workflow Lint

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install and run actionlint
        run: |
          set -euo pipefail
          curl --fail --silent --show-error --location \
            https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz \
            --output actionlint.tar.gz
          echo "023070a287cd8cccd71515fedc843f1985bf96c436b7effaecce67290e7e0757  actionlint.tar.gz" \
            | sha256sum --check
          tar --extract --gzip --file actionlint.tar.gz actionlint
          ./actionlint

  pinned-actions:
    name: SHA-pinned Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Check action pins
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@3db98c0363e2fa5df3e1c4c471777a7c10b24cc9
